### ISSUE TITLE
[core] Use of non-initialized final fields (not deterministic results)

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1010]
Sometimes jadx skips the initializations. So if you decompile the attached app a few times, you will see that in file `com/sec/android/app/voicenote/ui/dialog/NFCDialog.java` fields could be decompiled so
```java
    private static final int NFC_RETRY_CNT;
    private static final int NFC_RETRY_INTERVAL;
    private static final String TAG;
```
or so
```java
    private static final int NFC_RETRY_CNT = 10;
    private static final int NFC_RETRY_INTERVAL = 200;
    private static final String TAG = "NFCDialog";
```

(cli args could be taken from there https://github.com/skylot/jadx/issues/1007)

APK: https://drive.google.com/file/d/1cuzcWoP014UeKFFUQNUZLa4YdUeYJ5Am/view?usp=sharing

**Comment by skylot** [comment]
Fixed

**Comment by bagipro** [comment]
@skylot 
Thanks!
