### ISSUE TITLE
[core] Jadx decompiles a small app within 20 minutes

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1012]
APK: https://drive.google.com/file/d/1ihmhe-Sm9a0cnw3BJwhC7VSackW6x3Pt/view?usp=sharing

In console output I see only
```
WARN  - Type inference failed for: r0v12 in org.spongycastle.pqc.jcajce.provider.rainbow.BCRainbowPrivateKey.Dhg(int, java.lang.Object[]):java.lang.Object
WARN  - Type inference failed for: r0v13 in org.spongycastle.pqc.jcajce.provider.rainbow.BCRainbowPrivateKey.Dhg(int, java.lang.Object[]):java.lang.Object
WARN  - Type inference failed for: r0v27 in org.spongycastle.pqc.jcajce.provider.rainbow.BCRainbowPrivateKey.Dhg(int, java.lang.Object[]):java.lang.Object
WARN  - Type inference failed for: r0v30 in org.spongycastle.pqc.jcajce.provider.rainbow.BCRainbowPrivateKey.Dhg(int, java.lang.Object[]):java.lang.Object
WARN  - Type inference failed for: r0v33 in org.spongycastle.pqc.jcajce.provider.rainbow.BCRainbowPrivateKey.Dhg(int, java.lang.Object[]):java.lang.Object
WARN  - Type inference failed for: r0v34 in org.spongycastle.pqc.jcajce.provider.rainbow.BCRainbowPrivateKey.Dhg(int, java.lang.Object[]):java.lang.Object
```
appearing very slow

**Comment by skylot** [comment]
@bagipro I made some adjustments for processing limits and also fix unneeded type reapply in type inference. Hope it will help.
However protector in this apk is funny, it merges all class methods in one using switch to call needed code. So sometimes such methods become really big (like 30K instructions) and jadx will skip decompiling them :sob:

**Comment by bagipro** [comment]
@skylot 
Yeah, that helps, thanks!

**Comment by lxzh** [comment]
@skylot Can this limit be controlled by adding a configuration switch? Sometimes users do need to decompile large methods. #1079
