### ISSUE TITLE
[core] `AndroidManifest.xml` is not decoded

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1013]
Hey, `AndroidManifest.xml` isn't decoded because of error
```
Error decode manifest
java.io.IOException: Decode error: attrValSize != 0x08 not supported, position: 0x4d06
	at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:92)
	at jadx.core.xmlgen.BinaryXMLParser.parseAttribute(BinaryXMLParser.java:285)
	at jadx.core.xmlgen.BinaryXMLParser.parseElement(BinaryXMLParser.java:275)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:135)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:94)
```
This error is occurred for the first time among all APKs I tested. But I looked on apktool, it doesn't have such problem. Moreover, it doesn't verify all those values to be equal to e.g. `0x08` https://github.com/iBotPeaches/Apktool/blob/b4493a51bbc5582175e1f6a93a71ae7c58428818/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java#L931

When I removed 
```java
		if (attrValSize != 0x08) {
			die("attrValSize != 0x08 not supported");
		}
```
the file was decompiled correctly. Is there a reason why jadx checks those values?

**Comment by jpstotz** [comment]
@bagipro Can you please provide the APK file that causes this error?

**Comment by bagipro** [comment]
@jpstotz 
https://drive.google.com/file/d/1rIJ5SJqwFKbAjmo2-uNlKc-BvypLdo1s/view?usp=sharing

**Comment by jpstotz** [comment]
@bagipro Sorry but the file can not be downloaded. I am getting an error message that the file is not accessible due to a Google Drive usage violation.

**Comment by bagipro** [comment]
@jpstotz 
Have no idea. I see only
> Sorry, this file is infected with a virus
fce07034-209a-4375-babd-27fab8294f46.apk (18M) may harm your computer. Only download this file if you understand the risks.

But I can download it

**Comment by skylot** [comment]
@bagipro I also can't download file. Can you share just AndroidManifest.xml file?

> Is there a reason why jadx checks those values?

Here `attrValSize` is a size of data struct we are trying to parse. If it changed it is better to fail fast instead read garbage data.
But maybe here value was tampered. And as soon Android can also ignore this field, we may remove such checks.
Anyway, I will try to check Android sources to confirm this.

**Comment by bagipro** [comment]
File https://drive.google.com/file/d/1P3ag49-x2SETErDu3uIyyLaZ7EWrn-lo/view?usp=sharing

**Comment by skylot** [comment]
Ok. I just removed these checks, it looks safe enough.
