### ISSUE TITLE
[feature] Concat constants

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1014]
*Describe your idea:*
Sometimes I see code such as
```java
String value = "1" + "2";
```
Is that possible to implement a flag (or do it by default) to merge such constants? So after decompilation it would be
```java
String value = "12";
```

**Comment by skylot** [comment]
@bagipro sure this can be implemented.
But, did you know the reason why this happens? I mean, java compiler always concat constant strings, so this will not occur in normal java building pipeline. Did you see such cases in any open source projects, so I can trace the cause of the issue.

**Comment by bagipro** [comment]
@skylot 
Probably because it's concatenated from different `final` fields, so the compiler replaces field references with their values, but doesn't concatenate. I will find such examples

**Comment by bagipro** [comment]
@skylot 
APK: https://drive.google.com/file/d/1scyr_jQjtDN5ICSfExkbTRzTew_0n0Nw/view?usp=sharing

Class `com.dsi.ant.channel.EventBufferSettings`
```java
    public java.lang.String toString() {
        return "Event Buffer Settings:" + " -Buffer Time: " + this.mBufferTimeMilliseconds + "ms";
    }
```

And with int, class `com.dsi.ant.channel.EventBufferSettings`
```java
                android.util.Log.i(str, "Decoding version " + readInt2 + " AntContinuousScanController parcel with version " + 1 + " parser.");
```

**Comment by skylot** [comment]
Done.
@bagipro thanks for samples.

**Comment by bagipro** [comment]
@skylot 
Thanks!
