### ISSUE TITLE
Output dex or JAR for investigations [feature]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#1016]
Can we get the jar or dex output from the JADX?
For example, assume we have obfuscated APK and we can use the deobfuscation option in the JADX to deobfuscate it. 
If there any way to export the JAR or dex after deobfuscation then it'll be awesome. I don't know whether this is possible or not.

**Comment by jpstotz** [comment]
The Jadx deobfuscation is only renaming the displayed classes, methods, and so on on the fly. The changes are never applied to compiled code. 

This would also require an output e.g. to dex format which is currently not available at all (only reading). Not sure if skylot is planning such a feature.
