### ISSUE TITLE
[core] Some style item names aren't decoded

### ISSUE THREAD

**Issue by alissonlauffer** [skylot/jadx#1020]
File `res/values-v29/styles.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="e" parent="@android:style/Theme.Material.Light">
        <item name="android:statusBarColor">@color/f</item>
        <item name="android:navigationBarColor">@color/f</item>
        <item name="?0x10104e0">true</item>
        <item name="?0x101056c">true</item>
        <item name="?0x101056d">@android:color/transparent</item>
        <item name="?0x1010590">true</item>
    </style>
    ...
<resources>
```
The file should be decoded like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="e" parent="@android:style/Theme.Material.Light">
        <item name="android:statusBarColor">@color/f</item>
        <item name="android:navigationBarColor">@color/f</item>
        <item name="android:windowLightStatusBar">true</item>
        <item name="android:windowLightNavigationBar">true</item>
        <item name="android:navigationBarDividerColor">@android:color/transparent</item>
        <item name="android:isLightTheme">true</item>
    </style>
    ...
<resources>
```

APK: https://apkpure.com/via-browser-fast-light-geek-best-choice/mark.via.gp/download

**Comment by jpstotz** [comment]
The `resources.arsc` file that is included in the resources of jadx-core project seems to be a bit outdated and therefore does not know all attribute names. If I use the `resources.arsc` from API 30 android.jar the attribute names are decoded correctly. 

However file size of the new `resources.arsc` file has increased from 11 to 33MB. Have you included the original resources.arsc file or was the old file a stripped one?

Additionally there is the problem that as far as I know newer API versions do not always include all resource IDs from previous versions. Some times old resource entries are removed (not many just a few) so that it might be useful to use a custom format that can be updated with every newly released Android version by adding all resource entries. @skylot What do you think?

**Comment by skylot** [comment]
> it might be useful to use a custom format

@jpstotz yeah, right now I implementing simple converter from `.arsc` to text file with just mapping id to name (like stated in [this](https://github.com/skylot/jadx/blob/d1e5186d4adeabd51f52b42d5c07dd3cccd60f4b/jadx-core/src/main/java/jadx/core/xmlgen/entry/ValuesParser.java#L41) comment). And, as you mention, looks like it must accept several input `.arsc` files and merge them.

**Comment by jpstotz** [comment]
> yeah, right now I implementing simple converter from `.arsc` to text file with just mapping id to name (like stated in [this](https://github.com/skylot/jadx/blob/d1e5186d4adeabd51f52b42d5c07dd3cccd60f4b/jadx-core/src/main/java/jadx/core/xmlgen/entry/ValuesParser.java#L41) comment). And, as you mention, looks like it must accept several input `.arsc` files and merge them.

My suggestion would be to use two files as input: one `.arsc` file and the existing text file. Then it would be possible to update the text file by just merging the latest android.jar respectively it's `resources.arsc` file into our text file. 
In this way we don't have to keep all the old resources.arsc files of all 30 Android versions just for being able to regenerate/update the text file.

**Comment by skylot** [comment]
Sure, that will be more convient, thanks for suggestion!

**Comment by skylot** [comment]
Well, this becomes weird. I maid a converter and compare different android version. And looks like there are lots shifted ids.
Same resource name can have different ids on different android versions.
Here some example files for API 29 and 30: [res-map-29.txt](https://github.com/skylot/jadx/files/5562929/res-map-29.txt) and [res-map-30.txt](https://github.com/skylot/jadx/files/5562930/res-map-30.txt)
I suspect that some resources are internal, so it will be nice to exclude them. Maybe some flag exists, so we can filter such resources.
If anyone knows how these ids work please share your knowledge :+1:

**Comment by jpstotz** [comment]
May be we are trying to see pattern where there are no patterns.

The first problem is that we use `resources.arsc` file from `android.jar` which is part of the development SDK, hence it is designed to be used for compiling Android apps not for reading or reversing them.
We don't know which resource IDs are app-internal and which one are platform specific.

It would be interesting to see the resource mapping file used by Android itself, if this data is present at all on Android itself as mostly system resources are directly addressed by it's id, hence the name is of no relevance on the system. 

But let's look at an example, let's check the first resource ID mentioned in this issue: 0x10104e0 = 16844000

When I check this id in all the android.jar files I have (3-30) I get the following result:

```
API 21 set to: private_resource_pad33
API 22 not present
API 23 changed from private_resource_pad33 to windowLightStatusBar
API 24 unchanged: windowLightStatusBar
API 25 unchanged: windowLightStatusBar
API 26 unchanged: windowLightStatusBar
API 27 unchanged: windowLightStatusBar
API 28 unchanged: windowLightStatusBar
API 29 unchanged: windowLightStatusBar
API 30 unchanged: windowLightStatusBar
```

**Comment by skylot** [comment]
Ok. I merge API versions from 14 to 30.
Here log of entries count in every file and after merging:
```
INFO  - resources-14.arsc entries count: 6027, after merge: 6027
INFO  - resources-15.arsc entries count: 6075, after merge: 6075
INFO  - resources-16.arsc entries count: 6309, after merge: 6309
INFO  - resources-17.arsc entries count: 6650, after merge: 6650
INFO  - resources-18.arsc entries count: 6694, after merge: 6736
INFO  - resources-19.arsc entries count: 7017, after merge: 7107
INFO  - resources-20.arsc entries count: 7130, after merge: 7192
INFO  - resources-21.arsc entries count: 8623, after merge: 8734
INFO  - resources-22.arsc entries count: 8692, after merge: 9029
INFO  - resources-23.arsc entries count: 8508, after merge: 9217
INFO  - resources-24.arsc entries count: 9039, after merge: 9539
INFO  - resources-25.arsc entries count: 9174, after merge: 9630
INFO  - resources-26.arsc entries count: 9636, after merge: 10065
INFO  - resources-27.arsc entries count: 9836, after merge: 10262
INFO  - resources-28.arsc entries count: 10244, after merge: 10541
INFO  - resources-29.arsc entries count: 11230, after merge: 11513
INFO  - resources-30.arsc entries count: 11458, after merge: 11919
INFO  - Output entries count: 11919
INFO  - Total rewrites count: 83245
INFO  - Result file size: 486444 B
```
