### ISSUE TITLE
[core] Limit max parameter count to 255

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1026]
Hey, I've noticed a huge method with 65k parameters (probably obfuscation?). Is that possible to prevent such cases?

Class `p001a.p002a.p003a.C4687alockin` (`a.a.a.alockin`)
```java
public class C4687alockin {
    public static java.lang.String aa(java.lang.String str, java.lang.String str2, ...,  java.lang.String str65533) {
       return;
    }
```

APK: https://www.apkmonk.com/app/com.percent.royaldice/

**Comment by jpstotz** [comment]
LOL a really nice app. 

I assume your question is just because Jadx requires a lot of time to load and display the class that contains this method?

**Comment by bagipro** [comment]
@jpstotz 
Yeah, and also because my AST parser crashes with OutOfMemoryError

**Comment by skylot** [comment]
@bagipro in theory it is possible to call such method using `invoke-***/range` instruction, but java spec limits method args count to 255. So in general case, we can replace these args with object array arg (`Object[]`). Also depending on the specific case we can remove unused args, or remove the whole method if it is empty.
I will try to implement a general solution.
And thanks for the sample :+1:

**Comment by bagipro** [comment]
@skylot 
Hey! Can you please look at this one? This issue occurs sometimes and ruins my codes :D

**Comment by skylot** [comment]
@bagipro can you share one more sample? Because in this case method don't used, so I just remove it. I wonder how will look an invoke of such method :)

**Comment by bagipro** [comment]
@skylot 
Sorry for the long response. It appeared that all affected APKs were the same. If I notice this issue, I will let you know.

Thanks for the fix!

**Comment by skylot** [comment]
Ok, great. I will close this issue as fixed :)
