### ISSUE TITLE
Problem with string resource output [core]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#1030]
![image](https://user-images.githubusercontent.com/35992798/99984479-1c3c5f00-2dd3-11eb-9abc-4653b9ec8dbf.png)

As you can see in the above picture, jadx adds something 10\,1010\ to the strings file. I'm not sure why it was showing like that.

**Comment by skylot** [comment]
@redmi111 thanks. Fixed, this must be a new line char (`\n`).
