### ISSUE TITLE
weird background color when select code block containing reference

### ISSUE THREAD

**Issue by jiashie** [skylot/jadx#1031]
1. select code block.
![normal_select](https://user-images.githubusercontent.com/7597939/100056139-16d92600-2e60-11eb-970c-67243662780c.png)

2. mouse over some word containing 'reference'
![mouseover](https://user-images.githubusercontent.com/7597939/100056206-38d2a880-2e60-11eb-87a0-d038810e11b1.png)

the background color changed to white, but the selected block text color is also white !

ps. using the latest version , v1.2.0

**Comment by skylot** [comment]
@jiashie thank you for report!
I made a fix, please check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files).

**Comment by jiashie** [comment]
> @jiashie thank you for report!
> I made a fix, please check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files).

Fixed! 
Great praise! Many thanks for your prompt reply.
