### ISSUE TITLE
[feature]Cannot view java code in an aar file, but the previous version did

### ISSUE THREAD

**Issue by ljf1239848066** [skylot/jadx#1034]
*Describe your idea:*
Cannot view java code in an aar file, but the previous version did

**Comment by ljf1239848066** [comment]
ERROR: [429] JadxOverflowException in pass: RegionMakerVisitor in method: kotlin.collections.SlidingWindowKt$windowedIterator$1.invokeSuspend(java.lang.Object):java.lang.Object, file: classes2.dex, details: Regions count limit reached
ERROR: [77] StackOverflowError in pass: MarkFinallyVisitor in method: kotlin.concurrent.LocksKt.write(java.util.concurrent.locks.ReentrantReadWriteLock, kotlin.jvm.functions.Function0<? extends T>):T, file: classes2.dex, error: StackOverflowError

**Comment by jpstotz** [comment]
Can you provide the aar file that causes this problem?

**Comment by ljf1239848066** [comment]
https://jcenter.bintray.com/com/geetest/android/onelogin/2.3.4/

**Comment by jpstotz** [comment]
Looks like at the moment no `JadxInputPlugin` implementation feels responsible for .aar files.

**Comment by skylot** [comment]
I made a fix to support AAR files as input.
