### ISSUE TITLE
[core] generated resource names use capital letters

### ISSUE THREAD

**Issue by hedwinkoning** [skylot/jadx#1043]
Resource file names are created using a capital "RES_" as a prefix. From what I know capital letters are not allowed for resource file names.

From looking at the code using "RES_" is hardcoded in ./xmlgen/ResTableParser.java

**Comment by jpstotz** [comment]
Android Studio does not complain about resource names with capital letters. Also apps that use such resource names seem to work without problems, at least for those resources I have tested. 
Or may be this was an limitation of older versions of Android resource compiler?

**Comment by ANR2ME** [comment]
I had similar issue using Android Studio 4.1.1 with gradle 6.1.1
```
'R' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```

**Comment by MrIkso** [comment]
@skylot, I think this issue is not relevant now, it should be closed.

**Comment by anr2me** [comment]
> Hey, I'm using jadx 1.4.0 from homebrew with `--export-gradle` and face a similar issue - I get issues like the identifier "do" or "if" in a strings file (`if is not a valid resource name (reserved Java keyword)`) and names like tG.png `('G' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore).`
> 
> Is there any good workaround for this? It seems like the naming rules can't easily be circumvented. Could this be an obfuscation/annoyance technique by the app's vendor?

These are reserved words that's not allowed to be used as identifier: https://stackoverflow.com/questions/53328395/import-is-not-a-valid-resource-name-reserved-java-keyword

If this issue is still happening on the latest version, you probably want to open a new issue, so those words can be blacklisted from the identifier generator.
