### ISSUE TITLE
Improve confuse code

### ISSUE THREAD

**Issue by FinalLody** [skylot/jadx#105]
Sometimes JADX can detect the class name before confuse,it will generates an commet : /\* compiled from:XXX */, is it able to modify the class name before confuse?

**Comment by dasbiswajit** [comment]
@FinalLody Thanks for the post. I too have the same problem. After decompile I got the following lines- 
 /* renamed from: com.anwe.main.10 */
    class AnonymousClass10 implements Runnable {
        final /* synthetic */ Handler val$handler;
........

I too confused what does it mean.

**Comment by victorchoy** [comment]
Do someone know how jadx can work out the original class name? Thanks

**Comment by skylot** [comment]
@victorchoy original class name in dex is stored in class definition in field `source_file_idx` (see [here](https://source.android.com/devices/tech/dalvik/dex-format#class-def-item) for dex format details).
For example in smali you can set it in `.source` class attribute:
```java
.class public Lcom/test/helloworld/HelloWorldActivity;
.super Landroid/app/Activity;
.source "HelloWorldActivity.java"
```
For rename class to its source name in jadx enable this option in preferences:
![source_file_option](https://user-images.githubusercontent.com/118523/40167292-587299f2-59c9-11e8-9eab-97e2c2508e88.png)

But unfortunately this field often filled with garbage by obfuscators and protectors, so it is not very usefull.
