### ISSUE TITLE
[GUI] Can not select "Find reference" in context menu after I upgrade to macOS 11.1

### ISSUE THREAD

**Issue by shatyuka** [skylot/jadx#1052]
**Describe error**
As described in title, the GOTO and Find reference are both disabled, seems like I didn't select anything.

**Comment by shatyuka** [comment]
Currently find a way out: use [universalJavaApplicationStub](https://github.com/tofi86/universalJavaApplicationStub) to pack the jar to an app.

**Comment by shatyuka** [comment]
Seems that [`codeArea.getMousePosition()`](https://github.com/skylot/jadx/blob/7f8d03d1927b95565938a4e2089f4cbed3417979/jadx-gui/src/main/java/jadx/gui/ui/codearea/JNodeMenuAction.java#L39) failed to retrieve the position.
Now I have an alternative method. #1086

**Comment by skylot** [comment]
Fixed in PR #1086
