### ISSUE TITLE
[feature] Support APK Expansion Files (OBB) when opening/decompiling APK for additional resources

### ISSUE THREAD

**Issue by ANR2ME** [skylot/jadx#1056]
*Describe your idea:*

Sometimes we can find interface of functions/methods where the source code can't be found within the apk, so they might be exists within expansion files.

PS: The obb files may need to be renamed to the same file name of the apk and placed on the same folder with the apk for easier detection on expansion files existence.

**Comment by skylot** [comment]
@ANR2ME can you share any app (name or url in store) which stores code in obb files?
Anyway, I don't think there is any general approach, so you need to manually extract dex/apk and load them with the main apk.
