### ISSUE TITLE
Method renaming has no effect

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#1058]
1. Open the attached file in Jadx with enabled deobfuscation
2. Open interface `p009d.p402i.p403a.p404a.LoadControl`
3. Select a method that is marked  as `renamed from ...`
4. Rename this method
5. Jadx does something but the method name stays

[jadx-LoadControl.zip](https://github.com/skylot/jadx/files/5720882/jadx-LoadControl.zip)

**Comment by skylot** [comment]
@jpstotz can you try to remove .jobf file before decompilation? For me, it works correctly.
Looks like exists renaming override your rename. Not sure if this needs to be fixed, because the latest version should prevent such overriding.

**Comment by jpstotz** [comment]
@skylot I am using the latest version from master and delete the jobf file before opening the attached zip file in Jadx. 
On loading the jobf file is generated and afterwards I try to rename a method but it does not work for me.  

Even if I delete the jobf file while Jadx is running method renaming still does nothing. 

If I don't delete the jobf file and look at it while renaming the method(s) I can see that the method renameings are added at the end but it looks like they are not applied on loading. 
Only `onStopped` can be renamed.

If it works on your system and does not work on my system it might be a concurrency problem.

**Comment by skylot** [comment]
@jpstotz thanks. I will try to investigate this case deeper.

**Comment by jpstotz** [comment]
I also investigated this problem. I ended up in `Deobfuscator` class in method [`getAssignedAlias`](https://github.com/skylot/jadx/blob/master/jadx-core/src/main/java/jadx/core/deobf/Deobfuscator.java#L462-L473).

The automatically generated method name is stored in `mthMap`. And the method value I entered is stored in `deobfPresets`. 
Sadly only `mthMap` is checked and as there is an alias defined for the method `deobfPresets` is never checked for the renamed method name. Therefore the renamed method name can never be used...

**Comment by skylot** [comment]
@jpstotz root cause was in renaming only one method in deobf map file instead of all related overridden methods. Also list of related methods was calculated incorrectly for some case. I made a fix for these issues.
Next I will try to fix concurrent exceptions during reindex which occurs quite often:
```java
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1695)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at jadx.gui.utils.CodeUsageInfo.lambda$remove$2(CodeUsageInfo.java:79)
	at java.base/java.util.concurrent.ConcurrentHashMap.removeEntryIf(ConcurrentHashMap.java:1640)
	at java.base/java.util.concurrent.ConcurrentHashMap$EntrySetView.removeIf(ConcurrentHashMap.java:4836)
	at jadx.gui.utils.CodeUsageInfo.remove(CodeUsageInfo.java:75)
	at jadx.gui.jobs.IndexJob.refreshIndex(IndexJob.java:75)
	at jadx.gui.ui.RenameDialog.refreshJClass(RenameDialog.java:238)
	at jadx.gui.ui.RenameDialog.lambda$refreshState$0(RenameDialog.java:209)
```

**Comment by jpstotz** [comment]
@skylot Thanks for the first fixes. Unfortunately your concurrency issue does not occur in my set-up. But looking at the stack-trace I would assume that #1065 should synchronize access to `usageList` and therefore prevent your concurrency issue.
