### ISSUE TITLE
Disable constants references

### ISSUE THREAD

**Issue by sergey-toshin** [skylot/jadx#106]
It's really useless to see constant references instead of constants in reversing
Will be here an option for disabling constants recovery?

For example,
```
private static final String IS_SYNC_DATA = "is_sync_data";
// ...
getIntent().getStringExtra(EXTRA_OPERATION);
```
I want to see only
`getIntent().getStringExtra("is_sync_data");`

**Comment by giladbeeri** [comment]
+1

Also sometimes the constant dereferencing is wrong and confusing. For example when handling integers, jadx assigns a named constant it finds that is totally unrelated to the context but just happened to have the same value.

**Comment by skylot** [comment]
Added the option `--no-replace-consts` for disable constants dereferencing. 
Also made some improvements so there will be less incorrect replacements.
Please check latest [unstable](https://drone.io/github.com/skylot/jadx/files) build
