### ISSUE TITLE
Issues with resource on latest build[core]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#1060]
It seems in the latest build the style attribute names are changed by adding res_their_int_id_value as a prefix. For reference, I'm attaching the photo here.

![image](https://user-images.githubusercontent.com/35992798/102779190-d1a20880-43b9-11eb-9e4b-7ede6b2d04c0.png)

**Comment by jpstotz** [comment]
@redmi111 Can you please elaborate a bit more why this is a problem? According to #1043 the names used before are invalid.

**Comment by redmi111** [comment]
Yeah, you're right it should not be a problem.

**Comment by ANR2ME** [comment]
For resource names started with `$` (ie. `$avd_hide_password` which exist on most apk inside `res\drawable-v21`) we can safely just removing the `$` prefix instead of using the fallback `res_xxxx` names.
