### ISSUE TITLE
jadx-gui:createExe FAILED on Ubuntu 20.04

### ISSUE THREAD

**Issue by AungSiMin007** [skylot/jadx#1062]
> Task :jadx-gui:createExe FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jadx-gui:createExe'.
> net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/root/jadx/jadx-gui/build/tmp/launch4j/bin-launch4j-3.12/bin/windres": error=2, No such file or directory

**Comment by jpstotz** [comment]
Sorry but I am unable to reproduce your problem. In my Usbuntu 20.04 VM I installed git, openjdk-11-jdk, cloned jadx and executed `/gradlew createExe`. 

Worked without any problems.

Based on the path you have posted you are working in `/root`. In general working as root user isn't a good idea. Therefore don't login as root, and don't use `/root`. Just log-in as regular user and if a command needs root execute it via `sudo`. I recommend you to delete the cloned jadx directory and start over as regular user.
