### ISSUE TITLE
jadx bug: Method dump skipped

### ISSUE THREAD

**Issue by polarbear88** [skylot/jadx#1063]
jadx version: dev
![image](https://user-images.githubusercontent.com/38294644/103063254-b3bbea00-45eb-11eb-9e9b-0a0b3cb5fa37.png)
jadx version: 1.10
![image](https://user-images.githubusercontent.com/38294644/103063449-4b213d00-45ec-11eb-8a45-af5c007e3a30.png)

Is this a bug?

**Comment by jpstotz** [comment]
This is not a bug. The code dump was limited in commit https://github.com/skylot/jadx/commit/e054ea6683fd047d81803bf45be5cf8ff49d9cad to max. 100 instructions. 

Do you really work with the code dump? Usually Jadx users want the decompiled code, not the code dump.

**Comment by alissonlauffer** [comment]
I think that code dump should not be skipped when the user explicitly enables fallback mode. Just skip it when decompilation fails.

**Comment by skylot** [comment]
@alissonlauffer is right, looks like fallback mode enabled here, so jadx don't need to hide instructions.

**Comment by skylot** [comment]
Fixed.
@polarbear88 thank you for report!
