### ISSUE TITLE
Cannot decompile class compiled with jdk 15

### ISSUE THREAD

**Issue by wyghf18188** [skylot/jadx#1068]

**Comment by jpstotz** [comment]
Jadx is primarily an Android decompiler. The possibility to decompile Java Jar archives is just a workaround and uses a converter for generating Android dex code from the jar file. 
As far as I know Android `dx` is used for the conversion. 

Unfortunately `dx` is not capable of converting modern Java8+ language features. Therefore Java 15 is a bit far out of scope for the dx converter.

**Comment by wyghf18188** [comment]
Thank you
