### ISSUE TITLE
Implementing package-wise decompile feature

### ISSUE THREAD

**Issue by stypr** [skylot/jadx#107]
Few months ago I found jadx more useful than dex2jar+jad, since then I frequently use jadx-cli for research purposes. :smile:
The only problem I hate is that it takes a lot of time to decompile the entire dex/jar file. Maybe this is because the jadx also decompiles a lot of android.\* and other sdk packages(if included).
It would be very great if the package-wise decompilation feature is implemented on jadx-cli.

the package-wise decompilation feature exists in jad, so why not in jadx? :+1:
 `jad -o -r -d ./some_directory/ -sjava -dsrc com/package/name/**/*.class`.

**Comment by sergey-wowwow** [comment]
@stypr,
Please refer to this explanation https://github.com/skylot/jadx/issues/139#issuecomment-256658207

More over, a lot of errors were fixed, so the decompilation process takes now less time
