### ISSUE TITLE
[feature] Allow to use 'Go to declaration' for local variables

### ISSUE THREAD

**Issue by Surendrajat** [skylot/jadx#1084]
**Issue**:
So when I right-click on a local variable or argument and select `Go to declaration`, nothing seems to happen.

**Expected behavior:**
When I click `Go to declaration` the cursor should move to the declaration of the variable or to the function parameter definition.

**Comment by skylot** [comment]
@Surendrajat well, this is not yet implemented, so you actually can't select `Go to declaration` because it must be disabled.

Anyway, I plan to add info about local variables in the future, and this feature also related to #1023.

**Comment by skylot** [comment]
Implemented in PR #1098
