### ISSUE TITLE
[feature] Update Gradle exporting scheme

### ISSUE THREAD

**Issue by Fi5t** [skylot/jadx#1095]
Hello! I use exporting decompiled sources as a gradle project very frequently. And the current exporting template looks too outdated to work comfortably. I'd updated that template and added some useful features [here](https://github.com/Fi5t/jadx/commit/9324a23b4f5045171f02fe6fdaa20a4b2a9eb28d). @skylot , if you like it I can send PR with these changes.

**Comment by skylot** [comment]
> if you like it I can send PR with these changes

Sure! Nice changes. Please open PR :+1:
