### ISSUE TITLE
How to debug Jadx in IDEA?

### ISSUE THREAD

**Issue by Surendrajat** [skylot/jadx#1102]
@skylot the other day I was trying to hack into some Jadx-GUI code and wanted to debug it. But it turned out to be very complicated, so I didn't do it yet. Could you please point out into the right direction?
Basically if there's something that can help me avoid converting all `jadx-gui` script logic to run config and spend long on it. Thanks.

**Comment by jpstotz** [comment]
Debugging jadx-gui in IntelliJ is pretty simple. Just select the file `jadx-gui/src/main/java/jadx/gui/JadxGUI.java` and in it's context menu start it via "Debug".

IntelliJ then creates the correct run config. You can extend this run-comfig with special jadx command-line options e.g. the APK file to be loaded after Jadx has started.

Also the option `--select-class <full classname of a class in the loaded AK>` is sometimes pretty useful If you want to decompile a special class and check the result or execute a function from an element within this class.

**Comment by Surendrajat** [comment]
@jpstotz Thank you very much. Seems like, being a newbie, I was expecting a Java GUI app to be much complicated :)
