### ISSUE TITLE
[core] Jadx is replacing some method callers

### ISSUE THREAD

**Issue by alissonlauffer** [skylot/jadx#1109]
Class: `mark.via.o.p`, method `a` (There are more cases but I'm showing just one of them because it seems to be the same issue)

Smali code:
```smali
.method public final a(Landroid/view/View;Lcom/tuyafeng/support/b/c$l;)V
    .registers 4

    iget-object v0, p0, Lmark/via/o/p;->a:Landroid/os/Message;

    invoke-static {v0, p1, p2}, Lmark/via/o/b0$e;->a(Landroid/os/Message;Landroid/view/View;Lcom/tuyafeng/support/b/c$l;)V

    return-void
.end method
```

It should be decompiled to:
```java
public final void a(View view, c.l lVar) {
    b0.e.a(this.f1856a, view, lVar);
}
```

But somehow it is decompiling to:
```java
public final void a(View view, c.l lVar) {
    this.f1856a.sendToTarget();
}
```

APK: https://apkpure.com/via-browser-fast-light-geek-best-choice/mark.via.gp/download/20210109-APK

**Comment by skylot** [comment]
@alissonlauffer 
Hm, funny, but this is actually a feature of inlining synthetic methods.
`Lmark/via/o/b0$e;->a` is synthetic here, so it gets inlined:
```smali
.method static synthetic a(Landroid/os/Message;Landroid/view/View;Lcom/tuyafeng/support/b/c$l;)V
    .locals 0

    invoke-virtual {p0}, Landroid/os/Message;->sendToTarget()V

    return-void
.end method
```
Do you need an option to disable such inlining?

**Comment by alissonlauffer** [comment]
> this is actually a feature of inlining synthetic methods.

Ah, didn't know that was a feature, sorry. I've found it and though it were some parsing bug, but now everything is clarified :laughing:.
And this is probably related to #1089 2nd example.

> Do you need an option to disable such inlining?

For my use, it is not needed since it makes code more readable. But some people may like it (Just like some people only use Jadx fallback mode).

**Comment by skylot** [comment]
> Just like some people only use Jadx fallback mode

Is this really a case? Maybe I can make it more readable like use correct types and variable names?

Actually it is a big issue in jadx: different people use jadx differently, but I don't want to add switches for every small feature in jadx. That will cause tons of options, and it will be hard to test, reproduce issues and maintain.
I was thinking about some kind of 'profiles' which will combines some switches. I see 3 of them for now:
1. `low-level` - for compare with bytecode, like fallback but more precise (types, var names)
2. `compilable` - for compilation or code analysis - will disable some unstable feature, so code become more verbose.
3. `readable` - full set of jadx features, result is compact and readable code, possible errors can revert to previous profiles for affected methods or classes.

**Comment by MPeti1** [comment]
Not opener, but profiles like these would make sense to me.

But if we're speaking about compilable output, is Jadx made so that it should be possible to compile the app after fixing the build errors?
I mean, does it produce code that is similar enough to the original that it has the exact same effect in the majority of the code blocks? Asking because I usually come across code (in different apps) that doesn't seem to make sense, and I just don't know if that's actually how it works (however the smali confirms that most of the times), or if I have hit a bug in Jadx. e.g. from time to time I see empty methods, and ones that just return the parameter, but still called very frequently in certain classes.

**Comment by skylot** [comment]
> is Jadx made so that it should be possible to compile the app after fixing the build errors?

In general - no, there are always will be cases which jadx can't handle. Anyway, jadx try hard to produce correct code :)

May be 'compilable' not the best name here. I just mean that jadx will try to produce code with less compilation errors at the cost of readability by disabling some unstable optimizations.

> from time to time I see empty methods, and ones that just return the parameter, but still called very frequently in certain classes.

These may be a synthetic methods generated by compiler while moving inner classes outside parent

**Comment by MPeti1** [comment]
> These may be a synthetic methods generated by compiler while moving inner classes outside parent

In bigger classes I usually find inner classes that have /* syncthetic */ in them, but in this method there is no such a marking. It's the first method of two in a 25 line, very simple class (which for some reason implements Comparable<> with the type of itself, but does not implement it's method..)

I have been using Jadx for some time with multiple apps, but I still don't know what to think of things like this :D
