### ISSUE TITLE
[core] Decompile warnings and errors on Microsoft OneNote Apk

### ISSUE THREAD

**Issue by TheAlienDrew** [skylot/jadx#1111]
Apk trying to decompile: [com.microsoft.office.onenote.apk](https://anonymousfiles.io/D8GKPx06/)

Here's the log files:
- [jadx-debug.log](https://github.com/skylot/jadx/files/5899735/jadx-debug.log)
- [jadx-error.log](https://github.com/skylot/jadx/files/5899736/jadx-error.log)
- [jadx-warn.log](https://github.com/skylot/jadx/files/5899737/jadx-warn.log)

Summarized:
- Warnings: `Found 62 references to unknown classes, and 7002 warnings in 604 nodes`
- Errors: There are a bunch of 9-patch image decompilation errors, and then the "1 error" `[345] JadxOverflowException in pass: RegionMakerVisitor in method: com.microsoft.notes.sync.cw.a():com.microsoft.notes.sync.am<kotlin.r>, file: classes.dex, details: Regions count limit reached`

**Comment by skylot** [comment]
@TheAlienDrew thanks for report.
For 9-patch image decode error I opened separate issue: #1112 
Issue with `Regions count limit reached` error already reported in #889 
Many other warnings also already reported.
As for `Found 62 references to unknown classes` warning - it just means that jadx don't found these classes in classpath and in most cases this is ok :sweat_smile:

**Comment by TheAlienDrew** [comment]
Yeah, as you can tell, I'm a pretty novice android programmer. Thanks for looking into this though.
