### ISSUE TITLE
[feature] Bytes-Column for Smali Code

### ISSUE THREAD

**Issue by OdinVex** [skylot/jadx#1114]
I think it would be quite handy to show the bytes involved per instruction line of Smali code.

**Comment by jpstotz** [comment]
Unfortunately I don't think this is currently possible. Jadx uses [dexlib2](https://github.com/JesusFreke/smali) for generating smali code and this library seem to allow only smali code generation at class level. Therefore we can not generate a mapping between instructions and the raw bytes that belong to the instruction.

**Comment by OdinVex** [comment]
I've submitted a feature-request to dexlib2 for an option. Hopefully this can be incorporated.

**Comment by jpstotz** [comment]
I just checked and to be precise it is the baksmali part of that library not dexlib2.

**Comment by OdinVex** [comment]
I received a [response](https://github.com/skylot/jadx/issues/1114#issuecomment-777294174) from the author of baksmali.

**Comment by jpstotz** [comment]
OdinVex forgot to mention that baksmali is used as a library and on library level there seems no way to generate the smali code in smaller parts that on class level for adding some sort of mapping between smali code and the offset in the dex file.

**Comment by skylot** [comment]
Well, I checked smali dump command, looks like it dumps a whole dex file and not only one class. So we can't use this directly.
Another option: I can make my own smali printer, so we can add any feature into it. This is not hard but needs a lot of time, and I am not sure how many people need this. 
@OdinVex can you tell why you need this feature and how you will use it? I just wonder what kind of work require seeing raw bytes of instructions :smile:

**Comment by OdinVex** [comment]
> Well, I checked smali dump command, looks like it dumps a whole dex file and not only one class. So we can't use this directly.
> Another option: I can make my own smali printer, so we can add any feature into it. This is not hard but needs a lot of time, and I am not sure how many people need this.
> @OdinVex can you tell why you need this feature and how you will use it? I just wonder what kind of work require seeing raw bytes of instructions smile

I've already begun local work on a git clone. There are a lot of Android ROMs out there with drivers and software with no public source code available for _whatever_ reason. Porting Linux to certain devices needing certain drivers goes a lot easier with a decent decompiler. Knowing offsets allows manipulation of these libs to better modify their behavior such as rewriting fixed-length arrays with dynamic ones so that more cores (which were statically limited) can (or in some cases _must_) be used.

**Comment by skylot** [comment]
@OdinVex I see, so you are doing binary patching.
But I thought for dex it is easier editing smali and build it back rather than hardcore binary fixing.
Anyway thanks for reply, I will keep this issue open, maybe we will add this feature in the future.

**Comment by OdinVex** [comment]
> @OdinVex I see, so you are doing binary patching.
> But I thought for dex it is easier editing smali and build it back rather than hardcore binary fixing.
> Anyway thanks for reply, I will keep this issue open, maybe we will add this feature in the future.

The patching is to either extend, fix, or test the logic of functions, yes. Modifying the ports being polled for low-level drivers can be required, depending on whether boot-loaders are locked, as an example. Hardware may be set up on different ports, but the libraries can work across multiple devices needing binary changes to point to the correct hardware, as an obscure example that I've come across. (I have a _purely_ mainline project (Arch "mainline") that I am working on for several completely-FOSS devices, two cellular phones a laptop, and a tablet, all ARM and with impressive power for being such. I've grown so very sick and tired of Big Tech and the lack of affordable hardware to "do it ourselves". I don't expect any of it to go public, I'm doing it for myself at the moment.)

**Comment by OdinVex** [comment]
> But I thought for dex it is easier editing smali and build it back

??? Running on Linux, JADX gave no option to do any of that.

**Comment by skylot** [comment]
> ??? Running on Linux, JADX gave no option to do any of that.

Hm, I don't understand what are you trying to say. Jadx is a Dex decompiler, not any other binary, only Dex, and for Dex using `smali` or `apktool` you can dissemble, fix/edit smali code and assemble it back. All tools written in Java, so they run in Linux too.

**Comment by OdinVex** [comment]
> > ??? Running on Linux, JADX gave no option to do any of that.
> 
> Hm, I don't understand what are you trying to say. Jadx is a Dex decompiler, not any other binary, only Dex, and for Dex using `smali` or `apktool` you can dissemble, fix/edit smali code and assemble it back. All tools written in Java, so they run in Linux too.

I've no clue why you might not understand what I am saying. I know what they are, and I don't bother actually re-assembling anything, I simply determine the logic and implementation of drivers for their functionality and simply patch small bits to force different interactions to "black-box" libraries and interfaces. Furthermore, I already know that Java runs on Linux.

**Comment by LBJ-the-GOAT** [comment]
> > > ??? Running on Linux, JADX gave no option to do any of that.
> > 
> > 
> > Hm, I don't understand what are you trying to say. Jadx is a Dex decompiler, not any other binary, only Dex, and for Dex using `smali` or `apktool` you can dissemble, fix/edit smali code and assemble it back. All tools written in Java, so they run in Linux too.
> 
> I've no clue why you might not understand what I am saying. I know what they are, and I don't bother actually re-assembling anything, I simply determine the logic and implementation of drivers for their functionality and simply patch small bits to force different interactions to "black-box" libraries and interfaces. Furthermore, I already know that Java runs on Linux.

Do you have a tool that can apply the modified bytecodes on the fly? That's cool! May I have a look?

**Comment by Surendrajat** [comment]
@LBJ-the-GOAT I think a good hex editor([hexeditor](https://github.com/microsoft/vscode-hexeditor) VSCode plugin) or RE tool such as [cutter](https://cutter.re) can help with binary patching. For CLI, you can mix some `sed` and `xxd` magic :)

**Comment by LBJ-the-GOAT** [comment]
> @LBJ-the-GOAT I think a good hex editor([hexeditor](https://github.com/microsoft/vscode-hexeditor) VSCode plugin) or RE tool such as [cutter](https://cutter.re) can help with binary patching. For CLI, you can mix some `sed` and `xxd` magic :)

Thanks man, this hexeditor plugin looks so good!!!

**Comment by Surendrajat** [comment]
Also, @OdinVex @LBJ-the-GOAT, you can use [Cutter](https://cutter.re) to see opcodes and smali together for now.
![Screenshot from 2021-02-22 12-03-53](https://user-images.githubusercontent.com/11215000/108672219-b792bc80-7507-11eb-9b8b-3ec997a637af.png)

**Comment by OdinVex** [comment]
> Also, @OdinVex @LBJ-the-GOAT, you can use [Cutter](https://cutter.re) to see opcodes and smali together, for now.
Nice to see it does Arm too. I've everything for x86, but I'm growing my Arm tools. Thanks. :) This is also the exact kind of output I was looking for (Olly/x96 anyone? :))

**Comment by LBJ-the-GOAT** [comment]
Dear @skylot , long time no see, how are you. I found a SmaliPrinter in the jadx.plugins package and you've done all the decoding jobs, so I put them together to output smali content.

These smali ouput on screen went pretty well before I switched my font....

![Screenshot_present](https://user-images.githubusercontent.com/66319139/109412871-6db54500-79e5-11eb-880a-49921f8ffe08.png)

after swtiched to a font that has different size for it's characters, and text alignment messed up.

![Screenshot_present2](https://user-images.githubusercontent.com/66319139/109413337-cdaceb00-79e7-11eb-92a1-03812e92e71f.png)


my previous solution is to hardcode a font that has fixed character size for the smali area that shows smali output with
bytecodes, but it did't work because it seems like set font to a RSyntaxTextArea instance will also apply to the others.

So my present solution is to post this comment to ask you, any idea I can manage to do it?

thanks!

**Comment by skylot** [comment]
@LBJ-the-GOAT looks great!
> smali ouput on screen went pretty well before I switched my font....

Well, the only thing I can suggest here, is to make additional settings for fixed size font, so make it separate from editor font.

**Comment by LBJ-the-GOAT** [comment]
> @LBJ-the-GOAT looks great!
> 
> > smali ouput on screen went pretty well before I switched my font....
> 
> Well, the only thing I can suggest here, is to make additional settings for fixed size font, so make it separate from editor font.

Thanks for your advice, I just came up with an idea, count the width of every single character before format them.

**Comment by OdinVex** [comment]
I would rather one of two things:
Use only mono-spaced font and loop through all lines of byte-code to determine max-length and format to that.
Use a second textbox to the left of the src and use a mono-spaced font in it.

**Comment by LBJ-the-GOAT** [comment]
> @LBJ-the-GOAT looks great!
> 
> > smali ouput on screen went pretty well before I switched my font....
> 
> Well, the only thing I can suggest here, is to make additional settings for fixed size font, so make it separate from editor font.

Damn, your suggestion works, OK, I will open a PR soon. Thanks man :)

**Comment by jpstotz** [comment]
As this feature has already been implemented some time ago I think it is time to close this issue.
