### ISSUE TITLE
Mapping backup

### ISSUE THREAD

**Issue by osadchij** [skylot/jadx#1117]
I just lost whole my map file. Coz I could rename some method. At the logs I've saw 'the map file already exists use --deobf-rewrite-cfg" - I DID... (and my backup file of project doest have the map too...)

And now I've lost whole my work :D

Where JADX is storing map file??

**Comment by skylot** [comment]
@osadchij sorry to hear that :(
Deobfuscation map file saved in same directory as file you open with same name but `.jobf` extension.
Also, log message you mention contains a path to map file:
```
"Deobfuscation map file '/path/to/map.jobf' exists. Use command line option '--deobf-rewrite-cfg' to rewrite it"
```
We have an issue to save all renaming in project file: #1022, but it is not yet implemented.

**Comment by osadchij** [comment]
@skylot Sorry, but how to tell JADX to use my own file? If I'll copy one as a backup and in the future I'll want to use it?

**Comment by skylot** [comment]
@osadchij right now you can't change that, sorry :cry:
I can add command line option to allow use custom file.

**Comment by osadchij** [comment]
@skylot It will be very useful <3

**Comment by skylot** [comment]
> I can add command line option to allow use custom file

@osadchij done, cli option `--deobf-cfg-file`, check using [latest unstable build](https://nightly.link/skylot/jadx/workflows/build/master).

**Comment by osadchij** [comment]
@skylot It works AWESOME!! Thanks you alot <3
