### ISSUE TITLE
Making changes to jadx

### ISSUE THREAD

**Issue by Sputuks3** [skylot/jadx#112]
I tried to make some changes to jadx-gui source files, then rerun gradlew.bat dist (Windows) however, after recompiling, and there were no syntax errors as Gradle says build successful. jadx wouldn't start when running jadx-gui.bat. How do I modify jadx to suit my requirements?

**Comment by sergey-wowwow** [comment]
Build docs were updated: 
https://github.com/skylot/jadx#building-jadx-from-source
