### ISSUE TITLE
Extending ClassNode, MethodNode and FieldNode classes

### ISSUE THREAD

**Issue by JeffDerk** [skylot/jadx#1123]
I'm currently using the JadxDecompiler in my project and would like to add extra behavior to the Node classses to do further analysis of the code.
For example I would like to build a Class Graph and would like some additional fields in ClassNode.

Creation of these nodes is burried in the code so it cannot be extended easily... if not at all.
For example a ClassNode is created in RootNode.loadClasses().

I was thinking of making a PR and adding a NodeFactory which is responsible for creating the node classes. This can be passed to the RootNode and so forth...

```
public class NodeFactory {
	public RootNode createRootNode(JadxArgs args) {
		return new RootNode(args, this);
	}

	public ClassNode createClassNode(RootNode root, IClassData cls) {
		return new ClassNode(root, cls, this);
	}

	public ClassNode createClassNode(RootNode root, String name, int accessFlags) {
		return new ClassNode(root, name, accessFlags);
	}

	public MethodNode createMethodNode(ClassNode classNode, IMethodData mthData) {
		return MethodNode.build(classNode, mthData);
	}

	public FieldNode createFieldNode(ClassNode classNode, IFieldData fieldData) {
		return FieldNode.build(classNode, fieldData);
	}

	public FieldNode createBlockNode(ClassNode classNode, IFieldData fieldData) {
		return FieldNode.build(classNode, fieldData);
	}
}
```

I've already made these changes in my fork: https://github.com/skylot/jadx/compare/master...JeffDerk:master

**Comment by skylot** [comment]
@JeffDerk 
I think delegation is a better way to extend classes from other library. This way you don't depend on internal implementation and use only public methods.

**Comment by JeffDerk** [comment]
I would like to make changes to classes and still be able to generate sources afterwards. Extending in this case seems more appropriate to me.

**Comment by skylot** [comment]
Sorry, I don't want to expose internal classes, because I change internals quite often, and this will break your code.
