### ISSUE TITLE
[core] variable shadowing

### ISSUE THREAD

**Issue by glzlaohuai** [skylot/jadx#1124]
**jadx version**: 1.2.0
**jar**  : [classes.zip](https://github.com/skylot/jadx/files/6042207/classes.zip)
**class** : com.kwad.sdk.core.webview.a.g

<img width="931" alt="WeChat9bc52ea1bf396969c0e909f5ec17d8bd" src="https://user-images.githubusercontent.com/2596885/109138944-e58d3080-7795-11eb-8f2f-28312bc8d501.png">

As the screenshot shows, variables that have different types and scopes were given the same name `bVar`.

**Comment by jpstotz** [comment]
Have you tested the [latest unstable build](https://nightly.link/skylot/jadx/workflows/build/master) if the problem still exists? v1.2.0 is already 3 months old, much has changed since that release.

**Comment by glzlaohuai** [comment]
Just tried the latest unstable build, still exists.

**Comment by skylot** [comment]
@glzlaohuai thank you for report!
I commit a fix, so issue must be resolved.
