### ISSUE TITLE
[core] jadx-gui-1.2.0 can not decompile jar | 无法反编译jar

### ISSUE THREAD

**Issue by geekyouth** [skylot/jadx#1128]
![image](https://user-images.githubusercontent.com/12899262/109979718-278c1880-7d3a-11eb-8925-3bb5745571f1.png)

**Comment by jpstotz** [comment]
Looks like a spring-boot jar. lease check out the latest unstable version. There were some changes regarding JAR files that have class files in non-standard locations. Note that effectively your JAR file is not a standard JAR file as it contains classes multiple times. Jadx can not open JAR files directly and has to convert them to Android dex format, which has certain limitations. 

In the end I would suggest to better use a tool that is focused on Java JAR decompiling such as JD-Gui, that will be more suitable for such a JAR file.

**Comment by skylot** [comment]
@geekyouth jadx not very good at handling java bytecode, so looks like you get many errors during conversion to dex (check log window). And BTW decompiled source must be placed under `Source` tree (you got empty because of errors).
