### ISSUE TITLE
hi，I add some code to enable jadx can decompile apk by file's type, not only by file's extension

### ISSUE THREAD

**Issue by bigfool** [skylot/jadx#113]
hi，I add some code to enable jadx can decompile apk by file's type, not only by file's extension.

I just modified jadx/core/utils/files/FileUtils.java and  jadx/core/utils/files/InputFile.java.

my repo: https://github.com/bigfool/jadx

thanks!

**Comment by asashour** [comment]
Would this be interesting, to raise a PR for?

**Comment by skylot** [comment]
@asashour looks like this were already merged
