### ISSUE TITLE
[gui] Search index points to wrong location (latest unstable)

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#1141]
Since commit 4e5fac4b88e2d4a0a2b1b0f7270b569dc4de651f the search index often points to the wrong location.

Take for example this APK

https://apkpure.com/de/battery-alarm/simple.batttery.alarm/download/45-APK?from=versions%2Fversion

Make code search for `return` and select any of the first search results. The selected line seems to be always the method start instead of the return statement. For this example APK the methods are small and the actual search location is obvious but on larger APKs the difference can be up to 1000 lines...

Unfortunately the mentioned commit is pretty big so I wasn't able to identify the problem yet.

**Comment by skylot** [comment]
@jpstotz thanks! I used incorrect offset during code index, now it should work.

**Comment by jpstotz** [comment]
@skylot Thanks for the immediate fix :)
