### ISSUE TITLE
[core] unsupported class file version 55.0

### ISSUE THREAD

**Issue by williamchu123** [skylot/jadx#1142]
![image](https://user-images.githubusercontent.com/5689465/113405795-fbb58e80-93dc-11eb-85a5-f66d1ead35f1.png)

decompile with a jar that  write with java 11

**Comment by jpstotz** [comment]
Jadx can not decompile J2Se class files, therefore it uses `dx` to convert Java class files to Android dex files. 

Unfortunately dx is limited to Java 7 functionality. And for various reasons we can't switch to the newer d8 converter. 

Please use [JD-GUI](http://java-decompiler.github.io) or another Java decompiler for Java class file.
