### ISSUE TITLE
[feature] Allow exporting deobfuscation mapping when using --deobf option

### ISSUE THREAD

**Issue by pgp** [skylot/jadx#1144]
*Describe your idea:*
Do not know if jadx already has this capability... I'm doing some experiments with decompilation of complex apks, and I used the `--deobf` option in order to avoid having classes and packages with the same names. Even this way, importing the decompiled sources and resources in an Android Studio project clearly results in lots of build errors, so I'd like to compare the jadx decompilation outputs with those from apktool and dex2jar to perform further analysis. In order to do this however, I need the mapping that generated the deobfuscated class/method names when using `--deobf`.

**Comment by skylot** [comment]
@pgp jadx already saving rename mapping in `.jobf` file in same folder and same name as input file by default.
