### ISSUE TITLE
Non-hardcoded core.jcst

### ISSUE THREAD

**Issue by titze** [skylot/jadx#1145]
In `ClsSet`, the `CLST_FILENAME` is hardcoded:
https://github.com/skylot/jadx/blob/766e7193b9bb00bfd81bf2979d79a650bbf8c144/jadx-core/src/main/java/jadx/core/clsp/ClsSet.java#L49
I think the used file in 1.2 is for android-29.

If I see it correctly, this is the precomputed class hierarchy. Is there a specific reason why this is hardcoded, and not setable via a configuration? Wouldn't the decompilation of an older Android app be potentially incorrect with and android 29 class hierarchy?

 If so, a configurable clst-file might solve this limitation?

**Comment by skylot** [comment]
@titze this file used as a helper for type inference and in most cases not really needed. Also changes in Android API between versions are quite small compared to the total count of classes and methods. So I think android version in this file will not affect on decompilation result.
