### ISSUE TITLE
Can you just convert.dex files to.class files

### ISSUE THREAD

**Issue by dicce3** [skylot/jadx#1148]
*Describe your idea:*

**Comment by alissonlauffer** [comment]
You can use the [dex2jar](https://github.com/pxb1988/dex2jar) project.

**Comment by skylot** [comment]
@dicce3 just use other tools: like mentioned dex2jar or [enjarify](https://github.com/Storyyeller/enjarify).

**Comment by dicce3** [comment]
Thank you very much, I did it with the latest version of dex2jar.
