### ISSUE TITLE
[core] jadx at master outputs "INFO - loading ..." and then returns, 1.2.0 does more

### ISSUE THREAD

**Issue by carstenhag** [skylot/jadx#1150]
**Describe error**
Installed jadx via `brew install jadx --HEAD`. Via `brew install jadx`, which installs 1.2.0, it at least does more than that (still has 56 errors but thats ok for now).
```
$jadx -d enbw-app-jadx com.enbw.ev_6.9.0.apk
INFO  - loading ...
```
```
$ jadx -v -d enbw-app-jadx/ com.enbw.ev_6.9.0.apk
DEBUG - Loaded plugin: SmaliInput
DEBUG - Loaded plugin: JavaConvert
DEBUG - Loaded plugin: DexInput
DEBUG - Effective jadx args: JadxArgs{inputFiles=[com.enbw.ev_6.9.0.apk], outDir=enbw-app-jadx, outDirSrc=enbw-app-jadx/sources, outDirRes=enbw-app-jadx/resources, threadsCount=6, cfgOutput=false, rawCFGOutput=false, fallbackMode=false, showInconsistentCode=false, useImports=true, skipResources=false, skipSources=false, deobfuscationOn=false, deobfuscationMapFile=null, deobfuscationForceSave=false, useSourceNameAsClassAlias=false, parseKotlinMetadata=false, deobfuscationMinLength=3, deobfuscationMaxLength=64, escapeUnicode=false, replaceConsts=true, respectBytecodeAccModifiers=false, exportAsGradleProject=false, fsCaseSensitive=false, renameFlags=[CASE, VALID, PRINTABLE], outputFormat=JAVA, codeCache=NoOpCodeCache, codeWriter=SimpleCodeWriter}
INFO  - loading ...
```

The app is com.enbw.ev, uploading it to APKMirror atm, but it's not available there yet. It's too big for Github.

**Comment by skylot** [comment]
@carstenhag I tried apk from [here](https://apkpure.com/enbw-mobility-compare-charge-electric-cars/com.enbw.ev/download/119-APK?from=versions%2Fversion) (version 6.9.0) but can't reproduce your issue. Can you check if this a correct apk?

**Comment by carstenhag** [comment]
Doesn't seem to be the same 
```
shasum -a 256 EnBW\ mobility\ Compare\ Charge\ Electric\ Cars_v6.9.0_apkpure.com.apk
80d077ad3272327403368bebd7ac8fcd582b95ff05330b51702963914e317215  EnBW mobility Compare Charge Electric Cars_v6.9.0_apkpure.com.apk
shasum -a 256 com.enbw.ev_6.9.0.apk
c655f1848cd8f427a9f24e10297a9900aef87d545b5fd97b9f30e30f64ffd9b8  com.enbw.ev_6.9.0.apk
```
but I can reproduce the issue with both APKs on my Mac.

Here's the apk: https://drive.google.com/file/d/1uPSYKdwZNRh1idof4uwo6pwYBD_Jz1X-/view?usp=sharing

**Comment by winrg** [comment]
Encountered this same issue, fixed it by changing JVM versions. Try running with Java 11.

**Comment by skylot** [comment]
Ok, this time I am managed to find a way to reproduce this issue and made a fix.
To reproduce jadx should be build using java 11 and next executed with java 8. Doing so we will use not compatible classpaths and got a NoSuchMethodError:
```java
ERROR - Process error:
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at jadx.plugins.input.dex.sections.SectionReader.duplicate(SectionReader.java:60)
```
But because of incorrect handle of errors in jadx-cli `java.lang.Error` exception was ignored and not logged. I commit a fix for that.
So now jadx will show usable error, and it will be easier to understand what is going wrong.

Anyway, I recommend always use the latest java version. Or at least try to not mix compile and runtime java versions.
