### ISSUE TITLE
[core] ProcessAnonymous visitor causes code lost.

### ISSUE THREAD

**Issue by LBJ-the-GOAT** [skylot/jadx#1154]
Hi dear @skylot , I just got a little bug.

When Jadx trying to inline nested `IfNode` it skipped a `Block` that should be inlined in the condition expression.

Correct result:
![present_right](https://user-images.githubusercontent.com/66319139/115154028-6a683c80-a0ab-11eb-8bae-703579bf3bc2.png)

Block skipped:
![present_wrong](https://user-images.githubusercontent.com/66319139/115154039-7522d180-a0ab-11eb-93f0-b9f2b0dc8723.png)

This happens when the class is marked `ANONYMOUS_CLASS` and `DONT_GENERATE`  by `ProcessAnonymous` visitor, 
 I tried to fix it but failed, if comment out this two line in `ProcessAnonymous.class` and the skipped Block will be back again.
```java
			cls.add(AFlag.ANONYMOUS_CLASS);
			cls.add(AFlag.DONT_GENERATE);
```

The error occurs in method `MainActivity.20.run()` ,  or search `0x001e` in `MainActivity` panel to locate the position.

[classes.zip](https://github.com/skylot/jadx/files/6331729/classes.zip)  (about 200KB)

**Comment by skylot** [comment]
@LBJ-the-GOAT nice case!
This is odd that disabling anonymous class inlining (option in preferences) fix this issue.
And looks like an issue in result assign inline :(

**Comment by skylot** [comment]
Fixed :+1:

**Comment by LBJ-the-GOAT** [comment]
> Fixed 👍

Thank you 👍👍👍
