### ISSUE TITLE
Make JADX projects single-file [feature]

### ISSUE THREAD

**Issue by Martyx00** [skylot/jadx#1163]
*Describe your idea:* I would like to propose a new way of handling project files. It may be beneficial to use a single project file rather then *.jadx* and *.jobf*. This would allow for easier collaboration.

**Comment by skylot** [comment]
@Martyx00 I plan to save all renames made by user save to jadx project file (see #1022).
Not sure if we need to copy **all** renames from `.jobf` file, because for same apk will be generated same `.jobf` file.
So I think #1022 will cover your request.
