### ISSUE TITLE
[feature]: add a feature to inline lambda classes

### ISSUE THREAD

**Issue by AlucardTN** [skylot/jadx#1164]
Describe your idea: just i'd like you to add a feature to inline lambdas to original classes or a related feature.

**Comment by skylot** [comment]
@AlucardTN some cases already supported, see #523 with a list of not yet implemented cases.
If you have another case please share a sample apk.

**Comment by AlucardTN** [comment]
@skylot, i decompiled this apk [](https://ufile.io/g9nhxyhr), seems like some lambdas still not aligned, i decompiled it with Jadx-gui for windows

**Comment by skylot** [comment]
@AlucardTN thanks. This is a case with instance field mentioned in #523:
> Some lambda classes used by INSTANCE static field

I will close this issue as duplicate and increase priority of #523 (looks like I totally forget about that).
Anyway thanks for report!

**Comment by AlucardTN** [comment]
yeah no problem, i'm waiting for new update ! ,good luck
