### ISSUE TITLE
[core] Large code makes Jadx slow and laggy

### ISSUE THREAD

**Issue by LGLTeam** [skylot/jadx#1167]
**Checks before report**
- check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
- search existing issues by exception message

**Describe error**
The class ru.geokar2006.modmenu.FloatingModMenuService is large and makes jadx very slow and laggy. My PC is new and fast so nothing wrong with it.

https://drive.google.com/file/d/1b3i64mj7gz4YGRGYkQHWr0q2gG20_8t6/view

**Comment by jpstotz** [comment]
For large apps it may be necessary to assign more heap memory to Jadx. memory management is one of the disadvantages of Java ist is some times a bit unflexible. When Java is running out of RAM it can happen that the garbage collector run amok and uses a lot of CPU resources.
https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#assign-more-ram-eg-6gb-to-jadx

**Comment by skylot** [comment]
@LGLTeam can you share jadx version, java version and system you use?
Because for me (java 15 on linux) jadx-gui works well with your app, and app is quite small, so memory should not be a problem here.

**Comment by LGLTeam** [comment]
@jpstotz i have 4 GB heap size, it didn't used much
![image](https://user-images.githubusercontent.com/61142621/117315363-eaeab380-ae87-11eb-937f-63aa39ccbab2.png)

@skylot I used latest unstable commit because it has some nice features. I tried stable version, no slowdown so i'll use it

**Comment by skylot** [comment]
@LGLTeam I commit various performance improvements. Can you check latest unstable version?

**Comment by LGLTeam** [comment]
> @LGLTeam I commit various performance improvements. Can you check latest unstable version?

Tested, works smoothly without any lags!

**Comment by skylot** [comment]
> Tested, works smoothly without any lags!

Great, thanks!

**Comment by geokar2006** [comment]
> **Checks before report**
> 
> * check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
> * search existing issues by exception message
> 
> **Describe error**
> The class ru.geokar2006.modmenu.FloatingModMenuService is large and makes jadx very slow and laggy. My PC is new and fast so nothing wrong with it.
> 
> https://drive.google.com/file/d/1b3i64mj7gz4YGRGYkQHWr0q2gG20_8t6/view

Why you need my menu?
