### ISSUE TITLE
[build] fail

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1169]
Download the latest source code, but after compiling, the generated **build** folder cannot be found
![QQ截图20210514114901](https://user-images.githubusercontent.com/42903751/118218817-c5514180-b467-11eb-92e4-b4b0227da9e3.png)

**Comment by jpstotz** [comment]
From the pasted screen-shot I can only see that you have execute gradlew but without arguments. 

In such case only Gradle will be downloaded, extracted and prepared for being used by the build process but the actual build process has to be started using `gradlew dist`.

**Comment by xmhwws** [comment]
Thanks, you are right.
