### ISSUE TITLE
[core]smali code has these methods, but pseudo code does not have these methods

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1170]
windows10
Latest beta version of jadx
apk link：https://drive.google.com/file/d/1ns6UdqPvwopEFbLIB1e6s_HXoxWR3N_S/view?usp=sharing
class：**com.bat.conversation.ui.search.SearchMainActivity**

smali code has these methods, but pseudo code does not have these methods
![JADX SMALI](https://user-images.githubusercontent.com/42903751/118608653-74b05000-b7a9-11eb-9ca0-cdee080d2ce1.png)
![JADX1](https://user-images.githubusercontent.com/42903751/118608673-7bd75e00-b7a9-11eb-8019-524db2f61249.png)

in GDA：
![GDA](https://user-images.githubusercontent.com/42903751/118608698-8265d580-b7a9-11eb-8354-943a5df55601.png)

Jadx setting：
![jadx 设置](https://user-images.githubusercontent.com/42903751/118610222-1eb1cb80-b7ee-11eb-8a29-a41e1d1a771b.png)

**Comment by skylot** [comment]
@xmhwws looks like these methods was inlined.
Do you need an option to disable method inlining? Or maybe don't remove methods after inline?

**Comment by skylot** [comment]
Well, this feature already was reported as issue in #1109, so looks like jadx definitely need some improvement here.
Maybe mode for low level compare with bytecode like I mention previously in https://github.com/skylot/jadx/issues/1109#issuecomment-770416610:

Actually it is a big issue in jadx: different people use jadx differently, but I don't want to add switches for every small feature in jadx. That will cause tons of options, and it will be hard to test, reproduce issues and maintain.
I was thinking about some kind of predefined 'profiles' which will combines some switches. I see 3 of them for now:
1. `low-level` - for compare with bytecode, like fallback but more precise (types, var names)
2. `compilable` - for compilation or code analysis - will disable some unstable feature, so code will be more verbose.
3. `readable` - full set of jadx features, result is compact and readable code, possible errors can revert to previous profiles for affected methods or classes.

**Comment by xmhwws** [comment]
> @xmhwws looks like these methods was inlined.
> Do you need an option to disable method inlining? Or maybe don't remove methods after inline?

If these methods disappear due to being inlined, please keep them displayed normally.
I monitored the method calling process of APK and found that these methods were called. Then I didn't find these methods in jadx. I was a little bit crashed at that time.

**Comment by LBJ-the-GOAT** [comment]
Inlining methods is great for reading and understanding the code, meanwhile people may want to hook such inlined methods and it causes inconvenience. 

I think we can keep inlining these methods but don't remove them and add an auto-comment at the places they're being inlined.

**Comment by skylot** [comment]
> comment at the places they're being inlined

Sometime this can be in a complex expression and inserting inplace comment will make it more complex and hard to read.

Anyway, as a quick fix I add an option to completely disable methods inline.
