### ISSUE TITLE
[feature] Show hexdecimal instead decimal in Java view

### ISSUE THREAD

**Issue by LGLTeam** [skylot/jadx#1171]
I'm dealing with resource ID error and wanted to view in jadx to see which ID caused the problem, but the thing is it shows as decimal, i must view as Smali to see the hexdecimal of ID. I know it's easy to see field names in smali but i like to read in Java better, i don't understand smali much.

![image](https://user-images.githubusercontent.com/61142621/118686245-1fedf300-b804-11eb-97b9-e9cede60d6f2.png)

Can we have an option to show hexdecimal instead decimal in Java view? or at least right-click and select Hexdecimal like in IDA Pro?

![image](https://user-images.githubusercontent.com/61142621/118686193-149ac780-b804-11eb-839b-4b9e86b14590.png)

**Comment by skylot** [comment]
@LGLTeam I can make a right-click menu action like `Copy as Hex (0xFF)`, which also shows number in hex.
And yes, I can make a global option to render all numbers in hex format, not sure if it is really needed, but it is possible.

P.S.: As workaround you can export java code to Android Studio, next `Ctrl+Enter` on number and select `Convert number to ...`

**Comment by skylot** [comment]
As @LBJ-the-GOAT suggested in PR #1173 I made a hex format for IDs in R class.
@LGLTeam if you still want other option let me know :D

**Comment by LGLTeam** [comment]
The PR one is enough for me :)

**Comment by psolyca** [comment]
Hey ^^
Could this be reopened ?
I'd like an option to globally have hex number format.
My project uses hex numbers and converting dec to hex or hex to dec is a pain.
Thanks

**Comment by skylot** [comment]
> I'd like an option to globally have hex number format

@psolyca ok, I can do that

**Comment by FabianPastor** [comment]
Sorry for comenting it here, not suer if it's worth to open a new "issue"...
I am now at 1.4.4 and upgraded from 1.1.0 and by using the cli jadx i noticed that R.java and probably other places it changed all from decimal to hexadecimal.

Just asking to have some kind of flag to go back to the old behavior. Just leaving it here. If there are no plans to add it i'll deal with it xD. 
Thank you :D

**Comment by skylot** [comment]
Global option added by @Arsylk in PR #1869.
Auto - mode will use hex for resources values, dec - for others. Other modes will force selected type everywhere.
