### ISSUE TITLE
[core] Case-sensitive method names different across jadx and APKTool

### ISSUE THREAD

**Issue by Luffitys** [skylot/jadx#1177]
Jadx and APKTool output a different method name from an obfuscated apk, both in the java and smali code. Notice the case-sensitive name of the method.
Example below:
The found issue is in the class com.mi.device, shown here as smali code
Jadx: .method public Ooooooo()I
APKTool: .method public OooooOo()I

Link to the apk: https://drive.google.com/file/d/1blMTZaPYRGLaVmgdsi3l2Emow4WPzcfb/view?usp=sharing

**Comment by skylot** [comment]
@Luffitys can you specify full class name?

**Comment by Luffitys** [comment]
@skylot That would be com.mi.device.Umi in this case.

**Comment by skylot** [comment]
Hm, anyway I only found method `com.mi.device.Umi.Ooooooo()I`:
```java
    public int Ooooooo() {
        return 5;
    }
```
and can't find method `com.mi.device.Umi.OooooOo()I` either in apktool, jadx or dexdump output.
So please check again your names.
