### ISSUE TITLE
[core]smali code has these methods, but pseudo code does not have these methods

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1178]
windows10
Latest beta version of jadx
apk link：https://drive.google.com/file/d/1ns6UdqPvwopEFbLIB1e6s_HXoxWR3N_S/view?usp=sharing
class：**com.bat.conversation.ui.activity.GroupListActivity.e**
method: **a**

![image](https://user-images.githubusercontent.com/42903751/119342482-b8361d00-bcc7-11eb-882d-a9dcff17dfe6.png)
![image](https://user-images.githubusercontent.com/42903751/119341973-039bfb80-bcc7-11eb-9eab-87d70c2fd3a7.png)

in GDA:
![image](https://user-images.githubusercontent.com/42903751/119342092-25957e00-bcc7-11eb-8bce-368c5435c364.png)

jadx settings:
![image](https://user-images.githubusercontent.com/42903751/119342145-36de8a80-bcc7-11eb-8c58-bfdcf4df7cad.png)

Similar to the previous question: https://github.com/skylot/jadx/issues/1170#issuecomment-843040490

**Comment by skylot** [comment]
Hm, this code change technically is a rename and it is linked to rename flags, so you need to untick `rename valid identifiers` checkbox.

Also, as a workaround you can comment line with `passes.add(new ClassModifier());` in Jadx class: https://github.com/skylot/jadx/blob/8785c33d065baf0454ce1469bee22651bf306379/jadx-core/src/main/java/jadx/core/Jadx.java#L154

that visitor contains lots of various code changes for synthetic and bridge methods.

**Comment by xmhwws** [comment]
> Hm, this code change technically is a rename and it is linked to rename flags, so you need to untick `rename valid identifiers` checkbox.

You are right.
But what is the function of `rename valid identifiers`? I can't understand it literally

**Comment by skylot** [comment]
> But what is the function of rename valid identifiers? I can't understand it literally

I see, it must be `Rename class, method and field identifiers to make them valid`. So this flag renames any identifier if current name can make code incorrect.
For your case: synthetic or bridge methods can have same names with methods they wrap, so this case toggles with this switch.

I will reword current names for rename flags in cli and gui to make it more clear:
```
Rename identifiers:
- To fix case sensitivity issues
- To make them valid
- To make printable
```

 I hope it will help.
