### ISSUE TITLE
Get some defpackage

### ISSUE THREAD

**Issue by veryyoung** [skylot/jadx#118]
For example

```
import defpackage.ul$a;
import defpackage.ul$b;
import defpackage.uo;
import defpackage.up;
import defpackage.vd;
import defpackage.vj;
import defpackage.vk;
import defpackage.vl;
import defpackage.vm;
import defpackage.vm$1;
import defpackage.vq;
import defpackage.wd;
import defpackage.wl;
import defpackage.wr;
import defpackage.ws;
import defpackage.wt;
import defpackage.wv;
import defpackage.xf;
import defpackage.xm;
import defpackage.yf$e;
import defpackage.yf$h;
import defpackage.yf$j;
```

**Comment by redmi111** [comment]
Same issue here. @skylot Can you please explain what is this.

**Comment by jpstotz** [comment]
The app is obfuscated and the "defpackage" is the default package `""` (the packe without name). 
The problem is that in the Jadx treeview an entry without name is not (or really difficult) clickable. Therefore "defpackage" is used as replacement.

**Comment by skylot** [comment]
Actually "defpackage" used for another reason: code will be not compilable if class in default package use any class from other packages, but such classes often use outside classes, so this is easy way to make code compilable.
