### ISSUE TITLE
jadx-gui:createExe FAILED on Ubuntu 20.04

### ISSUE THREAD

**Issue by ZRunner** [skylot/jadx#1180]
When trying to compile jadx on my Ubuntu from git (like explained in your readme), gradle fails "for task ':jadx-gui:createExe'"
I re-ran the script with the --stacktrace and --info arguments, and put the whole output at https://pastebin.com/1rZz6NW0

TL;DR:
> What went wrong:
Execution failed for task ':jadx-gui:createExe'.
> net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (1): /home/XXX/Downloads/jadx/jadx-gui/build/tmp/launch4j/bin-launch4j-3.14/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /tmp/launch4j6963948432918856200rc /tmp/launch4j3547856662205766667o

About my java version:
> openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

Tell me if you need anything else

**Comment by alissonlauffer** [comment]
Looks like this is the same issue as #1062, have you run gradle with sudo? If yes, please retry without it.

**Comment by ZRunner** [comment]
Nope I didn't, I was using my regular account as usual. Also the error message is not exactly the same if I'm right ^^

**Comment by jpstotz** [comment]
@ZRunner what architecture is your Ubuntu 20.04 installation? execute `file windres` on the mentioned executable that can not be executed and check if it's architecture matches your system architecture. Launch4J only supports 32/64bit x86 architectures for Linux.

**Comment by ZRunner** [comment]
I couldn't find any file called createExe in the jadx-gui folder, except an xml file (which is obviously not executable lol)
But according to the nice `uname -m` command, I'm running on a x86_64 architecture, so that shouldn't be a problem
Btw I tried to download directly from the last "unstable" build (https://nightly.link/skylot/jadx/workflows/build/master) and that seems to work fine.

**Comment by skylot** [comment]
As workaround, I can suggest running `./gradlew dist -x copyExe` to disable `.exe` building.
And I think I will disable this task by default on not windows because most users don't need exe on linux :rofl:

**Comment by ZRunner** [comment]
All's good, thanks for the workaround and glhf ^^
