### ISSUE TITLE
[bug] Can't rename local variable to same name as global class variable

### ISSUE THREAD

**Issue by Iscle** [skylot/jadx#1183]
Sometimes, especially in constructors, people tend to name the parameters with the same name as the global class variables, and then assign them using `this.variableName = variableName;`, however, with jadx, if you try to rename the parameter to have the same name as the global class variable, a "2" will be added automatically at the end.

It would be nice for code readability to be able to use the same name since the decompiler already includes the "this." qualifier before every class variable.

**Comment by skylot** [comment]
@Iscle you right, variables forbid to have fields name, but I don't remember why this was done that way. And now I don't see any downside for your suggestions, so I think this can be fixed.

**Comment by skylot** [comment]
@Iscle done
