### ISSUE TITLE
[feature]Can Jadx expand the expression?

### ISSUE THREAD

**Issue by 101142TS** [skylot/jadx#1184]
*Describe your idea:*
Hello,
Can Jadx expand the expression（Similar to three address codes）？This will make it easier to do other analysis.

Code A and code B are semantically the same. Code A is generated by Jadx. For code B, I just expanded the expression in code A.

code A:
```Java
public final ZipEntry getNextEntry() {
        String name;
        ZipEntry nextEntry = super.getNextEntry();
        if (nextEntry == null || (name = nextEntry.getName()) == null || (!name.contains("../") && !name.contains("..\\"))) {
            return nextEntry;
        }
        throw new SecurityException(":" + nextEntry.getName());
    }
```
```Java
public final ZipEntry getNextEntry() {
        String name;
        ZipEntry nextEntry = super.getNextEntry();
        if (nextEntry == null)
            return nextEntry;
        ZipEntry c = nextEntry;
        name = c.getName();
        if (name == null)
            return nextEntry;
        
        boolean b1 = !name.contains("../");
        boolean b2 = !name.contains("..\\");
        if (b1 && b2)
            return nextEntry;

        throw new SecurityException(":" + nextEntry.getName());
    }
```

Thx! :D

**Comment by skylot** [comment]
@101142TS yeah, I also don't like long conditions. And here we have two issues actually:
1. Very aggressive assign inlining, without it code will look like this:
```java
public final ZipEntry test() {
	ZipEntry nextEntry = getNextEntry();
	if (nextEntry != null) {
		String name = nextEntry.getName();
		if (name != null && (name.contains("../") || name.contains("..\\"))) {
			throw new SecurityException(":" + nextEntry.getName());
		}
	}
	return nextEntry;
}
```
2. Jadx now trying not to duplicate code, so only one return used. I can force early return here to make code looks like this:
```java
public final ZipEntry test() {
	ZipEntry nextEntry = getNextEntry();
	if (nextEntry == null) {
		return nextEntry;
	}
	String name = nextEntry.getName();
	if (name == null || (!name.contains("../") && !name.contains("..\\"))) {
		return nextEntry;
	}
	throw new SecurityException(":" + nextEntry.getName());
}
```
And for last condition I don't see a reason to break it further.

Anyway, I will implement both of these fixes, but it is hard and  very error-prone, so it will take some time.

**Comment by 101142TS** [comment]
Thanks for the reply！

I'm using [_semgrep_](https://semgrep.dev/) to match vulnerability patterns in Android applications.  

However, semgrep cannot match statements in nested expressions. That's why I need to break all the expressions.

Would it be difficult to implement expressions split on my own by modifying Jadx?

**Comment by skylot** [comment]
> Would it be difficult to implement expressions split on my own by modifying Jadx?

I made a quick mod for you: check 6996f94 in [mod-1184](https://github.com/skylot/jadx/tree/mod-1184) branch:
```java
    public final ZipEntry test() {
        ZipEntry nextEntry = getNextEntry();
        if (nextEntry == null) {
            return nextEntry;
        }
        String name = nextEntry.getName();
        if (name == null) {
            return nextEntry;
        }
        boolean contains = name.contains("../");
        if (!contains) {
            boolean contains2 = name.contains("..\\");
            if (!contains2) {
                return nextEntry;
            }
        }
        throw new SecurityException(":" + nextEntry.getName());
    }
```
Although, these changes may not work for some other cases :(

**Comment by 101142TS** [comment]
Thx, I will try it! :D

**Comment by 101142TS** [comment]
> Although, these changes may not work for some other cases :(

mod-1184 branch worked very well for most expressions, except for a few examples.

```Java
// Generated by jadx 1.2.0
ZipEntry nextEntry = zipInputStream.getNextEntry();
if (nextEntry != null) {
    String name = nextEntry.getName();
    if (name == null || !name.contains("../")) {
        if (name == null || !name.equals(aPKInfo.iconPath)) {
            zipInputStream.closeEntry();
        } else {
            ByteArrayOutputStream byteArrayOutputStream2 = new ByteArrayOutputStream();
        }
    }
}

```
```Java
// Generated by jadx mod-1184 branch
ZipEntry nextEntry = zipInputStream.getNextEntry();
if (nextEntry != null) {
    String name = nextEntry.getName();
    if (name != null) {
        boolean contains = name.contains("../");
        if (contains) {
        }
    }    //Here I think it should be an else code block
    if (name != null) {
        boolean equals = name.equals(aPKInfo.iconPath);
        if (equals) {
            ByteArrayOutputStream byteArrayOutputStream2 = new ByteArrayOutputStream();
      
        }
    }
    zipInputStream.closeEntry();
}

```

**Comment by skylot** [comment]
> //Here I think it should be an else code block

Well, `else` is not enough here, it must be a duplicated code or return (if this is last statements).
You can check it yourself using IntelliJ IDEA with only `Invert 'if' conditions` and `Split into 2 if expressions` transformations, it will duplicate code to the hell :rofl: 

So this is kind of limitations here, jadx don't duplicate code now, and I am not sure if this can be fixed.
Also, jadx can't produce 100% correct code and there are always some errors exists, so be careful and don't rely much on decompiled code.
