### ISSUE TITLE
Error in the processing of code inside the implemented methods[core]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#1186]
![image](https://user-images.githubusercontent.com/35992798/120913000-6753fa80-c6b1-11eb-923e-574673e34608.png)

Attached the image for reference and I checked the older version of JADX such as 1.0 and in that those lines of codes are decompiled well. It is mostly method call or declaring values to fields. But the latest JADX versions adds the random method name which doesn't exist in the parent class or same class. Also, it would be awesome if the parameters are directly used instead of declaring it again (resulting in an unknown declaration like r1 or r2 as you can see in the image)

**Comment by skylot** [comment]
@redmi111 these issues is a part of #523. Right now not all lambda methods are inlined, but if method used it should not be removed, at least I don't find such cases after quick search. Can you share your apk sample and full class name, so I can check your case?
