### ISSUE TITLE
[core] [patches included] Prevent duplicated Override-annotations + minor optimization

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#1188]
I would like to propose two minor patches (tested with latest git version 592eef3):

The first patch prevents duplicated Override-annotations. This is the case if the bytecode contains explicit Override-annotations. See this smali example:

```smali
###### Class others.TestExplicitOverride (others.TestExplicitOverride)
.class public Lothers/TestExplicitOverride;
.super Ljava/lang/Exception;
.source "TestExplicitOverride.java"


# direct methods
.method public constructor <init>()V
    .registers 1

    .prologue
    .line 3
    invoke-direct {p0}, Ljava/lang/Exception;-><init>()V

    return-void
.end method


# virtual methods
.method public getMessage()Ljava/lang/String;
    .registers 2

    .annotation runtime Ljava/lang/Override;
    .end annotation

    .prologue
    .line 7
    invoke-super {p0}, Ljava/lang/Exception;->getMessage()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method
```

Decompiled output is:

```java
package others;

public class TestExplicitOverride extends Exception {
    @Override // java.lang.Throwable
    @Override
    public String getMessage() {
        return super.getMessage();
    }
}
```

Such cases can be found in this app: Java Manager 2.2 (https://java-manager-emulate-java.apk.gold/) e.g. in this method: com.java.manager.DecompileClassActivity.onCreate()

The second patch attached is a minor optimization: Skip override detection for private methods.

Thank you for reviewing my attached patches: [override_annotation_patches.zip](https://github.com/skylot/jadx/files/6643315/override_annotation_patches.zip).

**Comment by skylot** [comment]
@nitram84 thanks for report that case! But unfortunately I can't download your patches because GitHub says `Not found` for that file. Can't you upload it again or maybe open PR (it will be easier to review)?

**Comment by skylot** [comment]
Thanks @nitram84 !
