### ISSUE TITLE
[core] Non-printable chars are not escaped

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1195]
Hey @skylot 

I've noticed that non-printable Unicode characters are not escaped like in the original file https://android.googlesource.com/platform/frameworks/support/+/a9ac247af2afd4115c3eb6d16c05bc92737d6305/compat/src/main/java/androidx/core/util/PatternsCompat.java

It's decompiled to e.g. 
```java
    public static final java.util.regex.Pattern WEB_URL = java.util.regex.Pattern.compile("(((?:(?i:http|https|rtsp)://(?:(?:[a-zA-Z0-9\\$\\-\\_\\.\\+\\!\\*\\'\\(\\)\\,\\;\\?\\&\\=]|(?:\\%[a-fA-F0-9]{2})){1,64}(?:\\:(?:[a-zA-Z0-9\\$\\-\\_\\.\\+\\!\\*\\'\\(\\)\\,\\;\\?\\&\\=]|(?:\\%[a-fA-F0-9]{2})){1,25})?\\@)?)?(?:" + DOMAIN_NAME + ")(?:\\:\\d{1,5})?)([/\\?](?:(?:[a-zA-Z0-9[ -퟿豈-﷏ﷰ-￯𐀀-🿽𠀀-𯿽𰀀-𿿽񀀀-񏿽񐀀-񟿽񠀀-񯿽񰀀-񿿽򀀀-򏿽򐀀-򟿽򠀀-򯿽򰀀-򿿽󀀀-󏿽󐀀-󟿽󡀀-󯿽&&[^ [ - ]   　]];/\\?:@&=#~\\-\\.\\+!\\*'\\(\\),_\\$])|(?:%[a-fA-F0-9]{2}))*)?(?:\\b|$|^))");
```

APK is the same: https://drive.google.com/file/d/1qC3tlWs9AtPBpyS6iU9kcSphLryfJOxi/view

**Comment by jpstotz** [comment]
If you enable Unicode escaping in preferences then they look like `UCS_CHAR` field in source code. 

I am not sure if there is an easy way to identify which characters are printable on the local system and the selected font and which not. Especially as we have to deal with different OS, different Java versions and different fonts.

**Comment by bagipro** [comment]
@jpstotz 
Oh yeah, thanks! I forgot to enable that setting
