### ISSUE TITLE
[core]The pseudo code shows the incorrect class name

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1198]
windows10
Latest beta version of jadx
apk link：https://drive.google.com/file/d/1ns6UdqPvwopEFbLIB1e6s_HXoxWR3N_S/view?usp=sharing
class：com.bat.base.viewmodel.GroupInfoVM
method: public final java.lang.Object I(@org.jetbrains.annotations.NotNull java.util.List<com.bat.base.database.entity.GroupInfoTable> list, long j2, @org.jetbrains.annotations.NotNull kotlin.coroutines.d<? super kotlin.z> dVar)
![image](https://user-images.githubusercontent.com/42903751/123034022-5b8b6680-d41b-11eb-9b9b-3f0a429a305b.png)

The pseudo-code shows the class: `com.bat.base.database.a.a`, but the actual class name is: `com.bat.base.database.a`

jadx settings:
{
  "flattenPackage": false,
  "checkForUpdates": false,
  "fontStr": "",
  "smaliFontStr": "Monospaced.plain/plain/14",
  "editorThemePath": "/org/fife/ui/rsyntaxtextarea/themes/default.xml",
  "langLocale": {
    "locale": "zh_CN"
  },
  "autoStartJobs": false,
  "excludedPackages": "android androidx",
  "autoSaveProject": false,
  "showHeapUsageBar": true,
  "codeAreaLineWrap": true,
  "srhResourceSkipSize": 3,
  "srhResourceFileExt": ".xml|.html|.js|.json|.txt",
  "keepCommonDialogOpen": false,
  "smaliAreaShowBytecode": false,
  "mainWindowVerticalSplitterLoc": 300,
  "debuggerStackFrameSplitterLoc": 300,
  "debuggerVarTreeSplitterLoc": 700,
  "adbDialogPath": "",
  "adbDialogHost": "localhost",
  "adbDialogPort": "5037",
  "treeWidth": 495,
  "settingsVersion": 12,
  "skipResources": false,
  "skipSources": false,
  "exportAsGradleProject": false,
  "threadsCount": 5,
  "showInconsistentCode": true,
  "useImports": false,
  "debugInfo": true,
  "addDebugLines": false,
  "inlineAnonymousClasses": true,
  "inlineMethods": false,
  "replaceConsts": true,
  "escapeUnicode": false,
  "respectBytecodeAccessModifiers": true,
  "deobfuscationOn": false,
  "deobfuscationMinLength": 3,
  "deobfuscationMaxLength": 64,
  "deobfuscationForceSave": true,
  "deobfuscationUseSourceNameAsAlias": true,
  "deobfuscationParseKotlinMetadata": true,
  "renameFlags": [],
  "fsCaseSensitive": false,
  "cfgOutput": false,
  "rawCfgOutput": false,
  "fallbackMode": false
}

**Comment by jpstotz** [comment]
@xmhwws Sorry my Chinese isn't the best, it would be better if you would use the "Copy to clipboard" button and then paste that content instead of the settings screen shot.

**Comment by xmhwws** [comment]
@jpstotz  I have changed the content as you said

**Comment by skylot** [comment]
@xmhwws I don't see any issue here. `com.bat.base.database.a` is a class and next `a` is a static final field in that class of the same type, so the method invoked on that static field. Smali code looks like this:
```smali
    sget-object v1, Lcom/bat/base/database/a;->a:Lcom/bat/base/database/a;
    invoke-virtual {v1}, Lcom/bat/base/database/a;->g()Lcom/bat/base/database/k0/w0;
```
Also, jadx-gui correctly highlight these parts and navigation also works well.

Maybe we need to add some kind of tooltip for easier understanding, or maybe somehow mark static fields (like using bold font).

**Comment by xmhwws** [comment]
@skylot Sorry, I made a mistake, I mistakenly thought it was a class
