### ISSUE TITLE
Smali can be packaged as a JAR for confused Smali

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#1206]
Although you closed my issues yesterday, I still want to tell you that the tool JADX is not able to restore all the source code so that the source code compilation project can pass.Not confused with Smali, I just need to package some of the packages into a JAR.But now that I've packaged the obfuscated Smali, the JADX anti-obfuscated code can't be called.So I want the JADX tool to have an option to set up parts of the package to be JARs so that the entire project can compile and pass.

**Comment by jpstotz** [comment]
Based on the info displayed by GitHub you closed your own issue yesterday: https://github.com/skylot/jadx/issues/1205#event-4987357645
May you accidentally used the button "Close with comment" to post new info to the issue?

**Comment by zgfflc** [comment]
Oh, I'm so sorry.Can you understand my needs now?thank you!

**Comment by jpstotz** [comment]
Sorry but the language barrier seems to be too heavy at least I simply don't understand what you are talking about.

I am closing this issue in favor of #1205. If you think it is a valid feature request feel free to reopen it (should should be able to do so as you are the issue author).
