### ISSUE TITLE
[core] Broken AndroidManifest.xml

### ISSUE THREAD

**Issue by AndnixSH** [skylot/jadx#1208]
**Describe error**
I came across an APK with comes with broken AndroidManifest.xml which looks like obfuscation. This is not the first time i have seen this, other apk did come out as this as well when decompiled using apktool.jar, and i had already reported this issue on apktool repo as well, now it seems they already fixed it

Can jadx be implemented the fix as well?

APK https://apkcombo.com/apk-downloader/?package=com.abiss.roem&device=default&arches=armeabi-v7a&sdkInt=default&format=apk&dpi=480&lang=en

![image](https://user-images.githubusercontent.com/40742924/126072526-209db35a-e260-4e22-8b5d-2e7db388ec8a.png)

**Comment by jpstotz** [comment]
An interesting manifest. The XML strings pool contains obfuscated value, only the AndroidResMap contains the real value.

Currently Jadx prefers the value from xml strings pool and only uses the one from AndroidResMap if it is missing the the strings pool. Assuming all the entries in AndoridManifest.xml in the APK you found are valid (and not just garbage aiming in hiding the relevant entries) then Android seems to work the other way around, first check AndroidResMap and the the string pool.

I have prepared a branch with this change which works on the linked APK file. But I have not tested this [new branch](https://github.com/jpstotz/jadx/commits/manifest_attr) on other APK files.

Just the changes: https://github.com/jpstotz/jadx/commit/b71fac78ad594ffefef1f7bf8c2478afedd75b51

**Comment by skylot** [comment]
Should be fixed by PR #1214.
