### ISSUE TITLE
Search "Resource" does not actually work

### ISSUE THREAD

**Issue by swg0101** [skylot/jadx#1209]
It looks like jadx allows searching of resources via a separate checkbox in the nightlies (jadx-1.2.0.90-b5720bd1), but it looks like it doesn't actually search any resources. For example, grabbing a string within AndroidManifest.xml and putting that into the search box yielded no results even when all the checkboxes are checked. If the resource checkbox was meant for something other than "Resources", then it would be awesome if searching for resources was actually allowed, especially since jadx already decodes all the resources anyways.

This can be greatly useful when an app places attributes within strings.xml that you would otherwise have to search manually via aapt dump or some other mechanism.

**Comment by LBJ-the-GOAT** [comment]
Hi, you can try to increase the ' skip file size' threshold in the 'setting panel', the default value is '3MB' which is quite low for big apps. 😃

**Comment by swg0101** [comment]
Thanks - the value is already set to 256M but resources still are not being researched there. Memory is also readily available and is set to 8GB. Seems like the nightly is also missing some inner classes that get picked up by the stable version. I am guessing that it is a nightly bug somewhere... :)

**Comment by jpstotz** [comment]
@swg0101 Searching for something in AndroidManifest.xml works without problems for me using the latest unstable version. 

If you have problems please post your APK, your Jadx prefernces (use copy to clipboard) and what search term you were trying to find which wasn't found in by the `Resources` text search.

**Comment by swg0101** [comment]
Indeed the latest version works as expected - thank you!
