### ISSUE TITLE
inline method recursive call cause jadx into infinite loop

### ISSUE THREAD

**Issue by newskysecurity** [skylot/jadx#121]
When running on Baidu Tieba apk, jadx ran into infinite loop. Eventually it will exhaust memory and show deep nested call on producing code for inline method recursive call.

Root cause:
Insngen.java line 743, need to check if the inline method is invoking recursively.

**Comment by sergey-wowwow** [comment]
@newskysecurity 
Current version of jadx doesn't contain any known infinite loops. 

I also downloaded Baidu Tieba from this link http://c.tieba.baidu.com/c/s/download/pc, and it was decompiled successfully without any endless loops
