### ISSUE TITLE
Allow drag and drop reordering of tabs

### ISSUE THREAD

**Issue by swg0101** [skylot/jadx#1212]
It looks like jadx does not currently allow the reordering of tabs via drag and drop. If you have a lot of tabs open, it might be helpful to allow this so you are keeping all your interesting code close together rather than clicking through the different tabs to find which one you were working on.

**Comment by AdwitiyaMishra** [comment]
Hi @swg0101, is the issue still available? I would like to work on it. Can you assign it to me?

**Comment by AndreiKud** [comment]
@skylot could you provide status for this please? It's not clear from https://github.com/skylot/jadx/pull/1225
If it's not in work, I'd like to give it a shot. I'll tell you if it's too much for me in a couple weeks.

**Comment by skylot** [comment]
@AndreiKud this is not yet implemented, so if you want you can start working on it :+1:
In PR #1225 there are some implementation issues and author decided to stop working on it, but, I think, it is fine to reuse some code from that PR if you want to :slightly_smiling_face:
