### ISSUE TITLE
Nightly ea8b9ce4 missing some Kotlin inner classes?

### ISSUE THREAD

**Issue by swg0101** [skylot/jadx#1215]
I am comparing the stable 1.2.0 version and the nightly build, and although the nightly build seems much easier to use, I am finding that it sometimes is missing some inner classes that appear in the stable 1.2.0 version. 

Take this apk, for example, with obfuscation disabled:

Under io.fotoapparat.selector, the class tree looks very different between 1.2.0 stable and the nightly version:

Under the stable version, it looks like this:
<img width="239" alt="selector-stable" src="https://user-images.githubusercontent.com/14957466/126882168-eebbbf11-b6f8-4d34-b18e-391cdef91b76.png">

You can see that under PreviewFpsRangeSelectorsKt, there is an inner class called highestFixedFps.

However, this is completely missing on the nightly build:
<img width="289" alt="selector-nightly" src="https://user-images.githubusercontent.com/14957466/126882223-f28adae2-c2e4-4845-a53d-06a73aab0d39.png">

Likewise, using a code search to look for code that matches that name, you can see that both versions look very different:
<img width="817" alt="search-stable" src="https://user-images.githubusercontent.com/14957466/126882239-ac335fa5-e072-443a-8f1e-db995cfbbf27.png">

versus the nightly version:
<img width="1156" alt="search-nightly" src="https://user-images.githubusercontent.com/14957466/126882214-1e5d4e9b-06a5-4eea-ae3b-5ba2a7608902.png">

Am I missing something here? If I were to extract the class files directly from the apk and then run it through the nightly build they would appear by themselves, but I am not sure why they don't appear directly when an apk is opened, especially when they existed fine in 1.2.0 stable.

[ee.mtakso.client_CA.19.2-1726_minAPI21(nodpi)_apkmirror.com.zip](https://github.com/skylot/jadx/files/6873110/ee.mtakso.client_CA.19.2-1726_minAPI21.nodpi._apkmirror.com.zip)

**Comment by skylot** [comment]
@swg0101 thanks for report!
Current support for inlining anonymous/lamdba classes is not complete (check #523), so you can disable this feature in preferences (`Inline anonymous classes` checkbox).
Anyway, I made a quick fix to keep classes for such cases if inline is enabled, check latest build.

**Comment by swg0101** [comment]
Thank you - works as expected!
