### ISSUE TITLE
Correct processing of anonymous classes: OuterClass.this is outputed by wrong way

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#122]
Hi. I often see these constructions:

```java
    private AudioFileReadyListener k = new AudioFileReadyListener(this) {
        final /* synthetic */ AudioService a;
        {
            this.a = r1;
        }

        public final void OnAudioFileReady(final String str) {
            this.a.e.post(new Runnable(this) {
                final /* synthetic */ AnonymousClass4 b;

                public final void run() {
                    Intent intent = new Intent("audioserviceexample.FILE_READY");
                    this.b.a.sendBroadcast(intent);
                }
            });
        }
    };
```

But in real compiled code there is no `final /* synthetic */ AudioService a;` this statement.
`this.b.a.sendBroadcast(intent);` is actually `OuterClass.this.sendBroadcast(intent);`
Is there a chance that it is fixed? Thanks

**Comment by sergey-wowwow** [comment]
@skylot can you review this please? Extremely often bug and annoying

**Comment by skylot** [comment]
Ok, I will try to fix this

**Comment by sergey-wowwow** [comment]
@skylot 
Is that a hard thing to fix? Including embedded anonymous classes into anonymous classes

**Comment by sergey-wowwow** [comment]
@skylot 
You may observe such behaviour in WPS APK: https://drive.google.com/open?id=1a1qZtmu8ViLoRLkPQE28oSNb13LV9yuJ

Just search for ``` final /* ``` and you will find a lot of wrong constructions. E.g. in class ``` cn.wps.moffice.pdf.PDFReader ```:
```java
    private Runnable ixB = new Runnable(this) {
        final /* synthetic */ PDFReader ixC;

        {
            this.ixC = r1;
        }

        public final void run() {
            this.ixC.exit();
        }
    };
```

**Comment by skylot** [comment]
@sergey-wowwow  found and fixed that stupid bug in hardcoded field name ((

**Comment by sergey-wowwow** [comment]
@skylot 
Checked on a few apps -- seems to be fixed! Anonymous classes were changed to inner classes, but I don't think it's a problem. Thanks!
