### ISSUE TITLE
[core] Gradle issue

### ISSUE THREAD

**Issue by srk2014** [skylot/jadx#1222]
Team:
Thanks for offering this tool. Lately, "Save as gradleproject" feature is not working for me. Nothing has changed since the time when I had this option functional. Could you clarify the steps involved in creating the gradle project, and whether I need to do anything specific to make this work?
OS: Ubuntu 20.0.4

**Comment by srk2014** [comment]
Thanks for your response.

It was downloaded from here, ttps://github.com/skylot/jadx. I believe that it is v1.2.0.

**What does "not working for me" means? Is there an error occurring, are files missing in the generated gradle project or what else is wrong? Does it happen with every app or only with some or one specific app?**

During times when the save as gradle project option was functional, I would see a progress bar upon selection of the folder where it needs to be saved. Lately, I don't see that happening, and I don't even see an error message.  I even tried to restart the device to see whether it has anything to do with it, and that did not help either.

at jadx.core.export.ExportGradleProject.getApplicationParams(ExportGradleProject.java:116)
	at jadx.core.export.ExportGradleProject.<init>(ExportGradleProject.java:49)
	at jadx.api.JadxDecompiler.getSaveExecutor(JadxDecompiler.java:239)
	at jadx.api.JadxDecompiler.getSaveExecutor(JadxDecompiler.java:207)
	at jadx.api.JadxDecompiler.save(JadxDecompiler.java:172)
	at jadx.gui.JadxWrapper.lambda$saveAll$1(JadxWrapper.java:69)
	at java.lang.Thread.run(Thread.java:748)

**Comment by MrIkso** [comment]
@srk2014 i'm tested now this, export working. Use latest snapshot.

**Comment by srk2014** [comment]
> @srk2014 i'm tested now this, export working. Use latest snapshot.

Thanks. Could you elaborate further? Your comment is not clear to me. 

Can I also know what OS system, which version, and how you exported the gradle project?

**Comment by MrIkso** [comment]
OS Windows 10. Im looked logs and [this code](https://github.com/skylot/jadx/blob/667cae2e62b0a6ed713ddc4659564de925546350/jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java#L116), your app maybe not contains attribute `android:label` in AndroidManifest.xml?

**Comment by srk2014** [comment]
> OS Windows 10. Im looked logs and [this code](https://github.com/skylot/jadx/blob/667cae2e62b0a6ed713ddc4659564de925546350/jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java#L116), your app maybe not contains attribute `android:label` in AndroidManifest.xml?

I checked the manifest file, and there is a label defined within the app. For that matter, all the apps that I develop include a label section.

**Comment by MrIkso** [comment]
Maybe this attribute use this format? `android:label="My app name"`
Send full error log and problem app.

**Comment by srk2014** [comment]
> Maybe this attribute use this format? `android:label="My app name"` without reference to strings.
> Send full error log and problem app.

Coming to which app is throwing an error, right now, none of the created apk files are exporting the gradle project. For that matter, it was functional a couple of days ago, though it was more of a hit or miss generally. Note: I don't have any issue opening the file or accessing the content. Only the export part is not working.

Please see the attached image of a section of the manifest file.
![Screenshot from 2021-08-04 19-36-44_androidmanifestfile](https://user-images.githubusercontent.com/7888154/128273747-debfd001-7b70-4ccd-b697-1169b2e191bc.png)

Please see the full log for one of the apps that I tested today - This is a compiling app on Android Studio. I tried to open the created apk file using jadx-gui.

INFO  - output directory: app-release
INFO  - loading ...
INFO  - Loaded classes: 5983, methods: 45620, instructions: 1177410
WARN  - Incorrect args count in method signature: ()V in androidx.activity.result.ActivityResultCallerLauncher$resultContract$2.1.<init>(androidx.activity.result.ActivityResultCallerLauncher$resultContract$2):void
WARN  - Incorrect args count in method signature: ()V in androidx.activity.result.ActivityResultCallerLauncher$resultContract$2.1.<init>(androidx.activity.result.ActivityResultCallerLauncher$resultContract$2):void
WARN  - Incorrect args count in method signature: ()V in kotlin.collections.AbstractList.IteratorImpl.<init>(kotlin.collections.AbstractList):void
WARN  - Incorrect args count in method signature: ()V in kotlin.collections.AbstractList.IteratorImpl.<init>(kotlin.collections.AbstractList):void
WARN  - Incorrect args count in method signature: ()V in kotlin.collections.AbstractMap$keys$1.<init>(kotlin.collections.AbstractMap):void
WARN  - Incorrect args count in method signature: ()V in kotlin.collections.AbstractMap$values$1.<init>(kotlin.collections.AbstractMap):void
WARN  - Incorrect types in method signature: <C:[Ljava/lang/Object;:TR;R:Ljava/lang/Object;>(TC;Lkotlin/jvm/functions/Function0<+TR;>;)TR; in kotlin.collections.ArraysKt__ArraysKt.ifEmpty(java.lang.Object[], kotlin.jvm.functions.Function0):java.lang.Object
WARN  - Incorrect args count in method signature: ()V in kotlin.collections.RingBuffer$iterator$1.<init>(kotlin.collections.RingBuffer):void
WARN  - Incorrect args count in method signature: ()V in kotlin.io.FileTreeWalk.FileTreeWalkIterator.<init>(kotlin.io.FileTreeWalk):void
WARN  - Incorrect args count in method signature: ()V in kotlin.io.FileTreeWalk.FileTreeWalkIterator.<init>(kotlin.io.FileTreeWalk):void
WARN  - Incorrect args count in method signature: ()V in kotlin.io.LinesSequence$iterator$1.<init>(kotlin.io.LinesSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.DropSequence$iterator$1.<init>(kotlin.sequences.DropSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.DropWhileSequence$iterator$1.<init>(kotlin.sequences.DropWhileSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.FilteringSequence$iterator$1.<init>(kotlin.sequences.FilteringSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.FlatteningSequence$iterator$1.<init>(kotlin.sequences.FlatteningSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.GeneratorSequence$iterator$1.<init>(kotlin.sequences.GeneratorSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.IndexingSequence$iterator$1.<init>(kotlin.sequences.IndexingSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.MergingSequence$iterator$1.<init>(kotlin.sequences.MergingSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.SubSequence$iterator$1.<init>(kotlin.sequences.SubSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.TakeSequence$iterator$1.<init>(kotlin.sequences.TakeSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.TakeWhileSequence$iterator$1.<init>(kotlin.sequences.TakeWhileSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.TransformingIndexedSequence$iterator$1.<init>(kotlin.sequences.TransformingIndexedSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.sequences.TransformingSequence$iterator$1.<init>(kotlin.sequences.TransformingSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.text.DelimitedRangesSequence$iterator$1.<init>(kotlin.text.DelimitedRangesSequence):void
WARN  - Incorrect args count in method signature: ()V in kotlin.text.MatcherMatchResult$groupValues$1.<init>(kotlin.text.MatcherMatchResult):void
WARN  - Incorrect args count in method signature: ()V in kotlin.text.MatcherMatchResult$groups$1.<init>(kotlin.text.MatcherMatchResult):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.AbstractChannel$onReceive$1.<init>(kotlinx.coroutines.channels.AbstractChannel):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.AbstractChannel$onReceiveOrClosed$1.<init>(kotlinx.coroutines.channels.AbstractChannel):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.AbstractChannel$onReceiveOrNull$1.<init>(kotlinx.coroutines.channels.AbstractChannel):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.AbstractSendChannel$onSend$1.<init>(kotlinx.coroutines.channels.AbstractSendChannel):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.ConflatedBroadcastChannel$onSend$1.<init>(kotlinx.coroutines.channels.ConflatedBroadcastChannel):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.scheduling.CoroutineScheduler.Worker.<init>(kotlinx.coroutines.scheduling.CoroutineScheduler):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.scheduling.CoroutineScheduler.Worker.<init>(kotlinx.coroutines.scheduling.CoroutineScheduler):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.test.TestCoroutineContext.Dispatcher.<init>(kotlinx.coroutines.test.TestCoroutineContext):void
WARN  - Incorrect args count in method signature: ()V in kotlinx.coroutines.test.TestCoroutineContext.Dispatcher.<init>(kotlinx.coroutines.test.TestCoroutineContext):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.Cache$urls$1.<init>(okhttp3.Cache):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.MultipartReader.PartSource.<init>(okhttp3.MultipartReader):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.MultipartReader.PartSource.<init>(okhttp3.MultipartReader):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.cache.DiskLruCache$snapshots$1.<init>(okhttp3.internal.cache.DiskLruCache):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.cache2.Relay.RelaySource.<init>(okhttp3.internal.cache2.Relay):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.cache2.Relay.RelaySource.<init>(okhttp3.internal.cache2.Relay):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.concurrent.TaskRunner$runnable$1.<init>(okhttp3.internal.concurrent.TaskRunner):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.connection.RealCall$timeout$1.<init>(okhttp3.internal.connection.RealCall):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.AbstractSource.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.ChunkedSink.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.KnownLengthSink.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.UnknownLengthSource.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.AbstractSource.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.ChunkedSink.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.KnownLengthSink.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.UnknownLengthSource.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http2.Http2Stream.StreamTimeout.<init>(okhttp3.internal.http2.Http2Stream):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.http2.Http2Stream.StreamTimeout.<init>(okhttp3.internal.http2.Http2Stream):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.ws.RealWebSocket.WriterTask.<init>(okhttp3.internal.ws.RealWebSocket):void
WARN  - Incorrect args count in method signature: ()V in okhttp3.internal.ws.RealWebSocket.WriterTask.<init>(okhttp3.internal.ws.RealWebSocket):void
WARN  - Incorrect args count in method signature: ()V in okio.Buffer$inputStream$1.<init>(okio.Buffer):void
WARN  - Incorrect args count in method signature: ()V in okio.Buffer$outputStream$1.<init>(okio.Buffer):void
WARN  - Incorrect args count in method signature: ()V in okio.Pipe$sink$1.<init>(okio.Pipe):void
WARN  - Incorrect args count in method signature: ()V in okio.Pipe$source$1.<init>(okio.Pipe):void
WARN  - Incorrect args count in method signature: ()V in okio.RealBufferedSink$outputStream$1.<init>(okio.RealBufferedSink):void
WARN  - Incorrect args count in method signature: ()V in okio.RealBufferedSource$inputStream$1.<init>(okio.RealBufferedSource):void
INFO  - Deobfuscation map file set to: ......../app/release/app-release.jobf
INFO  - processing ...
Exception in thread "Thread-4" java.lang.ArrayIndexOutOfBoundsException: 1
	at jadx.core.export.ExportGradleProject.getApplicationParams(ExportGradleProject.java:116)
	at jadx.core.export.ExportGradleProject.<init>(ExportGradleProject.java:49)
	at jadx.api.JadxDecompiler.getSaveExecutor(JadxDecompiler.java:239)
	at jadx.api.JadxDecompiler.getSaveExecutor(JadxDecompiler.java:207)
	at jadx.api.JadxDecompiler.save(JadxDecompiler.java:172)
	at jadx.gui.JadxWrapper.lambda$saveAll$1(JadxWrapper.java:69)
	at java.lang.Thread.run(Thread.java:748)

**Comment by skylot** [comment]
@srk2014 issue should be fixed by PR #1124, please check in the [latest build](https://nightly.link/skylot/jadx/workflows/build/master).

**Comment by srk2014** [comment]
> @srk2014 issue should be fixed by PR #1124, please check in the [latest build](https://nightly.link/skylot/jadx/workflows/build/master).

Thanks to Yaroslav and skylot. I did try the new build, and the outcome was not much different. I even tried to save as a jadx file first prior to building the gradle, and that did not assist either.

**Comment by MrIkso** [comment]
@srk2014 send apk or new log, or write me on telegram. Link on profile.

**Comment by srk2014** [comment]
> @srk2014 send apk or new log, or write me on telegram. Link on profile. We cannot guess why the export does not work

Thanks @Mrlkso. Please check the latest log. Now, I see the blue progress bar on the left window, but not as before when I used to see a progressbar while the gradle is being built.

Version:jadx-1.2.0.98-5f24193c
OS: Ubuntu 20.0.4

I also tried to connect with you through your profile link, and I am getting the message,"There is no telegram account with this username".

Is there a requirement on where the jadx folder needs to be located? I tried both at /usr/local/bin and also on the Desktop, both loaded the script fine, but neither could build the gradle project.

![Screenshot from 2021-08-05 16-27-42image1](https://user-images.githubusercontent.com/7888154/128424822-5d0057c4-3d7d-49dd-9f66-f95506bfa849.png)
![Screenshot from 2021-08-05 16-28-37image2](https://user-images.githubusercontent.com/7888154/128424827-ac7bd16f-3fea-4a0d-847f-f1a5d914d2ba.png)


WARN : Incorrect args count in method signature: ()V in androidx.activity.result.ActivityResultCallerLauncher$resultContract$2.1.<init>(androidx.activity.result.ActivityResultCallerLauncher$resultContract$2):void
WARN : Incorrect args count in method signature: ()V in androidx.activity.result.ActivityResultCallerLauncher$resultContract$2.1.<init>(androidx.activity.result.ActivityResultCallerLauncher$resultContract$2):void
WARN : Incorrect args count in method signature: ()V in kotlin.collections.AbstractList.IteratorImpl.<init>(kotlin.collections.AbstractList):void
WARN : Incorrect args count in method signature: ()V in kotlin.collections.AbstractList.IteratorImpl.<init>(kotlin.collections.AbstractList):void
WARN : Incorrect args count in method signature: ()V in kotlin.collections.AbstractMap$keys$1.<init>(kotlin.collections.AbstractMap):void
WARN : Incorrect args count in method signature: ()V in kotlin.collections.AbstractMap$values$1.<init>(kotlin.collections.AbstractMap):void
WARN : Incorrect types in method signature: <C:[Ljava/lang/Object;:TR;R:Ljava/lang/Object;>(TC;Lkotlin/jvm/functions/Function0<+TR;>;)TR; in kotlin.collections.ArraysKt__ArraysKt.ifEmpty(java.lang.Object[], kotlin.jvm.functions.Function0):java.lang.Object
WARN : Incorrect args count in method signature: ()V in kotlin.collections.RingBuffer$iterator$1.<init>(kotlin.collections.RingBuffer):void
WARN : Incorrect args count in method signature: ()V in kotlin.io.FileTreeWalk.FileTreeWalkIterator.<init>(kotlin.io.FileTreeWalk):void
WARN : Incorrect args count in method signature: ()V in kotlin.io.FileTreeWalk.FileTreeWalkIterator.<init>(kotlin.io.FileTreeWalk):void
WARN : Incorrect args count in method signature: ()V in kotlin.io.LinesSequence$iterator$1.<init>(kotlin.io.LinesSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.DropSequence$iterator$1.<init>(kotlin.sequences.DropSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.DropWhileSequence$iterator$1.<init>(kotlin.sequences.DropWhileSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.FilteringSequence$iterator$1.<init>(kotlin.sequences.FilteringSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.FlatteningSequence$iterator$1.<init>(kotlin.sequences.FlatteningSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.GeneratorSequence$iterator$1.<init>(kotlin.sequences.GeneratorSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.IndexingSequence$iterator$1.<init>(kotlin.sequences.IndexingSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.MergingSequence$iterator$1.<init>(kotlin.sequences.MergingSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.SubSequence$iterator$1.<init>(kotlin.sequences.SubSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.TakeSequence$iterator$1.<init>(kotlin.sequences.TakeSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.TakeWhileSequence$iterator$1.<init>(kotlin.sequences.TakeWhileSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.TransformingIndexedSequence$iterator$1.<init>(kotlin.sequences.TransformingIndexedSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.sequences.TransformingSequence$iterator$1.<init>(kotlin.sequences.TransformingSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.text.DelimitedRangesSequence$iterator$1.<init>(kotlin.text.DelimitedRangesSequence):void
WARN : Incorrect args count in method signature: ()V in kotlin.text.MatcherMatchResult$groupValues$1.<init>(kotlin.text.MatcherMatchResult):void
WARN : Incorrect args count in method signature: ()V in kotlin.text.MatcherMatchResult$groups$1.<init>(kotlin.text.MatcherMatchResult):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.AbstractChannel$onReceive$1.<init>(kotlinx.coroutines.channels.AbstractChannel):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.AbstractChannel$onReceiveOrClosed$1.<init>(kotlinx.coroutines.channels.AbstractChannel):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.AbstractChannel$onReceiveOrNull$1.<init>(kotlinx.coroutines.channels.AbstractChannel):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.AbstractSendChannel$onSend$1.<init>(kotlinx.coroutines.channels.AbstractSendChannel):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.channels.ConflatedBroadcastChannel$onSend$1.<init>(kotlinx.coroutines.channels.ConflatedBroadcastChannel):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.scheduling.CoroutineScheduler.Worker.<init>(kotlinx.coroutines.scheduling.CoroutineScheduler):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.scheduling.CoroutineScheduler.Worker.<init>(kotlinx.coroutines.scheduling.CoroutineScheduler):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.test.TestCoroutineContext.Dispatcher.<init>(kotlinx.coroutines.test.TestCoroutineContext):void
WARN : Incorrect args count in method signature: ()V in kotlinx.coroutines.test.TestCoroutineContext.Dispatcher.<init>(kotlinx.coroutines.test.TestCoroutineContext):void
WARN : Incorrect args count in method signature: ()V in okhttp3.Cache$urls$1.<init>(okhttp3.Cache):void
WARN : Incorrect args count in method signature: ()V in okhttp3.MultipartReader.PartSource.<init>(okhttp3.MultipartReader):void
WARN : Incorrect args count in method signature: ()V in okhttp3.MultipartReader.PartSource.<init>(okhttp3.MultipartReader):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.cache.DiskLruCache$snapshots$1.<init>(okhttp3.internal.cache.DiskLruCache):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.cache2.Relay.RelaySource.<init>(okhttp3.internal.cache2.Relay):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.cache2.Relay.RelaySource.<init>(okhttp3.internal.cache2.Relay):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.concurrent.TaskRunner$runnable$1.<init>(okhttp3.internal.concurrent.TaskRunner):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.connection.RealCall$timeout$1.<init>(okhttp3.internal.connection.RealCall):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.AbstractSource.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.ChunkedSink.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.KnownLengthSink.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.UnknownLengthSource.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.AbstractSource.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.ChunkedSink.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.KnownLengthSink.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http1.Http1ExchangeCodec.UnknownLengthSource.<init>(okhttp3.internal.http1.Http1ExchangeCodec):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http2.Http2Stream.StreamTimeout.<init>(okhttp3.internal.http2.Http2Stream):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.http2.Http2Stream.StreamTimeout.<init>(okhttp3.internal.http2.Http2Stream):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.ws.RealWebSocket.WriterTask.<init>(okhttp3.internal.ws.RealWebSocket):void
WARN : Incorrect args count in method signature: ()V in okhttp3.internal.ws.RealWebSocket.WriterTask.<init>(okhttp3.internal.ws.RealWebSocket):void
WARN : Incorrect args count in method signature: ()V in okio.Buffer$inputStream$1.<init>(okio.Buffer):void
WARN : Incorrect args count in method signature: ()V in okio.Buffer$outputStream$1.<init>(okio.Buffer):void
WARN : Incorrect args count in method signature: ()V in okio.Pipe$sink$1.<init>(okio.Pipe):void
WARN : Incorrect args count in method signature: ()V in okio.Pipe$source$1.<init>(okio.Pipe):void
WARN : Incorrect args count in method signature: ()V in okio.RealBufferedSink$outputStream$1.<init>(okio.RealBufferedSink):void
WARN : Incorrect args count in method signature: ()V in okio.RealBufferedSource$inputStream$1.<init>(okio.RealBufferedSource):void

**Comment by MrIkso** [comment]
@srk2014 this log don't contain any errors related to export.  In the folder that you selected there should be an app folder.  All the sources are there.

**Comment by srk2014** [comment]
> @srk2014 this log don't contain any errors related to export. In the folder that you selected there should be an app folder. All the sources are there.

@MrIkso: Thanks again. 

But, nothing was created (HiddenCamera.jadx, where the other files should have been). I would like to share a folder that was created before using the same method, and what I see now lately. As mentioned, this issue is relatively new which I noticed during the last week or two where the gradle project folder is not being created, though there were hits and misses in the past.

![Screenshot from 2021-08-06 06-30-10_nootherfilescreated](https://user-images.githubusercontent.com/7888154/128504666-2c3d77b7-3357-42d2-a23a-d29a702432bd.png)
![Screenshot from 2021-08-06 06-32-30createdbefore](https://user-images.githubusercontent.com/7888154/128504767-9f9f2311-462f-42cc-b4c5-1248854774f5.png)

**Comment by MrIkso** [comment]
@srk2014 write me on [telegram](https://t.me/MrIkso), with full description this problem and attach apk or video, when use export to gradle project. I want to understand this problem to the end.

**Comment by srk2014** [comment]
> @srk2014 write me on [telegram](https://t.me/MrIkso), with full description this problem and attach apk or video, when use export to gradle project. I want to understand this problem to the end.

@Mrlkso. I tried to connect with you through the given link right after you suggested that option before, and I tried again today. However, I am getting the following message:
"there is no telegram account with the following username". I have reached out to telegram support team to find out the reason. In the meantime, if you have other ways to connect, let me know.

**Comment by MrIkso** [comment]
> if you have other ways to connect, let me know.

[Gmail](mrikso821@gmail.com)

**Comment by srk2014** [comment]
> > if you have other ways to connect, let me know.
> 
> Gmail [mrikso821@gmail.com](mailto:mrikso821@gmail.com)

Thanks for sharing your address. I have sent an email to this address.

**Comment by srk2014** [comment]
> > if you have other ways to connect, let me know.
> 
> Gmail [mrikso821@gmail.com](mailto:mrikso821@gmail.com)

Thanks, Mrikso. With your assistance, I was able to locate the latest build, which resolved the issue.

Skylot/Mrikso: As shared with Mrikso, the gradle project created using this tool results in multiple android resource failed errors, most of these errors revolve around attrib and layout files, though the original file compiles fine. Has anyone else shared the same issue before? If yes, is there a simple way to address this issue to get the application fully functional?
