### ISSUE TITLE
[core] multidex compile issue.

### ISSUE THREAD

**Issue by bobsort** [skylot/jadx#1226]
**Describe error**
- N/A
- N/A
- Any Multidex APK (Tested with 2 dex and 3 dex)
- - Version 1.2.0 from releases (on java 8.301 and also 11.0.12)

When Decompiling Multidex files and using deobfuscation, decompiler does not use same namespaces as previous dex. 

meaning if for example I have java.time.* used in multiple dex files, the first one will deobfuscate to xxxxx.yyyyy and second one will deobfuscate to  pppp.yyyy (or even pppp.zzzz)

I have tested this with multiple multidex apk files and had same result. 
I'm guessing this might have to do something with issue #1217 too, which removes both blocks instead of using at least one.

**Comment by skylot** [comment]
@bobsort did you open these dex files separately? You need to open whole apk file. If you still have issue, please provide example with description where to look add attach sample apk.

**Comment by bobsort** [comment]
Yes opened the apk itself. 


BTW I Also noticed many of Android.xxxxx and Java.xxx and my application static methods are moved to a common class.
does new dex move static methods to a common class?

**Comment by skylot** [comment]
@bobsort please provide sample apk and which classes to check. Otherwise, I don't know how to reproduce your issue.
