### ISSUE TITLE
some Method not Decompilation how can i resolve???? [core]

### ISSUE THREAD

**Issue by SolankiYagnik** [skylot/jadx#1233]
/* JADX WARNING: Removed duplicated region for block: B:28:0x0067  */
    /* JADX WARNING: Removed duplicated region for block: B:31:0x006d A[SYNTHETIC, Splitter:B:31:0x006d] */
    /* JADX WARNING: Removed duplicated region for block: B:39:? A[RETURN, SYNTHETIC] */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static void syncConnect(java.lang.String r2, java.util.Map<java.lang.String, java.lang.String> r3, com.lightcone.p029ad.helper.HttpConnectionUtil.HttpMethod r4, com.lightcone.p029ad.helper.HttpConnectionUtil.HttpConnectionCallback r5) {
        /*
            r0 = 0
            org.apache.http.impl.client.DefaultHttpClient r1 = new org.apache.http.impl.client.DefaultHttpClient     // Catch:{ Exception -> 0x005b }
            r1.<init>()     // Catch:{ Exception -> 0x005b }
            org.apache.http.client.methods.HttpUriRequest r2 = getRequest(r2, r3, r4)     // Catch:{ Exception -> 0x005b }
            org.apache.http.HttpResponse r2 = r1.execute(r2)     // Catch:{ Exception -> 0x005b }
            if (r2 == 0) goto L_0x0046
            org.apache.http.StatusLine r3 = r2.getStatusLine()     // Catch:{ Exception -> 0x005b }
            int r3 = r3.getStatusCode()     // Catch:{ Exception -> 0x005b }
            r4 = 200(0xc8, float:2.8E-43)
            if (r3 != r4) goto L_0x0046
            java.io.BufferedReader r3 = new java.io.BufferedReader     // Catch:{ Exception -> 0x005b }
            java.io.InputStreamReader r4 = new java.io.InputStreamReader     // Catch:{ Exception -> 0x005b }
            org.apache.http.HttpEntity r2 = r2.getEntity()     // Catch:{ Exception -> 0x005b }
            java.io.InputStream r2 = r2.getContent()     // Catch:{ Exception -> 0x005b }
            r4.<init>(r2)     // Catch:{ Exception -> 0x005b }
            r3.<init>(r4)     // Catch:{ Exception -> 0x005b }
            java.lang.StringBuilder r2 = new java.lang.StringBuilder     // Catch:{ Exception -> 0x0050, all -> 0x004d }
            r2.<init>()     // Catch:{ Exception -> 0x0050, all -> 0x004d }
            java.lang.String r4 = r3.readLine()     // Catch:{ Exception -> 0x0050, all -> 0x004d }
        L_0x0037:
            if (r4 == 0) goto L_0x0041
            r2.append(r4)     // Catch:{ Exception -> 0x0050, all -> 0x004d }
            java.lang.String r4 = r3.readLine()     // Catch:{ Exception -> 0x0050, all -> 0x004d }
            goto L_0x0037
        L_0x0041:
            java.lang.String r0 = r2.toString()     // Catch:{ Exception -> 0x0050, all -> 0x004d }
            goto L_0x0047
        L_0x0046:
            r3 = r0
        L_0x0047:
            if (r5 == 0) goto L_0x0053
            r5.execute(r0)     // Catch:{ Exception -> 0x0050, all -> 0x004d }
            goto L_0x0053
        L_0x004d:
            r2 = move-exception
            r0 = r3
            goto L_0x006b
        L_0x0050:
            r2 = move-exception
            r0 = r3
            goto L_0x005c
        L_0x0053:
            if (r3 == 0) goto L_0x006a
            r3.close()     // Catch:{ IOException -> 0x006a }
            goto L_0x006a
        L_0x0059:
            r2 = move-exception
            goto L_0x006b
        L_0x005b:
            r2 = move-exception
        L_0x005c:
            java.lang.String r3 = "HttpConnectionUtil"
            java.lang.String r4 = r2.getMessage()     // Catch:{ all -> 0x0059 }
            android.util.Log.e(r3, r4, r2)     // Catch:{ all -> 0x0059 }
            if (r0 == 0) goto L_0x006a
            r0.close()
        L_0x006a:
            return
        L_0x006b:
            if (r0 == 0) goto L_0x0070
            r0.close()     // Catch:{ IOException -> 0x0070 }
        L_0x0070:
            throw r2
        */
        throw new UnsupportedOperationException("Method not decompiled: com.lightcone.p029ad.helper.HttpConnectionUtil.syncConnect(java.lang.String, java.util.Map, com.lightcone.ad.helper.HttpConnectionUtil$HttpMethod, com.lightcone.ad.helper.HttpConnectionUtil$HttpConnectionCallback):void");
    }

**Comment by jpstotz** [comment]
1. Which version of jadx do you use? If you use the stable version please try the latest unstable build https://nightly.link/skylot/jadx/workflows/build/master
2. You have ignored the actions mentioned in the standard issue template. These actions are not for keeping them as they are they should be followed! Without we can't help you.

**Comment by SolankiYagnik** [comment]
please check tit

**Comment by jpstotz** [comment]
@SolankiYagnik Please answer the questions from my last post.
