### ISSUE TITLE
[core] Override annotation is added when it's not needed

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1234]
Hey, 

Class `androidx.transition.GhostViewImpl`:
```java
package androidx.transition;
/* loaded from: classes.dex */
interface GhostViewImpl {
    void reserveEndViewTransition(android.view.ViewGroup viewGroup, android.view.View view);

    @Override // androidx.transition.GhostViewImpl // <<<
    void setVisibility(int i);
}
```

APK: https://drive.google.com/file/d/1qC3tlWs9AtPBpyS6iU9kcSphLryfJOxi/view

**Comment by nitram84** [comment]
This issue can be reproduced with the dependency itself ('androidx.transition:transition:1.0.0' / https://maven.google.com/androidx/transition/transition/1.0.0/transition-1.0.0.aar).

**Comment by skylot** [comment]
@bagipro I made a fix :tada:

**Comment by bagipro** [comment]
@skylot 
Thanks! Time to research for new bugs :D
