### ISSUE TITLE
[core] Failed type inference 

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1238]
Hi,

Class `kotlin.sequences.SequencesKt___SequencesKt`
```java
    public static final <T extends Comparable<? super T>> T max(@NotNull Sequence<? extends T> sequence) {
        Intrinsics.checkParameterIsNotNull(sequence, "$this$max");
        Iterator<? extends T> it = sequence.iterator();
        if (!it.hasNext()) {
            return null;
        }
        T t = (T) ((Comparable) it.next());
        while (it.hasNext()) {
            ?? r1 = (Comparable) it.next(); // <<<
            if (t.compareTo(r1) < 0) {
                t = r1;
            }
        }
        return t;
    }
```

Probably there should be the same line: `T r1 = (T) ((Comparable) it.next());`

There are a lot of such errors in that file

APK: https://drive.google.com/file/d/1qC3tlWs9AtPBpyS6iU9kcSphLryfJOxi/view

**Comment by skylot** [comment]
@bagipro this case fixed. Although, same class have many similar warnings, but generated code don't have unresolved types (`??`). Maybe I will try to fix these later.

**Comment by bagipro** [comment]
Thanks!
