### ISSUE TITLE
jadx fails to compile with JDK 17

### ISSUE THREAD

**Issue by socram8888** [skylot/jadx#1244]
Current Gradle (7.0.1) does not support compiling jadx under OpenJDK 17, throwing an error. This is an issue as JDK 17 is the only version available on Termux, the Android terminal emulator.

Updating Gradle to 7.2 fixes the issue, and has no breaking changes to currently used version.

**Comment by skylot** [comment]
> Updating Gradle to 7.2 fixes the issue

Done in  e854ba3

**Comment by socram8888** [comment]
Thank you!

**Comment by socram8888** [comment]
A minor note: using [the recommended upgrade approach](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper) of ` ./gradlew wrapper --gradle-version 7.2` on my system yielded a larger diff. Seemingly the gradle wrapper JAR and the gradlew scripts have been also updated.

Not sure if updating them is also required because they include some bugfixes or will be with future Gradle versions.
