### ISSUE TITLE
[feature] Include the ability to go to declaration within the manifest file

### ISSUE THREAD

**Issue by green9317** [skylot/jadx#1246]
It would be useful if JadX had the ability jump to the correct part of code from within the manifest file. 

I also noticed that JadX doesn't appear to be storing most data when parsing the manifest.  I could see some value in storing the contents in a object and making it accessible with an api.

**Comment by skylot** [comment]
> It would be useful if JadX had the ability jump to the correct part of code from within the manifest file.

Jadx allows to [jump to class from AndroidManifest.xml](https://github.com/skylot/jadx/wiki/jadx-gui-features-overview#jump-to-class-from-androidmanifestxml). Do you need something else?

> I could see some value in storing the contents in a object and making it accessible with an api.

What kind of data do you need?
Also you can parse result xml using many available xml apis. Jadx already do it itself [here](https://github.com/skylot/jadx/blob/f9bf27579e3ad5f89239ea9f571e8b50739e8920/jadx-core/src/main/java/jadx/core/export/ExportGradleProject.java#L105). I agree this is not the best way, so I plan to fill [that object](https://github.com/skylot/jadx/blob/f9bf27579e3ad5f89239ea9f571e8b50739e8920/jadx-core/src/main/java/jadx/core/export/ApplicationParams.java#L3) during parsing. Anyway, manifest contains a lot of data and jadx not really need all that data.

**Comment by MrIkso** [comment]
@green9317 What data are we talking about? And what are the correct parts?

**Comment by green9317** [comment]
Turns out I was just using the wrong button :)  I was right clicking on the class and looking for the jump to option.  I just double clicked and it worked so I suppose this was just user error.

As for filling up the object I am just pointing out that JadX parses the manifest but doesn't store the permissions, activity, intents, ext.  I dont have an immediate need for this information; however, Jadx is already parsing it so I can see benefit to storing it for use by plugins.
