### ISSUE TITLE
[core][regression][try-catch] Behavior change when decompiling nested try-catch 

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#1249]
I found a regression between b5720bd1 and e854ba3c (after try-catch-rewrite). In b5720bd1 the following example could be decompiled without errors. In latest git version there is a behavior change in the decompiled code. Tested with openjdk8. 

This example can be used for a unit test.

This issue is related to #1248

```java
import java.io.IOException;

public class NestedTryCatchTest2 {

	public void doSomething1() throws IOException {
		throw new NullPointerException();
	}

	public void doSomething2() {
	}

	public void doSomething3() {
	}

	public void nestedTryCatchTest2() {
		try {
			try {
				doSomething1();
			} catch (IOException e) {
				doSomething3();
			}
		} finally {
			doSomething2();
		}
	}
}
```

**Comment by skylot** [comment]
@nitram84 I managed to fix this case. Thank you for report!
#1248 is slightly different, so I will try to fix it later 👍🏽
