### ISSUE TITLE
Decompile R

### ISSUE THREAD

**Issue by IlyaGazman** [skylot/jadx#125]
When decompiling and deobfuscating you don't replace the numbers with the R file.

So the code will have some thing like this:

setCotentView(2123543123);

You can use aapt  tool to get all the maping from the original apk. See here http://stackoverflow.com/questions/13133310/how-to-get-the-r-java-file-when-decoding-apk-file

**Comment by mingyuan-xia** [comment]
This could be tricky. As you compile, you lose the constant names. Everything boils down to numbers. If I have two constants having the same value of 1, decompilation could choose both~
One possible workaround is to conservatively guess some constants, e.g., If you see `setContentView` `findViewById` you know the integer parameter is an R ID, and look for that from `R.java`.
But anyhow, this wont be perfect.

**Comment by Ilya-Gazman** [comment]
Yeah man, I am only talking about the R constants as it makes it very hard to read the code without a reference to the layout. I don't care about the other constants.

And since you got the mapping you can fix all the setContentView, findViewById and in layout references.

No tricks are here.

**Comment by asashour** [comment]
I quickly checked, and I see that the constant is referenced, could you check and update with your APK?
