### ISSUE TITLE
[feature] String decryption

### ISSUE THREAD

**Issue by ghost** [skylot/jadx#1251]
*Describe your idea:*
I discovered an app that have string encrypted, but the decryption looks pretty simple, located on `com.xshield.aa`. So i wonder is it possible to generate decrypted Strings in runtime as part of deobfuscation for analysis?

[classes.zip](https://github.com/skylot/jadx/files/7204428/classes.zip)

**Comment by KarmaMod** [comment]
I see, i would go for a scripting then if it's available.

**Comment by MikeAndrson** [comment]
Have you tried using the String decryptor from **dex2jar**? It's pretty outdated but it should still work: https://github.com/pxb1988/dex2jar/wiki/DecryptStrings

**Comment by skylot** [comment]
Scripting feature added into master branch.
String decryption example script can be found here: https://github.com/skylot/jadx/blob/1a642108ef7fe0322f343187a9c21f7b3658aafb/jadx-plugins/jadx-script/examples/scripts/replace_method_call.jadx.kts#L19
