### ISSUE TITLE
[core] Find usage decompiles the APK again

### ISSUE THREAD

**Issue by theapache64** [skylot/jadx#1252]
## Screenshot

![image](https://user-images.githubusercontent.com/9678279/134813001-8576ffcb-3ad3-4cc5-b46a-bebd5a4d25db.png)

Let me know if you need more input from my side

**Comment by jpstotz** [comment]
May be the information which exact version of Jadx you use and what steps you perform? Also important are the Jadx options e.g. if you have enabled the option `Auto start background decompilation`?

When does Jadx decompiled the APK  the first time (by what action is that triggered by you)?

**Comment by theapache64** [comment]
**Steps to reproduce**
1. `sh bin/jadx-gui myapk.apk`
2. wait for decompile to finish
3. open any Java file 
4. right click on any method and choose "Find usage"

**Actual behavior**
- "Find usage" window appears and decompiles again

**Expected behavior**
- "Find usage" should launch without decompiling the APK\

**jadx version**
- `1.2.0`

**Comment by jpstotz** [comment]
Unless you have enabled the option `Auto start background decompilation` Jadx only loads the basic structure of an APK file when you open the file. 

The actual decompilation starts when you open the search/find usage dialog. If you are opening a class before that Jadx decompiles just the class you are looking at and it's dependencies. 

Therefore I would assume that this is just a misunderstanding on your side, what the "decompiling" step in Jadx is and when it is executed. Please enable `Auto start background decompilation` in preferences and try again.

**Comment by theapache64** [comment]
>The actual decompilation starts when you open the search/find usage dialog. If you are opening a class before that Jadx decompiles just the class you are looking at and its dependencies.

Ohh, I didn't know about this. Probably, I might be opening the "Find usage" parallel to the background decompiling. 

https://user-images.githubusercontent.com/9678279/134817117-d9df35cb-bbdd-4e55-86e3-ca60799d00d2.mp4

**Comment by jpstotz** [comment]
From your video I can see that everything works as expected. The decompilation is performed once and the search dialog is just waiting for the ongoing decompilation.

**Comment by theapache64** [comment]
Yes. My bad. I didn't. Thanks for the quick response.
