### ISSUE TITLE
[core]Error at the lookup call

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1254]
jadx latest beta version
apk link: https://drive.google.com/file/d/1er1nmvP2fKeCTC7-O_kngncB1kLmDp1b/view?usp=sharing

In class: **com.fengwoo.videoplayer.welfare.ui.EconomicsDetailActivity** method: **public void onClick(android.view.View view)** , you can see the presence of method **com.fengwoo. videoplayer.utils.g0.g()** call;but the method **com.fengwoo.videoplayer.utils.g0.g()** lookup call, but shows 0 results!
![2021-09-28_11-59-37](https://user-images.githubusercontent.com/42903751/135021313-de989aa8-748c-4527-9fe2-8c939b3f9452.png)

**Comment by skylot** [comment]
@xmhwws should be fixed, please check 👍🏽

**Comment by xmhwws** [comment]
The previously mentioned problem has been solved, thanks.
