### ISSUE TITLE
Decoding problem with xmlns in Manifest

### ISSUE THREAD

**Issue by DynamicBit** [skylot/jadx#126]
Hi,

I have a problems with the decoding of the minifest file. The xmlns: attribute is decoded without the "=" after "xmlns:" all the time. Im running the decompiler on a mac.

**Comment by DynamicBit** [comment]
I meant without, not with.

**Comment by sergey-wowwow** [comment]
Seems to be fixed in https://github.com/skylot/jadx/issues/231
