### ISSUE TITLE
[core] Duplicate methods

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1263]
Hey,

I've noticed errors in Kotlin lambdas. Example app: https://apkcombo.com/yandex-navigator/ru.yandex.yandexnavi/

Class `ru.yandex.yandexnavi.core.MapsUrlsActivity$onCreate$1`:
```java
    @Override
    public kotlin.Unit invoke(java.lang.String str) {
```
```java
    public final void invoke(java.lang.String str) {
```

It prevents resolving the correct method.

**Comment by skylot** [comment]
Should be fixed.
Anyway, this is not the best solution, better to inline non-synthetic method, but jadx now support only limited inlining cases.
