### ISSUE TITLE
[core] Usage of a missing method

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1264]
Hey,

The app is https://apkcombo.com/yandex-navigator/ru.yandex.yandexnavi/

Class `ru.yandex.yandexnavi.core.MapsUrlsActivity$onCreate`:
```java
        mapsUrlsActivity.startActivity(ru.yandex.yandexnavi.core.MapsUrlsActivity.access$getChooserIntent(mapsUrlsActivity, intent, str));
```

The problem is that method with the name `access$getChooserIntent` doesn't exist. However, `getChooserIntent` exists.

**Comment by jpstotz** [comment]
Usually if methods are missing the chance is high that they are marked as `synthetic`. To view them display in preference both `Inline .. ` options.

**Comment by bagipro** [comment]
@jpstotz 
Thanks! But in this case (especially for Kotlin-based apps), there will be a lot of garbage codes. This feature makes the code more beautiful. I believe jadx is designed to update references, but this specific case is a bug

**Comment by skylot** [comment]
Fixed, this case at least. I adjust class processing order, this potentially can introduce regression, but I don't spot any after quick tests. Also, I make additional checks before removing inlined methods, this will reduce number of other possible cases.
