### ISSUE TITLE
[core][gui] Task exceeded time limit and no way to change the limit

### ISSUE THREAD

**Issue by google-mirror** [skylot/jadx#1267]
![111](https://user-images.githubusercontent.com/70927995/140709925-ad447eb6-6088-4db6-bd8e-8c522643f604.png)
![2223](https://user-images.githubusercontent.com/70927995/140709936-a0fe44a9-2d80-41e3-b49f-98d8fd947cbf.png)

**Comment by jpstotz** [comment]
The timeout calculation bases on the environment variable `JADX_CLS_PROCESS_LIMIT` and takes the number of classes into account. 

Default value of `JADX_CLS_PROCESS_LIMIT` is 50. Set a value higher than 50 to increase the timeout.
