### ISSUE TITLE
[core] jadx CLI - Save resources first

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1270]
Hey @skylot,

In this PR https://github.com/skylot/jadx/pull/376, I changed the code to save resources first, but now I see that sources are saved first. The behavior was changed in https://github.com/skylot/jadx/commit/1c08d854fb3474d38d439d8e686720d6b99e2622

Can we change the order? Because there are cases when the app is too big, or there is not enough memory, in those cases jadx freezes. So it's better to have resources + 70% of sources than only 70% of sources.

**Comment by skylot** [comment]
@bagipro fixed. Sorry to break your changes 😞 
I added comment to these changes, so this will not happen again.

**Comment by bagipro** [comment]
Thanks!
