### ISSUE TITLE
tag 1.2 Startup crash 

### ISSUE THREAD

**Issue by PApatigers** [skylot/jadx#1272]
2021-11-14 16:23:33.692 java[78813:1088643] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x12fdcd3e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff803bc262b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff803924dce objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff803c47046 __CFExceptionProem + 0
	3   CoreFoundation                      0x00007ff803b2a26e ___forwarding___ + 1406
	4   CoreFoundation                      0x00007ff803b29c68 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007ff803b3d11f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00007ff803bd9b35 ___CFXRegistrationPost_block_invoke + 49
	7   CoreFoundation                      0x00007ff803bd9aa6 _CFXRegistrationPost + 496
	8   CoreFoundation                      0x00007ff803b0edfa _CFXNotificationPost + 803
	9   Foundation                          0x00007ff80487d996 -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
	10  AppKit                              0x00007ff806812ebf __NSSelectedKeyboardInputSourcesChangedNotification + 58
	11  CoreFoundation                      0x00007ff803b3d11f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	12  CoreFoundation                      0x00007ff803bd9b35 ___CFXRegistrationPost_block_invoke + 49
	13  libdispatch.dylib                   0x00007ff8038c6ad8 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00007ff8038c7cc9 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00007ff8038d45d8 _dispatch_main_queue_callback_4CF + 951
	16  CoreFoundation                      0x00007ff803b853b8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x00007ff803b469a6 __CFRunLoopRun + 2760
	18  CoreFoundation                      0x00007ff803b45809 CFRunLoopRunSpecific + 567
	19  HIToolbox                           0x00007ff80cbb23e1 RunCurrentEventLoopInMode + 292
	20  HIToolbox                           0x00007ff80cbb2008 ReceiveNextEventCommon + 284
	21  HIToolbox                           0x00007ff80cbb1ed5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	22  AppKit                              0x00007ff8064978f0 _DPSNextEvent + 886
	23  AppKit                              0x00007ff806495f5c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1411
	24  libosxapp.dylib                     0x000000012f9e46ce -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
	25  AppKit                              0x00007ff806488359 -[NSApplication run] + 586
	26  libosxapp.dylib                     0x000000012f9e4513 +[NSApplicationAWT runAWTLoopWithApp:] + 263
	27  libawt_lwawt.dylib                  0x000000012fd95a74 +[AWTStarter starter:headless:] + 496
	28  libosxapp.dylib                     0x000000012f9e6029 +[ThreadUtilities invokeBlockCopy:] + 15
	29  Foundation                          0x00007ff8048f5d63 __NSThreadPerformPerform + 179
	30  CoreFoundation                      0x00007ff803b47b68 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	31  CoreFoundation                      0x00007ff803b47ad0 __CFRunLoopDoSource0 + 180
	32  CoreFoundation                      0x00007ff803b47843 __CFRunLoopDoSources0 + 242
	33  CoreFoundation                      0x00007ff803b4625f __CFRunLoopRun + 897
	34  CoreFoundation                      0x00007ff803b45809 CFRunLoopRunSpecific + 567
	35  libjli.dylib                        0x00000001088a55ac CreateExecutionEnvironment + 398
	36  libjli.dylib                        0x00000001088a1817 JLI_Launch + 1315
	37  java                                0x00000001002562cc main + 364
	38  dyld                                0x000000020062f4fe start + 462
	39  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      /Users/tool/jadx-1.2.0/build/jadx/bin/jadx-gui

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by jpstotz** [comment]
Based on the error log you seem to try to run Jadx on an Apple system. Can you give more details on the used CPU, OS version and most important the use Java version and distribution?

Such errors usually are bugs in the Java Runtime we don't have much influence on. Therefore my recommendation is to try a different Java Runtime version. My recommendation is OpenJDK 11.
