### ISSUE TITLE
[core] Early decompilation error: no classes loaded, nothing to decompile

### ISSUE THREAD

**Issue by MPeti1** [skylot/jadx#1280]
The error happens so early with any apk that I tried, that I don't see any method or class names that I could mention here.

Jadx won't crash, and it only shows [a dialog](https://user-images.githubusercontent.com/9215491/142734471-ed20adb2-8f1c-491e-8e39-52e37b19659e.png) with the error message.
The log viewer shows this, with log level set to DEBUG:
```
INFO : output directory: F-Droid
INFO : loading ...
```
 
An example of an app with which I have this problem is the F-Droid app. The version I tried can be found here: [F-Droid.apk.zip](https://github.com/skylot/jadx/files/7574863/F-Droid.apk.zip)
The log output above was produced when trying to test Jadx with this apk.

Since this is a different kind of a decompilation error, I thought it might make sense to say a few words about my environment.
I'm on 64 bit Windows 10, the latest JRE I have installed is for 1.8.
The same problem happens with both the `jadx-gui-1.3.0-no-jre-win.exe` and the `jadx-gui-1.3.0-with-jre-win.zip` release.
Jadx 1.2.0 is able to decompile apk's that I give it.

Checking similar issues, #1276 might be related, but it has already been closed with a fix that is included in 1.3.0

The cross platform version (both gui and cli) can decompile the F-Droid apk, but with a lot of (possibly unrelated) [errors](https://gist.github.com/MPeti1/5ee902ec22da56e5bdcc33e06bc1ea15).

**Comment by skylot** [comment]
@MPeti1 it is sad, but I can't reproduce your issue. 
Can you run exe from `jadx-gui-1.3.0-with-jre-win` in terminal with `-v` (verbose) option, open file, and post output here?

**Comment by MPeti1** [comment]
Sure! Log Viewer contents with DEBUG log level:
```
DEBUG: Starting background task 'Loading', jobs count: 1, time limit: 0 ms, memory check: true
DEBUG: Register plugin: smali-input
DEBUG: Register plugin: dex-input
DEBUG: Register plugin: java-input
INFO : output directory: F-Droid
DEBUG: Effective jadx args: JadxArgs{inputFiles=[c:\Users\[REDACTED]\Downloads\F-Droid.apk], outDir=F-Droid, outDirSrc=F-Droid\sources, outDirRes=F-Droid\resources, threadsCount=8, cfgOutput=false, rawCFGOutput=false, fallbackMode=false, showInconsistentCode=true, useImports=true, skipResources=false, skipSources=false, deobfuscationOn=true, deobfuscationMapFile=null, deobfuscationForceSave=true, useSourceNameAsClassAlias=true, parseKotlinMetadata=true, deobfuscationMinLength=3, deobfuscationMaxLength=64, escapeUnicode=false, replaceConsts=true, respectBytecodeAccModifiers=false, exportAsGradleProject=true, fsCaseSensitive=false, renameFlags=[CASE, VALID, PRINTABLE], outputFormat=JAVA, commentsLevel=INFO, codeCache=InMemoryCodeCache: size=0, codeWriter=AnnotatedCodeWriter}
INFO : loading ...
```

**Comment by skylot** [comment]
@MPeti1 I uploaded fixed version of release files, please check.

**Comment by MPeti1** [comment]
It works now, thank you!

Could you tell what was the problem?

**Comment by skylot** [comment]
File without jre was build for java 11, but you use java 8, maybe it was the reason, so I rebuild it with java 8.
Bundle with jre was incorrectly configured, so it uses system jre instead bundled, and as soon it was build with java 17 it also not work with your system java 8.

**Comment by MPeti1** [comment]
oh. I suspected that it was because I use Java 8, but I ruled it out when the with-jre version didn not work either.
feel free to use never java version, thought, I will update when needed. Actually I think I've updated a few months ago, but the Java menu in the control panel says the latest I have is 1.8 so I'll need to sort it out either way

**Comment by skylot** [comment]
> feel free to use never java version, thought

Actually, I already updated required java to 11 in download section of readme, so it will push people to update java 🤣 
But I wonder how version compiled by java 11 managed to run on java 8? I thought it will just crash and force updating java. But as soon as this not happen and lead to weird errors, I decided to wait a little longer with this forced upgrade.
So anyway, thank you for test and report 👍🏽

**Comment by MPeti1** [comment]
I'm not sure if this could have caused it, but I have AdoptOpenJDK 16 installed, it just isn't installed as system Java, for some reason*. But then, `java -version` says this:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Windows 10 amd64-64-Bit Compressed References 20210421_24 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9)
```

\* or it is, and I just confuse system java with the Java installations shown in the Java menu in the control panel

**Comment by skylot** [comment]
Hm, `OpenJ9` can be the reason of issues, because I never checked it.
And yes, looks like this version was used and not java 8 :)
