### ISSUE TITLE
After Rename(n), the function of Find Usage(x) is broken 

### ISSUE THREAD

**Issue by jygzyc** [skylot/jadx#1281]
When I use jadx 1.3.0.1, I was very excited with the function of Rename(n). But I also need Find Usage(x) to get the location of Code logic. Both functions are not Compatible

**Comment by skylot** [comment]
@jygzyc I commit a quick fix for this issue, please check latest [unstable build](https://nightly.link/skylot/jadx/workflows/build/master).

Anyway, current solution just temporal and should be refactored to more suited usage data storage, also it is a good opportunity to support usage info for external functions (#1115)

**Comment by NilsIrl** [comment]
Is there a workaround a user can perform without using the unstable build?

**Comment by skylot** [comment]
@NilsIrl you can build from source. Actually, not sure what are you expecting to hear 😕
Anyway, I think I will make a new release next week, because this is quite big issue and there are many other important improvements.

**Comment by NilsIrl** [comment]
What I meant is using jadx 1.3.0, is there a way to force jadx to reload things correctly. I personally just ran the unstable build but the idea was to have a way to use jadx without restarting an already running instance.

**Comment by skylot** [comment]
@NilsIrl it is possible by resetting inner cache: by reopen project or enable/disable deobfuscation or change settings (like threads count), but this will cause full decompilation every time you open a search window and for big app this will take some time.
And still I don't see a reason to wait for these reloads instead updating to unstable if this issue affect you.
