### ISSUE TITLE
Update the report format parsing in Quark integration

### ISSUE THREAD

**Issue by haeter525** [skylot/jadx#1289]
For compatibility issues, Quark-Engine recently reverts a change to its report format in [v21.11.1](https://github.com/quark-engine/quark-engine/releases/tag/v21.11.1) (quark-engine/quark-engine#277).

As shown below, the reverted Quark report replaces two JSON arrays with JSON objects. Therefore, the parsing logic in the Quark integration might need to be adjusted.

![](https://i.imgur.com/4Y87liT.png)
![](https://i.imgur.com/1Svss1S.png)

I thought I can work on this and ensure the integration is compatible with both versions of Quark reports. If everything is OK, I will submit a PR linking to this issue later.

**Comment by skylot** [comment]
> I can work on this and ensure the integration is compatible with both versions

@haeter525 that will be great! 👍

**Comment by skylot** [comment]
Fixed in PR #1291
