### ISSUE TITLE
org.hamcrest.Matchers.is not in hamcrest-core-1.3.jar

### ISSUE THREAD

**Issue by fordMover** [skylot/jadx#129]
I built JADX from gradlew build without complaint, however trying to use it from Eclipse fails because Eclipse complains that import static org.hamcrest.Matchers.is; doesn't exist 

The method is(String[]) is undefined for the type TestEnums4.TestClsTestEnums4.java/jadx/jadx-core/src/test/java/jadx/tests/integration/enums

It seems that the 'is()' method is in the CodeMatchers class (and is deprecated).  Should the jadx code be updated to use CodeMatchers, or do I have the wrong version of hamcrest-core-1.3.jar?  I think that hamcrest wouldn't change the class method signatures and keep the same 1.3 version number.  (Gradle downloaded the version of hamcreat-core-1.3,jar)
 What's the problem here?

**Comment by asashour** [comment]
This works as of now, with `gradle` and with Eclipse.
