### ISSUE TITLE
[feature]Create auto-copy function for word

### ISSUE THREAD

**Issue by zhongqingsong** [skylot/jadx#1292]
*Describe your idea:*
As we know, Ida pro(another famous tool) has a function: when user click a word, its all letter will be choosen, it's color will be inverse. 
Of course, we already have that capability. But the last feature is useful, and jadx still lacks this feature:
**When word's color is inverse, we can direct press Ctrl + C to copy the word.**
For example, there is some code text.
`super.onCreate(savedInstanceState);`
When we click the word,(such as onCreate, and not double click), it's color will change. And feature is that we press Ctrl + C, the word will be copy to clipboard.
This will be easy to people, and dont have to copy word by drag the mouse.

Difficulty：now we can turn color to another color, we can add a shortcut key binding, and it's callback is copy. Then it's ok.
According to my judgement, the feature may be easy to do, but i'm not sure you will like it, so i submit a feature.

**Comment by skylot** [comment]
@zhongqingsong sure, that will be a nice feature! 👍🏽

**Comment by skylot** [comment]
Done :tada:

**Comment by dalishen99** [comment]
Hi how to close this feature?

Thanks.

**Comment by dalishen99** [comment]
It bings me some inconvenience,  i hope you can add a switch for this  thanks. @skylot @zhongqingsong
