### ISSUE TITLE
forward hot key seems not work in macos[feature]

### ISSUE THREAD

**Issue by stAticasd** [skylot/jadx#1297]
*Describe your idea:*
![image](https://user-images.githubusercontent.com/54659765/144164766-c32f8f14-1aac-4001-b7b1-8453c045dffe.png)

it doesn't work

**Comment by skylot** [comment]
@stAticasd I hope someone will make a PR to fix this issue 😞

**Comment by Surendrajat** [comment]
@stAticasd I've tried to fix this one(not a good solution because it also moves the cursor, but it works fine).
Can you try linked PR and see if it works for you too?

**Comment by stAticasd** [comment]
@Surendrajat it works for me well,thanks a lot
