### ISSUE TITLE
[feature] Add minimize/maximize buttons to SearchDialog and UsageDialog

### ISSUE THREAD

**Issue by jacopotediosi** [skylot/jadx#1298]
Hi,
using Jadx I often open multiple tabs starting from SearchDialog and UsageDialog. I use a lot the already implemented "keep open" feature of theese dialogs, but I would also like to be able to minimize or maximize them quickly. My actual workaround is to move them to unused screen areas, but it's a bit uncomfortable. I think to add the buttons we may need to convert the JDialogs to JFrames. Could it be worth it?

**Comment by skylot** [comment]
@jacopotediosi I made a change as you suggested, hope it will help 😄
