### ISSUE TITLE
[core] Failed to decompile try-catch-finally - Try blocks wrapping queue limit reached

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#1304]
Decompiling this sample fails with an error in BlockProcessor pass: "Try blocks wrapping queue limit reached".

I tested with latest git revision 0f00fb9 and openjdk8. Same result with java-input and java-convert.

```java
public class TestTryCatch1 {

  public void doSomething(int i) {
    try {
      doSomething1();

      if (i == -12) {
        return;
      }
      
      if (i > 10) {
        doSomething2();
      } else if (i == -1) {
        doSomething3();
      }
    } catch (Exception ex) {
      logError();
    } finally {
      doSomething4();
    }
  }

  private void logError() {
  }

  private void doSomething1() {
  }

  private void doSomething2() {
  }

  private void doSomething3() {
  }

  private void doSomething4() {
  }
}
```

This sample can be used in unit tests.

**Comment by skylot** [comment]
@nitram84 fixed, although it is not general enough so may break something else :smiling_face_with_tear:

**Comment by nitram84** [comment]
@skylot Thank you a lot for fixing this issue. Usually my examples are taken from real code. I minimized the code to the root and obfuscated it - every change to my example makes it decompilable. Think of a complex method with 100 or 200 lines that can now be decompiled by this fix. I think the best way to break large apps with large methods is to report and fix all the smaller problems.

**Comment by skylot** [comment]
> I think the best way to break large apps with large methods is to report and fix all the smaller problems.

You are right and this is the only way! Thank you for your work :+1:
