### ISSUE TITLE
[core] Compilation issues with nested anonymous classes

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#1305]
I would like to report some compilation issues with nested anonymous classes. I tested the following sample with latest git revision 0f00fb9 and openjdk8:

```java
public class JobProcessor {

  public interface Job {
    public void executeJob();
  }

  public void start() {
    runJob(new Job() {
      @Override
      public void executeJob() {
        runJob(new Job() {

          @Override
          public void executeJob() {
            doSomething();
          }
        });
      }

      private void doSomething() {
      }

    });
  }

  public static void runJob(Job job) {
  }
}
```

Case 1: When I am using this settings
[x] inline anonymous classes
[x] inline methods 
the result can't be compiled since "AnonymousClass1" does not exist.

Case 2: When I am using this settings
[ ] inline anonymous classes
[x] inline methods 
the result can't be compiled too. Error is "class JobProcessor.AnonymousClass1 is already defined in class JobProcessor".

I'm getting the same result with java-input and java-convert.

This sample can be used in unit tests.

**Comment by skylot** [comment]
@nitram84 both cases fixed. In second case was a stupid bug in rename code :confused:
Thanks for report!
