### ISSUE TITLE
process hasn't exited / Failed to set breakpoint at onCreate

### ISSUE THREAD

**Issue by pi0projects** [skylot/jadx#1309]
I followed the steps in the wiki for setting up the smali debugger. AVD version 8.1, uncrackable-1.apk. However I am not able to launch the app to setup the breakpoints on "onCreate"'. Here are a couple of screenshots with the error messages, any assistance is greatly appreciated.

![error3](https://user-images.githubusercontent.com/44707484/146610323-ace77999-0fff-4f57-a16f-6f8697820c48.png)

![debug](https://user-images.githubusercontent.com/44707484/146610345-91b507ea-d725-4d99-907c-d0b4962de242.png)

**Comment by skylot** [comment]
@pi0projects looks like you need to open that apk in jadx, so debugger will be able to find main activity and set breakpoint to `onCreate` method.
Not sure if this is only issue, hope @LBJ-the-GOAT will also join discussion.

**Comment by pi0projects** [comment]
thank you so much for the quick response, that was it!
