### ISSUE TITLE
Inapplicable path traversal attack error message

### ISSUE THREAD

**Issue by CmP-lt** [skylot/jadx#1310]
Opening any DEX file leads to error message of the following type getting logged:
```
ERROR: Path traversal attack detected, invalid name: C:\Users\Admin\Downloads\classes.dex
```
It seems that when a DEX file is opened separately, not as part of an APK file, JADX mistakenly treats it as being an entry of a ZIP archive and calls the following method to check validity of file path, as if it was name of an entry in a ZIP archive:
https://github.com/skylot/jadx/blob/d47483f957af709bf709e6c7ec7a857a9af71869/jadx-plugins/jadx-plugins-api/src/main/java/jadx/api/plugins/utils/ZipSecurity.java#L47-L62

**Comment by skylot** [comment]
@CmP-lt I can't reproduce your issue :disappointed: 
Can you provide jadx version and how you run jadx-gui (if from command line: share that command)?
Also, maybe someone else saw this issue and can add any detail? Stack trace to that method will be the best option :rofl:

**Comment by CmP-lt** [comment]
JADX version: 1.3.1
Java version: 11.0.12
Startup type: double-clicking "jadx-gui.bat" file

**Comment by skylot** [comment]
@CmP-lt thanks! I commit a fix :+1:
This issue not appear on Linux only on Windows. Unlike Windows, Linux is fine with merging two absolute paths :rofl:
