### ISSUE TITLE
[gui] Log window inconveniences

### ISSUE THREAD

**Issue by CmP-lt** [skylot/jadx#1311]
Using log window becomes inconvenient when it needs to be opened and closed multiple times because: 
- each time new log window is created;
- previously opened log windows need to be closed manually to avoid having many log windows that are all brought to foreground when new log window is created;
- log window gets blocked by main window when the former is sent to background, i.e. need to minimize main window or adjust it's size and/or position to be able to access existing log window.

There would be no such inconveniences if only one log window, that would be brought to foreground when called, could be created.

**Comment by skylot** [comment]
Fixed in PR #1649 by @jpstotz
