### ISSUE TITLE
[feature] Use relative paths in project file

### ISSUE THREAD

**Issue by kingfisher63** [skylot/jadx#1312]
Paths in the _files_ section of the project file (.jadx) are currently absolute paths. As a result paths become invalid when the project folder is moved to a new location. Using relative paths (if a file is in the same folder as the project file or a subfolder thereof) would resolve this.

**Comment by jpstotz** [comment]
A very good idea. I prepared the necessary changes.

**Comment by skylot** [comment]
Fixed in PR #1313
