### ISSUE TITLE
Passing the proper arguments [core]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#1314]
![image](https://user-images.githubusercontent.com/35992798/146764472-850bb9e6-b672-4ab9-92af-b641dc673bb1.png)

Hello there, Take the above code block as an example and as you can see there the arguments was not decompiled but rather it applies some anonymous field value such as r1 and r2.

![image](https://user-images.githubusercontent.com/35992798/146764720-6fb7d9c9-3519-4ec0-b7c0-742f9233ff2a.png)
![image](https://user-images.githubusercontent.com/35992798/146764741-7e1cc777-298e-44d2-a181-ae0acd252de7.png)

And as you can above that's a JADX version 1.2.0 and it doesn't inline anonymous class to the parent and arguments are correct. While it is great see the inlined anonymous classes (good job for that) but it'll be better if those arguments can be handle properly like in the older versions (where the anonymous classes not inlined)

**Comment by skylot** [comment]
@redmi111 as a workaround, it is possible to disable anonymous class inlining (check preferences). 
Also, this is a known issue, check #523.
Anyway, thanks for reminder! I will increase priority for that issue :+1:
