### ISSUE TITLE
[core][java-convert] Unable to decompile constructor - Illegal instructions before constructor call

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#1315]
I would like to report a really strange issue. This sample (compiled with openjdk8) can't be decompiled with latest git and java-convert enabled. Please try to compile this sample with comments.
```java
public class ExpressionInContructorException extends Exception {
  public ExpressionInContructorException(final Object message) {
    super((message == null) ? "" : message.toString());
    /* something weird happens here: without these comments everything decompiles fine. Only java-convert is affected. Only line numbers in smali view are modified with comments. But this is not the cause. 
    /*
	    r1 = this;
	    if (r2 != 0) goto L_0x0008
	    java.lang.String r0 = ""
	L_0x0004:
	    r1.<init>(r0)
	    return
	L_0x0008:
	    java.lang.String r0 = r2.toString()
	    goto L_0x0004
	*/
  }
}
```

With comments removed everything decompiled fine. Java-input is also not affected. I'm not able to reproduce this with plain smali code. The comments do only change line numbers in smali.
(I found this case by minimizing a complex sample by commenting out and removing not relevant code. Instead of comments there might be some code, but with comments only this issue is even stranger.)

Please tell me if this issue can't be reproduced. If so, I would provide a class file.

This sample can be used for unit tests.

**Comment by skylot** [comment]
@nitram84 thanks! Nice catch :rofl:
Issue description: during ternary restoring jadx uses line numbers as a hint and don't use ternary if branches have different line numbers. But somehow here line number from `return` instruction (at the method end) set for only one of the branches and ternary transform not applied, this make impossible to set super call as a first instruction in method (required by java compiler) so jadx raise error.
I need to dig deeper to understand why line number from `return` leaked to that branch.

**Comment by skylot** [comment]
Fixed.
