### ISSUE TITLE
[feature] No single variable name?

### ISSUE THREAD

**Issue by shirshak55** [skylot/jadx#1321]
Single method and variable name are very hard to search

There was one method called new r(.....)

Now I tried to search for r(  but I can't search efficiently because it matches with other nonsense like Builder(. It would be nice if we can use a minimum 3 letters or 2 letters so there is less chance of conflict and searching is easy?

I tried searching on google and issue tracker but I was unable to find it :p

**Comment by skylot** [comment]
@shirshak55 I think it is better to enable `regex` search option and use something like `\Wr\(` (`\W` - a non-word character). Check [Java Pattern class](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html) for full list of regex predefined vars.
Also, for a single method you can use `Find usage` from context menu on method name (`x` keyboard shortcut).
