### ISSUE TITLE
Difference between the screenshot and the actual.

### ISSUE THREAD

**Issue by SetoKaiba** [skylot/jadx#133]
From the screenshot, I see that it's available to jump to the method by clicking. But the actual running not. I'm trying to decompile a jar file.

**Comment by dnet** [comment]
What do you mean? Clicking on items in the left tree panel takes me to the method by clicking, just like on the screenshot.

**Comment by SetoKaiba** [comment]
No. I mean in the right panel. From the screenshot, there's a underline with the fields and methods. Then I think it should be able to jump to declaration of fields or methods by clicking on them.

**Comment by SetoKaiba** [comment]
For example, from the screenshot, getInnerClasses should be able to click to jump to the declaration of it.

**Comment by jpstotz** [comment]
Press and hold the Ctrl key.

**Comment by SetoKaiba** [comment]
@jpstotz Thank you. That's it. That's what I need.
