### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Nisarga-Developer** [skylot/jadx#1333]
**FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'jadx'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.diffplug.spotless:spotless-lib:2.21.0.
     Required by:
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.0 > com.diffplug.spotless:spotless-plugin-gradle:6.1.0
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.0 > com.diffplug.spotless:spotless-plugin-gradle:6.1.0 > com.diffplug.spotless:spotless-lib-extra:2.21.0
      > Could not resolve com.diffplug.spotless:spotless-lib:2.21.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib/2.21.0/spotless-lib-2.21.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/diffplug/spotless/spotless-lib/2.21.0/spotless-lib-2.21.0.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve io.github.x-stream:mxparser:1.2.1.
     Required by:
         project : > com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.39.0 > com.github.ben-manes:gradle-versions-plugin:0.39.0 > com.thoughtworks.xstream:xstream:1.4.17
      > Skipped due to earlier error
   > Could not resolve com.googlecode.concurrent-trees:concurrent-trees:2.6.1.
     Required by:
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.0 > com.diffplug.spotless:spotless-plugin-gradle:6.1.0 > com.diffplug.spotless:spotless-lib-extra:2.21.0
      > Skipped due to earlier error
   > Could not resolve org.codehaus.groovy:groovy-xml:3.0.9.
     Required by:
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.0 > com.diffplug.spotless:spotless-plugin-gradle:6.1.0 > com.diffplug.spotless:spotless-lib-extra:2.21.0
      > Skipped due to earlier error
   > Could not resolve com.googlecode.javaewah:JavaEWAH:1.1.12.
     Required by:
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.0 > com.diffplug.spotless:spotless-plugin-gradle:6.1.0 > org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r
      > Skipped due to earlier error
   > Could not resolve org.slf4j:slf4j-api:1.7.30.
     Required by:
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.0 > com.diffplug.spotless:spotless-plugin-gradle:6.1.0 > org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r
      > Skipped due to earlier error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
9 actionable tasks: 9 up-to-date

[process exited with code 1]

**Comment by Nisarga-Developer** [comment]
Got this when I ran gradlew.bat

**Comment by skylot** [comment]
> status code 502 from server: Bad Gateway

@Nisarga-Developer looks like a bad connection, try again :)
