### ISSUE TITLE
[core] Missing casts and cast optimizations

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#1336]
I made some tests with casts and would like to report some compilation issues (missing casts) and a little feature request (avoid intermediate or unnecessary casts). My tests were made with openjdk8, latest git version, java-input and java-convert (same results):

```java
public class JadxCastTest {
  public void testCasts() {
    testShort((short)0);  // compilation issue, cast missing after decompilation
    testShort((short)getInt()); // ok
    testByte((byte)0);  // ok
    testByte((byte)getInt());  // ok
    testChar((char)0);  // compilation issue, cast missing after decompilation
    testChar((char)getInt()); // ok
    testShort((short)0L);  // compilation issue, cast missing after decompilation
    testShort((short)getLong()); // ok, but no intermediate cast to int necessary
    testByte((byte)0L);  // const becomes an int
    testByte((byte)getLong()); // ok, but no intermediate cast to int necessary
    testChar((char)0L);  // compilation issue, cast missing after decompilation, const becomes an int
    testChar((char)getLong()); // ok, but no intermediate cast to int necessary
    testShort((short)' ');  // compilation issue, cast missing after decompilation, const becomes an int
    testShort((short)getChar());  // ok
    testByte((byte)' ');  // ok, but const becomes an int
    testByte((byte)getChar());  // ok
  }

  private long getLong() {
    return 1L; // const becomes an int
  }

  private char getChar() {
    return ' ';
  }

  private int getInt() {
    return 1;
  }

  private void testChar(char c) {
  }

  private void testByte(byte b) {
  }

  private void testShort(short s) {
  }
}
```

I observed that jadx converts long and char constants to int. I don't see a problem here as long as the results are the same. But I think cascading casts (long -> int -> short) could be optimized.

This sample can be used for unit tests.

**Comment by skylot** [comment]
@nitram84 I commit a fix for compilation issues and unnecessary cascading casts.
Although, I must note that type of some constants can't be restored during decompilation because java compiler can convert/cast constant at compile time, so in bytecode appear already converted ones, so jadx don't know original type.
In your sample, for example, this happens with char constants: bytecode load them as a byte, so char type info is lost completely.

**Comment by nitram84** [comment]
Thank you very much for your fixes and your explanation!
