### ISSUE TITLE
Add argument that restores obfuscated packages

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#134]
Hi. In obfuscated Android apps I ofter see code like

```
package android.support.v7.a;
// imports
/* compiled from: AppCompatActivity */
public class ag extends aa implements dn, ah, h {
```

You somehow know the real class name. So is that possible to add a parameter which will enable deobfuscation of class and package names? Thanks.

**Comment by asLody** [comment]
Open the following Switch:
Settings -> Enable deobfuscation
Settings -> Use source file name as class name alias.
