### ISSUE TITLE
[core] Invalid member access expressions

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1340]
Hey!

APK: https://drive.google.com/file/d/1itnzM0TmVY22OFebbD9VHxbpOZ_otZ4k/view?usp=sharing

There are a lot of such issues, but an example is in class `androidx.compose.animation.C0427am`
```java
    final androidx.compose.animation.core.C0473ba<androidx.compose.animation.EnterExitState>.androidx/compose/animation/core/bb f1744a;
```

![image](https://user-images.githubusercontent.com/15173437/150004781-2396c41b-3294-4ce4-aff4-2560827a787d.png)

**Comment by jpstotz** [comment]
@bagipro For reproducibility it would better you would add the original class name(s), not the class names generated by deobfuscation as those names seem to be not deterministic so it is difficult to reproduce the state shown in the screen shot. 

I am also not sure what you want to point out. Are you referring to the `.androidx/compose/animation/core/bb` part included in the class name?

**Comment by skylot** [comment]
> Are you referring to the .androidx/compose/animation/core/bb part included in the class name?

@jpstotz it is definitely this :)
```java
ba<EnterExitState>.androidx/compose/animation/core/bb
```
Looks like originally `bb` class was inner class for `ba` and use that generic variable from `ba`.
So jadx needs to detect such signatures and move `bb` into `ba` class.

**Comment by skylot** [comment]
@bagipro fixed, please check

**Comment by bagipro** [comment]
Hey @skylot, sorry for the long response. 

I don't think that it's fixed completely. Example in class `androidx.compose.animation.core.TransitionKt$createDeferredAnimation$1`:
```java
            androidx.compose.animation.core.C0473ba<S>.androidx.compose.animation.core.C0473ba.C0474bb<T, V>.C0475bc<T, V> bcVar = deferredAnimation.f1886a;
```

the generated name is incorrect `androidx.compose.animation.core.C0473ba<S>.androidx.compose.animation.core.C0473ba.C0474bb`

Should I reopen the issue?

**Comment by skylot** [comment]
@bagipro sorry, forget to check with full names (with disabled `use imports`) 😞 
Please check latest commit :grin:

**Comment by bagipro** [comment]
@skylot 
Thanks! Yes, that's fixed
