### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: newPosition > limit: (8899092 > 8413288)[core]

### ISSUE THREAD

**Issue by wangxw0820** [skylot/jadx#1342]
![image](https://user-images.githubusercontent.com/29654121/150290828-d85b3b0c-a9da-4da5-b8de-67cd8749e9f9.png)

**Comment by wangxw0820** [comment]
[0xd2e00000.zip](https://github.com/skylot/jadx/files/7903073/0xd2e00000.zip)

**Comment by skylot** [comment]
@wangxw0820 looks like this file is corrupted. Dexdump report bad checksum:
> Failure to verify dex file '0xd2e00000.dex': Bad checksum (cd1e5784, expected 8979edf8)

I think jadx also need to implement checksum verification, I will open separate issue.
