### ISSUE TITLE
How to build without Internet?

### ISSUE THREAD

**Issue by Dave1991** [skylot/jadx#137]
I wanna run jadx on my server, however, there is no Internet on the server. So the command ./gradlew dist will be error. How to fix it?

**Comment by M1kep** [comment]
You could more than  likely build on computer, and upload the dependencies it's grabbing to the server

**Comment by ForsakenHarmony** [comment]
@Dave1991 why does your server not have an internet connection?

**Comment by Dave1991** [comment]
Because the server store something sensitive.

**Comment by ForsakenHarmony** [comment]
@Dave1991 it doesn't have to be publicly accessible
