### ISSUE TITLE
[core]No classes loaded, nothing to decompile!

### ISSUE THREAD

**Issue by Lunction** [skylot/jadx#1373]
![image](https://user-images.githubusercontent.com/51918328/152993565-e90eba15-e63d-4d65-abcf-92c7a3b2525b.png)

**Comment by jpstotz** [comment]
That is the way of Jadx to tell you that what ever file you have loaded into Jadx is not supported.

What type of file(s) have you tried to open with Jadx?

**Comment by GamerXD8991** [comment]
Same problem, tried to open apk and dex files and the folder of the extracted apk file

**Comment by skylot** [comment]
@Lunction @GamerXD8991 please share files you are trying to open, otherwise I am unable to reproduce this issue.

**Comment by Lunction** [comment]
I  know why

**Comment by jpstotz** [comment]
> I know why

@[Lunction](https://github.com/Lunction) Would you mind sharing the reason for this problem with us? So others who have the same problem are able to check if in their case the reason is also the same.

**Comment by chenyue404** [comment]
I encountered the same problem, 1.3.0.1 works fine, but higher versions report the same error.

**Comment by jpstotz** [comment]
> I encountered the same problem, 1.3.0.1 works fine, but higher versions report the same error. This is true for any apk

@[chenyue404](https://github.com/chenyue404) Then please provide more details on the used OS and version, the used Java version (version and distribution) and which Jadx release asset you have downloaded and how you load the APK into Jadx (via command-line argument, drag & drop, open menu). 
And finally it would be good to provide one of the APK files that don't work.

**Comment by chenyue404** [comment]
> 
Sorry for not providing valid information before.

The operating system used is Windows 11 21H2 22000.527, and there is another windows 10 with the same problem.

The java version is 
> java version "1.8.0_162"
> Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)".

The jadx version is jadx-gui-1.3.3-no-jre-win.exe.

The way to load the apk is "File-open Files".

The error message is "No classes loaded, nothing to decompile!"
Click on the Summary file, it shows 
> Error build summary:
> NullPointerException" at java.lang.
> 	at jadx.gui.ui.treenodes.SummaryNode.writeInputSummary(SummaryNode.java:71)
> 	at jadx.gui.ui.treenodes.SummaryNode.getContent(SummaryNode.java:47)
> 	at jadx.gui.ui.panel.HtmlPanel. (HtmlPanel.java:25)
> 	at jadx.gui.ui.treenodes.SummaryNode.getContentPanel(SummaryNode.java:146)
> 	at jadx.gui.ui.TabbedPane.getContentPanel(TabbedPane.java:321)
> 	at jadx.gui.ui.TabbedPane.showNode(TabbedPane.java:207)
> 	at jadx.gui.ui.MainWindow.nodeClickAction(MainWindow.java:753)
> 	at jadx.gui.ui.MainWindow.access$1100(MainWindow.java:147)

The apk file is placed in the attachment, and in fact, any apk will not load.
[systemUI.zip](https://github.com/skylot/jadx/files/8108919/systemUI.zip)

**Comment by skylot** [comment]
@chenyue404 thanks for that information!
I was using a later version of java to build that bundle. I re-upload it, please check: [jadx-gui-1.3.3-1-no-jre-win.exe](https://github.com/skylot/jadx/releases/download/v1.3.3/jadx-gui-1.3.3-1-no-jre-win.exe)
Anyway, it is always better to use the latest java version or use jadx bundle with built-in java (i.e [jadx-gui-1.3.3-with-jre-win.zip](https://github.com/skylot/jadx/releases/download/v1.3.3/jadx-gui-1.3.3-with-jre-win.zip))

**Comment by chenyue404** [comment]
> @chenyue404 thanks for that information! I was using a later version of java to build that bundle. I re-upload it, please check: [jadx-gui-1.3.3-1-no-jre-win.exe](https://github.com/skylot/jadx/releases/download/v1.3.3/jadx-gui-1.3.3-1-no-jre-win.exe) Anyway, it is always better to use the latest java version or use jadx bundle with built-in java (i.e [jadx-gui-1.3.3-with-jre-win.zip](https://github.com/skylot/jadx/releases/download/v1.3.3/jadx-gui-1.3.3-with-jre-win.zip))

@skylot Thank you for such a quick reply, this version worked great.
