### ISSUE TITLE
Compile with Excelsior JET

### ISSUE THREAD

**Issue by Sputuks3** [skylot/jadx#138]
Hey @skylot , in case you don't already know, this nifty tool allows compilation to native code for performance purposes. And JADX qualifies!

![untitled](https://cloud.githubusercontent.com/assets/1269084/19240238/10f76af2-8f3c-11e6-8291-f2a25a890812.png)

Follow the instructions here https://www.excelsiorjet.com/free#apply to obtain a free enterprise license. Then you can publish release builds in native binary for download!

![untitled-2](https://cloud.githubusercontent.com/assets/1269084/19240289/4cb6a616-8f3c-11e6-8962-1fdae6d13a76.png)

Please consider.

**Comment by sergey-wowwow** [comment]
@Sputuks3 
Current version of jadx already generates native executables
