### ISSUE TITLE
[feature] single class flag outputs more than one class

### ISSUE THREAD

**Issue by yotamN** [skylot/jadx#1384]
Currently, trying to decompile a single class will output multiple classes, it seems those are the classes the requested class is dependent on. I think the expected behavior is to get only the requested class and maybe add an option to include dependencies.

**Comment by skylot** [comment]
@yotamN I add custom processing for single class mode, so dependencies will not be saved.
Also, I add option to set an output file or directory, check https://github.com/skylot/jadx/issues/1344#issuecomment-1046264789 for details.
