### ISSUE TITLE
[feature] add verify dex file checksum switch

### ISSUE THREAD

**Issue by Jackjun724** [skylot/jadx#1385]
I have bad dex file, it's checksum is error. It comes from the frida-DEXDUMP, I used to use 1.2.0 version of jadx, which can normally open this DEX (maybe there are some errors). In 1.3.3 version, I can't open it. I think decompiling some code is better than unable to decompile. I think jadx need a switch to control `verify dex file checksum`

**Comment by skylot** [comment]
@Jackjun724 done. New option to disable checksum verification added for cli and gui.
Actually, it is a plugin option, so there are a lot of changes to automatically pull options data from plugins and show/parse in cli and gui. Hope it will work as expected :slightly_smiling_face:

**Comment by Jackjun724** [comment]
Thank you for your 🙂

**Comment by Jackjun724** [comment]
@skylot I found a new bug, If `Jadx-gui` does not open any files, a NullPointerException will be thrown when opening the setting window, I think it is because the decompiler is uninitialized when the file is not open. [bug code](https://github.com/skylot/jadx/blob/54683e319804e607bcc37a8e37b7b6f693bb43fe/jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsWindow.java#L564)

**Comment by skylot** [comment]
> I found a new bug

@Jackjun724 thanks! NPE fixed :+1:
