### ISSUE TITLE
decompiler by need

### ISSUE THREAD

**Issue by tiann** [skylot/jadx#139]
when the apk file is too large, jadx may produce OutOfMemoryError, and it is also annoying to wait for the completion of decompiler; 

If jadx support decompiler-by-need——when i click the directory in the src dir, it begin decompiler.

**Comment by jpstotz** [comment]
One major feature of Jadx is that it indexes the decompiled source code. This allows you to search for cross references, strings, method calls, and so on. For doing so decompiling everything is mandatory. 

If you really want to work with such big dex files I would strongly recommend not to use Jadx but a different file based tool instead (apktool, CodeInspect, JEB2, ...).

**Comment by sergey-wowwow** [comment]
@tiann,
The latest version of jadx fixes multiple issues which caused that error, and my 16GB of installed RAM is enough to process huge apps like Uber or Airbnb pretty fast
