### ISSUE TITLE
[feature][GUI][Display overlapping content residual shadow]

### ISSUE THREAD

**Issue by shumxin** [skylot/jadx#1401]
as shown in the figure
<img width="438" alt="1646495775(1)" src="https://user-images.githubusercontent.com/10057278/156890952-5082e03b-5519-4bf0-b107-47a0770aac7b.png">

**Comment by skylot** [comment]
@shumxin if possible, check with the latest java version (17) or using bundle with included java ([this](https://github.com/skylot/jadx/releases/download/v1.3.3/jadx-gui-1.3.3-with-jre-win.zip))
If this doesn't help, share your OS and java version (can be found in help->about)

**Comment by shumxin** [comment]
Sorry for the late reply, using bundle with included java works for me.
Thank you so much for your reply.

**Comment by shumxin** [comment]
![image](https://user-images.githubusercontent.com/10057278/160238582-2eba3d23-199f-4d21-838f-e5651694991d.png)

@skylot The problem  occurred again when I using bundle with included java. Maybe it's because my monitor has 4K resolution?

![image](https://user-images.githubusercontent.com/10057278/160238858-c91fc000-9995-486a-be5e-b9bca1982818.png)
![image](https://user-images.githubusercontent.com/10057278/160238886-aa62ee35-ab5b-40cd-9c70-bf33300c832c.png)

**Comment by skylot** [comment]
@shumxin I think these issue caused by rendering problem in java. Also, I can't reproduce such issues, so it is hard to help you.
I only can suggest checking that you use the latest java version at runtime by opening `Help` -> `About` (because it can be different from version in your screenshot).

**Comment by shumxin** [comment]
> @shumxin I think these issue caused by rendering problem in java. Also, I can't reproduce such issues, so it is hard to help you. I only can suggest checking that you use the latest java version at runtime by opening `Help` -> `About` (because it can be different from version in your screenshot).

Thanks. When something goes wrong, I try to switch the display resolution for a while

![image](https://user-images.githubusercontent.com/10057278/160264455-a35d72aa-9703-4a8b-b0d3-24c1faccf73b.png)
