### ISSUE TITLE
[feature] Zoom-in & Zoom-out

### ISSUE THREAD

**Issue by x0xman** [skylot/jadx#1403]
Can you add Zoom-in & Zoom-out in Editor Code ? 
This feature is not present , it is tiring when watching the source-code and causes eye strain

Very very important feature  👍

**Comment by meiraxx** [comment]
@skylot I am unable to use `CTRL +`, `CMD +`, `CTRL Mouse Wheel Up/Down` or `CMD Mouse Wheel Up/Down`.

Setup:
- JADX 1.4.7 (brew install jadx)
- MacOS 13.4.1
