### ISSUE TITLE
jitPack not found lib

### ISSUE THREAD

**Issue by TimScriptov** [skylot/jadx#1404]
![Screenshot_1](https://user-images.githubusercontent.com/31324315/157702234-7f8b092b-6790-4eba-aa46-be8b4642bdcd.png)

**Comment by skylot** [comment]
@TimScriptov 
Jadx now available on [Maven Central](https://search.maven.org/search?q=jadx) please check [this wiki page](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library) for usage help.
