### ISSUE TITLE
How to use the .jobf file to rename methods, classes, packages and variables?

### ISSUE THREAD

**Issue by M1kep** [skylot/jadx#141]
Hello there,

So I'm wondering how I can go about modifying a .jobf file to rename methods in classes and how I would go about handing two methods with the same decompiled name but different parameters, for example the following should have different names which I'd like to define:

private static void a(aWv aWv, aWw aWw)
public void a(Object obj)

I know the jobf file supports p, c, m, and f but I'm not sure how to use anything other than the p and c ones. Any sort of information would be greatly appreciated.

**Comment by M1kep** [comment]
Figured it out, for a method like:

private boolean a(@y l lVar, boolean z) in the package com.alexvasilkov.gestures;

You'd add the following the .jobf file to re-name it:

m com.alexvasilkov.gestures.a.a(Lcom/alexvasilkov/gestures/l;Z)Z = test123

**Comment by sergey-wowwow** [comment]
> Figured it out
