### ISSUE TITLE
[feature] Add Logcat output into debugger

### ISSUE THREAD

**Issue by TheCobraChicken** [skylot/jadx#1411]
I would like the Jadx debugger to include the logcat output within the Jadx GUI.  Ive been building the feature and have it working for my purposes but not quite ready to include into production.  Creating this issue to get others opinion.

Currently can be found at https://github.com/green9317/jadx/tree/logcatAddition  

![jadx_logcat_example](https://user-images.githubusercontent.com/38409554/158965118-81710fd9-7efb-4bc3-bfbb-e777e8f975f2.gif)

Before I submit I still want to add 
1. ability to filter to debugged process 
2. automatically update process list
3. button to clear logcat
4. button to pause logcat (for performance sensitive users)
5. Change how logcat output is displayed to make it easier to read
6. clean code

**Comment by green9317** [comment]
Ill do that.  I wasn't sure if not having the latest commit would cause an issue when I do a pull request.
