### ISSUE TITLE
[feature] Allow copy(复制) on hover

### ISSUE THREAD

**Issue by b0123456789** [skylot/jadx#1421]
![2022-03-24 09-49-41屏幕截图](https://user-images.githubusercontent.com/21169660/159826553-ddb1700f-0437-4c3d-9346-5496a5a2f71c.png)

I found that to enable copy(复制) menu item should  select  text before.
if it enable on hover is convenient .

**Comment by zhongqingsong** [comment]
Jadx now supports IDA-style copying: you **click on a word and Ctrl + C** directly. You don't have to drag to copy the whole word.
Of course this click copy is only available in the latest version of JADX. I think this kind of click copy is a better way to synthesize balance comparison.

**Comment by b0123456789** [comment]
thx
