### ISSUE TITLE
distribute as flatpak on flathub.org

### ISSUE THREAD

**Issue by Bleuzen** [skylot/jadx#1427]
Hi, I currently package jadx as flatpak to be available on flathub.org.
You can see the current progress in this pr: https://github.com/flathub/flathub/pull/2942

1) Are you fine with distributing jadx on flathub?
2) If so, this still needs some metadata. The appstream.xml should be included in this repo, see: https://github.com/skylot/jadx/pull/1426

**Comment by skylot** [comment]
> Are you fine with distributing jadx on flathub?

Sure, that will be great!

**Comment by skylot** [comment]
@Bleuzen I have a small question: you mention that I will need to include `appdata.xml` in release zip, does anything else needs to done on release? Maybe you can link some docs about new release process?

**Comment by Bleuzen** [comment]
@skylot 

> Maybe you can link some docs about new release process?

Here is the spec:
https://www.freedesktop.org/software/appstream/docs/

> does anything else needs to be done on release?

Yes. In the metadata file there is a releases node, where I already added version 1.3.4.
See: 
https://github.com/skylot/jadx/blob/e5fa818b5c370145b28626918d64c154a67bf633/appdata.xml#L39

Before a new version is released, you should add the new release there.

You _could_ even add a changelog / release description there (in `<description>` tag within a `<release>`).
As an example look at the file here:
https://github.com/flathub/com.github.hopsan.Hopsan/blob/2d9c0c698a5cb8109e351a75a5948a18c4d2c3b3/com.github.hopsan.Hopsan.appdata.xml

Also there are other attributes available, see:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases

However this is optional.
Minimum is that at least one release with version and date is provided.
See: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html

> The application metainfo should at least provide one <releases/> tag, which has one or more <release/> children to define the version and release date of this application.

So if you don't care about version history and changelog to show up in software stores, you can always only have one `<release>` tag in there and just use a text replace tool like `sed` to put in the newest version and date of its release.

How much you want to provide is up to you, as long as at least the newest release with version and date is in there.
