### ISSUE TITLE
GUI Does not support 4K display

### ISSUE THREAD

**Issue by IRMobydick** [skylot/jadx#143]
Hi There,
The GUI does not support 4K displays and icons are so small and text are so hard to read :(
I'm using the latest one

**Comment by jpstotz** [comment]
Which OS do you use and how do you start jadx?

**Comment by IRMobydick** [comment]
I'm using windows 10 and I'm run it from command line `/jadx-gui.bat`

**Comment by jpstotz** [comment]
JadX uses Java Swing for the UI and it look like Swing does not work well on high DPI displays.
Search for it and you will get plenty of results. JadX already uses the "SystemLookAndFeel" theme which works "best" (in the meaning less worse than others) for high res displays. 

May be you should try a beta of Java 9 - it seems like Java 9 will finally come with high-res display support.

**Comment by IRMobydick** [comment]
Best Solution for me ( on Windows 10 ) was:
1. find `java.exe` , `javaw.exe`, `javaws.exe`
2. For each one Right click -> `Properties`
3. Go to `Compatibility` tab
4. **Check** `Override high DPI scaling behavior`
5. Choose `System` for `Scaling performed by:`

**Comment by neworld** [comment]
In the Linux I improved DPI with `export GDK_SCALE = 2`

**Comment by asashour** [comment]
I guess this should be closed, Java 9 was released almost two years ago, and nothing would be done at the moment from Jadx side.
