### ISSUE TITLE
[core] com.google.android.gms

### ISSUE THREAD

**Issue by 89z** [skylot/jadx#1437]
If I try to extract the above APK, with command like this:

~~~
jadx.bat com.google.android.gms.apk
~~~

It starts off OK, but once it gets to about 80%, the CPU goes up to 100% for several minutes, and it doesnt really make any progress.

**Comment by 89z** [comment]
As a workaround, older version 21.09.65 (2021) seems to extract without problem.

**Comment by jpstotz** [comment]
Can you please provide the APK file or a link to the file? I just tried latest Google Play services_v22.09.20 (080406-434869283) from Apkpure.com and it decompiled quite well using latest unstable Jadx version (GUI and command-line). 

If on Windows a Java process uses 100% for a long time this may indicate that it is running out of memory (the high CPU usage is caused by the garbage collector which is executed again and again to regain memory). But without being able to reproduce it this is just a guess, it could be also something going wrong in Jadx.

**Comment by 89z** [comment]
I believe this is what I tried:

https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-22-09-20-release/google-play-services-22-09-20-040700-434869283-android-apk-download/download/?forcebaseapk=true

**Comment by 89z** [comment]
Yeah, I think that was the problem.

Looking at my memory, after the change, I saw it go up to 6,511 MB.

But after the change, it finished in normal time.

**Comment by jpstotz** [comment]
@skylot May be we should replace `-Xmx4g` in jadx.bat by `-XX:MaxRAMPercentage=70.0` (use max 70% of RAM).

According to [Stackoverflow](https://stackoverflow.com/a/57895677/150978) it is supported since Java 8u191 and of course Java9+.

**Comment by skylot** [comment]
@jpstotz 
> May be we should replace -Xmx4g in jadx.bat by -XX:MaxRAMPercentage=70.0 (use max 70% of RAM)

Sure, this will simplify memory setup (most users will no need to change it), and it is already set for launch4j executable.
Only drawback I see is increased total memory usage (GC can run less often).
Anyway, apps grows in size very fast, so looks like I should increase priority of saving decompilation results on disk (#784).

**Comment by skylot** [comment]
I commit changes suggested by @jpstotz (`-XX:MaxRAMPercentage=70.0` instead fixed `-Xmx4g`).
I think this issue can be closed now.

**Comment by 89z** [comment]
@skylot please note that as I mentioned, and as @NikolozCh mentioned, this will fail for users with 8 GB of RAM (which includes @NikolozCh)

**Comment by skylot** [comment]
> this will fail for users with 8 GB of RAM

@89z I understand that. But we are very limited in what we can do here, so I just apply better option for most users.
If these settings don't work, users can try workarounds from [troubleshooting guide](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#out-of-memory-problems).

**Comment by 89z** [comment]
couldnt you just do something like `-Xmx7g`?

I am not skilled with Java, so I dont know the drawbacks
