### ISSUE TITLE
[feature] current gradle configuration doesn't allow publishToMavenLocal without signature keys

### ISSUE THREAD

**Issue by root-intruder** [skylot/jadx#1438]
Currently the gradle task publishToMavenLocal can not be executed:
```
Execution failed for task ':jadx-core:signMavenJavaPublication'.
 Cannot perform signing task ':jadx-core:signMavenJavaPublication' because it has no configured signatory
```
-> gradle tries to sign all publishing tasks. But one might not have proper signing keys configured and one should not need signing for local builds.

Thus, I propose skipping signing for local builds according to:
https://docs.gradle.org/current/userguide/signing_plugin.html#sec:conditional_signing

Using:
```
signing {
    required { gradle.taskGraph.hasTask("publish") }
    sign publishing.publications.mavenJava
}
```
and thus only sign builds that should be published to the internet will be signed...publishing to local stays unsigned

Implementing this will also fix builds on jitpack.io ...see:
https://jitpack.io/#root-intruder/jadx

while skylot/jadx fails with aforementioned error:
https://jitpack.io/#skylot/jadx

**Comment by skylot** [comment]
@root-intruder thanks. I agree that `publishToMavenLocal` should be fixed, but I intentionally will break jitpack build because jadx artifacts now available on maven central ([list](https://search.maven.org/search?q=jadx), [usage help](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library)).

**Comment by root-intruder** [comment]
@skylot thanks! I don't get the point of intentionally breaking jitpack. I agree that using maven central should be first option. Keep in mind that bugfixes to maven central will take a few weeks, whenever you feel like creating a new release. Using jitpack to get latest commit builds is in my opinion a valid alternative during waiting for newest bugfixes arrive in the releases on maven central. Sometimes it's not an option to wait a few weeks during development.

**Comment by root-intruder** [comment]
there is no effort to support it...isn't that the whole idea of jitpack!? it will work as long as there is a gradle build file (and no mandatory signatures  ;-) )
