### ISSUE TITLE
[core] Rename exception 

### ISSUE THREAD

**Issue by AdminHcat** [skylot/jadx#1441]
**Describe error**
- com.corrodinggames.rts.gameFramework.utility.m
- [1.15p8.zip](https://github.com/skylot/jadx/files/8439343/1.15p8.zip)

![image](https://user-images.githubusercontent.com/50044729/162111686-4d285c82-c13c-432a-b1da-0f9b5b82593c.png)
![image](https://user-images.githubusercontent.com/50044729/162113786-711f5650-28f8-4375-99d6-2c4d90e1af1f.png)
![image](https://user-images.githubusercontent.com/50044729/162111270-e834a113-ef96-40e9-bad5-58d9227028dd.png)
![image](https://user-images.githubusercontent.com/50044729/162113274-42db837e-491f-452b-a67c-8cf96f7f0516.png)

**Comment by skylot** [comment]
@AdminHcat you are trying to rename constructor method, which name should be equal to class name, so looks like jadx just ignore such renames and use class name. Also, exception you mention is not relevant to this rename, but anyway should be fixed.
So... I am not sure how to fix this, possible options are:
1. forbid constructor rename (just ignore or show warning dialog)
2. rename class (will also rename constructor)

I think second option is better, but can be confusing if you don't notice it is a constructor and don't want to rename a whole class.

**Comment by skylot** [comment]
Both issues fixed.
