### ISSUE TITLE
[gui]Can't rename the WORD that create by get method.

### ISSUE THREAD

**Issue by zhongqingsong** [skylot/jadx#1443]
**Checks before report**
- I check the word 'rename', and not find the issue recent year.
- jadx 1.3.4
- jdk 17
 
**Describe error**
- Jadx has a function that auto rename field'name by Guess according to the following text. The function is nice.
Ep: 
```
// they can't rename by user
String stringExtra = intent.getStringExtra("COMIC_NAME");
String stringExtra2 = intent.getStringExtra("EPISODE_ID");
String stringExtra3 = intent.getStringExtra("EPISODE_TITLE");
```
jadx will auto rename String by the follow method name. This function will be nice in general.
But it can't be 100% correct, so I want to rename field name by myself. 
As in the code example above, i want to rename stringExtrato comic_name, and others will rename too.
That's where the problem comes in, **I can't rename stringExtra to what i want.** When i 'N', rename over, enter. Jadx will flush, and nothing happen. My rename is not work, jadx will also show name generated by JADX.
I try to reopen jadx, and change rename name.It can't work too.
And I test other way, i find that :
if filed name is generated by JADX‘s auto rename, then I can't change.
But this below can rename success.
```
this.hL = getIntent().getStringExtra("EXTRA_KEY_COMIC_TITLE");
// hL rename to comictitle, it's ok
this.comictitle = getIntent().getStringExtra("EXTRA_KEY_COMIC_TITLE");
```
So I have a guess, as long as the generated variable name is automatically guessed by the method name(getXXXX), then it can't be rename by user. By extension, there is other way that can't rename by user. Sorry I didn't write it down
- **IMPORTANT!** attach or provide link to apk file (double check apk version)
I've known this problem for a long time, I thought someone would ask that issue. But it seems there's always been this problem.

**Comment by skylot** [comment]
@zhongqingsong unfortunately I can't reproduce your issue, rename for these variables works fine for me.
It is possible that an issue related to your sample, so, if possible, please share your apk and full class name where to rename these variables. Also, it can depend on your settings, so please share them too (`Copy to clipboard` button in preferences window).
