### ISSUE TITLE
[core]Jadx- gui Decompiled ghosting on win10

### ISSUE THREAD

**Issue by crispony** [skylot/jadx#1444]
![image](https://user-images.githubusercontent.com/58875727/162608793-4061475d-0222-4b53-b51f-894dd8e58bac.png)
like this.

**Comment by skylot** [comment]
@crispony please try to use the latest java version.
Easiest option is to use release bundle with included JRE: [jadx-gui-1.3.4-with-jre-win.zip](https://github.com/skylot/jadx/releases/download/v1.3.4/jadx-gui-1.3.4-with-jre-win.zip)
