### ISSUE TITLE
Decompiled code should be improved

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#1445]
jadx code1:
   public a() {
            r1 = this;
            r0 = 0
            r1.<init>(r0, r0)
            return
    }
It needs to be changed so that it can be compiled
    public a() {
            this(null,null);
    }

 jadx code2:
        public C0002a(int r1, int r2) {
                r0 = this;
                r0.<init>()
                r0.a = r1
                r0.b = r2
                return
        }
It needs to be changed so that it can be compiled
    public static class C0002a {
        public  int a;
        public  int b;

        public C0002a(int r1, int r2) {
                super();
                this.a = r1;
                this.b = r2;
        }
    }

jadx code3:
    /* renamed from: a */
    public int m2768a(DzPrinterInfo r3, DzPrinterInfo r4) {
            r2 = this;
            String r0 = r3.mConnectTime
            String r1 = r4.mConnectTime
            int r0 = com.dothantech.common.DzString.m3024d(r0, r1)
            int r0 = -r0
            if (r0 != 0) goto L_0x0013
            String r0 = r3.mDeviceAddress
            String r1 = r4.mDeviceAddress
            int r0 = com.dothantech.common.DzString.m3024d(r0, r1)
        L_0x0013:
            return r0
    }
String and integer types are named r0,This will cause ambiguity and difficult to understand.Thank you.

**Comment by zgfflc** [comment]
This is a decompiled file.

**Comment by skylot** [comment]
@zgfflc looks like you enable `Fallback mode` disable it in preferences to get proper java code. Or you can just reset all preferences if you can't find fallback option.
