### ISSUE TITLE
Can I export the anti aliased smali file

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#1446]
Sometimes I want to package SmalI into jars for project calls. If the jar package packaged after confusion is called by anti confusion code, there will be a problem, so I need to output the anti confusion smali code.

**Comment by jpstotz** [comment]
Sorry but your question confuses me ;) I assume you are talking about opening an obfuscated APK file in Jadx and viewing the Smali code, that is what I understand. But I don't understand what you mean by "anti confusion smali code" or "anti aliased smali file". 

May be you should describe what you have (input files) and what you are trying to do.

In general once a code file has been obfuscated it is not possible to recover the original code before obfuscation. There might be indicators for some parts that were removed by the obfuscator but these are just very small parts (and it depends on the used obfuscator some obfuscators remove really everything and just leave unreadable code).

**Comment by jpstotz** [comment]
You can disable deobfuscation in the `Tools` menu in Jadx.

**Comment by zgfflc** [comment]
I know that. Our goal is to better recompile the decompiled code to a new project. Then I still want to export the anti confusion Smali code.And I've written a quick to package the SmalI code into jar packages. Now confused java code can  called normally, but the anti - confused code can't be called.

**Comment by jpstotz** [comment]
Sorry but I still don't understand what you are trying to do. Especially the part about "anti aliased/deobfuscated Smali code" I don't understand, because if I remember correctly the Smali code displayed by Jadx is never deobfuscated. It is always shown in it's original state without renaming anything. 

Therefore I assume you are referring to the Java code which is affected by deobfuscation.

Smali code looks like this, by default the decompiled Java code on the `Code` tab is shown.
```
# direct methods
.method static constructor <clinit>()V
    .registers 1

    .line 1
    const-class v0, Ld/a/f/a;

    invoke-static {v0}, Le/a/c;->a(Ljava/lang/Class;)Le/a/b;

    move-result-object v0

    sput-object v0, Ld/a/f/a;->a:Le/a/b;

    return-void
.end method
```

**Comment by zgfflc** [comment]
If I package part of the code into jars and the anti aliasing mode is set for the decompilation option of jadx, the compilation project will encounter problems now.
Normal confusion mode:
public class b{
 static  int a(int a,int b)
   {
      return a+b;
   }
}
This is the case when calling:    b.a(1,1);

Now I package class B into jar, and the method I call is set with anti aliasing.

The normal call should be like this:   SumClass.sum(1,1);  However, such a call will lead to the failure to find the method in the jar package.So I hope the calls designed to the jar package will remain the same:  b.a(1,1);

**Comment by skylot** [comment]
@zgfflc sorry, but I still don't understand what are you trying to archive.
