### ISSUE TITLE
[feature] Bookmarks and search history

### ISSUE THREAD

**Issue by threerog** [skylot/jadx#1448]
*Describe your idea:*
Bookmark function: when there are many files, it can quickly mark and locate to the specified place for secondary opening and analysis.
Search history: it is convenient to quickly locate the searched location during the initial analysis of the project.

The above functions hope to support a separate pop-up window display and improve efficiency.
Jadx is great, thanks to the author

**Comment by threerog** [comment]
The "search history" in the unstable version has been realized. Is there any plan for the "bookmark function"

**Comment by skylot** [comment]
>  Is there any plan for the "bookmark function"

Well, yes, but I think the "comment feature" works very similar for now, i.e. you can leave comment in code and next in search switch to the `comment` option, also you can leave search text empty, this will show all comments at once. Thus, I will give bookmark low priority, so don't expect it soon.

**Comment by threerog** [comment]
Can the search window display all comment information? I just tested it. I need to confirm again that if all the comments can be displayed, the "bookmark function" can indeed reduce the priority

**Comment by threerog** [comment]
In addition, in the unstable version, even if I turn off the automatic search, the automatic search will still be performed when I open the search window by selecting part of the text with my mouse. I am not sure whether it is appropriate to force the automatic search in this place, but just give feedback

**Comment by skylot** [comment]
> Can the search window display all comment information?

Yes, just leave search field empty

> automatic search will still be performed when I open the search window by selecting part of the text 

Sure, I will disable search for that case, thanks!

**Comment by threerog** [comment]
When multiple search windows are opened, the new window will still automatically search the code text selected by the previous mouse (note that I have deselected the text at this time). No matter how many search windows are opened, I think this is an unreasonable bug. The default search content of the newly opened window should be empty.

**Comment by threerog** [comment]
In addition, how to clear or delete a useless record in the search history

**Comment by threerog** [comment]
@skylot 
Hello, I'm not sure whether you have received the above unstable version bug feedback. Please confirm again
