### ISSUE TITLE
Peer not authenticated

### ISSUE THREAD

**Issue by RyoHao** [skylot/jadx#145]
I am building jadx with Ubuntu 16.04 like this:  ./gradlew dist

But the terminal shown “peer not authenticated" error.

Here is the follow error message:
--------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* Where:
Build file '/home/ryohao/Android/Tools/jadx/build.gradle' line: 9

* What went wrong:
Error resolving plugin [id: 'com.github.kt3k.coveralls', version: '2.3.1']
> Could not GET 'https://plugins.gradle.org/api/gradle/2.7/plugin/use/com.github.kt3k.coveralls/2.3.1'.
   > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
--------------------------------------------------------------------------------------

**Comment by fookeet** [comment]
I'm having this same issue

**Comment by skylot** [comment]
Please confirm that latest commit fix issue

**Comment by fookeet** [comment]
@skylot yeah, issue is fixed now. Thanks!
