### ISSUE TITLE
不能对smali修改吗

### ISSUE THREAD

**Issue by aacai** [skylot/jadx#1465]
只能看不能写吗

Google Translate:
> Can you only read and not write? (Smali)

**Comment by skylot** [comment]
@aacai
I don't think smali editing will be implemented in near future. Please use [Apktool](https://github.com/iBotPeaches/Apktool) to modify and rebuild.

**Comment by aacai** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
