### ISSUE TITLE
[feature] Add "SkipDependencies" argument to not save dependencies to disk

### ISSUE THREAD

**Issue by NASGregorio** [skylot/jadx#1466]
I'm doing research on static analysis of decompiled code, and I'd like to only save the source files that exactly match the class filter.
Right now, when saving, using a filter for "com.foo" for example, the output folder will include the matching files plus dependencies ("com.google", etc)

Something like "setSkipDependencies" and "isSkipDependencies" would do the trick.
I already implemented this change, so if this is useful to others, I can make a PR.

The tool itself has been quite helpful so far. Thanks :)

**Comment by skylot** [comment]
> I can make a PR

@NASGregorio this will be very helpful :+1:
Actually, this sounds like a bug, class filter intended to output only passed classes without dependencies.
Not sure if someone really needs dependencies after filtering, but having such option is nice anyway :slightly_smiling_face:

**Comment by NASGregorio** [comment]
If it is a bug, perhaps make excluding dependencies the default behaviour, and add the option "setIncludeDependencies".
I'll open a PR soon with the changes.
