### ISSUE TITLE
Decompilation crashes

### ISSUE THREAD

**Issue by PeterJoins** [skylot/jadx#1470]
Jadx version: 1.3.5
java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
Platform: Windows 10 (10.0 amd64)
set DEFAULT_JVM_OPTS="-Xms256M" "-Xmx6g" "-XX:MaxRAMPercentage=70.0" "-XX:+UseG1GC" "-Dawt.useSystemAAFontSettings=lcd" "-Dswing.aatext=true"

How can i do?

**Comment by jpstotz** [comment]
What do mean by crash? Please describe what you do (start jadx, load APK xyz, start decompilation, ..) and what happens.

**Comment by PeterJoins** [comment]
> What do mean by crash? Please describe what you do (start jadx, load APK xyz, start decompilation, ..) and what happens.

During the decompilation process after loading the apk, the program crashes and exits

**Comment by jpstotz** [comment]
That a Java program crashes is pretty rare. Please check if Jadx has enough RAM for completely decompiling the APK you are trying to load. You can enable memory usage bar in Jadx to check memory usage. If RAM is too small increase it as described here: https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#out-of-memory-problems-

From your command-line I can see that Jadx is started with two memory related parameters: `"-Xmx6g" "-XX:MaxRAMPercentage=70.0"` I am not sure what Java does in case both parameters are present, therefore my recommendation is to remove one of them.

**Comment by skylot** [comment]
@PeterJoins do you have enough system memory to allocate 6 GB (from your jvm options)? Java may fail to allocate this amount of memory and crash. So you can reduce this number to keep app running or just reduce system memory usage by closing other apps.

@jpstotz after a quick check if both options a set, java will use value from `-Xmx`

**Comment by PeterJoins** [comment]
> @jpstotz after a quick check if both options a set, java will use value from `-Xmx`
The memory is sufficient, but the problem still exists, which does not exist in 1.3.0
