### ISSUE TITLE
0.6 can not search code 0.6.1 open too slow to account for the memory computer no response

### ISSUE THREAD

**Issue by qssq** [skylot/jadx#148]
My computer 16g memory i767006 generation CPU ask how should I configure it？

**Comment by legendaryzp** [comment]
IT is not problem，you can find me 。qq775475051.

or change the jadx-gui.bat 
set DEFAULT_JVM_OPTS=-Xmx3000m

**Comment by qssq** [comment]
@legendaryzp  我尝试过...还是 很卡 很慢。 。受不了。 特别是公司的电脑 。

**Comment by ananas-xxj** [comment]
@qssq  解决了吗  我这indexing 很久 如果x掉就不能搜索

**Comment by sergey-wowwow** [comment]
Should be fixed in the previous commits
