### ISSUE TITLE
method.getBasicBlocks() is null when using jadx as a library

### ISSUE THREAD

**Issue by icepng** [skylot/jadx#1482]
I try to use jadx as a library following the document: https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library.

`for (JavaClass cls : jadx.getClasses()) {
    for (JavaMethod mth : cls.getMethods()) {
        System.out.println(mth.getName());
    }
}`

However, all methods' basicBlocks are null,  is there any extra options for generating blocks?

**Comment by skylot** [comment]
@icepng basic blocks available only during decompilation process inside jadx passes. Right now there is no nice API to insert custom passes, but if you really want to, you can get passes list after `jadx.load()` like this:
```java
List<IDexTreeVisitor> passes = jadx.getRoot().getPasses();
```
You need to implement [IDexTreeVisitor](https://github.com/skylot/jadx/blob/d586c84b5632be0bca22250a7081506136e8a85e/jadx-core/src/main/java/jadx/core/dex/visitors/IDexTreeVisitor.java#L11) and add it to passes list, or better insert at desired position. This list building in [Jadx](https://github.com/skylot/jadx/blob/cf25cc4faad86489b1f5861ae139c4eeda226e3b/jadx-core/src/main/java/jadx/core/Jadx.java#L101) class depending on input options, so to insert it after desired pass you need to use method like this:
```java
public static void addCustomPassAfter(List<IDexTreeVisitor> passes, Class<?> passCls, IDexTreeVisitor customPass) {
    for (int i = 0; i < passes.size(); i++) {
        IDexTreeVisitor pass = passes.get(i);
        if (pass.getClass().equals(passCls)) {
            passes.add(i + 1, customPass);
            break;
        }
    }
}
```
Complete example will be like this:
```java
jadx.load();
List<IDexTreeVisitor> passes = jadx.getRoot().getPasses();
AbstractVisitor customPass = new AbstractVisitor() {
    @Override
    public void visit(MethodNode mth) {
        if (mth.isNoCode()) {
            return;
        }
        List<BlockNode> basicBlocks = mth.getBasicBlocks();
        System.out.println(basicBlocks);
    }
};
addCustomPassAfter(passes, TypeInferenceVisitor.class, customPass);
for (JavaClass cls : jadx.getClasses()) {
    // your pass will be executed during decompilation
    cls.decompile();
}
```

**Comment by icepng** [comment]
thank you and this is resolved.
