### ISSUE TITLE
[feature] Update variable names after renaming class

### ISSUE THREAD

**Issue by j4k0xb** [skylot/jadx#1487]
*Describe your idea:*
When renaming classes, it would be useful if all variables/parameters/etc of that type get their names based on the new instead of original name.

Example (`j5` got renamed to `Preferences`):
```java
Preferences j5Var = this.prefs;
```
should be shown as `preferences` or `preferencesVar` instead of `j5Var`

Similar thing when hovering, it should show `Map<ServerRegion, String>` instead:
![image](https://user-images.githubusercontent.com/55899582/169410136-a1c96073-5f9e-4f95-8116-67460406fef2.png)

**Comment by j4k0xb** [comment]
Thanks for implementing, already makes it so much easier to look through the code 👍🏻 

However I noticed that the tooltip for local variables still shows the original name and `null`:
![image](https://user-images.githubusercontent.com/55899582/169664035-deb6f2f7-9b20-4b1d-9af7-e4bbcf17237b.png)

**Comment by skylot** [comment]
> However I noticed that the tooltip for local variables still shows the original name and null

@j4k0xb sure. This part is a little harder to fix, so I will fix it later.

**Comment by skylot** [comment]
@j4k0xb fixed. Please check :smile:

**Comment by j4k0xb** [comment]
thx, works as intended now
