### ISSUE TITLE
  Class decompile not found after the correct path

### ISSUE THREAD

**Issue by qssq** [skylot/jadx#149]
jd-gui  decompile  result

FileRecv\weixin_6.3.18_800_dex2jar.jar!\com\tencent\mm\plugin\luckymoney\c\ab.class

jdax result

/* renamed from: com.tencent.mm.plugin.luckymoney.sns.a.a */
public final class C6600a implements C3135i {

    /* renamed from: com.tencent.mm.plugin.luckymoney.sns.a.a.1 */

renamed??? how to fix?

**Comment by qssq** [comment]
I hook something in xposed so I hope not to change the class name

**Comment by sergey-wowwow** [comment]
It happens when ``` --deobf ``` (deobfuscation in settings) option is enabled, errors in deobfuscator should be reported in individual issues
