### ISSUE TITLE
Version 1.4.0 do not want to save anything

### ISSUE THREAD

**Issue by skavengeer** [skylot/jadx#1496]
*Describe your idea:*
Version 1.3.3 and ver 1.3.5 save all, but ver 1.4.0 do not save files on disk

**Comment by skylot** [comment]
@skavengeer I can't reproduce this issue. Did anyone else have this issue?

**Comment by ZachQin** [comment]
> @skavengeer I can't reproduce this issue. Do any errors appear in logs? Did anyone else have this issue?

I can reproduce this issue. There are no messages in logs.

**Comment by llwwbb** [comment]
same, I'm using windows 11, jadx-gui-1.4.0-with-jre-win.zip, nothing in logs
