### ISSUE TITLE
Code decompiled incorrectly, please refer to instructions dump

### ISSUE THREAD

**Issue by sam4444** [skylot/jadx#150]
Please check above code it's there are still show missing code.

**Here i have used jadx-gui-6.0.1**

I am try to understand this missing code but i can't get it can you please solve this problem in project even help me for get this code.

Here i also attach other file there are also given log entries.

`/* JADX WARNING: inconsistent code. */`
`    /* Code decompiled incorrectly, please refer to instructions dump. */`
`    public void processFinish2(java.lang.String r11) {`
`        /*`
`        r10 = this;`
`        r9 = 1;`
`        r8 = 0;`
`        r8 = r11.equals(r8);	 Catch:{ Exception -> 0x004a }`
`        if (r8 == 0) goto L_0x0010;`
`    L_0x0008:`
`        r8 = "";`
`        r8 = r11.equals(r8);	 Catch:{ Exception -> 0x004a }`
`        if (r8 != 0) goto L_0x0094;`
`    L_0x0010:`
`        r4 = 0;`
`        r4 = org.xmlpull.v1.XmlPullParserFactory.newInstance();	 Catch:{ XmlPullParserException -> 0x0045 }`
`    L_0x0015:`
`        r8 = 1;`
`        r4.setNamespaceAware(r8);	 Catch:{ Exception -> 0x004a }`
`        r7 = 0;`
`        r7 = r4.newPullParser();	 Catch:{ XmlPullParserException -> 0x0060 }`
`    L_0x001e:`
`        r8 = new java.io.StringReader;	 Catch:{ XmlPullParserException -> 0x0065 }`
`        r8.<init>(r11);	 Catch:{ XmlPullParserException -> 0x0065 }`
`        r7.setInput(r8);	 Catch:{ XmlPullParserException -> 0x0065 }`
`    L_0x0026:`
`        r3 = 0;`
`        r3 = r7.getEventType();	 Catch:{ XmlPullParserException -> 0x006a }`
`    L_0x002b:`
`        r8 = 4;`
`        r6 = new java.lang.String[r8];	 Catch:{ Exception -> 0x004a }`
`        r5 = 0;`
`    L_0x002f:`
`        if (r3 != r9) goto L_0x006f;`
`    L_0x0031:`
`        r8 = r10.p3;	 Catch:{ Exception -> 0x004a }`
`        r8 = r8.isShowing();	 Catch:{ Exception -> 0x004a }`
`        if (r8 == 0) goto L_0x003e;`
`    L_0x0039:`
`        r8 = r10.p3;	 Catch:{ Exception -> 0x004a }`
`        r8.dismiss();	 Catch:{ Exception -> 0x004a }`
`    L_0x003e:`
`        r8 = 2;`
`        r8 = r6[r8];	 Catch:{ Exception -> 0x004a }`
`        r10.showinfo(r8);	 Catch:{ Exception -> 0x004a }`
`    L_0x0044:`
`        return;`
`    L_0x0045:`
`        r0 = move-exception;`
`        r0.printStackTrace();	 Catch:{ Exception -> 0x004a }`
`        goto L_0x0015;`
`    L_0x004a:`
`        r0 = move-exception;`
`        r8 = r10.p3;`
`        r8 = r8.isShowing();`
`        if (r8 == 0) goto L_0x0058;`
`    L_0x0053:`
`        r8 = r10.p3;`
`        r8.dismiss();`
`    L_0x0058:`
`        r8 = r10.tv1;`
`        r9 = "Connnectivity error";`
`        r8.setText(r9);`
`        goto L_0x0044;`
`    L_0x0060:`
`        r1 = move-exception;`
`        r1.printStackTrace();	 Catch:{ Exception -> 0x004a }`
`        goto L_0x001e;`
`    L_0x0065:`
`        r0 = move-exception;`
`        r0.printStackTrace();	 Catch:{ Exception -> 0x004a }`
`        goto L_0x0026;`
`    L_0x006a:`
`        r0 = move-exception;`
`        r0.printStackTrace();	 Catch:{ Exception -> 0x004a }`
`        goto L_0x002b;`
`    L_0x006f:`
`        r2 = r7.getName();	 Catch:{ Exception -> 0x004a }`
`        switch(r3) {`
`            case 2: goto L_0x007b;`
`            case 3: goto L_0x0076;`
`            case 4: goto L_0x008;`
`            default: goto L_0x0076;`
`        };`
`    L_0x0076:`
`        r3 = r7.next();	 Catch:{ XmlPullParserException -> 0x008a, IOException -> 0x008f }`
`        goto L_0x002f;`
`    L_0x007b:`
`        r8 = "nameadd";`
`        r2.equals(r8);	 Catch:{ Exception -> 0x004a }`
`        goto L_0x0076;`
`    L_0x0081:`
`        r8 = r7.getText();	 Catch:{ Exception -> 0x004a }`
`        r6[r5] = r8;	 Catch:{ Exception -> 0x004a }`
`        r5 = r5 + 1;`
`        goto L_0x0076;`
`    L_0x008a:`
`        r0 = move-exception;`
`        r0.printStackTrace();	 Catch:{ Exception -> 0x004a }`
`        goto L_0x002f;`
`    L_0x008f:`
`        r0 = move-exception;`
`        r0.printStackTrace();	 Catch:{ Exception -> 0x004a }`
`        goto L_0x002f;`
`    L_0x0094:`
`        r8 = r10.p3;	 Catch:{ Exception -> 0x004a }`
`        r8 = r8.isShowing();	 Catch:{ Exception -> 0x004a }`
`        if (r8 == 0) goto L_0x00a1;`
`    L_0x009c:`
`        r8 = r10.p3;	 Catch:{ Exception -> 0x004a }`
`        r8.dismiss();	 Catch:{ Exception -> 0x004a }`
`    L_0x00a1:`
`        r8 = r10.tv1;	 Catch:{ Exception -> 0x004a }`
`        r9 = "Data error";`
`        r8.setText(r9);	 Catch:{ Exception -> 0x004a }`
`        goto L_0x0044;`
`        */`

Can you please do something for this problem. Thank you in advance.

**Comment by abozanona** [comment]
Did you find a solution for this problem, sir?

**Comment by rongdongliu** [comment]
I also encountered such a problem, part of the code can not compile，help

**Comment by fuxingkai** [comment]
使用这个命令来反编译你的apk
jadx-gui --show-bad-code acc.apk
方案来源：
https://stackoverflow.com/questions/41424442/jadx-output-decompile-error-code-decompiled-incorrectly-please-refer-to-instr

**Comment by a3349384** [comment]
@fuxingkai 即使不报错了，反编译的代码会不会本身也是有问题的

**Comment by acegishniz** [comment]
@fuxingkai  you saved my life!

**Comment by asashour** [comment]
Is anything we can do here? Please provide the APK, or test case, to reproduce the issue.
