### ISSUE TITLE
[core]AndroidManifest.xml decode Error

### ISSUE THREAD

**Issue by CKCat** [skylot/jadx#1502]
Some APK AndroidManifest.xml decode Error。Because AndroidManifest.xml the version is 0 。

![image](https://user-images.githubusercontent.com/18586344/170946809-834212f0-c0f7-423c-b574-1a461765393f.png)

[5dfa1dd3d217b330e1812ae926665f31.zip](https://github.com/skylot/jadx/files/8796666/5dfa1dd3d217b330e1812ae926665f31.zip)

![image](https://user-images.githubusercontent.com/18586344/170947224-0ff7088f-9078-4540-a3ec-b9227e9eb22c.png)

Before
![image](https://user-images.githubusercontent.com/18586344/170947589-5b552d5e-7ee5-47d0-8832-6af1c1ee05cd.png)

After
![image](https://user-images.githubusercontent.com/18586344/170947434-5abc3fdc-d011-453b-bd46-30bbe41254c7.png)

**Comment by skylot** [comment]
@CKCat thanks! Sure, this will resolve the issue, and this version check is indeed not really needed.
You can submit a PR if you want :smiley:

**Comment by skylot** [comment]
Fixed in PR #1504 by @CKCat :tada:
