### ISSUE TITLE
Duplicate resources line when decompiling APK

### ISSUE THREAD

**Issue by Hiacine** [skylot/jadx#151]
Hi,

When I try to decompile this app
https://play.google.com/store/apps/details?id=fr.leboncoin&hl=fr

I have got duplicate entries in res/*.xml files

I can't compile

**Comment by tzachi-dar** [comment]
Happens to me as well, with another apk.

**Comment by elekt** [comment]
+1 A lot of duplicate resources

**Comment by sergey-wowwow** [comment]
Fixed
