### ISSUE TITLE
[gui] Map file handle mode setting having no effect after settings upgrade from version 15 to 16

### ISSUE THREAD

**Issue by CmP-lt** [skylot/jadx#1513]
If [`deobfuscationForceSave`](https://github.com/skylot/jadx/blob/b4fa6644bcd14af625430889c019876b78c414f4/jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java#L127) is `true` when setting are upgraded from version `15` to `16` https://github.com/skylot/jadx/blob/b4fa6644bcd14af625430889c019876b78c414f4/jadx-gui/src/main/java/jadx/gui/settings/JadxSettings.java#L697-L704 the value will be saved in settings and there will be no way to set it to `false` from the application itself.

This causes the problem of [`deobfuscationMapFileMode`](https://github.com/skylot/jadx/blob/b4fa6644bcd14af625430889c019876b78c414f4/jadx-core/src/main/java/jadx/api/JadxArgs.java#L74) being set to `DeobfuscationMapFileMode.OVERWRITE` regardless of which option is chosen in preference window: https://github.com/skylot/jadx/blob/b4fa6644bcd14af625430889c019876b78c414f4/jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java#L262-L266

That puts user in situation of having no control over map file handle mode, since it is forcefully overridden to `OVERWRITE` after saved settings are loaded on application startup.

The problem can be addressed using any of the following approaches (although there may be better ones):
  - set `deobfuscationForceSave` to `false` in the code for handling settings upgrade from version `15` to `16`;
  - exclude `deobfuscationForceSave` from being saved (since it has been removed from preferences window).

**Comment by skylot** [comment]
@CmP-lt thanks! This field, supposed to be excluded from saving in jadx-gui. But I think now it can be safely removed as it deprecated for several versions already.
