### ISSUE TITLE
[GUI]Right-click to select cross-reference doesn't work, but shortcut x works properly

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1514]
jadx latest version: git: [b4fa664](https://github.com/skylot/jadx/commit/b4fa6644bcd14af625430889c019876b78c414f4)

Right-click to select cross-reference doesn't work, but shortcut x works properly

![image](https://user-images.githubusercontent.com/42903751/172090384-98a60b99-1f38-4b51-9650-352483ff98a2.png)

I think it may be that any apk has this bug, so there is no need to provide apk, class name, method name. If others test without the bug, please reply me and I will attach the relevant information.

**Comment by skylot** [comment]
Fixed. Check details in #1529.

**Comment by xmhwws** [comment]
Ok, thank you for your excellent work!
