### ISSUE TITLE
Mac Unrecognized VM option 'MaxRAMPercentage=70.0'

### ISSUE THREAD

**Issue by yefangqingchen** [skylot/jadx#1520]
Unrecognized VM option 'MaxRAMPercentage=70.0'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by odyright** [comment]
Same issue: Unrecognized VM option 'MaxRAMPercentage=70.0'
`java --version`
```
java 18.0.2 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)
```

**Comment by jpstotz** [comment]
@odyright If I remember correctly Jadx first checks environment variable `JAVA_HOME` if it points to an JRE and uses it. Please check if the env variable `JAVA_HOME` is set on your system and points to an older Java version, for example check output of `$JAVA_HOME/bin/java --version`.

**Comment by ff-frida** [comment]
> If I remember correctly Jadx first checks environment variable `JAVA_HOME` if it points to an JRE and uses it. Please check if the env variable `JAVA_HOME` is set on your system and points to an older Java version, for example check output of `$JAVA_HOME/bin/java --version`.

What is the maximum Java version of running jadx? I don't know why I suddenly prompted this. Mac Java 8

**Comment by ff-frida** [comment]
> 

我也遇到了这个问题，最近怎么解决的呢

**Comment by mvpboss1004** [comment]
> > 
> 
> 我也遇到了这个问题，最近怎么解决的呢

jadx-gui这个命令写死了java路径，所以如果java版本不够高就会有问题。
解决办法就是编辑/usr/local/bin/jadx-gui，将JAVA_HOME指向高版本的java路径，比如/usr/local/opt/openjdk
```
~/Music  $ jadx-gui
Unrecognized VM option 'MaxRAMPercentage=70.0'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
~/Music  $ which jadx-gui                                                                                                                           
/usr/local/bin/jadx-gui
~/Music  $ cat /usr/local/bin/jadx-gui 
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-@@HOMEBREW_JAVA@@}" exec "/usr/local/Cellar/jadx/1.4.4/libexec/bin/jadx-gui"  "$@"
~/Music  $ echo ${JAVA_HOME:-@@HOMEBREW_JAVA@@}
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
~/Music  $ /usr/local/opt/openjdk/bin/java -version
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment Homebrew (build 19)
OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)
```

**Comment by mvpboss1004** [comment]
> > 
> 
> 我也遇到了这个问题，最近怎么解决的呢

在启动时将JAVA_HOME指定到高版本的java路径，比如/usr/local/opt/openjdk。
```
~/Music  $ jadx-gui
Unrecognized VM option 'MaxRAMPercentage=70.0'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
~/Music  $ which jadx-gui                                                                                                                           
/usr/local/bin/jadx-gui
~/Music  $ cat /usr/local/bin/jadx-gui 
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-@@HOMEBREW_JAVA@@}" exec "/usr/local/Cellar/jadx/1.4.4/libexec/bin/jadx-gui"  "$@"
~/Music  $ echo ${JAVA_HOME:-@@HOMEBREW_JAVA@@}
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
~/Music  $ /usr/local/opt/openjdk/bin/java -version
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment Homebrew (build 19)
OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)
~/Music  $ JAVA_HOME=/usr/local/opt/openjdk jadx-gui
```

**Comment by happylee1** [comment]
> > > 
> > 
> > 
> > 我也遇到了这个问题，最近怎么解决的呢
> 
> 在启动时将JAVA_HOME指定到高版本的java路径，比如/usr/local/opt/openjdk。
> 
> ```
> ~/Music  $ jadx-gui
> Unrecognized VM option 'MaxRAMPercentage=70.0'
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> ~/Music  $ which jadx-gui                                                                                                                           
> /usr/local/bin/jadx-gui
> ~/Music  $ cat /usr/local/bin/jadx-gui 
> #!/bin/bash
> JAVA_HOME="${JAVA_HOME:-@@HOMEBREW_JAVA@@}" exec "/usr/local/Cellar/jadx/1.4.4/libexec/bin/jadx-gui"  "$@"
> ~/Music  $ echo ${JAVA_HOME:-@@HOMEBREW_JAVA@@}
> /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
> ~/Music  $ /usr/local/opt/openjdk/bin/java -version
> openjdk version "19" 2022-09-20
> OpenJDK Runtime Environment Homebrew (build 19)
> OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)
> ~/Music  $ JAVA_HOME=/usr/local/opt/openjdk jadx-gui
> ```

For me, the last command `JAVA_HOME=/usr/local/opt/openjdk jadx-gui` outputed "zsh: command not found: jadx-gui". I changed the command  to `JAVA_HOME=/usr/local/opt/openjdk ./jadx-gui`at the "bin" folder of jadx root path, and it worked for me.
