### ISSUE TITLE
[feature]Class!!!Anti obfuscation of classes

### ISSUE THREAD

**Issue by typeofi** [skylot/jadx#1528]
*Describe your idea:*
The usual confusion method is .source "AI.java", if its original name -AI is still there, I want to restore these class names with one click button, mean is all. one button do all.

**Comment by jpstotz** [comment]
Sorry but I don't understand your feature idea.

**Comment by typeofi** [comment]
Thank you. I know how to use it. Thank you. I will delete this nonsense question

**Comment by typeofi** [comment]
> Sorry but I don't understand your feature idea. Jadx already has the deobfuscation feature where it uses all available source to recover the original name or else generate a more or less meaningful name.

Thank you. I know how to use it. Thank you. I will delete this nonsense question

**Comment by skylot** [comment]
A similar thing was asked some time ago in #814, and I was going to fix it by excluding renaming to source name from deobfuscation pass. So I will close this issue as duplicate and increase priority for #814.
