### ISSUE TITLE
[gui] `JNodeAction`s not working when called from context menu

### ISSUE THREAD

**Issue by CmP-lt** [skylot/jadx#1529]
Since 0c3afcc24cdc911667f373f3753223796cd46539 all actions that extend `JNodeAction` don't work (as if their `runAction` method doesn't get called, which may be the case) when they are called from context menu, but work normally when called with bound key. This issue doesn't affect actions that extend `AbstractAction` directly (like `CommentAction` and `CommentSearchAction`), they work normally both from context menu and with bound key.

**Comment by skylot** [comment]
@CmP-lt thank you for the tip!
It is weird that method `popupMenuWillBecomeInvisible` called before `actionPerformed`. Yeah, docs mention `Note that a JPopupMenu can become invisible any time` but I didn't think this can be before the reason of menu closing :confused:
I commit a fix which don't reset current node in `popupMenuWillBecomeInvisible` method.
Also looks like this fix resolves a #1529.
