### ISSUE TITLE
there is one error in Bat file。

### ISSUE THREAD

**Issue by legendaryzp** [skylot/jadx#154]
start "jadx-gui" /B "%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %JADX_GUI_OPTS%  -classpath "%CLASSPATH%" jadx.gui.JadxGUI %CMD_LINE_ARGS%

when change DEFAULT_JVM_OPTS ，jvm do not run。

**Comment by sergey-wowwow** [comment]
@legendaryzp 
There should be an issue how you change ``` %DEFAULT_JVM_OPTS% ```, but not jadx itself. If you believe it's a jadx issue, please reopen that report and attach your version of ``` %DEFAULT_JVM_OPTS% ```
