### ISSUE TITLE
[feature]Add a switch not to jump to declare when double click something.

### ISSUE THREAD

**Issue by MG1937** [skylot/jadx#1540]
Add a switch not to jump to declare when double click something.
Every time when I double click some object(such as a var or class name),it just auto jump to the declare.
It's really annoy when I trying to copy something:(
Every time I trying to copy some var name,suddenly the content of the screen just changed,break my mind again and again.....

**Comment by skylot** [comment]
@MG1937 done.
I add option `Enable jump on double click` in `Other` preferences group. Check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).
Anyway, to copy name under cursor you don't need to select text, you can just press `Ctrl+C` (added in #1292).
