### ISSUE TITLE
[gui] Renaming a method to something that would match a keyword breaks the intellisense functionality for that method

### ISSUE THREAD

**Issue by Dragas** [skylot/jadx#1557]
The title is kind of verbose, but it summarizes the issue as best as possible. I run preference settings where I would attempt to deobfuscate anything that's less then 3 characters long (the default), so that I would afterwards rename the methods, variables, and etc. to proper names after figuring out what they're doing. In poor judgement, I had renamed a single method to `assert`, which corresponds to a keyword in java.
![image](https://user-images.githubusercontent.com/6078508/175612175-86fd449c-791b-4526-ac38-4a4a4208a622.png)
As a result, jad-gui now considers the method to be a keyword, and I am no longer able to perform any intellisense operations (such as find usages, rename, go to declaration) on that method, and any callers of that method.
![image](https://user-images.githubusercontent.com/6078508/175612883-4385dbe1-d38c-4b2b-8fbd-cd4b4365b0c4.png)
In addition, the tool prevents reverting this action.

**Comment by Dragas** [comment]
Looking at the logs, they do not seem to provide anything besides the bad byte error.
https://pastebin.com/M8W6DbGN

**Comment by skylot** [comment]
@Dragas I add a check before rename to forbid not valid java identifiers.
