### ISSUE TITLE
# There is insufficient memory for the Java Runtime Environment to continue.

### ISSUE THREAD

**Issue by PeterJoins** [skylot/jadx#1566]
**win10  java 11.0.8  jadx-1.3.5 
There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 1545601024 bytes for Failed to commit area from 0x0000000653000000 to 0x00000006af200000 of length 1545601024.
 Possible reasons:
The system is out of physical RAM or swap space
The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap

I have made the following configuration, but it still crashes and reports the above error, how can I solve this problem?

set DEFAULT_JVM_OPTS="-Xms128M"  "-Xmx8g" "-XX:MaxRAMPercentage=70.0" "-XX:+UseG1GC" "-Dawt.useSystemAAFontSettings=lcd" "-Dswing.aatext=true"

**Comment by jpstotz** [comment]
@PeterJoins Please add more details about the used computer and Jadx (Jadx version, OS, available RAM, used Java version).

**Comment by PeterJoins** [comment]
> @PeterJoins Please add more details about the used computer and Jadx (Jadx version, OS, available RAM, used Java version).

**win10 java 11.0.8 jadx-1.3.5

**Comment by jpstotz** [comment]
Please use latest Jadx version 1.4.2. It has the capability to offload the decompiled sources to disk which reduces the maximum RAM usage. 

But if your computer only has a small amount of RAM (e.g. 4GB) Jadx may still fail because of low memory.

**Comment by PeterJoins** [comment]
thank you, i will try it
