### ISSUE TITLE
[search] jadx sometimes freezes during search ( code , case insensitive )

### ISSUE THREAD

**Issue by mcirsta** [skylot/jadx#1568]
On my machine which has 16 core ( 32 with HT ) sometimes search gets stuck and then all of jadx freezes.  This is with 1.4.2 and newer nightly builds.
 I've tried different versions of Java and even both Linux and Windows but the result is the same.
 The APK that I opened is Waze and decompilation finished before starting the search.

 I suspect this is a deadlock somewhere but it doesn't happen all the time.
 If you need additional info I can try to get the source code so that I can pause with the debugger and see where it gets stuck.

**Comment by daMatz** [comment]
Also happens for me frequently now.

**Comment by skylot** [comment]
I commit a fix for this lock, not sure if it was the only cause.
Anyway, now search task canceling will happen in background and shouldn't cause UI freeze.
Please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Comment by Alireza-Razavi** [comment]
@skylot I think the search experience was so better in version 1.2
Now JADX is always processing for every search and makes slower than before.

**Comment by mcirsta** [comment]
Problem is fixed for me. Thank you very much for the quick fix. It was quite hard to use the app before this fix.

**Comment by skylot** [comment]
> Problem is fixed for me

@mcirsta thanks for confirm :+1:

@Alireza-Razavi 
Jadx now uses limited search, so it stops if results count hit limit, this can cause partial decompilation so on next search decompilation will continue. Such behavior is useful for slow loading from disk if disk cache enabled.
If you want to decompile everything at once you can enable `Auto start background decompilation` option in preference, it will run full decompilation after loading, and once it finished next search shouldn't process any classes. If it still does, please submit an issue (note that I just commit a fix for such issue, so use the latest unstable build)

**Comment by psolyca** [comment]
With the latest unstable build, search do not freeze and could be cancelled correctly ^^
Thanks for the fix.

**Comment by Alireza-Razavi** [comment]
> If you want to decompile everything at once you can enable `Auto start background decompilation` option in preference, it will run full decompilation after loading, and once it finished next search shouldn't process any classes.

@skylot Thanks i didn't know this option :)

**Comment by daMatz** [comment]
Thank you, also works for me :)

**Comment by shezik** [comment]
Working for me as well. Thank you!
