### ISSUE TITLE
[core]ERROR - Zip bomb attack detected, invalid sizes: compressed 476, uncompressed 262152,

### ISSUE THREAD

**Issue by PeterJoins** [skylot/jadx#1570]
ERROR - Zip bomb attack detected, invalid sizes: compressed 476, uncompressed 262152, name assets/style/base/teeth/TeethModel.bin

How can i resolve this problem.

**Comment by jpstotz** [comment]
You don't have to do anything. The mentioned entry will just be ignored. This is just a protection measure to keep Jadx in an operational state. 

In this case it does not seem to be a real ZIP bomb attack as the target size of 260KB is pretty small, but an APK could contain multiple of such files which could consume a lot of memory.

**Comment by leumasme** [comment]
I think this should be revisited. A 2kb file decompressing to 250kb is quite normal, and from what I can see, jadx will simply refuse to decompress the file if it was compressed too well.  
Here is a "ZIP bomb" image that decompressed from 1.8kb to 262kb:
![image](https://github.com/skylot/jadx/assets/29953391/1384723a-fa12-424b-aa9d-cbdbb751c02c)
If you can't see a way to improve this check, at least add a CLI flag to disable it.

**Comment by jpstotz** [comment]
1.8kb to 262kb is a decompression factor of 145. The ZIP bomb detection factor Jadx uses is 100. Just increasing the Jadx factor to may be 150 would be sufficient for this case, but this would not be very sustainable.

In my opinion we should skip the ZIP bomb detection for elements that have a decompressed size of less than a few MB (may be 10 or 20MB?). Constructing an DoS ZIP bomb attack using decompressed elements of less than 20MB would require a high number of entries.

**Comment by skylot** [comment]
@jpstotz thanks for PR, this should resolve incorrect detection for small files :+1:

Although, because such issues sometimes appear, I think we need to add a way to disable zip security check completely.
The easiest way is to store switch in final static field and init it from an environment variable value with name like `JADX_DISABLE_ZIP_SECURITY=true`.
