### ISSUE TITLE
[core]Part of the code is missing from a static block of decompiled code

### ISSUE THREAD

**Issue by bhwxha** [skylot/jadx#1572]
link: https://drive.google.com/file/d/1_LvHtYY4MnBa3zBZ-WbXJ6gsQi7SeysM/view?usp=sharing

Enumerated class name: com.qq.e.comm.plugin.i.b

You can see that there is a member property **h** in the static block, which will be assigned a value.

![image](https://user-images.githubusercontent.com/107301547/177730713-a15f81c6-8786-489b-8436-b194166ee384.png)

You can also see it in smali
![image](https://user-images.githubusercontent.com/107301547/177731793-3c3049a8-1d5e-404e-a005-5dd20c850bb0.png)

But the jadx pseudocode is missing this piece

![image](https://user-images.githubusercontent.com/107301547/177731923-506647ac-51db-4bac-aa80-44d9b99d7ae8.png)

**Comment by skylot** [comment]
@bhwxha this is renamed `$VALUES` array generated by java compiler, and it can be safely removed. Also, it was not used in your case, so there is no any issue.
Anyway, I add more checks before removing this field or a custom 'values()' method.
