### ISSUE TITLE
[core] Deobfuscator keeps illegal names

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1582]
Hey!

Seems that this issue was introduced recently because previously that error was missing

Class `kotlin.collections.unsigned._UArrays`:
```java
    private static final kotlin.UInt m660elementAtOrNullqFRl0hI(int[] iArr, int i) {
        return kotlin.collections.unsigned.UArraysKt.getOrNull-qFRl0hI(iArr, i); // `getOrNull-qFRl0hI` is invalid
    }
```

APK: https://drive.google.com/file/d/1ryk4779zQfllLrgJm3Kfw0GjFn-sR4-u/view?usp=sharing

**Comment by skylot** [comment]
> We're sorry. You can't access this item because it is in violation of our Terms of Service.

@bagipro I can't download attached sample :(
Can you upload it using other service? Or maybe just share app name (with package) and version.

**Comment by bagipro** [comment]
I uploaded it here

[app-release.apk.zip](https://github.com/skylot/jadx/files/9176047/app-release.apk.zip)

**Comment by skylot** [comment]
@bagipro thanks! I commit a fix. That was a stupid regression :slightly_frowning_face:
