### ISSUE TITLE
[core]

### ISSUE THREAD

**Issue by Arashvscode** [skylot/jadx#1587]
![Screenshot_20220726-110355_MT Manager](https://user-images.githubusercontent.com/101287880/180939586-d160502e-b5b8-4299-93a6-8ade3aae481b.jpg)
JadxArgs jadxArgs = new JadxArgs();
jadxArgs.isSkipResources();
jadxArgs.isRespectBytecodeAccModifiers();
jadxArgs.isShowInconsistentCode();
jadxArgs.isFallbackMode();
jadxArgs.setInputFile(new java.io.File(input.getText().toString()));
jadxArgs.setOutDir(new java.io.File(output.getText().toString()));
try (JadxDecompiler jadxDecompiler = new JadxDecompiler(jadxArgs)) {
		
		jadxDecompiler.load();
		jadxDecompiler.save();
		
} catch (Exception e) {
		e.printStackTrace();
		
}
I use this code, but it does not decompile the .dex file, but I change the name to .jar, it decompiles not as a java file but as a class. Can you send me the real code?

**Comment by skylot** [comment]
@Arashvscode most likely you forget to include `jadx-dex-input` plugin, check [wiki page](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library).

**Comment by Arashvscode** [comment]
> @Arashvscode most likely you forget to include `jadx-dex-input` plugin, check [wiki page](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library).

Can you help me a little more with the Java code, I just started the Java course, it's hard for me😅😅😅😅

**Comment by skylot** [comment]
Well, you just need to create a maven or gradle project and add maven dependencies mentioned in wiki :slightly_smiling_face:
