### ISSUE TITLE
[gui] Sort resources by deobfuscated name

### ISSUE THREAD

**Issue by LongNghia** [skylot/jadx#1595]
Resource files are currently sorted by original names. They should be sorted by deobfuscated name.
Before | After
--- | ---
![image](https://user-images.githubusercontent.com/41385034/182039621-6de8d62f-3eb1-4809-a423-901c5917d1e4.png)|![image](https://user-images.githubusercontent.com/41385034/182039600-27fbebcf-fcdc-48f1-be3b-8556e5db89bd.png)

I changed in `jadx-gui/src/main/java/jadx/gui/treemodel/JRoot.java`:
``` java
private JResource getHierarchyResources(List<ResourceFile> resources) {
JResource root = new JResource(null, NLS.str("tree.resources_title"), JResType.ROOT);
String splitPathStr = Pattern.quote(File.separator);
for (ResourceFile rf : resources) {
	String rfName;
	if (rf.getZipRef() != null) {
		rfName = rf.getDeobfName();
	} else {
		rfName = new File(rf.getDeobfName()).getName();
	}
	String[] parts = new File(rfName).getPath().split(splitPathStr);
	JResource curRf = root;
	int count = parts.length;
	for (int i = 0; i < count; i++) {
		String name = parts[i];
		JResource subRF = getResourceByName(curRf, name);
		if (subRF == null) {
			if (i != count - 1) {
				subRF = new JResource(null, name, JResType.DIR);
			} else {
				subRF = new JResource(rf, rf.getDeobfName(), name, JResType.FILE); //here
			}
			curRf.getFiles().add(subRF);
		}
		curRf = subRF;
	}
}
root.update();
return root;
}
```

**Comment by skylot** [comment]
@LongNghia thanks! Looks like this is a correct fix. Do you want to make a PR to get some credit? :slightly_smiling_face:

**Comment by LongNghia** [comment]
> @LongNghia thanks! Looks like this is a correct fix. Do you want to make a PR to get some credit? slightly_smiling_face

I would love to! Thank you 😅️
