### ISSUE TITLE
Fields are not initialized after setContentView [core]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#1599]
Fields on the image are supposed to be initialized after setContentView because right now in this way objects are null since they're not initialized properly.

v1.4.3
![image](https://user-images.githubusercontent.com/35992798/182283361-e934d815-4ca9-44ed-be8b-8e428bca0a91.png)

P.S: Those are global variable and not inside onCreate method and that's the problem (trying to initialize in the field declaration itself)

**Comment by skylot** [comment]
@redmi111 can you share a sample for this issue? Also share class which contains this code. Without this, it is hard to understand the issue.

**Comment by redmi111** [comment]
https://we.tl/t-ksKXl4VSeS

Here is the APK and you can find this inside ExitDialog class

**Comment by jpstotz** [comment]
@redmi111 If you look at the smali code then you will see that the decompiled code is correct, they are initialized in `<init>(Landroid/content/Context;)V`. So if the code is incorrect this is a bug created by the author of the app. Jadx can only decompile what is present, no matter if it is correct Android code or not.

**Comment by redmi111** [comment]
Understood, Thanks for the clarification.

**Comment by skylot** [comment]
As I understand @redmi111 point to the incorrect initialization order and indeed this is an issue here.
I prepare a simple test case:
```java
	StringBuilder sb;
	int field;

	public TestCls() {
		initBuilder(new StringBuilder("sb"));
		this.field = initField();
		this.sb.append(this.field);
	}

	private void initBuilder(StringBuilder sb) {
		this.sb = sb;
	}

	private int initField() {
		return sb.length();
	}
```
Decompiled code:
```java
    int field = initField();
    StringBuilder sb;

    public TestFieldInitOrder3$TestCls() {
        initBuilder(new StringBuilder("sb"));
        this.sb.append(this.field);
    }
...
```
Decompiled code throw NPE from `initField` method because it called before `initBuilder`.

**Comment by skylot** [comment]
Fixed.
