### ISSUE TITLE
fail in multi classes.dex when decompiler 多个classes.dex时反编译失败 例如微信6.5.4

### ISSUE THREAD

**Issue by ruidalin** [skylot/jadx#160]
I can't decompile WeChat v6.5.4 but i can decompile WeChat v6.3.9 .
All WeChat download URL  http://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_faq_list

WeChat v6.5.4 URL http://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=page/faq/android/654/index&faq=android_654

WeChat v6.3.9 URL http://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_faq&faq=android_639

Can you help me , thanks very much !

当我反编译微信v6.5.4的时候卡主反编译不了 , 但微信v6.3.9 的可以.
可以帮助我吗 , 谢谢!

**Comment by cv0cv0** [comment]
我的也很卡。

**Comment by ruidalin** [comment]
调大jadx的运行内存就可以了

**Comment by danzoo** [comment]
请问怎么设置运行内存？

**Comment by ruidalin** [comment]
路径 bin/jadx-gui.bat

@rem Add default JVM options here. You can also use JAVA_OPTS and JADX_GUI_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS=-Xmx5128m

**Comment by chxchen** [comment]
it works for me,thanks

**Comment by chxchen** [comment]
This tool is fantastic,it helps me much,appreciation to author!

**Comment by ruidalin** [comment]
good
