### ISSUE TITLE
Code Editor 

### ISSUE THREAD

**Issue by TimScriptov** [skylot/jadx#1604]
Line numbering is incorrect

Example:

```
empty
20
empty
21
23
49
53
...
209
...
104
```

**Comment by jpstotz** [comment]
The default line numbering shown by Jadx uses the line numbers saved in the compiled code (if present). Those line numbers do not match the line numbers of the decompiled code. 

If you want to see the line numbers of the decompiled code you can click on the line number column to toggle between debug line numbers (only visible for lines that have such data in the code) and the Jadx decompiled code line numbers.

Does this solve your confusion about the shown line numbers?

**Comment by skylot** [comment]
@jpstotz thanks.
I also want to add that there is also an option `Editor lines numbers mode` in preferences, so it is possible to change that behavior (auto switching is set by default).

**Comment by TimScriptov** [comment]
@jpstotz thanks
