### ISSUE TITLE
[feature] keyboard shortcut for saving project

### ISSUE THREAD

**Issue by Bleuzen** [skylot/jadx#1609]
*Describe your idea:*

So usually in every program the shortcut `Ctrl + S` saves the project. But in JADX this standardized shortcut does... save decompiled sources. And there is no shortcut at all to save the current project.

A simple solution for now could be to move the `Ctrl + S` shortcut from saving sources to saving the project.
Here is why (extremely scientific me study):
- saving decompiled sources is an action one most likely won't need often, maybe only once for an app
- saving the project is an action used much more often (for me after every change so sometimes every few seconds) -> makes more sense to have the shortcut here, not having one is purely annoying

If you don't want to 'just move' the shortcut maybe assign a different one to saving the decompiled sources.
But `Ctrl + S` is a standard for saving the project and I suggest JADX doing the same.

**Comment by skylot** [comment]
Sure! Looks like I totally forgot about #1085, it already has that mapping :rofl:
And for `Save source` I want to set shortcut to <kbd>CTRL</kbd> + <kbd>E</kbd> after merging it with export, but for now <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>E</kbd> is also fine.

**Comment by skylot** [comment]
Not is possible to change these shortcuts. The feature was implemented by @Mino260806 in PR #1980.
