### ISSUE TITLE
Smali2java

### ISSUE THREAD

**Issue by TimScriptov** [skylot/jadx#1610]
Please show me, how used jadx library for smali to java latest

**Comment by skylot** [comment]
Follow steps shown on [wiki page](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library). You need to include `jadx-smali-input` plugin and next set input files to `.smali` files or directory which contains smali files.
If you have any questions, feel free to ask :slightly_smiling_face:

**Comment by TimScriptov** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/31324315/183482514-9e7ac438-9c38-4c31-8839-99396bba566f.png)

Working

**Comment by skylot** [comment]
@TimScriptov good, but I highly recommend to use `JadxDecompiler` inside `try-resource` block or just call `close()` to remove created temp files.
Also, you don't need to use `addCustomLoad` you can just use `jadxArgs.setInputFiles(` method:
```java
JadxArgs jadxArgs = new JadxArgs();
jadxArgs.setInputFiles(listOfFiles);
try (JadxDecompiler jadx = new JadxDecompiler(jadxArgs)) {
	jadx.load();
} catch (Exception e) {
	e.printStackTrace();
}
```
And please note that jadx library not really suited for use on Android, now it may not work on Android API < 26, check https://github.com/skylot/jadx/pull/1255#issuecomment-1138169103

**Comment by TimScriptov** [comment]
@skylot thanks
