### ISSUE TITLE
Silent output?

### ISSUE THREAD

**Issue by tamtam22** [skylot/jadx#162]
Currently jadx prints a lot of messages, is there a command line option to silence the output/errors? Thanks

**Comment by jpstotz** [comment]
Which OS do you use?

**Comment by tamtam22** [comment]
Windows.

Hopefully I can suppress messages as such:
~~~~
15:57:56 ERROR - Inconsistent code in method: android.support.v7.content.res.AppCompatResources.getCachedColorStateList(android.content.Context, int):android.content.res.ColorStateList
15:57:56 WARN  - Finally extract failed: remBlock pred: B:13:0x005d, [B:12:0x004c, B:11:0x004a], method: android.support.v7.widget.AppCompatBackgroundHelper.loadFromAttributes(android.util.AttributeSet, int):void
15:57:56 WARN  - Finally extract failed: remBlock pred: B:13:0x0059, [B:12:0x0048, B:11:0x0046], method: android.support.v7.widget.AppCompatCompoundButtonHelper.loadFromAttributes(android.util.AttributeSet, int):void
15:57:56 ERROR - Inconsistent code in method: android.support.v7.widget.ActivityChooserModel.setActivitySorter(android.support.v7.widget.ActivityChooserModel$ActivitySorter):void
15:57:56 ERROR - Inconsistent code in method: android.support.v7.widget.ActivityChooserModel.setHistoryMaxSize(int):void
15:57:56 WARN  - Finally extract failed: remBlock pred: B:11:0x0036, [B:10:0x0033, B:9:0x0031], method: android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(android.util.AttributeSet, int):void
15:57:56 ERROR - JadxRuntimeException in pass: BlockFinish in method: android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(android.util.AttributeSet, int):void
~~~~

**Comment by jpstotz** [comment]
You are using the command-line version, not jadx-gui right?

AFAIK there is no command-line option to silence jadx. However you can create a custom `logback.xml` like this one:

`<configuration>
    <root level="OFF">
    </root>
</configuration>
`

Save it and specify it in the jadx.bat:

`set DEFAULT_JVM_OPTS=-Dlogback.configurationFile=C:\path-to-jadx\jadx-0.6.1\logback.xml`

**Comment by tamtam22** [comment]
Yup I'm using jadx-cli! I see.. because my java program uses Log4j as well, and I only want to see log from my program (exclude jadx errors/warnings). Probably this can be a feature request for jadx-cli!

**Comment by jpstotz** [comment]
JadX does not use Log4J, it uses SLF4J with Logback as the actual logging backend. This combination is much more powerful.

May be you should think about switching to SLF4J, too, there are simple wrappers (log4j-over-slf4j) that implement the Log4J API and redirect the output to SLF4J. Hence only one logging framework is active. Then you could configure all logging with one config file.

**Comment by sergey-wowwow** [comment]
@tamtam22 
You should modify your program and don't redirect out and error streams of jadx to out and error streams of your app

**Comment by androidovshchik** [comment]
This works
```
jadx-1.0.0/bin/jadx my.apk -d out| grep -vE "(ERROR|WARN|JADX INFO|Debug info|^\s)"
```
```
INFO  - loading ...
INFO  - processing ...
INFO  - done
```

**Comment by skylot** [comment]
@androidovshchik I implement options for control log level and by default set output as you describe, see [this comment](https://github.com/skylot/jadx/issues/735#issuecomment-519466109).
