### ISSUE TITLE
Single dex file decompiled can't save as gradle project

### ISSUE THREAD

**Issue by xlg** [skylot/jadx#1629]
Hi:
    Most apps today are multi-dex,but single dex file decompiled can't save as gradle project,it only works for the entire apk.
    I remember the old version was ok，is it deleted？I think this is a very useful feature and would like to be supported.
    Thanks!

**Comment by jpstotz** [comment]
What type of gradle project would you expect as output? A single dex file misses `AndroidManifest.xml` and also resources and assets like layouts.

**Comment by xlg** [comment]
What you said is the problem，I just want to import the source code into android studio which more convenient to operate.In this case, packageName and resources and others are not necessary.Now,I found I can use "save all" to solve my need.and copy the source code into a empty project.
