### ISSUE TITLE
Search results truncated(limit: 100)

### ISSUE THREAD

**Issue by tianqiujie** [skylot/jadx#163]
Search results truncated(limit: 100)  where is the config ?

**Comment by jpstotz** [comment]
Displaying more than 100 entries can cost a lot of CPU power hence can cause long delays - I tried this out.
If you want to see all search results you can give my personal fork a try. I changed the search result handling in a way that allows to see them all - 100 per page. Scroll to the end of the list to see the item that allows to switch to the next 100 entries. This way is not perfect however it works for me.

**Comment by tianqiujie** [comment]
3ks
