### ISSUE TITLE
Resources styles

### ISSUE THREAD

**Issue by TimScriptov** [skylot/jadx#1631]
```
<item name="android:gravity">0x11</item>

center
```
```
<item name="android:textStyle">0x1</item>

bold
```
```
<item name="android:ellipsize">@null</item>

none
```
```
<item name="android:layout_gravity">0x53</item>

bottom|center|left
```
```
<item name="android:imeOptions">0x4</item>

actionSend
```
```
<item name="android:inputType">0x20001</item>

textMultiLine
```
```
<item name="android:scrollbars">0x200</item>

vertical
```
```
<item name="android:gravity">0x33</item>

center|left|top
```
```
<item name="android:gravity">0x5</item>

right
```

**Comment by TimScriptov** [comment]
Many attributes are represented as constants of type 0x33. As I understand it, you need to add an android framework

**Comment by jpstotz** [comment]
@TimScriptov Do you have a sample APK file you can provide? That would simplify developing a fix as we don't have to search for a suitable APK file

**Comment by TimScriptov** [comment]
[bad_styles.txt](https://github.com/skylot/jadx/files/9310716/bad_styles.txt)

**Comment by TimScriptov** [comment]
[good_styles.txt](https://github.com/skylot/jadx/files/9310720/good_styles.txt)

**Comment by TimScriptov** [comment]
> @TimScriptov Do you have a sample APK file you can provide? That would simplify developing a fix as we don't have to search for a suitable APK file

https://mega.nz/file/6FND1JBJ#eQ0p2J4qnCeSFpF0wcVgf0vXUZWCz50R_siOJJIxvv0
