### ISSUE TITLE
Error Decompilation

### ISSUE THREAD

**Issue by TimScriptov** [skylot/jadx#1633]
Minecraft 1.19.10.03
com.mojang.minecraftpe.MainActivity

![Screenshot_3](https://user-images.githubusercontent.com/31324315/184424629-d9fbc490-b944-4bf7-83f0-fb3828da45e7.png)
![Screenshot_4](https://user-images.githubusercontent.com/31324315/184424632-5504d027-365b-4a61-8f1c-997a8fe6ff43.png)

**Comment by TimScriptov** [comment]
Fix

![Screenshot_6](https://user-images.githubusercontent.com/31324315/184425713-a78d0727-2093-46d0-b4c6-f3954b51a2ea.png)

**Comment by TimScriptov** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/31324315/184439337-02817d92-09e3-4afe-a544-629163f07c48.png)

**Comment by skylot** [comment]
Both cases fixed, thanks for report!
