### ISSUE TITLE
Decompile support for multi dex - [join classes.dex+classes2.dex]

### ISSUE THREAD

**Issue by Hopfengetraenk** [skylot/jadx#164]
Sample:
http://apkpure.com/navigon/com.navigon.navigator_one/download?from=details

This file has two dex that belongs together.
If I decompile them separately I get:

```
classes.dex_source_from_JADX\org\flinc\sdk\popup\
FlincPopup.java
```
```
classes2.dex_source_from_JADX\org\flinc\sdk\popup\
FlincPopup$1.java
FlincPopup$2.java
FlincPopup$4.java
FlincPopup$3.java
```
Decompiling the apk they are shown together but they are not 'combined'.

1. make the open dialog to accept multiple files
2. When decopmile combine/integrate closures like this FlincPopup$1.java so the there will be just one 
FlincPopup.java

**Comment by enovella** [comment]
> Decompiling the apk they are shown together but they are not 'combined'.

You mean the dex files are not virtually merged? I've not experienced this issue so far.

**Comment by mingyuan-xia** [comment]
Like you said, you decompile them **separately**.
Two dexes are two dexes, they dont  "belong to" each other. They are likely jars~
Just decompile the entire APK and you will have all dexes in the APK "combined".
