### ISSUE TITLE
[feature] Search optimization

### ISSUE THREAD

**Issue by threerog** [skylot/jadx#1640]
*Describe your idea:*
1. Can real-time loading be prohibited during the search? When the APK is large, real-time loading will frequently lead to jams and crashes of jadx during the search process. You should click the button to search or enter.
2. When a new search is performed in the result window of the previous search, jadx will occasionally get stuck and crash

**Comment by skylot** [comment]
Check https://github.com/skylot/jadx/issues/1641#issuecomment-1214409998
