### ISSUE TITLE
[core]search crash！！！！

### ISSUE THREAD

**Issue by threerog** [skylot/jadx#1641]
on version 1.4.3

1. Can real-time loading be prohibited during the search? When the APK is large, real-time loading will frequently lead to jams and crashes of jadx during the search process. You should click the button to search or enter.
2. When a new search is performed in the result window of the previous search, jadx will occasionally get stuck and crash

**Comment by threerog** [comment]
My computer configuration
cpu：i9-12900K
ram：128GB
The crash should have nothing to do with my computer configuration
Target APK size: 257mb

**Comment by threerog** [comment]
I don't dare to manually enter the search target in the jadx search box, otherwise it will cause blocking and crash due to the real-time loading of jadx. I can only edit the search target in advance and paste it directly into the search window of jadx, but sometimes it will block and crash.

**Comment by jpstotz** [comment]
@threerog The APK download link just points to the website but there is no download link, only links to app stores. What version have you tried and what SHA-1 does your APK file has?

What preference have you configured in Jadx for `Code cache mode`?

**Comment by threerog** [comment]
> @threerogAPK下载链接仅指向网站，但没有下载链接，只有指向应用商店的链接。您试过什么版本，您的APK文件有什么SHA-1？
> 
> 您在 Jadx 中为哪些首选项配置了什么？`Code cache mode`

{
  "flattenPackage": false,
  "checkForUpdates": true,
  "fontStr": "",
  "smaliFontStr": "",
  "editorThemePath": "/org/fife/ui/rsyntaxtextarea/themes/default.xml",
  "lafTheme": "FlatLaf Light",
  "langLocale": {
    "locale": "zh_CN"
  },
  "autoStartJobs": true,
  "excludedPackages": "",
  "autoSaveProject": false,
  "showHeapUsageBar": true,
  "alwaysSelectOpened": false,
  "codeAreaLineWrap": false,
  "srhResourceSkipSize": 10,
  "srhResourceFileExt": ".xml|.html|.js|.json|.txt",
  "keepCommonDialogOpen": true,
  "smaliAreaShowBytecode": true,
  "lineNumbersMode": "AUTO",
  "mainWindowVerticalSplitterLoc": 300,
  "debuggerStackFrameSplitterLoc": 300,
  "debuggerVarTreeSplitterLoc": 700,
  "adbDialogPath": "",
  "adbDialogHost": "localhost",
  "adbDialogPort": "5037",
  "codeCacheMode": "DISK_WITH_CACHE",
  "jumpOnDoubleClick": true,
  "treeWidth": 633,
  "settingsVersion": 18,
  "skipResources": false,
  "skipSources": false,
  "exportAsGradleProject": false,
  "threadsCount": 20,
  "decompilationMode": "AUTO",
  "showInconsistentCode": true,
  "useImports": true,
  "debugInfo": true,
  "addDebugLines": false,
  "inlineAnonymousClasses": true,
  "inlineMethods": true,
  "replaceConsts": true,
  "escapeUnicode": true,
  "respectBytecodeAccessModifiers": false,
  "deobfuscationOn": true,
  "deobfuscationMinLength": 3,
  "deobfuscationMaxLength": 64,
  "deobfuscationMapFileMode": "READ",
  "deobfuscationUseSourceNameAsAlias": true,
  "deobfuscationParseKotlinMetadata": true,
  "useKotlinMethodsForVarNames": "APPLY",
  "renameFlags": [
    "CASE",
    "VALID",
    "PRINTABLE"
  ],
  "fsCaseSensitive": false,
  "cfgOutput": false,
  "rawCfgOutput": false,
  "fallbackMode": false,
  "useDx": false,
  "commentsLevel": "INFO",
  "pluginOptions": {}
}

**Comment by skylot** [comment]
@threerog recently I commit several search improvements including option to disable auto search and various performance optimizations (related issue #1600 and #1601), so please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Comment by threerog** [comment]
> @threerog The APK download link just points to the website but there is no download link, only links to app stores. What version have you tried and what SHA-1 does your APK file has?
> 
> What preference have you configured in Jadx for `Code cache mode`?

[download here](https://4406a71fef40c77072f574c59ebd1a71.rdt.tfogc.com:49156/dldir1.qq.com/weixin/android/weixin8025android2200_arm64_1.apk?mkey=62f907e8aa200b8591170cfcb527ef2f&arrive_key=938128590870&cip=183.227.28.18&proto=https)
