### ISSUE TITLE
[feature] Set search result count

### ISSUE THREAD

**Issue by LaryGala3** [skylot/jadx#1652]
*Describe your idea:*
I didn't found a way to set the search result count, I think the default is 50 and when I want more I should click load more every time..
Please add option to set this number or to give up this limit at all.

Thanks!

**Comment by skylot** [comment]
@LaryGala3 done. Option to change search results count per page added to preferences. Please try [latest unstable version](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).
