### ISSUE TITLE
Running Jadx on Termux

### ISSUE THREAD

**Issue by Xinul-Hacker** [skylot/jadx#1656]
*Describe your idea:*
Is it possible to update jadx to the current version if I'm using Android 5.1? If not, is it possible to release a compatible version? (By the way, I do have java 8 on Android 5.1 Termux.)

**Comment by jpstotz** [comment]
So you are using the Jadx cli version inside Termux. As Jadx still requires only Java 8 you should be able to use any version of Jadx you want.

**Comment by skylot** [comment]
As @jpstotz mention, jadx should work on Java 8. So, @Xinul-Hacker, if you found any issues feel free to open new issue with provided error details.
