### ISSUE TITLE
[core]cross-reference doesn't work on `default` package (package name is empty)

### ISSUE THREAD

**Issue by google-mirror** [skylot/jadx#1662]
![111](https://user-images.githubusercontent.com/70927995/188048772-f79f08d2-5228-44bc-811a-ed5c1d8e6673.png)
![2222](https://user-images.githubusercontent.com/70927995/188048782-6467727e-df23-401a-b247-903ba898d549.png)
![333](https://user-images.githubusercontent.com/70927995/188048786-8c43125d-aa21-474b-afc9-73662dfe0347.png)

**Comment by jpstotz** [comment]
I tried to reproduce this problem using Jadx 1.4.4 as well as latest version from master branch, but no matter which class I select from `defpackage` they all had the "Find Usage" menu entry enabled.
