### ISSUE TITLE
[UI] Glitch screen when hovering over "create a new issue at Github" button

### ISSUE THREAD

**Issue by choiman1559** [skylot/jadx#1665]
**Checks before report**
- check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
- search existing issues by exception message

**Describe error**

On my computer (Ubuntu 20.04.4 LTS), after focusing the Jadx error window, without clicking the "create a new issue at Github" button in that window, just hovering over it, the following happens:

https://user-images.githubusercontent.com/43315227/188475005-77cb98a3-7e74-4806-bace-1e16d312da45.mp4

Is this a problem with gnome shell or graphics driver and not with jadx? Or is it a problem with jadx itself?

I've put down as much information as possible that might be relevant to this issue in case you're wondering:

```
uname>
Linux 5.19.2-051902-generic #202208171037 SMP PREEMPT_DYNAMIC Wed Aug 17 14:41:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

lshw -C display>
 *-display                 
       description: VGA compatible controller
       product: Advanced Micro Devices, Inc. [AMD/ATI]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:05:00.0
       logical name: /dev/fb0
       version: c1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi msix vga_controller bus_master cap_list fb
       configuration: depth=32 driver=amdgpu latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:fc0-fbf iomemory:fc0-fbf irq:43 memory:fce0000000-fcefffffff memory:fcf0000000-fcf01fffff ioport:1000(size=256) memory:d0400000-d047ffff

gnome-shell --version>
GNOME Shell 3.36.9                       
```

**Comment by skylot** [comment]
@choiman1559 looks like an issue with wayland/xwayland, java apps now have various issues with popup tooltips (your case) and menus in Wayland. Updating JVM to latest version may help, if not, try switch to XOrg session.
