### ISSUE TITLE
反编译的包太大会卡死

### ISSUE THREAD

**Issue by Flyjun** [skylot/jadx#168]

**Comment by Flyjun** [comment]
反编译的包太大会卡死

**Comment by XuTuntun** [comment]
打开jadx-gui文件（其实就是个启动的script），加上：

set JAVA_OPTS=-server -Xms1024m -Xmx8192m -XX:PermSize=256m -XX:MaxPermSize=1024m

**Comment by fatcats** [comment]
加了直接打不开

**Comment by gyc990326** [comment]
换成64位jre

**Comment by danzoo** [comment]
请问楼主解决了吗？

**Comment by mingyuan-xia** [comment]
https://github.com/skylot/jadx/commit/6870c05ffa2e3040646ad4cc56e2d2fd7c1bbc8a
这个修复了，build 最新版本即可
