### ISSUE TITLE
[core] Missing referenced methods

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1680]
Hey!

APK: https://drive.google.com/file/d/1XBpFGkIORvQkPu8sYaWFpSZ1ZI87QpxR/view?usp=sharing

File `com/android/settings/accessibility/AccessibilityDialogUtils$$ExternalSyntheticLambda1.java`:
```java
    public final void onClick(View view) {
        AccessibilityDialogUtils.m71$r8$lambda$F89HzqjFJpwf2rTv8FkXEQZ4E(this.f$0, view); // <<<
    }
```

Method `$r8$lambda$F89HzqjFJpwf2rTv8FkXEQZ4E()` is missing. And this error happens in almost every originally lambda declaration

**Comment by jpstotz** [comment]
From the code you have posted I assume you have the preferences `Inline Anonymous classes: disabled` and `Inline Methods: Enabled`?

As workaround you can also disable `Inline Methods`, then method `$r8$lambda$F89HzqjFJpwf2rTv8FkXEQZ4E()` should exist (tested using latest unstable version of Jadx).

**Comment by bagipro** [comment]
Hey @jpstotz,

Thanks for your message! I use the following configuration:
- `Inline Methods` = enabled
- `Inline Anonymous classes` = disabled

**Comment by skylot** [comment]
Fixed
