### ISSUE TITLE
0x10  in styles.xml  <item name="android:gravity">0x10</item> <item name="android:textStyle">0x1</item>

### ISSUE THREAD

**Issue by tsatatwer** [skylot/jadx#1682]
Hi , 
after decompilation I found  in styles.xml file these :
`<item name="android:gravity">0x10</item> <item name="android:textStyle">0x1</item>`
Any idea??

**Comment by jpstotz** [comment]
Yes, attributes values like `gravity` are not yet decoded to a constant value. We already have an issue open on that problem: https://github.com/skylot/jadx/issues/1631

**Comment by skylot** [comment]
Fixed in PR #1812 by @nitram84.
