### ISSUE TITLE
Tab Pinning, Tab Re-Ordering, and Search Copy

### ISSUE THREAD

**Issue by idb-** [skylot/jadx#1684]
I tend to have a ton of tabs open while jumping around from reference to reference. Some of these tabs are more important than others, but when class names are obfuscated it becomes hard to keep track of the important tabs vs. the trivial tabs. Being able to pin a tab similar to how Chrome/Firefox can would be a huge help.

Being able to drag/re-order tabs to would also be a great feature. I would love to be able to group tabs in a certain vicinity of one another.

Finally, considering that there can be unlimited amount of search results it would be extremely helpful to be able to search the results that have been returned. I realize it would be ridiculous to ask for a search to search through the search results, but I feel like being able to select and copy  the text of all/selected rows (for a specific column, or both) would be extremely helpful (presently only 1 result is allowed to be selected at a time though). This way user could just paste into something like notepad++/notepad/whatever and perform a find in that to narrow the search down more. Perhaps if the search results had index #'s that would make it easier to find a narrowing match when performing the action I just described.

Hopefully these features can be implemented, but if not, no big deal. Love this particular piece of software. Thanks for all the work you've put in!

**Comment by skylot** [comment]
@idb- thanks for suggestions.
Some of them already requested: tab pinning in #847 and tab reordering in #1212.
Multi selection of search results can also be done (for text copy and open several tabs), but I think using regex will be easier to narrow search. Also sounds like you need something similar to bookmarks, for that you can use code comments and next search inside these comments (check https://github.com/skylot/jadx/issues/1448#issuecomment-1214413600)
