### ISSUE TITLE
[core] Usage of registers in enum declarations

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1686]
Hey!

APK: https://drive.google.com/file/d/1XBpFGkIORvQkPu8sYaWFpSZ1ZI87QpxR/view?usp=sharing

File `com/samsung/context/sdk/samsunganalytics/internal/connection/Domain.java`
```java
public enum Domain {
    REGISTRATION(Utils.isEngBin() ? r2 : "https://regi.di.atlas.samsung.com"),
    POLICY(r2),
    DLS("");
    
    String domain;

    static {
        String str = "https://stg-api.di.atlas.samsung.com";
        if (!Utils.isEngBin()) {
            str = "https://dc.di.atlas.samsung.com";
        }
    }
```

I believe that there shouldn't be the `static`  block, but `str` should be initialized with `"https://stg-api.di.atlas.samsung.com"`

**Comment by skylot** [comment]
Fixed.
