### ISSUE TITLE
[core] Usage of `??` instead of `boolean` type

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1688]
Hey!

APK: https://drive.google.com/file/d/1XBpFGkIORvQkPu8sYaWFpSZ1ZI87QpxR/view?usp=sharing

File `com/samsung/context/sdk/samsunganalytics/internal/sender/DMA/DMALogSender.java`:
```java
    public void sendCommon() {
        ?? isEnableUseInAppLogging = this.configuration.isEnableUseInAppLogging(); // <<< it should be `boolean`
```

**Comment by skylot** [comment]
Fixed. Thank you for this case :+1:
