### ISSUE TITLE
Error in copying frida snippet

### ISSUE THREAD

**Issue by 335158573** [skylot/jadx#1692]
> 当hook构造函数的时候，返回时应该为init，不是new
  let ret = this.$init("哎呦", amount);

Google Translate:
When hooking the constructor, the return should be `init`, not new `let ret = this.$init("Whoops", amount);`

**Comment by skylot** [comment]
@335158573 I think this issue already fixed in PR #1605 by replacing `$init` with `$new`, so please upgrade jadx to the latest version. If this is not your case, please add more details to your report.
