### ISSUE TITLE
Unable compile jadx on Ubuntu 17.04.

### ISSUE THREAD

**Issue by limkokhole** [skylot/jadx#170]
The output:

`xb@dnxb:~/n/apk/jadx$ ./gradlew dist --stacktrace --debug
22:37:28.077 [ERROR] [org.gradle.BuildExceptionReporter] 
22:37:28.144 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:37:28.145 [ERROR] [org.gradle.BuildExceptionReporter] 
22:37:28.146 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
22:37:28.146 [ERROR] [org.gradle.BuildExceptionReporter] java.lang.ExceptionInInitializerError (no error message)
22:37:28.149 [ERROR] [org.gradle.BuildExceptionReporter] 
22:37:28.149 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
22:37:28.151 [ERROR] [org.gradle.BuildExceptionReporter] java.lang.ExceptionInInitializerError
22:37:28.152 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.classloader.DefaultClassLoaderFactory.createFilteringClassLoader(DefaultClassLoaderFactory.java:63)
22:37:28.152 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultClassLoaderRegistry.restrictToGradleApi(DefaultClassLoaderRegistry.java:45)
22:37:28.152 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultClassLoaderRegistry.<init>(DefaultClassLoaderRegistry.java:36)
22:37:28.153 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.scopes.GlobalScopeServices.createClassLoaderRegistry(GlobalScopeServices.java:201)
22:37:28.153 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:37:28.153 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:37:28.153 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:37:28.153 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.Method.invoke(Method.java:547)
22:37:28.154 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
22:37:28.154 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry.invoke(DefaultServiceRegistry.java:462)
22:37:28.154 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry.access$1200(DefaultServiceRegistry.java:84)
22:37:28.154 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:796)
22:37:28.154 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:752)
22:37:28.155 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:589)
22:37:28.155 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:634)
22:37:28.157 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:253)
22:37:28.157 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:214)
22:37:28.158 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:352)
22:37:28.158 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.service.ServiceRegistryBuilder.build(ServiceRegistryBuilder.java:52)
22:37:28.158 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.BuildActionsFactory.runBuildInProcess(BuildActionsFactory.java:103)
22:37:28.158 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.BuildActionsFactory.createAction(BuildActionsFactory.java:76)
22:37:28.159 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.createAction(CommandLineActionFactory.java:244)
22:37:28.159 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:234)
22:37:28.159 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
22:37:28.159 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
22:37:28.160 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
22:37:28.160 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
22:37:28.160 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
22:37:28.160 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
22:37:28.161 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
22:37:28.161 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
22:37:28.161 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
22:37:28.163 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:37:28.163 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:37:28.163 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:37:28.164 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.Method.invoke(Method.java:547)
22:37:28.164 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
22:37:28.164 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
22:37:28.164 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
22:37:28.165 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:37:28.165 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:37:28.165 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:37:28.165 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.Method.invoke(Method.java:547)
22:37:28.165 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
22:37:28.166 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
22:37:28.166 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
22:37:28.166 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "opens java.lang" to unnamed module @3bcd05cb
22:37:28.166 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:335)
22:37:28.166 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:278)
22:37:28.167 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:196)
22:37:28.167 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.Method.setAccessible(Method.java:190)
22:37:28.167 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:34)
22:37:28.169 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:38)
22:37:28.169 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaReflectionUtil.method(JavaReflectionUtil.java:224)
22:37:28.169 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.classloader.FilteringClassLoader.<clinit>(FilteringClassLoader.java:43)
22:37:28.170 [ERROR] [org.gradle.BuildExceptionReporter]        ... 46 more
22:37:28.170 [ERROR] [org.gradle.BuildExceptionReporter] 
xb@dnxb:~/n/apk/jadx$ 
`
Note: I use `sudo apt-get install openjdk-9-jdk-headless` to download java and `git clone https://github.com/skylot/jadx.git` to get the source.

xb@dnxb:~/n/apk/jadx$ uname -a
Linux xiaobai-Latitude-E6430s 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
xb@dnxb:~/n/apk/jadx$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
xb@dnxb:~/n/apk/jadx$

**Comment by PerspectivesLab** [comment]
this is confirmed also for java jdk 8: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jadx-core:compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.

nb: on ubuntu 17, its impossible to install jdk 7.

**Comment by supaplextor** [comment]
Same issue with 16.04.2 using openjdk-8-jre-headless

supaplex@supaplex-gtx760m:~/usr/src/jadx$ ./gradlew dist
:jadx-core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jadx-core:compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.183 secs

**Comment by ZanyXDev** [comment]
./gradlew dist
:jadx-core:compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':jadx-core:compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
------------------------------------
Linux kdeb9 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
Debian GNU/Linux 9

**Comment by mingyuan-xia** [comment]
Guys, please google. It is most likely you only have JRE installed, the error message is straightforward enough. `where is your tools.jar included in the JDK`?
