### ISSUE TITLE
can't not open folder. sum.wat.shell.Win32ShellFolder2.getIshellFolder() 

### ISSUE THREAD

**Issue by Rado0z** [skylot/jadx#1709]
can't open folder to select any file. i tried that with all version of java 11,13,19 which i am using now windows 10

![jadxrs](https://user-images.githubusercontent.com/46728071/197804358-4ade155d-34ec-4b77-9d8c-49320a89185f.PNG)

**Comment by jpstotz** [comment]
This is the same problem as in #1657. We already tried to find the bug in the Java run-time, but unfortunately this bug occurs only on very few Windows systems. So we were not able to reproduce this issue yet.

Is there something special on the used Windows system? Is it part of a domain, has special network folders mounted, or any other special software that may add virtual drives or something like this?

**Comment by Rado0z** [comment]
none of these.

**Comment by jpstotz** [comment]
Is it a Windows 10 Home or Pro ? Have you enabled Windows Virtualization features like Sandboxing, WSL2 or the Hyper-V Hypervisor system?

**Comment by Rado0z** [comment]
enterprise and WSL/Hyper-V not enabled. but why? how is that related?

**Comment by jpstotz** [comment]
I just mentioned technologies and features that are not very common and may change the system behavior of executed applications. I don't know if these features have something to do with the problem but from my perspective they were possible candidates.

**Comment by skylot** [comment]
I made several fixed:
1. Tried to disable some paths to the problem method in 2bace2bde2d947fe9d59858eeac82292ac03619d. It may help, but chances are low.
2. As workaround, I add alternative file dialog, look for `Use alternative file dialog` in `Other` group in preferences. It have many limitations like: filters not working on Windows and no way to select directory for open, also it can crush sometimes :rofl:

@Rado0z please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master), if default file dialog not fixed try to switch to alternative one. Hope it will help.
