### ISSUE TITLE
[core] The "Summary" section shows a wrong count of code sources

### ISSUE THREAD

**Issue by raulsiles** [skylot/jadx#1716]
Version: jadx 1.4.5

When decompiling a large APK, the "Summary" section shows a wrong count under the "Code sources" section. It displays 11 when in reality there are only 10 "classes*.dex" files, but the list it displays is correct:

```
Code sources
Count: 11
classes.dex
classes10.dex
classes2.dex
classes3.dex
classes4.dex
classes5.dex
classes6.dex
classes7.dex
classes8.dex
classes9.dex
```

**Comment by skylot** [comment]
Haha, thanks! Result list contains only dex files, but count include other files.
I commit fix with removed dex filter, so now all files are shown.
Not sure what you got, but I often see a `DebugProbesKt.bin` file, which is actually a dex file and leftover of `kotlinx-coroutines` library (mention [here](https://github.com/Kotlin/kotlinx.coroutines#avoiding-including-the-debug-infrastructure-in-the-resulting-apk)).

**Comment by raulsiles** [comment]
Jejeje. Yes, the ```DebugProbesKt.bin``` file is exactly what I got as extra, and it is quite common to find it in many apps as a leftover, as you mentioned.
