### ISSUE TITLE
BUG: jadx-gui is having serious visual issues in Windows 10

### ISSUE THREAD

**Issue by meiraxx** [skylot/jadx#1719]
Tested with jadx/jadx-gui versions 1.3.3 and 1.4.4, the jadx-gui program's GUI starts breaking when hovering code.

In Macbook, I have never experienced this issue with jadx. I am now trying to use it on Windows and have been experiencing this issue for some weeks now.

I don't know exactly why it occurs, but it usually happens when I'm in jadx for a while (>15 mins). This issue is really bad because I have to restart jadx, recompile the program and reopen the interesting classes to continue my reversing.

I'm happy to share with you any details you need to get this issue fixed, as it's a real nuisance (for me or for anyone else experiencing the same issue).

Screenshots:
![issue_jadx1](https://user-images.githubusercontent.com/25626434/199852768-97bf6665-3ec6-4cfe-a1fe-621a15dc00c2.png)
![issue_jadx2](https://user-images.githubusercontent.com/25626434/199852824-8876f167-5f78-43d7-b66d-d122efb3a70e.png)

**Comment by meiraxx** [comment]
Also, this information could help: I've noticed this issue only occurs when the mouse cursor is put on the RIGHT SIDE (where the code is displayed) of jadx-gui. When the mouse is on the left side, the issue does not occur. However, I need to put the mouse on the right side to properly reverse applications, so this is not a solution

**Comment by meiraxx** [comment]
P.S.: this issue seems to be fixed when I use only 1 monitor.

The setup that is giving the issue shown is when I have my double-monitor setup (extended displays) turned on.

FYI, I use a 4K monitor 60hz and a 2K monitor 144hz. I use the 2K monitor as primary, 4K monitor as secondary

**Comment by skylot** [comment]
Looks like tooltip rendering issue (similar to #1665).
Using latest java version may help, I suggest trying latest jadx bundle with packed java i.e. [jadx-gui-1.4.5-with-jre-win.zip](https://github.com/skylot/jadx/releases/download/v1.4.5/jadx-gui-1.4.5-with-jre-win.zip).
