### ISSUE TITLE
能否增加导出lib的功能以及点击函数跳转到响应函数和函数参考功能？

### ISSUE THREAD

**Issue by BackTrackCRoot** [skylot/jadx#172]
能否增加导出lib的功能以及点击函数跳转到响应函数和函数参考功能？

**Comment by ppma** [comment]
> 
> 
> 能否增加导出lib的功能以及点击函数跳转到响应函数和函数参考功能？

难怪没人理你，你和一个歪果仁说话用中文？
万一别人不懂英文啊！！！

**Comment by BackTrackCRoot** [comment]
> > 能否增加导出lib的功能以及点击函数跳转到响应函数和函数参考功能？
> 
> 难怪没人理你，你和一个歪果仁说话用中文？
> 万一别人不懂英文啊！！！

呃 我看上面有中文发的…… 我以为他是中国人
