### ISSUE TITLE
Error Code not work

### ISSUE THREAD

**Issue by Arashvscode** [skylot/jadx#1720]
hello me using in code 
``` java


tv.setOnClickListener((v) -> {

			File file = new File("/storage/emulated/0/ApkEditor/classes_merge.dex");
			File fi = new File("/storage/emulated/0/ApkEditor");
			JadxArgs jadxArgs = new JadxArgs();
			jadxArgs.setInputFile(file);
			jadxArgs.getOutDir();
			jadxArgs.setOutDir(fi);
			try (JadxDecompiler jadx = new JadxDecompiler(jadxArgs)) {
				jadx.load();
				
				jadx.save();
			} catch (Exception e) {
				e.printStackTrace();
			}

		});


```

to Dicompile (dex) file and not Work me please Help me Tnks❤

**Comment by skylot** [comment]
Please follow suggestions from https://github.com/skylot/jadx/issues/1683#issuecomment-1259943303.

**Comment by Arashvscode** [comment]
> Please follow suggestions from [#1683 (comment)](https://github.com/skylot/jadx/issues/1683#issuecomment-1259943303).

Greetings and respect, unfortunately I did not understand anything and the Dehangan Android development site is blocked because I am Iranian and it could not be opened for me with any vpn.  The case should be prevented, thanks

**Comment by skylot** [comment]
> I did not understand anything

You need to learn how to manage project dependencies.
