### ISSUE TITLE
Restore the original shortcut key[feature]

### ISSUE THREAD

**Issue by javaeryang** [skylot/jadx#1721]
*Describe your idea:*
Ctrl + Alt + left   ===> back
Ctrl + Alt + right   ===> forward

Used for a long time
Please

**Comment by j4k0xb** [comment]
I would rather prefer <kbd>alt</kbd>+<kbd>left</kbd> and <kbd>alt</kbd>+<kbd>right</kbd> because it's so common in other programs (browsers, IDEs, file explorers, ...)

**Comment by javaeryang** [comment]
@j4k0xb It would be better if we could set it ourself

**Comment by skylot** [comment]
Now is possible to change these shortcuts. The feature was implemented by @Mino260806 in PR #1980.
