### ISSUE TITLE
[core]M1 mac A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by smile1847** [skylot/jadx#1722]
A fatal error has been detected by the Java Runtime Environment:

SIGBUS (0xa) at pc=0x000000010c99b435, pid=71724, tid=0x0000000000016d4f

JRE version: Java(TM) SE Runtime Environment (8.0_351-b10) (build 1.8.0_351-b10)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.351-b10 mixed mode bsd-amd64 compressed oops)
Problematic frame:
J 4142 C2 jadx.core.dex.info.ClassInfo.fromType(Ljadx/core/dex/nodes/RootNode;Ljadx/core/dex/instructions/args/ArgType;)Ljadx/core/dex/info/ClassInfo; (42 bytes) @ 0x000000010c99b435 [0x000000010c99b3a0+0x95]

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

if you would like to submit a bug report, please visit:
 http://bugreport.java.com/bugreport/crash.jsp

**Comment by skylot** [comment]
Looks like an issue with JVM. I suggest to use more recent java version, also you can install native build for your CPU from [Azul](https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk) (scroll down to download section).
