### ISSUE TITLE
[gui] Scaled main window size in Hi-DPI environment

### ISSUE THREAD

**Issue by shatyuka** [skylot/jadx#1728]
For 200% scaled monitor, jadx got scaled twice, for `DisplayMode` returns native resolution.

https://github.com/skylot/jadx/blob/bb4d88cc6841eaf3368e96943a59aa42fe1cb26b/jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java#L1425-L1427

Also, main window size got even bigger with multiple screens.

I'll make a PR later.

**Comment by skylot** [comment]
@shatyuka thanks! I merged your PR.
Also, I hope that someone else can check and confirm this fix :slightly_smiling_face:

**Comment by shatyuka** [comment]
Delete registry key `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\jadx\gui` to reset settings for testing.
