### ISSUE TITLE
[Question] Unable to set breakpoint

### ISSUE THREAD

**Issue by Nova-Noir** [skylot/jadx#1733]
I can't set breakpoint using F2 in both `Code` view and `Smali` view ( they 're not synchronized either)

I looked up [Wiki](https://github.com/skylot/jadx/wiki/Smali-debugger) which said smali debugger is supported, but that doesn't work for me.

Is there any step to enable this feature?

My Jadx-gui version is 1.4.5, my phone is rooted, and I was able to attach debugger on any application.
![image](https://user-images.githubusercontent.com/68760718/202849386-85805c35-2cb4-4c88-8983-d99a6012065a.png)

**Comment by Nova-Noir** [comment]
sorry for setting the lables incorrectly.

**Comment by skylot** [comment]
@Nova-Noir breakpoints now works only in smali viewer in `Show dalvik bytecode` mode (checkbox in right click menu in smali viewer) this mode should be enabled automatically on debug start, but looks like something goes wrong this time :cry:

**Comment by Nova-Noir** [comment]
Yes, I tried it and it now working ! Thanks for your kind help.
