### ISSUE TITLE
Jadx debugger couldn't connect to Nox emulator via ADB

### ISSUE THREAD

**Issue by Alireza-Razavi** [skylot/jadx#1742]
Jadx debugger couldn't connect to Nox emulator via ADB.

**Comment by musaulker** [comment]
@Alireza-Razavi did you resolve the problem?

**Comment by Alireza-Razavi** [comment]
@musaulker Not yet unfortunately :(

**Comment by jpstotz** [comment]
As far as I know NOX ships an own version of adb. Make sure to use `nox_adb.exe` which came with NOX.

ADB problems with NOX seem to be common. See e.g. https://stackoverflow.com/questions/51214825/adb-cant-connect-to-nox
