### ISSUE TITLE
[feature] Fix name confusion due to multiple overridden methods with the same name

### ISSUE THREAD

**Issue by sad-dev** [skylot/jadx#1743]
I ran into problems on an obfuscated jar. The essential code is as follows:

```
interface A {
  B a();
  C a();
};
abstract class B implements A {
  @Override
  C a() { ... } ;
};
class C extends A {
  @Override
  B a() { ... };
};
```
Deobfuscation renames the first `a` method, but class B ends up with the wrong alias. This also happens if the renaming is done manually.
```
interface A {
  B xxx();
  C a();
};
abstract class B implements A {
  C xxx() { ... } ;
};
class C extends B {
  B a() { ... };
};
```
I suspect this is due to overly lax (name based instead of prototype based?) identification of `MethodNodes` or `MethodInfo` objects. Also not too sure how easy it would be to triage and fix, so submitted as a feature request

**Comment by skylot** [comment]
Fixed.
@sad-dev thanks for test case!
