### ISSUE TITLE
decompiling APK using JadxDecompiler class (jadx library)

### ISSUE THREAD

**Issue by XingYuanWei** [skylot/jadx#1759]
thanks for you . I have a question. i use jadx as lib in java intellij idea project.as follow code.

```java
import jadx.api.JadxArgs;
import jadx.api.JadxDecompiler;
import jadx.api.JavaClass;
import jadx.api.JavaMethod;

import java.io.File;
public class DecompilationAPk {
    public static void main(String[] args) {
        // this is apk path
        String testApkPath = "E:\\smallData\\malware\\000a067df9235aea987cd1e6b7768bcc1053e640b267c5b1f0deefc18be5dbe1";
        JadxArgs jadxArgs = new JadxArgs();
        jadxArgs.setInputFile(new File(testApkPath));
        jadxArgs.setOutDir(new File("output"));
        try (JadxDecompiler jadx = new JadxDecompiler(jadxArgs)) {
//            jadx.load();
//            jadx.save();
            System.out.println(jadx.getClasses());
            System.out.println(jadx.getPackages());
            for (JavaClass cls : jadx.getClasses()) {
                for (JavaMethod mth : cls.getMethods()) {
                    System.out.println(mth.getName());
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

i output the jadx.getClasses() but the result is empty. as follow
[]
[]
last but not least.the decompilation source directory  on can find R.java. I change other apk files, but the result always **Only R.java**
![image](https://user-images.githubusercontent.com/30373199/212475719-b6b987c3-c52f-4aa1-ab2b-28ef7198acc1.png)

**Comment by jpstotz** [comment]
Instead of posting screen shots it may be better to post your source code as text. Best would be a minimal code snippet that can be executed (no external dependencies except jadx libs).

**Comment by skylot** [comment]
@XingYuanWei you **must** invoke `jadx.load()` before accessing any jadx data.

**Comment by XingYuanWei** [comment]
so sorry. i will change my post question as soon as in free time.



---Original---
From: "Jan ***@***.***&gt;
Date: Fri, Jan 13, 2023 16:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [skylot/jadx] [core] (Issue #1759)




 
Instead of posting screen shots it may be better to post your source code as text. Best would be a minimal code snippet that can be executed (no external dependencies except jadx libs).

**Comment by XingYuanWei** [comment]
hi. i change my post



---Original---
From: "Jan ***@***.***&gt;
Date: Fri, Jan 13, 2023 16:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [skylot/jadx] [core] (Issue #1759)




 
Instead of posting screen shots it may be better to post your source code as text. Best would be a minimal code snippet that can be executed (no external dependencies except jadx libs).
