### ISSUE TITLE
[feature] close tab keyboard shortcut

### ISSUE THREAD

**Issue by Ran-Naor** [skylot/jadx#1765]
Currently it is only possible to close tabs using a mouse: by clicking the little x icon, by clicking the mouse wheel while hovering over the tab name, or by right clicking the tab and pressing the Close option in the menu.

I try to use the mouse as little as possible while I work, so I added an option to close the tab using ctrl+w (the default shortcut for closing current tab in most of the programs I know).

I would also add the PR  of this feature to this issue :).

as a side comment, I went over the Key bindings list on the wiki, and would recommand adding shortcut for moving to the the left tab and right tab, I can add it myself and PR it if you also think that it's worth adding ;).

**Comment by skylot** [comment]
@Ran-Naor I merged your PR. Thank you for your work!

> shortcut for moving to the the left tab and right tab

Sure! This will be nice, PR are welcome :slightly_smiling_face:

**Comment by Ran-Naor** [comment]
no problem :D
Nice to know, I do have some things I would like to fix or add, I would do it when I have some free time :)
