### ISSUE TITLE
Html rendering problem when renaming varaibles

### ISSUE THREAD

**Issue by Ran-Naor** [skylot/jadx#1769]
When you rename variables the html is printed out as plain text instead of being rendered.
The solution is to just override the disableHtml function in the JVariable class to return false.

before fix:
![before](https://user-images.githubusercontent.com/38539376/215079685-9cf2484e-4e8a-4df1-8a24-4e1edbcac339.png)
after fix:
![after](https://user-images.githubusercontent.com/38539376/215079693-12992037-5b92-4b24-8135-76f0cdfceb9c.png)

I will add the PR of the simple fix.

**Comment by skylot** [comment]
@Ran-Naor PR merged. Thank you for the fix!
