### ISSUE TITLE
Why is Jadx-gui not loading edited java code

### ISSUE THREAD

**Issue by solomom399** [skylot/jadx#1771]
I have decompiled the apk file and I've made changes to the code but, jadx-gui is not loading the changes i made when I open the codes in it...please help.

**Comment by skylot** [comment]
@solomom399 it is hard to help because your description skips a lot of detail what exactly you have done.
It is not likely that jadx can cause such issue, but to be sure that jadx code caching is not a cause, you can change `Code cache mode` to `Memory` in preferences.

**Comment by solomom399** [comment]
> @solomom399 it is hard to help because your description skips a lot of detail what exactly you have done. It is not likely that jadx can cause such issue, but to be sure that jadx code caching is not a cause, you can change `Code cache mode` to `Memory` in preferences.

Actually, I edited the decompiled java code in vscode and I wanted to convert it to smali syntax but jadx-gui still shows the old java code...
I have changed the 'code cache mode' to 'memory'
Thanks for the response...I really appreciate.

**Comment by skylot** [comment]
Editing decompiled code is pointless because it will be hard to compile it. You should use [apktool](https://github.com/iBotPeaches/Apktool) and edit smali code to be able to build apk.
