### ISSUE TITLE
[fix] Frida snippet empty method arguments

### ISSUE THREAD

**Issue by Ran-Naor** [skylot/jadx#1775]
A problem that happens when copying a frida snippet, where no arguments appear in the snippet.
This problem occurs almost always after renaming methods which add comments above them, or adding comments yourself. 

problem example:
![bug](https://user-images.githubusercontent.com/38539376/216146354-46b9caef-3b10-449e-a619-e6d08a19f7a9.png)

after fix:
![fix](https://user-images.githubusercontent.com/38539376/216146384-f23d59b1-d14c-45e0-ab0d-d2844199b2c3.png)

I found out why this happen after reading the code and debugging it using logs, and I saw that in the collectMethodArgNames function the getDefPos is used the get the function start, and starting from this position you try to find the function arguments, the problem is that this position dont get changed when the user renames functions above for example which adds comments and change the actual start position of the function (or when the user adds comments).
Instead of using the getPos I changed the logic a bit to just scan the class for this method variables until you have an amount equivlent to the method arugments amount.

I added the PR for this fix of course.

**Comment by skylot** [comment]
@Ran-Naor thanks for this workaround, but root cause of this issue need to be fixed anyway, because it can cause similar issues in other places. I will try to investigate and resolve it, so please wait couple days :thinking:

**Comment by Ran-Naor** [comment]
No problem, If you can fix the getDefPos it will be better :)

**Comment by skylot** [comment]
Ok, I commit a fix to resolve caching which cause usage of outdated method instance after code reload. Instead of using maps, I moved cached object into node it references, so it always will be point on correct one.
Anyway, just to be sure, @Ran-Naor please check latest unstable build :slightly_smiling_face:

**Comment by Ran-Naor** [comment]
From my tests it works great! thanks 😄
