### ISSUE TITLE
How to import deobfuscation mapping file into jadx gui?

### ISSUE THREAD

**Issue by only52607** [skylot/jadx#1778]
I built some deobfuscation mapping using an automation script, what format should I output it in and import it into the jadx gui, any suggestions?

**Comment by skylot** [comment]
@only52607 now jadx support only own `.jobf` format. It is simple line by line mapping like this:
```
c org.pkg.ClassName = NewClassName
f org.pkg.ClassName.fieldName:Ljava/lang/String; = newFieldName
m org.pkg.ClassName.methodName(I)V = newMethodName
p org.pkg.pkgName = newPackageName
```
You can set path to this file using cli option: `--deobf-cfg-file`:
```
  --deobf-cfg-file                    - deobfuscation map file, default: same dir and name as input file with '.jobf' extension
  --deobf-cfg-file-mode               - set mode for handle deobfuscation map file:
                                         'read' - read if found, don't save (default)
                                         'read-or-save' - read if found, save otherwise (don't overwrite)
                                         'overwrite' - don't read, always save
                                         'ignore' - don't read and don't save
```
Now, there is no way to set that path in jadx-gui.
Work to support import of other formats and ui improvements going in `jadx-next` branch, through it is not yet finished.

**Comment by only52607** [comment]
Ok. Thank you for your response.

**Comment by Mohammad-Azizi** [comment]
Can you explain jobf structure what is f in the beginning?
