### ISSUE TITLE
Custom Frida snippets[feature]

### ISSUE THREAD

**Issue by gavriksobaken** [skylot/jadx#1784]
It would be cool if you made it possible to add my own snippets.
To do this, you need to make a list of placeholders that will be replaced by jadx in the pasted code during the snippet generation call. something like this:
$CLASS_NAME
$METHOD_NAME
$ARG_TYPES[]
$ARGS[]
$ARGS_LEN
and so on
at example: 
```
let a = Java.use($CLASS_NAME);
a[$METHOD_NAME].overload( '$ARG_TYPES[0]').implementation = function ($ARGS[0]) {
  console.log('$CLASS_NAME-$METHOD_NAME called' + ', ' + '$ARGS[0]: ' + $ARGS[0]);
   let ret = this[$METHOD_NAME]($ARGS[0]);
  return ret;
};
```

**Comment by skylot** [comment]
@gavriksobaken you can use `jadx-next` branch with [`gui_custom_frida`](https://github.com/skylot/jadx/blob/jadx-next/jadx-plugins/jadx-script/examples/scripts/gui_custom_frida.jadx.kts) script.
