### ISSUE TITLE
Installation problem.

### ISSUE THREAD

**Issue by JohnTill123** [skylot/jadx#1786]
After install on Linux, running build/bin/jadx returns: 

$:/home/username/git/jadx/build/jadx/bin/jadx
Error: Could not find or load main class jadx.cli.JadxCLI
Caused by: java.lang.ClassNotFoundException: jadx.cli.JadxCLI

CLASSPATH is set to the directory :/home/username/git/jadx/build/jadx/lib/

**Comment by skylot** [comment]
@JohnTill123 it is hard to help here, because if build finished without errors this issue shouldn't happen. Make sure you don't make any changes to jadx repo. And try to run clean task before build: `./gradlew clean dist`
