### ISSUE TITLE
[core]The inline error eliminates the constructor!

### ISSUE THREAD

**Issue by bhwxha** [skylot/jadx#1789]
app：https://drive.google.com/file/d/1w3ZTTSDu54qrSfao7KfDlmffId3MKTWO/view?usp=share_link

method：com.meituan.android.common.mtguard.wtscore.plugin.sign.core.a.a(android.content.Context, java.net.URI, boolean, byte[], java.lang.String, java.lang.String, java.util.Map, java.lang.String, java.util.Map) : java.net.URI

jadx's pseudo-code makes logical errors due to incorrect inline processing.

jeb
![image](https://user-images.githubusercontent.com/107301547/222083197-b313ea94-c9ee-4e0c-89a7-520208e93016.png)

jadx
![image](https://user-images.githubusercontent.com/107301547/222083427-b0753cfa-3034-4959-8c9d-986db9094700.png)

**Comment by skylot** [comment]
Hm, I don't see any issue here.
Jadx just undo compiler modifications and directly use variables from current method scope. Similar to this:
```java
public void test(boolean a, boolean b) {
	boolean c = a && b;
	new Runnable() {
		@Override
		public void run() {
			System.out.println(a + " && " + b + " = " + c);
		}
	}.run();
}
```
If you disable anonymous class inlining code will be:
```java
    class AnonymousClass1 implements Runnable {
        final boolean val$a;
        final boolean val$b;
        final boolean val$c;

        AnonymousClass1(boolean z, boolean z2, boolean z3) {
            this.val$a = z;
            this.val$b = z2;
            this.val$c = z3;
        }

        @Override // java.lang.Runnable
        public void run() {
            System.out.println(this.val$a + " && " + this.val$b + " = " + this.val$c);
        }
    }

    public void test(boolean a, boolean b) {
        boolean c = a && b;
        new AnonymousClass1(a, b, c).run();
    }
```
@bhwxha do this resolve this issue, or maybe I missed something?

**Comment by bhwxha** [comment]
@skylot This question 1789, you are correct, I am not familiar with java and did not think it was an argument to an external function.

However, https://github.com/skylot/jadx/issues/1671, this does have a lot less pseudo code, I'll go to 1671 and give you the details.
