### ISSUE TITLE
Same Package have inner class have issue

### ISSUE THREAD

**Issue by rossyang** [skylot/jadx#179]
If we have two class A and B at the same package, if A class have inner class C, B class used the inner class C, after decompile, the class B don't have imports C class and have build error, how can I fix this issue?

**Comment by sergey-wowwow** [comment]
> how can I fix this issue?

You can use option ``` --no-imports ``` to prevent such issues. If you don't want, please provide an example of code causing the bug. I tried to reproduce it, but no luck
```java
package com.example.app;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import com.example.app.MyReceiver.Inner; // correct import statement is generated

public class MainActivity extends AppCompatActivity {
    public void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        Inner inner = new Inner();
    }
}
```
