### ISSUE TITLE
[feature] Class method list panel

### ISSUE THREAD

**Issue by Iscle** [skylot/jadx#1790]
Greetings!

Sometimes, while reverse engineering obfuscated classes that extend Android classes (BroadcastReceiver, Service, Activity, etc.) I tend to look for overriden methods by their names. I normally use the search function but it can be a pain to use sometimes.

It would be nice to have the left panel (where the files are listed) have a tab that lets us show a list of the methods and variables present in the current file, sorted alphabetically or by type.

I've been searching for similar open issues but I haven't seen one.

I hope my idea is clear enough.

JetBrains IDEs have this functionality, named "Structure".
<img width="351" alt="image" src="https://user-images.githubusercontent.com/8018823/222203052-b4da9401-e854-426c-a3ba-f74b509201ec.png">

Regards,  
Iscle

**Comment by skylot** [comment]
Well, jadx currently can show all class members if you unfold class in left panel:
![screenshot_2023-03-01-195010](https://user-images.githubusercontent.com/118523/222207612-490630cc-3d8f-47b4-aa63-3ec3a5551873.png)
(you can use `Sync with editor` (Ctrl+T) to quickly find current class in tree)
@Iscle is that you are looking for?
Anyway, I don't think additional panel is really needed.

Also, for search overridden methods, modification of search dialog already requested in #1368.

**Comment by Iscle** [comment]
Oh! I completely missed that!

That's exactly what I was looking for...

I'm closing the issue, sorry for the hassle!

Regards,
Iscle
