### ISSUE TITLE
How does jadx(command line version) obtain APK signature?

### ISSUE THREAD

**Issue by wujian0601** [skylot/jadx#1791]
I see that jadx-gui has APK signature view which shows the details of all versions of signatures used. But, I don't know use jadx(command line version) to obtain  APK signature.Which command should I input？please tell me,thanks

**Comment by jpstotz** [comment]
The command-line version Jadx does not process the APK signature. 
The necessary library and the code to decode the signatures is not included in the command-line version. 

If you want to verify an APK signature please use `apksigner` from Android SDK.
