### ISSUE TITLE
[feature] Guessing logging functions based on method call frequency

### ISSUE THREAD

**Issue by Gvald** [skylot/jadx#1810]
I have been using the jadx project for some time now and have found it to be a great tool for decompiling and analyzing Java code. I would like to propose an enhancement that I believe would be beneficial to the community.

My idea is to add a feature that could guess the logging function used in code, based on the number of calls to a specific method. This would have several advantages, such as reversing the code and renaming obfuscated log methods to their real names. Additionally, by seeing multiple TAGs across one class, we could assume the class name and follow the idiom of Log.d(TAG, message). This will probably require some statistics to be taken into account.

I believe this enhancement would be valuable to developers who are trying to understand the code, especially in cases where the code is obfuscated or the logging function is not explicitly specified. If this sounds like a feature that would be useful to the community, I would be happy to contribute to its development.

I would appreciate any guidance on which classes to look at to begin the development process. Once I have familiarized myself with the codebase, I plan to implement a method call frequency analysis feature and then use that information to infer the logging function used in the code. From there, I will work on integrating the feature into the existing codebase and testing it to ensure it is working as intended.

Thanks for considering my proposal. I look forward to hearing back regarding it.
Best regards,
Gvald

**Comment by skylot** [comment]
@Gvald this sounds nice, but I am not sure what exactly you want to archive, so sample app with examples before/after will be very useful :slightly_smiling_face:
Anyway, for case of renaming most used method with required signature, you can use already collected usage info for every method ([MethodNode.useIn](https://github.com/skylot/jadx/blob/4d00fede56a85ba37daa5c2d231c754393dfeb32/jadx-core/src/main/java/jadx/core/dex/nodes/MethodNode.java#L73)) and rename method in a new visitor placed after `UsageInfoVisitor` [here](https://github.com/skylot/jadx/blob/691d5cd1e69dcae8dbbc2151c4f63787194a340e/jadx-core/src/main/java/jadx/core/Jadx.java#L95), you can rename method node by `methodNode.getMethodInfo().setAlias("newName")`.

**Comment by Gvald** [comment]
Thanks for the quick response.
I'll try to explain it a little more, since app examples are less relevant here. Hopefully this time it'll be clearer.

I want to make to process of renaming method much easier, and automate it as much as we can.
I think that due to the [Android idiom](https://developer.android.com/reference/android/util/Log) of `Log.e|v|i|...(TAG, message)` - we can gather information that will help up rename classes, methods and fields to their original name, pretty accurate.

Since most (decent) Android apps have logging mechanism, and most of the logging mechanism conform to the Android idiom - we can look for the most called method across all code-base and assume in high level of certainty that this is the Log calls. Thus, we benefit one big renaming/deobf. - the method with most occurrences.

From there, we can conclude that the first parameter to this method (hopefully - `java.lang.String`, as the **TAG** parameter) - is the class name. This will we can benefit huge advantage of de-obfuscating *every* class that have log prints somewhere in it.  Method names can also be derived this way.

I think the first steps in this direction will be to build some statistic system, which can give some indication on the level of certainty regarding initial log method existence.

Is it clearer now?

**Comment by jpstotz** [comment]
@Gvald In general an option to list or search function in Jadx based on their usage number would be a good improvement.

In addition we could think about a mass rename feature that e.g. allows renaming of multiple selected methods e.g. in the Usage search of a selected method like Log.d. 

However I do not agree your assumption that Logging usually follows the "Android idiom". Most logging frameworks were developed for J2SE, and because it is used in Java libraries those logging frameworks are also used on Android. But all of those logging frameworks like log4j, slf4j/logback, apache commons logging do not follow  the "Android idiom".

**Comment by Gvald** [comment]
Well, TBH - I don't enough experience reviewing Android applications, to know whether most of them using the Android Logging mechanism or not.
It's just seems to me natural enough that if someone is building Android application - the first choice will be to use `android.util.Log`.
Anyway - I think that even by trying to find to log function by itself there's enough added value, so I will start working on this.
Already looked at the points @skylot referred me to, I got to say Jadx is not a simple project as I thought it is... :)

I will update as soon as I'll have something concrete in hands.
