### ISSUE TITLE
[core]JADX ERROR: Method code generation error

### ISSUE THREAD

**Issue by greenozon** [skylot/jadx#1816]
**Checks before report**
- check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
- search existing issues by exception message

**Describe error**
example of recurring error (seen in 65 files in jar)

```
    @Override // java.util.TimerTask, java.lang.Runnable
    public void run() {
        long j = this.a;
        SwingUtilities.invokeLater(()
        /*  JADX ERROR: Method code generation error
            jadx.core.utils.exceptions.CodegenException: Error generate insn: 0x000a: INVOKE  

...

```

- **IMPORTANT!** attach or provide link to apk file (double check apk version)

ref jar inside #1814

**Comment by skylot** [comment]
@greenozon fixed.
