### ISSUE TITLE
[feature] improve searching performance

### ISSUE THREAD

**Issue by dvdface** [skylot/jadx#1820]
*Describe your idea:*
When RE a big app, such as WeChat,    searching string in codes takes long time, could you speed it up by some indexing tech?

**Comment by skylot** [comment]
@dvdface before search jadx needs to decompile whole app and this is a most consuming part, but after decompilation is finished search should be fast. In latest unstable build `Tools/Decompile all classes` button was added, use it to run full decomplation, so next searches will be much faster.
