### ISSUE TITLE
All xml files in android assets/xml sub-directory are not de-compiled 

### ISSUE THREAD

**Issue by cmeng-git** [skylot/jadx#1823]
It is found that all the xml files in the android assets/xml sub-directory of the attached apk file are not de-compiled. Appreciate if you add support to decompile these xml files.

[just-grandma-and-me-1-11-11100.zip](https://github.com/skylot/jadx/files/11245403/just-grandma-and-me-1-11-11100.zip)

**Comment by jpstotz** [comment]
These files doesn't look like binary XML files (no plain text sections visible when looking at it in a hex editor), thus they are most likely encrypted or compressed and decrypted by custom code when loaded. So Jadx can not decompile these files because the file format is not known.

**Comment by cmeng-git** [comment]
Many thanks for the info.

Yes, I see the mentioned class is in fact used for encrypting the file content.

**Comment by cmeng-git** [comment]
In decompiled source for bf.java class, method public static void a() is not decompiled.  How do I resolve this problem, or any recommended tools for a manual decompile.

    /* JADX WARN: Removed duplicated region for block: B:26:0x00fc  */
    /* JADX WARN: Removed duplicated region for block: B:35:0x013b  */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct code enable 'Show inconsistent code' option in preferences
    */
    public static void a() {
        /*
            Method dump skipped, instructions count: 568
            To view this dump change 'Code comments level' option to 'DEBUG'
        */
        throw new UnsupportedOperationException("Method not decompiled: com.oceanhouse_media.bookcommon.bf.a():void");
    }

**Comment by cmeng-git** [comment]
I am able to decompile all the methods that were failed in jadx with UnsupportedOperationException().
e.g throw new UnsupportedOperationException("Method not decompiled: com.oceanhouse_media.bookcommon.p.d(java.lang.String):byte[]");

Using [Bytecode-Viewer-2.11.2.jar](https://github.com/Konloch/bytecode-viewer/releases/download/v2.11.2/Bytecode-Viewer-2.11.2.jar)

**Comment by cmeng-git** [comment]
Finally manged to get the source to compile and run. Below is some of my observation while the various decompiler i.e.
jadx and bytecodeViewer. (bcv)

Generally the jadx generates a better source as compare to bcv.
gadx decompiles the enum constant with proper names, bcv just uses integer values.

==> bcv generates proper for() loop for better source review,
        for (int j = 0; j < ci.d.b.size(); ++j) {
            if (((ci)ci.d.b.get(j)).g.size() > 0) {
                this.bi = (ci)ci.d.b.get(j);
            }
        }

==>  whereas jadx always uses while(true) with break; 
        while (true) {
            int i3 = i2;
            if (i3 >= ciVar.d.b.size()) {
                break;
            }
            if (ciVar.d.b.get(i3).g.size() > 0) {
                this.bi = ciVar.d.b.get(i3);
            }
            i2 = i3 + 1;
        }
