### ISSUE TITLE
[core]Error occurred when decoding the list again

### ISSUE THREAD

**Issue by s1g0day** [skylot/jadx#1825]
#1797

```
Error decode manifest
java.io.IOException: Expected strings start, expected offset: 0x574, actual: 0x1624
	at jadx.core.xmlgen.ParserStream.checkPos(ParserStream.java:124)
	at jadx.core.xmlgen.CommonBinaryParser.parseStringPoolNoType(CommonBinaryParser.java:29)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:110)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:82)
```

**Comment by jpstotz** [comment]
Can you please try an [unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master)? The latest release version does not yet include the changes that fix #1797.

As the difference between expected and actual offset is pretty large in your example it would be nice if you could provide the APK that causes this problem. Just to see what is in the 4272 bytes between...

**Comment by s1g0day** [comment]
Sorry, I can't provide the original APK, but I found some other APKs instead, I think their problem may be the same.

APK Download: https://userscloud.com/hf60ox635ioa

AndroidManifest Error:
```
Error decode manifest
java.io.IOException: Expected strings start, expected offset not reachable: 0x590, actual: 0x29f0
```

**Comment by s1g0day** [comment]
I think the reason for this may be that there are protective measures in the APK program, such as packing and obfuscation, which are individual cases
