### ISSUE TITLE
[feature] Jadx script: jump to symbol and rename listener

### ISSUE THREAD

**Issue by yoavst** [skylot/jadx#1832]
**Background:**
I'm the author of  [Graffiti](https://github.com/yoavst/Graffiti), a tool for creating graphs interactively from the IDE.
In order to support JADX, those features in jadx-script are required:

- [x] Keybinding/menu for code area - Using `Gui.addPopupMenuAction`.
- [x] Get the method name and class from `ICodeNodeRef `
- [x] Detect renames so I could update the graph
- [ ] Given an "address" (full method signature), show it on JADX.

So those features are missing for support:

**Rename listener**
It would be nice to able to listen to the events of user renaming a symbol (class, method, field, package, package for class)

JEB for example, uses the following api:
```py
dex = prj.findUnit(IDexUnit)
dex.addListener(RenameListener())

class DexListener(IEventListener):
    def onEvent(self, e):
        if isinstance(e, JebEvent) and e.type == J.UnitChange and e.data is not None:
            if e.data.type == UnitChangeEventData.NameUpdate:
                target = e.data.target
```

**Jump to symbol**
Given a symbol (For example `ICodeNode`), it would be really helpful if we could be able to open its code in the view programmatically. Same as [The implementation](https://github.com/skylot/jadx/blob/master/jadx-gui/src/main/java/jadx/gui/ui/dialog/CommonSearchDialog.java#L149) in `CommonSearchDialog` probably.

JEB for example, uses:
```py
dex = prj.findUnit(IDexUnit)
ctx.navigate(dex, FULL_DEX_ADDRESS)
```
on IDA, it is:
```py
ida_kernwin.jumpto(addr)
```

**Comment by skylot** [comment]
@yoavst recently I make a [jadx example plugin](https://github.com/jadx-decompiler/jadx-example-plugin) and also implement a way to install/manage plugins from cli and gui.
So, if you want, you can create a plugin instead script :slightly_smiling_face:

**Comment by yoavst** [comment]
I'll try this, thanks!
Closing the issue as it is fixed.
