### ISSUE TITLE
[core] Jadx may generate incorrect code for assignment to an object-type variable

### ISSUE THREAD

**Issue by xxh160** [skylot/jadx#1838]
Hi! I am doing some research based on Jadx, and I found a bug related to object type variables!

When assigning object type variables, Jadx may generate code that does not accurately reflect the original source code. 

I have tested this issue with several different code samples, here is an example code snippet:

```java
class Demo {
    public static void foo(Object o) {
        if (o instanceof Boolean) System.out.println("Boolean: " + o);
        if (o instanceof Float) System.out.println("Float: " + o);
    }
    public static void main(String[] args) {
        final Float f = (float) -47.99;
        Boolean b = args.length == 0;
        Object o = ((b) ? false : f);
        foo(o);
    }
}
```

I compiled the code above into dex bytecode and then decompiled it into Java code:

```java
package defpackage;
import java.io.PrintStream;
/* renamed from: Demo  reason: default package */
class Demo {
    Demo() {
    }
    public static void foo(Object obj) {
        if (obj instanceof Boolean) {
            PrintStream printStream = System.out;
            printStream.println("Boolean: " + obj);
        }
        if (obj instanceof Float) {
            PrintStream printStream2 = System.out;
            printStream2.println("Float: " + obj);
        }
    }
    public static void main(String[] strArr) {
        boolean valueOf = Float.valueOf(-47.99f);
        if (Boolean.valueOf(strArr.length == 0).booleanValue()) {
            valueOf = false;
        }
        foo(valueOf);
    }
}
```

A variable of type float is assigned to a variable of type boolean, and it raised a compilation error:

```shell
./out/sources/defpackage/Demo.java:22: error: incompatible types: Float cannot be converted to boolean
        boolean valueOf = Float.valueOf(-47.99f);
                                       ^
1 error
```

Would you please take a look at this? It is essential for me!
Thanks a lot!

Jadx version: 1.4.7.
Java version: 11.0.18.
D8 version: D8 2.1.7-r1 (build 4443fac8e25c38e6ecfb5a8b0d212a3fad6f7f63 from go/r8bot (luci-r8-ci-archive-0-ewc5))

I also attach the source files and the decompilation results and I hope they will be helpful: [demo.zip](https://github.com/skylot/jadx/files/11304461/demo.zip).

**Comment by skylot** [comment]
Fixed
