### ISSUE TITLE
[core]Type cast expression in super constructor call may cause decompilation error

### ISSUE THREAD

**Issue by xxh160** [skylot/jadx#1854]
Hi! I am doing some research based on JADX. I found that When trying to decompile code that contains a type cast expression in a super constructor call, JADX may encounter an error and is unable to decompile the code correctly.

Here is an example:

```java
class T3 <A, B> {}

class T2 {}

class T1 extends T2 {
    public T1(T3<? extends Boolean, ? extends Byte> t3, T2 t2) {
    }
}

class Demo1 extends T1 {
    public Demo1() {
        super((T3<Boolean, Byte>) null,
              new T1((T3<Boolean, Byte>) null, new T2()));
    }
}
```

After decompiling the bytecode using JADX, the following code was generated:

```java
package defpackage;
/* renamed from: Demo1  reason: default package */
class Demo1 extends T1 {
    /* JADX WARN: Illegal instructions before constructor call */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public Demo1() {
        /*
            r3 = this;
            r0 = 0
            T3 r0 = (defpackage.T3) r0
            T1 r1 = new T1
            T2 r2 = new T2
            r2.<init>()
            r1.<init>(r0, r2)
            r3.<init>(r0, r1)
            return
        */
        throw new UnsupportedOperationException("Method not decompiled: defpackage.Demo1.<init>():void");
    }
}
```

JADX fails to decompile the code sample. I think it may be related to type cast expression in super constructor call. By the way, in my testing, the code example above cannot be further minimized.

I'm providing another example in hopes that it may be helpful:

```java
class T1<S> {
    public final S s1;
    public final S s2;

    public T1(S s1, S s2) {
        this.s1 = s1;
        this.s2 = s2;
    }
}

class T2 {}

class Demo<S extends T2> extends T1<S> {
    public Demo() {
        super((S) null, (S) null);
    }
}
```

After decompiling the bytecode using JADX, the following code was generated:

```java
package defpackage;

import defpackage.T2;
/* renamed from: Demo2  reason: default package */
class Demo2<S extends T2> extends T1<S> {
    /* JADX WARN: Illegal instructions before constructor call */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public Demo2() {
        /*
            r1 = this;
            r0 = 0
            T2 r0 = (defpackage.T2) r0
            r1.<init>(r0, r0)
            return
        */
        throw new UnsupportedOperationException("Method not decompiled: defpackage.Demo2.<init>():void");
    }
}
```

Would you please take a look at this? It is essential for me!
Thanks a lot!

Jadx version: 1.4.7.
Java version: 11.0.18.
D8 version: D8 2.1.7-r1 (build 4443fac8e25c38e6ecfb5a8b0d212a3fad6f7f63 from go/r8bot (luci-r8-ci-archive-0-ewc5)).

I also attach the source files and I hope they will be helpful: [demo.zip](https://github.com/skylot/jadx/files/11377057/demo.zip).

**Comment by skylot** [comment]
@xxh160 this is a same issue as in #1830
Now jadx don't duplicate instructions (const + cast) by default and result code:
```java
    public Demo() {
        S value = (S) null;
        super(value, value);
    }
```
will not compile, because java don't allow to have code before `super`. So jadx trying to fix that by moving super to method start which make code worse and next check just fail whole method :rofl:

I plan to add flag to allow duplication for such cases, but this task is slightly hard, so I postpone the fix.

**Comment by xxh160** [comment]
Thank you for your hard work! Looking forward to the fix!
