### ISSUE TITLE
Suggestion for a New Feature: Exporting Merged Dex Files

### ISSUE THREAD

**Issue by base64linqi** [skylot/jadx#1865]
Firstly, I want to express my gratitude for your excellent work. Jadx is an incredibly useful tool that has saved me considerable time in my development tasks.

I have noticed that Jadx is capable of parsing multiple dex files, which is indeed a useful function. However, I've found that when dealing with multiple dex files, there currently isn't a feature to merge them and export as a single, complete dex file.

I believe this feature would be immensely beneficial to many developers, especially those who handle and analyze a large number of dex files. With the ability to merge dex files, we could conduct more comprehensive code analyses and modifications with greater ease.

I understand that implementing new features may require substantial time and effort, but I feel the potential value of this functionality could well outweigh these investments. I would love to hear your thoughts on this suggestion, and I am willing to offer support where I can.

Once again, thank you for your outstanding work, and I look forward to your response.

Best regards

**Comment by jpstotz** [comment]
I not sure if this proposed feature fits into Jadx. To my knowledge Jadx does not provide a functionality to output dex files at all, but as Jadx changes pretty fast the last time this can be already outdated or I simply don't know this feature.

I also don't fully understand how dex merging would allow to "conduct more comprehensive code analyses" - do you really have a code analysis tool that can not handle multi-dex APK files? Even the good old dex2jar tool can as far as I know handle multi-dex APK files.

**Comment by skylot** [comment]
Hm, in most cases dex files splitted because of dex file format limitations, i.e. maximum method reference count is 65K. For such cases, it is impossible to merge these dex files into one.
For other cases, you can use [D8 utility](https://developer.android.com/tools/d8) (can merge several dex files) or manually arrange classes with smali.
So I think this feature is out of scope for jadx project.
