### ISSUE TITLE
jadx-gui code rendering issues

### ISSUE THREAD

**Issue by XuanLong18** [skylot/jadx#1867]
![image](https://github.com/skylot/jadx/assets/67423696/987297d4-4958-4daf-805f-f30624ee104d)
I often get like this on all versions of Jadx who can help me fix them. Please

**Comment by skylot** [comment]
@XuanLong18 try to use latest java version or release bundle with included java like [jadx-gui-1.4.7-with-jre-win.zip](https://github.com/skylot/jadx/releases/download/v1.4.7/jadx-gui-1.4.7-with-jre-win.zip).
If this not resolve this issue, please share your java version and OS.
