### ISSUE TITLE
[GUI]windows system can not start jadx

### ISSUE THREAD

**Issue by bhwxha** [skylot/jadx#1868]
Command line runs:`.\jadx-gui.bat`

Report an error:
```
输入行太长。
命令语法不正确。
```
```
The input line is too long.
Command syntax is incorrect.
```

It seems that if the folder path where jadx is located is longer, it will not be able to start jadx.

**Comment by jpstotz** [comment]
The start-up scripts are automatically generated by gradle, not sure why they use such a complicated way:

The command to execute Jadx used by `jadx-gui.bat` included the complete class path of all 51 JAR files used by Jadx. The same 51 Jar files are also included in the `Class-Path` in the file `MANIFEST.MF` of the main Jadx-gui jar file. 

In the end this means the way `jadx-gui.bat` is starting Jadx is more complex as necessary. It could simply be replaced by `java -jar jadx-gui-x.y.z.jar` and some additional options for Java.

We already do some search and replace in the Gradle `startScripts` task, however changing the execution fro classpath to a java -jar execution isn't something you want to do with search and replace, even with regex.

@bhwxha Is there a reason why you don't use the Jadx-gui.exe version which uses a launch4j based starter?

**Comment by bhwxha** [comment]
@jpstotz  Hi, since I don't know how to configure the size of memory that `Jadx-gui.exe` can use, I haven't used it before.

The file `jadx-gui.bat`, I just need to add `"-Xms1024M" "-Xmx32g"` to configure the size of memory that jadx can use.

Also,`jadx-gui.bat` worked fine on Windows systems before, but only recently this bug appeared, so feedback to see if the author can fix this bug?

**Comment by jpstotz** [comment]
@bhwxha How to change the heap size when using the Launch4J EXE launcher is documented in our FAQ section [out-of-memory-problems](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#out-of-memory-problems).

**Comment by bhwxha** [comment]
@jpstotz Thanks, I can now use `Jadx-gui.exe`.
But `jadx-gui.bat` doesn't start properly, still 1 bug.

**Comment by skylot** [comment]
I made a fix by using shadow jar, it was easy because shadow plugin support such integration with application plugin.
Hard was to force both cli and gui scripts to use one jar, so I use some regexp and file renames :rofl:
Can anyone check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master)? :slightly_smiling_face:

**Comment by QAQQL** [comment]
[中文整合]关于使用exe关联打开 的调整内存的方法
参考:  https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#out-of-memory-problems
在 `jadx-gui.exe` 的根目录下创建一个和你exe文件同名("jadx-gui")的 `jadx-gui.l4j.ini` 文件
并在里面填上DEFAULT_JVM_OPTS的参数,如下:
-Xms1024M
-Xmx32g

![图片](https://github.com/skylot/jadx/assets/51136763/707cc926-67d4-4bca-9398-aefa7fcd961d)
./
├─ jadx-gui.exe
└─ jadx-gui.l4j.ini
