### ISSUE TITLE
[feature] let me opt out from "renamed from" code comments in jadx-gui

### ISSUE THREAD

**Issue by Giszmo** [skylot/jadx#1872]
When working with obfuscated code, these "renamed from" comments are not helpful.

Arguably de-obfuscation made things worse already. No need to add more noise.

I'd prefer

```
public final class C5163f {
    public static final C5163f f13491c = new C5164a().mo14029a();

    private final Set<C5165b> f13492a;

    private final AbstractC6796c f13493b;

    public static final class C5164a {
        private final List<C5165b> f13494a = new ArrayList();
```

over

```
/* renamed from: k8.f */
public final class C5163f {

    /* renamed from: c */
    public static final C5163f f13491c = new C5164a().mo14029a();

    /* renamed from: a */
    private final Set<C5165b> f13492a;

    /* renamed from: b */
    private final AbstractC6796c f13493b;

    /* renamed from: k8.f$a */
    public static final class C5164a {

        /* renamed from: a */
        private final List<C5165b> f13494a = new ArrayList();
```

**Comment by jpstotz** [comment]
Have you disabled all entries in Jadx Preferences `Rename Identifiers` section?

**Comment by Giszmo** [comment]
I don't mind the renaming. I mind the comment about it.

![Screenshot from 2023-05-16 21-38-53](https://github.com/skylot/jadx/assets/96378/55a76050-66ac-4c49-a43d-2dcb08f514db)

Last in Decompilation section is "Don't decode resources". I see no "Code comments level", "renamed", "warn" or "info"
