### ISSUE TITLE
[feature] Support decompiling Flutter apps

### ISSUE THREAD

**Issue by Giszmo** [skylot/jadx#1873]
I'm coming across more and more obfuscated Flutter apps and jadx provides no insight into the business logic. Strings rendered on screen are not found anywhere in jadx-gui.

Edit: [This 2 years old article](https://blog.tst.sh/reverse-engineering-flutter-apps-part-2/#conclusion) suggests this feature would be quite hard but maybe there is a compromise that's doable. Not decompile to Dart but to Assembly. Extract strings. Something.

**Comment by skylot** [comment]
I think for Flutter it is better to use tools for native dissembler/decompiler like IDA or JEB.
And I don't want to implement that in jadx, it is too much of work, sorry :slightly_frowning_face:
