### ISSUE TITLE
[core]Rename method to prohibit jadx errors

### ISSUE THREAD

**Issue by bhwxha** [skylot/jadx#1876]
link: https://drive.google.com/file/d/1EYP3KNNmSez3SNjFjX7Qe4kdl8kCmi4V/view?usp=sharing

As in the picture, jadx wrongly changes the method name to `showVersionInfo`, how to prohibit it from renaming incorrectly?

![image](https://github.com/skylot/jadx/assets/107301547/211f663c-4e87-4bcf-a75c-d730fa7023a7)

![image](https://github.com/skylot/jadx/assets/107301547/e1855d86-fe5a-42de-978d-c3e23182cb53)

**Comment by skylot** [comment]
This is a feature to remove synthetic bridge methods by "merging" with wrapped method.
This can be disabled by `Inline methods` option (if checkbox missing, please use latest unstable build :sweat_smile:)
I also commit an additional rename reason: `/* merged with bridge method [inline-methods] */`
And if debug code comments are enabled, merged methods signatures will be shown:
```
    /* JADX DEBUG: Method merged with bridge method: showVersionInfo(Lcom/nomagic/b/ag;)Z */
    /* JADX DEBUG: Method merged with bridge method: showVersionInfo(Lcom/nomagic/rcpf/product/lic/ProductVersion;)Z */
```
Hope this makes it easier to understand why method was renamed and what option control it.

Related issues #1109 and #1170.
