### ISSUE TITLE
[gui] `Rename` entry in tree context menu bypasses enabled check

### ISSUE THREAD

**Issue by NebelNidas** [skylot/jadx#1890]
When right-clicking a renamable element in the code area, `jadx.gui.ui.codearea.RenameAction#isActionEnabled` gets checked, and if the return value is `false`, the corresponding context menu entry gets greyed out.
However, renaming can also be done via the tree context menu, and here the above mentioned check doesn't happen, thus allowing the user to rename elements that shouldn't be.

**Comment by skylot** [comment]
Fixed, I hope, because I didn't find test cases to check :rofl:
