### ISSUE TITLE
Author abandoned the project?

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#190]
Hello, I don't see any new commits within almost a year. So is author no more supporting his project? If yes, are there any forks of jadx which are fixing reported bugs and improving the development?

**Comment by liupeng110** [comment]
同求，有没有api文档之类 或者其他人fork 过后，添加扩展的

**Comment by enovella** [comment]
Anyone can ensure this information? @skylot

**Comment by matejdro** [comment]
Check out pull request, there are some bug fixes in other repos. But there is no one big repo that contains all of them combined.

**Comment by enovella** [comment]
Hi @matejdro ,
Could you point in here such repos?

**Comment by enovella** [comment]
Yeah, it would be nice to clone the repo and add all the PRs one by one to see if they can be merged in a non-official way.

**Comment by dannyZhou** [comment]
> Yeah, it would be nice to clone the repo and add all the PRs one by one to see if they can be merged in a non-official way at least.

Is there anyone want to do this?

I think this project is important.

**Comment by sergey-wowwow** [comment]
I created a fork of this (https://github.com/sergey-wowwow/jadx), and will begin support of the project after these holidays. If anybody wants to contribute too, please reply and I will add you

**Comment by skylot** [comment]
@sergey-wowwow this is great! )
I can add you as collaborator so you can support this project without forking
or even transfer ownership to you if collaborator permissions is not enouth (please check [this](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account))
What you think?

**Comment by sergey-wowwow** [comment]
Hi, @skylot 
I think this is cool, collaborator access would be enough. I had plans to firstly fix all security issues I found (because I will use jadx on server side in the nearest future, so they are the most important)

**Comment by dgulak** [comment]
Looks like promising news

**Comment by dannyZhou** [comment]
GOOOOOOD!!!!!  @All_Of_Developers Thank you very much.

**Comment by smarek** [comment]
@skylot cool, wouldn't mind to become one too, jadx is great project!

**Comment by enovella** [comment]
The most important thing to do at this moment is to review the pull requests and attempt to merge them one by one.
