### ISSUE TITLE
[core] Decompilation error without exception/warning (string replaced with r2)

### ISSUE THREAD

**Issue by Iscle** [skylot/jadx#1901]
When attempting to decompile a .dex file, a specific method did not get decompiled correctly in the "Code" tab, but does have the correct code in the "Smali" tab. Jadx did not throw any error or warning, so I assume this is an edge case.

The method is: fpg.go.pl.love.SDK.simple
![7UTafWwZSvw7wvJ](https://github.com/skylot/jadx/assets/8018823/bb147c70-9377-441f-a258-53898266ca9b)
![6gJnuzaqooJWC45](https://github.com/skylot/jadx/assets/8018823/b0c032aa-ffbe-4895-83f4-eceb0cfed2af)

File (replace .zip with .dex):
[stud.zip](https://github.com/skylot/jadx/files/11688634/stud.zip)

Regards,
Iscle

**Comment by Iscle** [comment]
Just noticed, in line 45 the same issue happened, but with r3, in the "loadClass" call.

**Comment by skylot** [comment]
@Iscle thanks!
Looks like an issue in propagating external variables after anonymous class inline.
As a workaround, you can disable `Inline anonymous classes` option in preferences.

**Comment by skylot** [comment]
Fixed.
Hope this commit will not introduce any regressions, because fix become unexpectedly complicated :slightly_frowning_face:
