### ISSUE TITLE
[core][regression] app/src/main/res/values/public.xml starts with a line-break

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#1907]
I would like to report a regression introduced by e9a7ccd. This commit readds an initial line-break in app/src/main/res/values/public.xml. Removing the first empty line should be allowed for xml resources.

Steps to reproduce:
Export sources of https://github.com/ds10git/tvbrowserandroid/releases/download/release_0.7.0.8/TV-Browser-v0.7.0.8.apk as gradle project and try to rebuild.

`> Task :app:mergeDebugResources FAILED
ERROR:app/src/main/res/values/public.xml:2:6: Resource and asset merger: The processing instruction target matching "[xX][mM][lL]" is not allowed.
    org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.`

If this regression is fixed, I can provide a PR to fix the last remaining resource issue of this apk.

**Comment by skylot** [comment]
Fixed :slightly_smiling_face:
Is this the only resource with such an issue?

**Comment by nitram84** [comment]
Thank you for this fix! You're right, it was only this file. I'll close this issue.
