### ISSUE TITLE
[feature] How can I use okhttp3 in jadx-script? 

### ISSUE THREAD

**Issue by jygzyc** [skylot/jadx#1912]
Dear skylot, I have noticed that **jadx** has introduced scripts to handle some special cases, such as script `replace_method_call.jadx.kts`. Now I want to write a script to request the server for decryption, but this requires introducing the `okhttp` library for communication. Is there any solution available? Thank you.
Here are my example script:
```kotlin
@file:DependsOn("com.squareup.okhttp3:okhttp:4.11.0")
import com.squareup.okhttp.MediaType.Companion.toMediaType
import com.squareup.okhttp.OkHttpClient
import com.squareup.okhttp.Request
import com.squareup.okhttp.RequestBody.Companion.toRequestBody
import okhttp3.Response
import jadx.core.dex.instructions.ConstStringNode
import jadx.core.dex.instructions.InvokeNode
import jadx.core.dex.instructions.args.InsnArg
import jadx.core.dex.instructions.args.InsnWrapArg
import jadx.core.dex.instructions.args.RegisterArg

val jadx = getJadxInstance()

val mthSignature = "com.android.extensions.ilililii(Ljava/lang/String;)Ljava/lang/String"

jadx.replace.insns { mth, insn ->
	if (insn is InvokeNode && insn.callMth.rawFullId == mthSignature) {
		val str = getConstStr(insn.getArg(0))
		if (str != null) {
			val resultStr = decrypt(mthSignature, str)
			log.info { "Decrypt '$str' to '$resultStr' in $mth" }
			return@insns ConstStringNode(resultStr)
		}
	}
	null
}

fun getConstStr(arg: InsnArg): String? {
	val insn = when (arg) {
		is InsnWrapArg -> arg.wrapInsn
		is RegisterArg -> arg.assignInsn
		else -> null
	}
	if (insn is ConstStringNode) {
		return insn.string
	}
	return null
}

fun decrypt(mthSignature: String, param: String): String?{
	val client = OkHttpClient()
    val json = """
        {
            "${mthSignature}": "${param}"
        }
    """.trimIndent()

	val requestBody = json.toRequestBody("application/json; charset=utf-8".toMediaType())

	val request = Request.Builder()
        .url("http://127.0.0.1:5000/decrypt")
        .post(requestBody)
        .build()

    val response = client.newCall(request).execute()
	return response.body?.string().toString()
}
```

**Comment by jygzyc** [comment]
When I run the deobf2.jadx.kts script, I also encountered a similar issue: 
```
WARN : Script execution issue: File 'com.github.javafaker:javafaker:1.0.2' not found (deobf2.jadx.kts:2:1)
WARN : Script execution issue: ArtifactResolutionException: Could not transfer artifact com.github.javafaker:javafaker:pom:1.0.2 from/to maven central (https://repo.maven.apache.org/maven2/): Cannot access https://repo.maven.apache.org/maven2/ with type default using the available connector factories: BasicRepositoryConnectorFactory (deobf2.jadx.kts:2:1)
ERROR: Script execution failed: deobf2
ERROR: Unresolved reference: DependsOn (deobf2.jadx.kts:2:7)
ERROR: Unresolved reference: javafaker (deobf2.jadx.kts:4:19)
ERROR: Unresolved reference: Faker (deobf2.jadx.kts:14:13)
```
May I ask if there is any problem with introducing the library?

**Comment by skylot** [comment]
Well, you use correct way to add library and this code and imports should work:
```java
@file:DependsOn("com.squareup.okhttp3:okhttp:4.11.0")

import jadx.core.dex.instructions.ConstStringNode
import jadx.core.dex.instructions.InvokeNode
import jadx.core.dex.instructions.args.InsnArg
import jadx.core.dex.instructions.args.InsnWrapArg
import jadx.core.dex.instructions.args.RegisterArg
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody

val jadx = getJadxInstance()
...
```

But, using run button in UI not work now because of incorrectly configured checks.
So if you use reload toolbar button, the script will execute (at least for me, it actually tries to send the request).

I will make a quick workaround shortly :slightly_smiling_face:

**Comment by skylot** [comment]
> Script execution issue: ArtifactResolutionException: Could not transfer artifact com.github.javafaker:javafaker:pom:1.0.2 from/to maven central (https://repo.maven.apache.org/maven2/): Cannot access https://repo.maven.apache.org/maven2/

This looks like a network issue, maybe it is temporary.

**Comment by skylot** [comment]
Ok, I commit workaround, so "Run" button will skip faulty checks for now ("Check" button still report issues)

**Comment by jygzyc** [comment]
Thank you.  And I can access the `https://repo.maven.apache.org/maven2/` with the Internet browser. Hmm... anyway, I will try again.

**Comment by jygzyc** [comment]
> > Script execution issue: ArtifactResolutionException: Could not transfer artifact com.github.javafaker:javafaker:pom:1.0.2 from/to maven central (https://repo.maven.apache.org/maven2/): Cannot access https://repo.maven.apache.org/maven2/
> 
> This looks like a network issue, maybe it is temporary.

I'm sorry, but I have been having this issue consistently. To resolve this problem, I tried adding `implementation("com.squareup.okhttp3:okhttp:4.11.0")` in `jadx-plugins/jadx-script/examples/build.gradle.kts`, but it didn't have any actual effect. Is there a way to make `jadx` use locally downloaded **JAR** library files during the load time or are there any other localized solutions available? @skylot

**Comment by jygzyc** [comment]
> 
I tried two ways to access it. One way is that I can access https://repo.maven.apache.org/maven2/ normally without a proxy, the other way is that I can also access it with the proxy enabled. Meanwhile, I used the ping command to confirm if the network was working properly, and the result seemed fine. Anyway, I will try it locally first.
```bash
Pinging maven.map.fastly.net [2a04:4e42:1a::215] with 32 bytes of data:
Reply from 2a04:4e42:1a::215: time=110ms
Reply from 2a04:4e42:1a::215: time=109ms
Reply from 2a04:4e42:1a::215: time=99ms
Reply from 2a04:4e42:1a::215: time=211ms

Ping statistics for 2a04:4e42:1a::215:
Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
Minimum = 99ms, Maximum = 211ms, Average = 132ms
```

**Comment by jygzyc** [comment]
> > Is there a way to make jadx use locally downloaded JAR library files
> 
> You can specify full path to jar file, for `okhttp` however it will require to add all its dependencies, so it will look like:
> 
> ```kotlin
> @file:DependsOn("/home/skylot/okio-jvm-3.2.0.jar")
> @file:DependsOn("/home/skylot/okio-3.2.0.jar")
> @file:DependsOn("/home/skylot/okhttp-4.11.0.jar")
> ```
> 
> links: https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/4.11.0/okhttp-4.11.0.jar https://repo1.maven.org/maven2/com/squareup/okio/okio/3.2.0/okio-3.2.0.jar https://repo1.maven.org/maven2/com/squareup/okio/okio-jvm/3.2.0/okio-jvm-3.2.0.jar
> 
> Anyway, I am still curious why normal dependency don't work for you? Do you use any VPN or proxy to access internet?

**Comment by skylot** [comment]
Ok, I commit a better workaround :rofl:
Checks will run compile instead analyze for scripts with dependencies.
Although code complete will not work for classes from dependencies, I will open a separate issue for that.
