### ISSUE TITLE
Is it possible to compile back to apk  ?

### ISSUE THREAD

**Issue by ranshalit** [skylot/jadx#192]
Hello,

Is it possible to compile to code back to apk and install the apk back in android studio ? 
Can you please give some hints how this should be done ? Does it require to sign the apk too ?
I have tried with a simple helloworld.apk (https://apkpure.com/helloworld/my.v1rtyoz.helloworld) to save both as gradle and not as gradle, and to open it in android studio, yet it failed with many errors.

Thanks for any idea,

**Comment by mingyuan-xia** [comment]
1. the current decompilation is not perfect and there could be missing imports, wrong conditional branches that fail Android Studio.
2. If the above is addressed to a certain extent and your APK is simple enough to be "fully" decompiled, you might still have problem with generated sources (R.java) and related refs. Consider a `findViewById(123)` how could a decompiler knows 123 is one of the values from R. Thus if Android Studio decides to regen an R, the ref will be broken.
3. Yes, you are right, sign the APK. But this should be taken care of by the IDE.

**Comment by victorchoy** [comment]
@mingyuan-xia   Hi,  How jadx can work out the original class name?  Could you explain it ? Thanks

**Comment by mingyuan-xia** [comment]
take a close look at the dex file. No magic here
