### ISSUE TITLE
[gui][unstable] Cache reset and decompilation on each file opening

### ISSUE THREAD

**Issue by psolyca** [skylot/jadx#1929]
With the unstable 1.4.7.180-1426a7b, opening a file takes time with the GUI.

Project seems to be saved correctly (main window is backed up).
BTW when I open the project again, cache is reset and decompilation is done another time.

It was not the case with the 1.4.7.

**Comment by skylot** [comment]
Oops, forgot to remove that line :smiling_face_with_tear:
Fixed, regression since a72e6ae.
@psolyca thanks for report! :+1:
