### ISSUE TITLE
[feature] Customized features.

### ISSUE THREAD

**Issue by USTCerirl** [skylot/jadx#1936]
First, Thank you for your selfishless work! which is one of the greatest tools I ve ever used.

But, I wanna add some customized features such as "ONETAP to frida" with scripts. so, could you please add a feature of plugin just like ida?

We d appreciate it if you can take your precious time :)

**Comment by jpstotz** [comment]
Can you please describe in detail how a feature "ONETAP to frida" should work?

**Comment by USTCerirl** [comment]
> Can you please describe in detail how a feature "ONETAP to frida" should work?

It's just an example. For me personal, I like to pack some complex operations together into a simple way.

 For "ONETAP to frida", when I select a function, I will right-click and choose "ONETAP to frida", it asks me "spawn" or "attach", "positive hook" or "negative hook", "native hook" or "non-native", "attach" or "replace" with Interceptor etc......

Even I could add a openai plugin for GPT to help me analyze.

ps: I 'm just a beginner of AndroidRE rn, there're many stuffs I havent learnt yet, I can't complie the jadx src by myself yet. so, plz be kind;)

**Comment by skylot** [comment]
@USTCerirl if you request a scripting or plugins support... it is already in master, and you can try it in [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).
For scripting support, check [this page](https://github.com/skylot/jadx/tree/master/jadx-plugins/jadx-script#readme) and use [custom_frida.jadx.kts](https://github.com/skylot/jadx/blob/master/jadx-plugins/jadx-script/examples/scripts/gui/custom_frida.jadx.kts) as template.
For example of jadx plugin, use [this repo](https://github.com/jadx-decompiler/jadx-example-plugin).

**Comment by USTCerirl** [comment]
Oh, I see. Gonna try tomorrow, thank you so much!
