### ISSUE TITLE
[feature] Option to set cache location

### ISSUE THREAD

**Issue by Yehh22** [skylot/jadx#1941]
*Describe your idea:*
When catching code as disk/disk with cache, it creates a folder besides the input file. I don't want that, it messes my directory and I have to delete it everytime. Sure, I can cache in memory only but I want to cache in disk. Can you please add an option to set cache location so I can have it saved somewhere else, or at least cache in %TEMP%?

**Comment by skylot** [comment]
Done.
I added these options for cache locations:
- use common system app cache (default)
- use same directory as project file (previous behavior)
- use custom directory

Also, I add a view for all known cache directory with its disk usage (press 'Calculate usage') and option to remove.
So cache preferences now looks like this:
![screenshot_2023-07-17-011040](https://github.com/skylot/jadx/assets/118523/ee174d8f-6366-4ace-aad2-be017b440f57)

Please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master) and share your thoughts/bugs :slightly_smiling_face:
