### ISSUE TITLE
[core] Stuck on decompiling and memory leak

### ISSUE THREAD

**Issue by Yehh22** [skylot/jadx#1942]
**Describe error**
I discovered an APK that caused Jadx to get stuck on decompiling and causes huge memory leaks. When closing Jadx, it just freezes while still leaking memory. I must end the process from Task manager. Tried both stable 1.4.7 and unstable 1.4.7.189-3e4c6a9c
I'm using WIndows 11 2h22 with JDK 20.0.1

![image](https://github.com/skylot/jadx/assets/127546925/e43ab4ca-2591-48c7-a28a-c5d00c6feb93)

APK link: https://mega.nz/file/bJBz1BrZ#6uWDMVzMKLdeyreak4C5KApHXMU8iOmc4xtpynwrOHM

**Comment by skylot** [comment]
Fixed. Cause was an endless loop in classes 'super' loop, like: A extends B and B extends A.
