### ISSUE TITLE
[feature] Option to configure indentation

### ISSUE THREAD

**Issue by NebelNidas** [skylot/jadx#1945]
Currently, indentation is [hardcoded to four spaces](https://github.com/skylot/jadx/blob/3e4c6a9c51ca937c1c13cedbeab81c614ebfb182/jadx-core/src/main/java/jadx/api/ICodeWriter.java#L12). I'd prefer this to be configurable (so I can use tabs instead for example).

**Comment by skylot** [comment]
Done, now it is possible to set indent string in JadxArgs:
```java
args.setCodeIndentStr("\t");
```
