### ISSUE TITLE
[feature][plugins] Provide a way to access JNode list and codeJump

### ISSUE THREAD

**Issue by Areizen** [skylot/jadx#1946]
Currently the `JadxGuiContext` methods do not contain a proper way to interact with the code generated.
It would be nice to have a way to interact with the interface, to do basic things like `codeJump` and get `JNode` list.

**Comment by skylot** [comment]
@Areizen code jump was added in PR #1903.

> get JNode list

How you plan to use such list?
Actually, I don't plan to expose JNode classes, because there are already too many classes and interfaces to represent nodes like: ICodeNodeRef, ClassNode, JavaClass, etc. So adding yet another will be very confusing :slightly_smiling_face:

**Comment by Areizen** [comment]
Seems like this PR solve it for scripting, but I'm trying to do the equivalent when creating a plugin (https://github.com/jadx-decompiler/jadx-example-plugin), but maybe i'm missing something.

Before plugin, I used the following code to jump to a java class : 
```java
JavaClass element = ...;
JNode node = mainWindow.getCacheObject().getNodeCache().makeFrom(element);
if (node instanceof JResSearchNode) {
	JumpPosition jmpPos = new JumpPosition(((JResSearchNode) node).getResNode(), node.getPos());
	tabbedPane.codeJump(jmpPos);
} else {
	tabbedPane.codeJump(node);
}					
```
this is why I needed access to JNode :)

**Comment by skylot** [comment]
Ok, looks like I forget to update artifacts shapshot :(
After project reload, you should be able to see these new methods from PR.

If you want to open `JavaClass` type just use `guiContext.open(javaClass.getCodeNodeRef());`
Here example how to add global menu (i.e. `Plugins`) and open 'first' class (put code in plugin init method):
```java
JadxGuiContext guiContext = context.getGuiContext();
if (guiContext != null) {
	guiContext.addMenuAction("Open first class", () -> {
		JavaClass javaClass = context.getDecompiler().getClasses().get(0);
		guiContext.open(javaClass.getCodeNodeRef());
	});
}
```

**Comment by Areizen** [comment]
thank you :)
