### ISSUE TITLE
jadx crasing while decompilling on 94%

### ISSUE THREAD

**Issue by HiguP** [skylot/jadx#195]
Hello. I've got problem with decompiling .apk file. Jadx is crashing on 94% and the only way to close it is killing a process in Task Manager. 
Java version: 1.8.0_151
I've got installed JDK and JRE, both the same version (1.8.0_151)

**Comment by sergey-wowwow** [comment]
Could you please attach the apk file?

**Comment by HiguP** [comment]
It's crashing on all apk files, but on some files it's crashing on 98%

**Comment by HiguP** [comment]
Should I install other version of java?

**Comment by skylot** [comment]
1. Did you try to increase java maximum heap size? [Check here](https://github.com/skylot/jadx#out-of-memory-error)
2. Did you see any exception in log? (To get log run jadx from command line)
 Can you post it here?

**Comment by HiguP** [comment]
I deleted java and then installed older version, now it is 1.8.0_144 and after that I've increased java maximum heap size in .bat files and now it's running perfectly. Thanks for help.
