### ISSUE TITLE
[feature] Add soft-wrap to code area

### ISSUE THREAD

**Issue by Fi5t** [skylot/jadx#1958]
It would be nice to have an ability to add soft-wrap to code area. Unfortunately, I haven't found this ability in the appearance menu.

`AndroidManifest.xml` without wraps
<img width="1519" alt="image" src="https://github.com/skylot/jadx/assets/3126033/d1424058-33bb-4fe4-9c4a-faa04ee91ade">

`AndroidManifest.xml` with wraps
<img width="1497" alt="image" src="https://github.com/skylot/jadx/assets/3126033/42a09b33-7edb-4b74-9fe2-6e3a63a532d6">

It looks much more convenient and understandably from my point of view 🌚

Moreover. It's quite easy to implement:
```java:highlight={2}
public final class CodeArea extends AbstractCodeArea {
        ...
	CodeArea(ContentPanel contentPanel, JNode node) {
		super(contentPanel, node);
                ...
                // Add these lines
		setLineWrap(true);
		setWrapStyleWord(true);
```
Of course, this solution is terribly "straightforward". I think this can be implemented as a menu item or something else.

**Comment by jpstotz** [comment]
The context menu of the code area has "Line Wrap" which can enable/disable. Is this what you are looking for?
