### ISSUE TITLE
Cannot edit the code

### ISSUE THREAD

**Issue by 2575044704** [skylot/jadx#1959]
why?

**Comment by jpstotz** [comment]
What edits do you want to apply? In Jadx-GUI you can rename methods, classes, and so on. 

Please keep in mind that Jadx is a decompilation tool  not a development IDE.

**Comment by skylot** [comment]
Edit java code is pointless because in most case it is not possible to recompile app.
But if you really want to, you can export as gradle project, open it in your IDE and edit/fix as you want.

Although, editing smali code is may be useful and such issue already opened (#1537)
