### ISSUE TITLE
[GUI][bug?] Fix horizontal scrolling on touchpad

### ISSUE THREAD

**Issue by Mino260806** [skylot/jadx#1960]
Currently, when I scroll horizontally on my laptop touchpad (swipe horizontally with 2 fingers), the GUI switches to the previous tab. I always do it unconsciously and it frustrates me every time because it messes everything I'm doing.

Can you fix it so it actually scrolls horizontally in the current tab ?

**Comment by skylot** [comment]
Sorry, but I can't reproduce this issue because I don't have a laptop and/or touchpad :sob:
So I hope some else can provide fix and PR for this issue.

**Comment by jpstotz** [comment]
I have an HP notebook on Win10 which supports two-finger scrolling in vertical and horizontal direction. But in Jadx only vertical scrolling is active. I can not switch between tabs.

@Mino260806 What OS do you use and what touchpad [driver] is installed?

**Comment by Mino260806** [comment]
I have a HP Laptop (15-dw3xxxx). I dual boot Windows 10 and Linux Mint 21.1. Here are my observations after further testing:
- Windows 10: horizontal scrolling works as expected
   - Horizontal scrolling in text region scrolls the text horizontally
   - Horizontal scrolling in tabs region returns to the previous tab
- Linux Mint 21.1 
   - Horizontal scrolling **anywhere** (text region, left panel, toolbar, menu, litterally the entire screen except the title bar) returns to previous tab.
   - Please note that horizontal scrolling works in other apps (chrome, text editor...), so the problem is specific to jadx gui and not to the driver or hardware

### Driver Details
Shell `xinput list-props 11`
```
amin@Laptop-HP:~$ xinput list-props 11
Device 'ELAN0709:00 04F3:30A0 Touchpad':
	Device Enabled (189):	1
	Coordinate Transformation Matrix (191):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Tapping Enabled (349):	1
	libinput Tapping Enabled Default (350):	0
	libinput Tapping Drag Enabled (351):	1
	libinput Tapping Drag Enabled Default (352):	1
	libinput Tapping Drag Lock Enabled (353):	0
	libinput Tapping Drag Lock Enabled Default (354):	0
	libinput Tapping Button Mapping Enabled (355):	1, 0
	libinput Tapping Button Mapping Default (356):	1, 0
	libinput Natural Scrolling Enabled (328):	1
	libinput Natural Scrolling Enabled Default (329):	0
	libinput Disable While Typing Enabled (357):	1
	libinput Disable While Typing Enabled Default (358):	1
	libinput Scroll Methods Available (330):	1, 1, 0
	libinput Scroll Method Enabled (331):	1, 0, 0
	libinput Scroll Method Enabled Default (332):	1, 0, 0
	libinput Accel Speed (337):	0.000000
	libinput Accel Speed Default (338):	0.000000
	libinput Accel Profiles Available (339):	1, 1
	libinput Accel Profile Enabled (340):	1, 0
	libinput Accel Profile Enabled Default (341):	1, 0
	libinput Left Handed Enabled (342):	0
	libinput Left Handed Enabled Default (343):	0
	libinput Send Events Modes Available (313):	1, 1
	libinput Send Events Mode Enabled (314):	0, 0
	libinput Send Events Mode Enabled Default (315):	0, 0
	Device Node (316):	"/dev/input/event5"
	Device Product ID (317):	1267, 12448
	libinput Drag Lock Buttons (344):	<no items>
	libinput Horizontal Scroll Enabled (345):	1
	libinput Scrolling Pixel Distance (346):	15
	libinput Scrolling Pixel Distance Default (347):	15
	libinput High Resolution Wheel Scroll Enabled (348):	1
```

**Comment by Mino260806** [comment]
Closing this issue because it's a duplicate of #1718
> If I use the horizontal scroll wheel to scroll right or left with the mouse cursor over the code window - jadx-gui does not scroll the code window but reacts as if I pressed the "forward"/"back" mouse buttons (back for left-to-right scroll, forward for right-to-left scroll).
