### ISSUE TITLE
[GUI] Source tree: empty package shown as <html><body><nobr>...

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#1961]
There seems to be a small visual problem with JPackage nodes in the source tree if the package name is an empty string.

In such a case `PACKAGE_DEFAULT_HTML_STR` is returned which contains the string `<html><body><nobr><span style='color:#888888;'>&lt;empty&gt;</span></nobr></body></html>`. 
![image](https://github.com/skylot/jadx/assets/924885/15d57bd7-4598-4763-aace-958310fbf41b)

But the html content is not displayed because `disableHtml()` returns `true` for `JPackage` instances. 

To me it seems like the definition of `PACKAGE_DEFAULT_HTML_STR` - which is really a nice engineering work ;) - is a bit too complicated, if I understand correctly how the tree model works...

```
public static final String PACKAGE_DEFAULT_HTML_STR = wrapHtml(fadeHtml(escapeHtml("<empty>")));
```

**Comment by skylot** [comment]
@jpstotz I commit a fix. Not the best solution, but it should work :slightly_smiling_face:
