### ISSUE TITLE
[feature] Add export dialog with options

### ISSUE THREAD

**Issue by skylot** [skylot/jadx#1983]
It will be nice to have a single export dialog with options:
- export as a Gradle project
- don't save classes from excluded packages
- don't save resources
- maybe others

Now excluded packages not applied, and other options only available in preferences dialog.
Also, current name `Save All` not clear and can interfere with saving project actions, so it is better to rename it to `Export`.

Original discussion started in https://github.com/skylot/jadx/issues/1085#issuecomment-770338533

**Comment by MrIkso** [comment]
@skylot hi, currently im implementing feature. Could this be?
![image](https://github.com/user-attachments/assets/cc1ccf8b-da45-471d-948c-09a0cc9eb2be)

**Comment by skylot** [comment]
@MrIkso sure! Looks good :slightly_smiling_face:
