### ISSUE TITLE
[feature] Disable the automatic reset of appearance settings.

### ISSUE THREAD

**Issue by geordo** [skylot/jadx#1985]
I'm using `jadx-gui-1.4.7-with-jre-win`. Whenever I restart `jadx`, my appearance settings like theme and font get automatically reset. Do you know how I can turn this off?

![](https://i.ibb.co/tK9try2/Screenshot-2023-08-10-012613.png)

**Comment by geordo** [comment]
> @geordo can you check log viewer for errors after jade open? It might be caused by settings load/parsing.

Sorry, I am late in replying. This is a log viewer.

![](https://i.ibb.co/QH1k8Yd/Screenshot-2023-08-16-080125.png)

**Comment by jpstotz** [comment]
@geordo Thanks, but I think skylot was asking for the log from a start when your appearance settings are reset. Only on such a Jadx run there may be log entries regarding appearance settings reset. If your appearance settings had been reverted some time ago you won't find anything in the log.
