### ISSUE TITLE
[feature] GPU has been used 99% by jadx-gui-1.4.7

### ISSUE THREAD

**Issue by legend-zl** [skylot/jadx#1986]
*Describe your idea:*
How to solve the problem
GPU has been used 99% by jadx-gui-1.4.7

<img width="1297" alt="573046226b5ccc244e47590a0d2c33e" src="https://github.com/skylot/jadx/assets/7513310/4379a1a1-11f8-49c4-8649-28430e9d16d4">
<img width="386" alt="dc7e4513e4c368d7f84050c7e0bab50" src="https://github.com/skylot/jadx/assets/7513310/6e6e9649-2091-4ad1-aca5-9b767e3f2320">

**Comment by jpstotz** [comment]
Does this happen reproducible? Because Jadx does not make use of GPU directly (may be the Java UI rendering makes use of it). GPU can also be used by background apps, so it may be just coincidence. What Java runtime (exact version and who provides the JDK) do you use?

**Comment by skylot** [comment]
Maybe related to #2030, check for suggested workarounds.
