### ISSUE TITLE
[feature] A way to copy config directly to JADX

### ISSUE THREAD

**Issue by krizzsk** [skylot/jadx#1989]
### Describe your idea

Introduce a new feature that enables users to directly copy any custom configurations to JADX. This feature would streamline the process of setting up JADX with the necessary configuration options, making it more convenient for users to quickly start analyzing their Android applications.

**Comment by jpstotz** [comment]
Latest unstable version saves all configuration data as JSON files in a directory structure in user home directory (e.g. on Windows `%APPDATA%\skylot\jadx\config`). 

This allows copying Jadx settings to a new computer in a few seconds. Is this what this feature request is about?

**Comment by krizzsk** [comment]
Yes!! It was. Thank you!!
