### ISSUE TITLE
[gui] Weird Behaviour on hover

### ISSUE THREAD

**Issue by RealYukiSan** [skylot/jadx#1993]
### Issue details

when I browse the decompiled project, an unexpected popup keeps appearing:
![image](https://github.com/skylot/jadx/assets/126035476/56a0272e-2568-4880-9e43-b4f528bc10c9)

### Jadx version

1.4.7

### Java version

20.0.2

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by Reyuki-san** [comment]
Restarting the jadx-gui solved this issue, but I'm still wondering what's actually happened.

**Comment by Reyuki-san** [comment]
![image](https://github.com/skylot/jadx/assets/126035476/778e4ada-1004-473c-9067-0d63fffbefd9)

It's a little bit annoying when I need to restart frequently when this bug appears :(
@skylot any suggestion?

**Comment by skylot** [comment]
@Reyuki-san it looks like tooltip rendering issue. There are several similar reports (#1401, #1867), but I still not sure what causing it and how to fix this. Also, I can't reproduce it :sob:

I can suggest trying to check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master) (both with bundled jre and without).
Maybe issue was in FlatLaf lib and was fixed already, also might worth trying switching to `default` theme.

As a last resort, I can add an option to disable tooltips in code area to check if it was a cause.

**Comment by Reyuki-san** [comment]
Thanks for the response, I will try your advice if the bug shows up again and give the feedback
unfortunately now the bug occurs infrequently, so at this time I did not change the jadx version or try to decompile another apk.

**Comment by kotori2** [comment]
I think it's a Java issue rather than Jadx. I can reproduce this glitch on many Java desktop applications (BurpSuite etc.). This issue can be triggered if you are using a high-end monitor (4K resolution with 200% scaling). 
I found this solution from BurpSuite community, and it does solve the issue for Jadx:
Simply append `"-Dsun.java2d.noddraw=true" "-Dsun.java2d.d3d=false" "-Dswing.useflipBufferStrategy=True" "-Dsun.java2d.ddforcevram=true" "-Dsun.java2d.ddblit=false"` to the end of `set DEFAULT_JVM_OPTS=` in `jadx-gui.bat`.

**Comment by SiboVG** [comment]
> I think it's a Java issue rather than Jadx. I can reproduce this glitch on many Java desktop applications (BurpSuite etc.). This issue can be triggered if you are using a high-end monitor (4K resolution with 200% scaling). I found this solution from BurpSuite community, and it does solve the issue for Jadx: Simply append `"-Dsun.java2d.noddraw=true" "-Dsun.java2d.d3d=false" "-Dswing.useflipBufferStrategy=True" "-Dsun.java2d.ddforcevram=true" "-Dsun.java2d.ddblit=false"` to the end of `set DEFAULT_JVM_OPTS=` in `jadx-gui.bat`.

Oh man, this comment solved this very annoying and long-standing window ghosting bug in our program [openrocket](https://github.com/openrocket/openrocket). Thank you!
