### ISSUE TITLE
[gui] Bug with Zoom-In Feature

### ISSUE THREAD

**Issue by meiraxx** [skylot/jadx#1994]
### Issue details

I am unable to use `CTRL +`, `CMD +`, `CTRL Mouse Wheel Up/Down` or `CMD Mouse Wheel Up/Down`.

Only `CMD -` worked to zoom out, and there is no way to zoom back in.

Relates to https://github.com/skylot/jadx/issues/1403

Setup:
- `JADX 1.4.7` (brew install jadx)
- `MacOS 13.4.1`

### Jadx version

1.4.7

### Java version

11.0.13

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by jpstotz** [comment]
Please test the latest unstable version https://nightly.link/skylot/jadx/workflows/build-artifacts/master

In this version key bindings are configurable.

**Comment by meiraxx** [comment]
The test with that unstable version is also unsuccessful. Out of the box, only `Cmd -` works to zoom out, `Cmd +` doesn't do anything. Same with any mouse wheel combination, as before.

Also, as you can see, there is no option to change those key bindings in any of the Shortcuts menu options (nor elsewhere in the Preferences menu):
- `Menu / Toolbar`
![image](https://github.com/skylot/jadx/assets/25626434/87fdd57b-afeb-4f02-a67a-7aeabd844ac2)
- `Code Area`
![image](https://github.com/skylot/jadx/assets/25626434/c19a07d9-e317-49b4-b091-0d10c09ff5c7)
- `Plugin Script`
![image](https://github.com/skylot/jadx/assets/25626434/9a209501-f387-4ceb-9c56-c5673957face)

**Comment by jpstotz** [comment]
Could be a MacOS Ventura specific problem as on Windows `CTRL +/-`, `CTRL Mouse Wheel Up/Down` works without problems (latest unstable version).

On a Mac running Monterey, zoom was working using the key combinations but not using the mouse scroll wheel. But the non-working mouse wheel could also be a problem of my very unusual way to access the Mac.

**Comment by meiraxx** [comment]
I'm running Mac Ventura. Maybe it's a Ventura-specific issue? Only `Cmd +` works with Macbook.

Either way, there should still be controls to change these keybindings in preferences, that would at least provide a way for any user to solve this issue by themselves. What do you think?

**Comment by meiraxx** [comment]
This issue occurred with Java version `11.0.13`. Updating it to `20.0.1` resolved the issue.

**Comment by tvildo** [comment]
I had same problem in windows suddenly it got super zoomed out. it seems somehow font size got changed to 2 and I changed it back to 13 and fixed my issue
![image](https://github.com/user-attachments/assets/6319295c-cdf2-4803-b094-79e387412336)
