### ISSUE TITLE
[gui] r vs v

### ISSUE THREAD

**Issue by Reyuki-san** [skylot/jadx#1995]
### Issue details

I am new to smali, and want to know what is r and v shown in the image:
![image](https://github.com/skylot/jadx/assets/126035476/dfee8ca1-fccc-40d6-a375-d48f8856c7a6)

is r stand for register? and v for virtual register?

### Jadx version

1.4.7

### Java version

20.0.2

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
The screen shot is a bit small to understand what it is showing can you please ad a larger image and describe in detail what you are trying to do?

**Comment by Reyuki-san** [comment]
I am trying to understand the implication between the register shown in the Smali file and the popup one shown in the previous image
![image](https://github.com/skylot/jadx/assets/126035476/293149f5-32d2-41b0-9c46-737c2ed1f86f)

**Comment by jpstotz** [comment]
The tooltip for your first screenshot is defined here: https://github.com/skylot/jadx/blob/f83ee45ac80d669ce64aa20b87015d7826a114f9/jadx-gui/src/main/java/jadx/gui/treemodel/JVariable.java#L85

As you can see it is just the register number plus the `ssa` value (I think this is the number of previous assignments).

**Comment by Reyuki-san** [comment]
thanks for the answer!
I have a little more questions:
- does `ssa` stand for `static single assignment`?
- how do I make `code view` writeable? so I can observe how register names change while I modify particular codes in `code view`

**Comment by Reyuki-san** [comment]
Thanks for your help @jpstotz @skylot 😄 
I will keep learning

**Comment by Reyuki-san** [comment]
Emmmm, How to get byte offset in jadx? https://github.com/JesusFreke/smali/issues/602#issuecomment-1703666440
