### ISSUE TITLE
[feature] Option for automatic renaming

### ISSUE THREAD

**Issue by MarcoBalossini** [skylot/jadx#1996]
### Describe your idea

While working on some Android application, I noticed that sometimes classes have useful information in `toString()` or log methods. e.g.

```java
public String toString() {
        String str = this.a;
        String str2 = this.b;
        TokenProvider tokenProvider = this.c;
        return "PlatformServiceConfig(apiUrl=" + str + ", apiKey=" + str2 + ", tokenProvider=" + tokenProvider + ")";
 }
```

It would be nice to automate these class/attributes rename

**Comment by jpstotz** [comment]
Next Jadx version will have scripting support so you can write your own deobfuscation code.

You can test this version by downloading the [latest unstable version](https://nightly.link/skylot/jadx/workflows/build-artifacts/master). See also the existing sample scripts https://github.com/skylot/jadx/tree/master/jadx-plugins/jadx-script/examples/scripts

**Comment by skylot** [comment]
@MarcoBalossini unfortunately toString patterns can be very different, so it is hard to implement a common solution. Scripts is the only way. I commit simple implementation for your case, check [deobf_from_tostring](https://github.com/skylot/jadx/blob/master/jadx-plugins/jadx-script/examples/scripts/deobf_from_tostring.jadx.kts) example. Hope it will work for your apk :slightly_smiling_face:

**Comment by MarcoBalossini** [comment]
@skylot thanks a lot for the script

**Comment by laladlala** [comment]
Hi @skylot , thanks for your help!
I have an APK with a lot of "toString" functions but the arguments and objects names remained the same (a,b,c). is this should work only for kotlin? if so, how can I change it to java too?

Thank you!!!
