### ISSUE TITLE
[feature] How to rename method param with script plugin?

### ISSUE THREAD

**Issue by cesaryuan** [skylot/jadx#2004]
Hello everyone, thank you very much for developing such an excellent tool.

I noticed that the script plugin will be introduced in the next version. I downloaded the nightly version and tried to use it, but I am not particularly familiar with the API, so I would like to ask if you can help me write an example.

The functionality I want to achieve is as follows: rename method params by reading param's `retrofit2.http.Query` annotation.
```java
import com.cloud.network.bean.RspMsg;
import retrofit2.http.POST;
import retrofit2.http.Query;

public interface CloudService {
    @POST("get_donate_record")
    Call<RspMsg> get_donate_record(@Query("phone_id") String str); // Rename `str` to `phone_id`
}
```

I would be grateful if you guys could help me. 🥰

**Comment by skylot** [comment]
@cesaryuan script:
```kotlin
/**
 * Rename method parameters from values in attached annotation
 */

import jadx.api.plugins.input.data.attributes.JadxAttrType
import jadx.core.deobf.NameMapper
import jadx.core.dex.nodes.MethodNode
import jadx.plugins.script.runtime.data.ScriptDecompilePass

val annCls = "Lretrofit2/http/Query;"

val jadx = getJadxInstance()

// access to method parameters variables available only in decompile passes
jadx.addPass(object : ScriptDecompilePass(
	jadx,
	"RenameParams",
) {
	override fun visit(mth: MethodNode) {
		// parameter annotations stored in method annotation
		mth.get(JadxAttrType.ANNOTATION_MTH_PARAMETERS)?.let { paramsAttr ->
			for ((i, param) in paramsAttr.paramList.withIndex()) {
				param.get(annCls)?.let { ann ->
					val name = ann.values["value"]?.value as String
					if (NameMapper.isValidIdentifier(name)) {
						mth.argRegs[i].name = name
						log.info { "Rename param $i to $name in method $mth" }
					}
				}
			}
		}
	}
})

jadx.afterLoad {
	// force decompilation and run rename pass for all classes (optional)
	jadx.decompile.allThreaded()
}
```

**Comment by cesaryuan** [comment]
https://github.com/skylot/jadx/blob/72180164d88d7751a2ccbc86f6d0647a58718fdb/jadx-plugins/jadx-script/examples/scripts/deobf/deobf_method_param.jadx.kts#L21

Thanks so much for your help! It works.

btw, there seems to be some places that can be improved. 

I added one safe call `?.` and changed `String` to `String?` as shown below:

`val name = annAttr?.get(annCls)?.values?.get(annParam)?.value as String?`
