### ISSUE TITLE
[feature] Only highlight whole word in Find Usage dialog.

### ISSUE THREAD

**Issue by cesaryuan** [skylot/jadx#2006]
### Describe your idea

Currently, the Find Usage dialog box is a bit confusing in terms of highlighting, and some wrong options are highlighted. I have put an example image below, please check it out.

![image](https://github.com/skylot/jadx/assets/35998162/b6781558-ffbe-4174-b119-97b583fcf79a)

I checked your source code and found that the core logic is here,

https://github.com/skylot/jadx/blob/de603ef90978b8d963632cba23d1475ff8f89541/jadx-gui/src/main/java/jadx/gui/ui/dialog/CommonSearchDialog.java#L115-L121

And just add the statement `highlightContext.setWholeWord(true);` to achieve better results, as shown below:

![image](https://github.com/skylot/jadx/assets/35998162/ae69638a-e69d-4195-860a-4de363028d58)

But I dare not put forward a PR without authorization, because I don't know if it will have side effects. I would be very grateful if you could check it out.

**Comment by skylot** [comment]
@cesaryuan thanks for bringing up this issue :+1:
Indeed, your PR in a nice improvement, thanks.
Although, jadx knows exactly what should be highlighted, and we just need to use that info.
I will open a separate issue to address such improvement.

BTW, this is also related to search dialog with selected Class/Method/Field options.
