### ISSUE TITLE
& and &&

### ISSUE THREAD

**Issue by JamesLiAndroid** [skylot/jadx#202]
This is the java code from jadx translate:

```
this.tv_printPreview2.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Cut_activity.this.playSound();
                if ((Cut_activity.this.isWork | Cut_activity.this.cutStatus) != 0) { // please see this line 
                    MyToast.createToastConfig().ToastShow(Cut_activity.this.getApplicationContext(), "打印设置前请停止工作");
                    return;
                }
                Intent intent = new Intent(Cut_activity.this, NewRun.class);
                intent.putExtra("CutCreate", true);
                Cut_activity.this.startActivityForResult(intent, 1001);
            }
        });
```
maybe 
`
if ((Cut_activity.this.isWork | Cut_activity.this.cutStatus) != 0) { 
`

should be translate to this:

`
if (Cut_activity.this.isWork || Cut_activity.this.cutStatus) { 
`

I have to change this error in AndroidStudio many times, so I want to listen your advice!

**Comment by skylot** [comment]
Can you provide link to this apk? Or part of this method in smali or in jadx fallback format?
I don't know how to write the test to reproduce this issue.

**Comment by asashour** [comment]
I am trying to look into this, and I want to create the corresponding code as in `if (boolean1 || boolean2)` to replace a single `IfNode`, in `SimplifyVisitor`

What would be the best way? Create `IfNode`s, then how to put them in a block? Or should two blocks are created?

Thanks.

**Comment by skylot** [comment]
I think that optimization must be placed in [`IfCondition.simplify`](https://github.com/skylot/jadx/blob/e1f4955286f73a6ca4525fc27b11fd02106f7f08/jadx-core/src/main/java/jadx/core/dex/regions/conditions/IfCondition.java#L142) method.
