### ISSUE TITLE
[gui] Menu fonts and icons are oversized even without scaling

### ISSUE THREAD

**Issue by alexmaloteaux** [skylot/jadx#2025]
### Issue details

I m using i3 with 2 monitors , one is 4k and second one is 2k,
the main monitor is the 2k one and jadx-gui is automatically started on this monitor.

My menu fonts and icon are too big and there are no settings i can find to reduce it to normal size.
I tried to use the -Dsun.java2d.uiScale=1.0" "-Dsun.java2d.uiScale.enabled=true java parameters but it looks like the minimum size of 1.0 is too big.

I m not sure what else can be done, i tried overriding the paint method of the MainWindow JFrame, with 
```	@Override
    public void paint(Graphics g) {
	float scale = 0.5;
        Graphics2D g2d = (Graphics2D) g;
        g2d.scale(scale , scale);
        super.paint(g2d);
    }
```
and various other tests but nothing helps.

Any idea how to fix this gui issue ?

Thanks

![F20231007_134146](https://github.com/skylot/jadx/assets/1566812/b438ec25-c263-40c7-b352-56662b397165)

### Jadx version

dev / master

### Java version

17.0.8.1

### OS

- [ ] Windows
- [X] Linux
- [ ] macOS

**Comment by skylot** [comment]
@alexmaloteaux looks like you already set some scaling, so I suggest checking your environment variables (can be in `JDK_JAVA_OPTIONS` variable).
Another way is to use `-Dflatlaf.uiScale=0.5` to change scaling with `FlatLaf` option, hope it will help.

**Comment by alexmaloteaux** [comment]
@skylot  thanks a lot , flatlaf.uiScale did the trick, i was out of ideas on this one , thanks again :)
