### ISSUE TITLE
[core] 

### ISSUE THREAD

**Issue by yangjw** [skylot/jadx#2028]
### Issue details

% jadx
Unrecognized VM option 'MaxRAMPercentage=70.0'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by jpstotz** [comment]
`Unrecognized VM option 'MaxRAMPercentage=70.0'` is usually an indicator that the used Java Runtime is pretty old. 

Possible duplicate of #1520
