### ISSUE TITLE
[feature] filter in xref window

### ISSUE THREAD

**Issue by aj3423** [skylot/jadx#2034]
# 1. filter by read/write access
When pressing `x` on an variable like `this.data`, the references window contains both read/write operations, sometimes I need to find where it's written, but there may be 30+ reading, and only 1 writing, not very easy to spot the writing one.

For example, the x-refs window looks like:
```
a = obj.data   // read
fn(obj.data)   // read
obj.data = 1   // write
``` 
If I choose "write only" from a filter combobox, then the list only contains:
```
obj.data = 1
```
The combobox contains 3 items: 
1. read+write (default)
2. read
3. write

# 2. filter by inheritance/implementation
For example, when x-ref for: `public interface apyt {`, the result may look like:
![image](https://github.com/skylot/jadx/assets/4710875/df81ef23-9928-4c5a-bbd4-1ad149b09cd2)
I need only the row that implements this interface, which is the highlighted row.

Maybe add one more item in the filter combobox: "inheritance/implementation"

**Comment by skylot** [comment]
@aj3423 thank you for suggestions!
I added your requests to common refactoring issue for references search (#1368). As mentioned in that issue, I plan to add collapsible sections with various usage/reference categories instead of options/toggles.
