### ISSUE TITLE
[gui] Locate class file after using search feature is problematic

### ISSUE THREAD

**Issue by Uzver123** [skylot/jadx#2035]
### Issue details

After opening APK with lots of classes and files its problematic to find out what file path to the opened source code file if you use search function in Jadx to open the file where matches found. 

I don't believe there even a way to see where if file tree currently open file is located if you opened it trough the search function.

### Jadx version

1.4.7

### Java version

portable

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
@Uzver123 not sure what you are really want, but `Sync with editor` action looks like is what you are asking:
in menu `View -> Sync with Editor` or on toolbar, this action will expand left tree and make selected node from the currently opened tab. Also, there is a `Always Select Opened File/Class` checkbox to auto apply this action on tab switch/open.
Hope, this will help :slightly_smiling_face:
