### ISSUE TITLE
[feature] Implement AI to Deobfuscation?

### ISSUE THREAD

**Issue by queerzard** [skylot/jadx#2036]
### Describe your idea

As mentioned in the title of this request,
I asked myself if it were possible to implement
AI to the deobfuscator, naming the variables according to their functionality , maybe add comments to what functions do.
This would make it easier to trace back field usages.

**Comment by skylot** [comment]
@queerzard please check my reply in similar issue: https://github.com/skylot/jadx/issues/1884#issuecomment-1564587269
In short: it is a good idea, but I don't want to do it, you can create a jadx plugin if you want to :slightly_smiling_face:
