### ISSUE TITLE
[feature] Can you add a function to close all sub-windows with one click?

### ISSUE THREAD

**Issue by pll177** [skylot/jadx#2043]
### Describe your idea

![image](https://github.com/skylot/jadx/assets/60816646/5f1ed127-b95d-44a8-95eb-9020851c8619)

**Comment by skylot** [comment]
@pll177 by default, search and usage windows will close after opening any result. But, looks like you enable option forcing windows to stay open (`Keep open` checkbox in bottom-left corner). If this is not your case, or you don't want to disable this option for some reason, please add more details to your request.
