### ISSUE TITLE
jadx-gui does not start: 'UseG1GC' is experimental (MacOS, Java 8)

### ISSUE THREAD

**Issue by xuqinghao1991** [skylot/jadx#2045]
### Issue details

M2pro芯片Mac 电脑
xuqinghao@192 ~ % jadx-gui
Error: VM option 'UseG1GC' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Jadx version

1.4.7

### Java version

1.8

### OS
macOS

**Comment by xuqinghao1991** [comment]
java版本是 1.8.0_381

**Comment by skylot** [comment]
@xuqinghao1991 not sure why you got this error, I can't reproduce it using `OpenJDK 1.8.0_392-b08`.
Maybe you are using other JDK distributions (shown with `java -version`), or the behavior of that flag changed between minor versions.
Anyway, I suggest to use more recent version, like Java 17.
Another way is to pass that option suggested in error message by adding `JADX_GUI_OPTS` env variable:
```bash
JADX_GUI_OPTS="-XX:+UnlockExperimentalVMOptions" jadx-gui
```

**Comment by Aaronwk** [comment]
> ![图像](https://private-user-images.githubusercontent.com/5636556/290461269-e702c69f-4c1a-4bb3-8e70-d143a2cadd8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDM0ODQsIm5iZiI6MTcwODUwMzE4NCwicGF0aCI6Ii81NjM2NTU2LzI5MDQ2MTI2OS1lNzAyYzY5Zi00YzFhLTRiYjMtOGU3MC1kMTQzYTJjYWRkOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDgxMzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YyMTg2YjNlMDRlNmMwNGQyYTYyZjA3ODc3MzVlNWZjODAyODBkZDU1MDllZjg5NGU1ZGY0MGNlMzFmYzhiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7XwvYaQ6E9_BJ0lp0L-s4VkmDMf6C4JI0OKrjCqj-c8)
> 
> 也可以通过在“-XX:+UseG1GC”之前添加“-XX:+UnlockExperimentalVMOptions”来解决此问题

你好，麻烦问一下，这个文件在哪里能找到。我没有找到这个文件
