### ISSUE TITLE
connection refused 

### ISSUE THREAD

**Issue by ronmazor** [skylot/jadx#2046]
### Issue details

when i open the gui on win 11 , adb path c:adb.exe localhost , port 5037 , i get a popup connection refused: connect , 

can you help

### Jadx version

1.47

### Java version

21

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
@ronmazor as mentioned in [wiki](https://github.com/skylot/jadx/wiki/Smali-debugger): Android Studio can cause such issue, so just close it. Also check if adb can connect from terminal (`adb logcat` for example).
If above suggestions didn't help please run jadx with verbose logging (`jadx-gui -v`) and share errors from log viewer or terminal.
