### ISSUE TITLE
[gui] High memory consumption

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#2059]
### Issue details

Hi, I'm using the JADX unstable version and it seems consuming too much memory. Attaching the screenshot for reference.
![image](https://github.com/skylot/jadx/assets/35992798/5bf03856-eb4e-4599-ae8a-1652a0616bfa)
I only opened the APK, did not even click any classes to decompile so even without engaging decompiling it consumes too much memory.

### Jadx version

1.4.7.260-b6155afd

### Java version

1.4.7.260-b6155afd

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by redmi111** [comment]
Btw, it used to be above 5 gigs, I clicked the memory bar in JADX GUI and it trimmed some memory to be at 3 Gigs.

**Comment by skylot** [comment]
@redmi111 setting code cache mode to 'Disk' can reduce memory usage.

**Comment by redmi111** [comment]
![image](https://github.com/skylot/jadx/assets/35992798/4f125dec-ffda-44b6-926e-602db0a5bec9)
It's already in Disk

**Comment by skylot** [comment]
'Code cache mode' to 'DISK' :)
'Disk with cache' still stores a lot of data in memory.
Also depending of apk you load 5G is not too much actually :rofl:

**Comment by redmi111** [comment]
Thanks,== > 'Code cache mode' to 'DISK' :) this significantly reduced under 2G, 

"Also depending of apk you load 5G is not too much" ==> I didn't realize this until I load the 1 MB APK today with apparently very low amount of classes. So far I thought it's due to heavy APKs I load into it.
