### ISSUE TITLE
[gui] The interface is confusing. When the mouse pointer moves, the interface follows the pointer and overlaps and displays repeatedly.

### ISSUE THREAD

**Issue by Da-Miao** [skylot/jadx#2079]
### Issue details

![屏幕截图 2024-01-09 121039](https://github.com/skylot/jadx/assets/26597570/241de854-0b84-4f07-85e3-34ff6628617f)
![屏幕截图 2024-01-09 121145](https://github.com/skylot/jadx/assets/26597570/f26191a2-0c21-440e-a9d6-1c0011b686a1)
The interface is confusing. When the mouse pointer moves, the interface follows the pointer and overlaps and displays repeatedly.

### Jadx version

1.4.7

### Java version

1.8.0_333

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by Da-Miao** [comment]
![%7BAFDDF059-F11D-4d5b-AA28-6FC9A8249451%7D](https://github.com/skylot/jadx/assets/26597570/7894dfb6-97c0-4c8c-a528-bd4c5d6b4649)

**Comment by skylot** [comment]
@Da-Miao as mentioned in [Troubleshooting guide](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#others):
Try the newer java version (prefer Java 17):
    - Use release bundle with included JRE: jadx-gui-***-with-jre-win.zip (for 1.4.7: [link](https://github.com/skylot/jadx/releases/download/v1.4.7/jadx-gui-1.4.7-with-jre-win.zip))
    - Or download from [oracle.com](https://www.oracle.com/java/technologies/downloads/#java17)

**Comment by Da-Miao** [comment]
thanks

**Comment by jpstotz** [comment]
@mkx173 Can you please give us more details about your used JDK (which one do you use, Oracle, Eclipse, Corretto, ..) and about your used graphics chip + driver version?

Also please give the latest unstable version a try: https://nightly.link/skylot/jadx/workflows/build-artifacts/master
