### ISSUE TITLE
It can not decompile which Class file compiled by java8

### ISSUE THREAD

**Issue by MrXionGe** [skylot/jadx#208]
jadx version = 0.6.1.
local jvm version = 8u151 64bit -windows10
-----------------------------------------------------------------------------
If my demo use some new feature in java8 , jadx can't decompile .
Of course , in java 7 or java 6 , there is not this problem .

**Comment by skylot** [comment]
This is known issue that jadx don't support Dex with version 38. I will fix this on weekend (I hope).
But lower Dex version supported in latest [unstable](https://bintray.com/skylot/jadx/unstable#files) version, please try it.
Also I can suggest to build apk to lower android target version. I'm not sure it will work but you can try.

**Comment by MrXionGe** [comment]
@skylot Oh , sorry . I am not a Android developer . 
I decompile jar file by jadx .
I created 2 demos , and I found the problem .
java7(class) can be decompiled . And the java8 class(use new feature) can not be compiled .

**Comment by skylot** [comment]
I see. So you need to wait until I implement support of new invoke instructions in Dex 38.
Sorry for this :(

**Comment by MrXionGe** [comment]
@skylot  
Thanks for receive my issue .
Nice tool . Nice friend !
