### ISSUE TITLE
[GUI] Feature request: Double-click to allow multiple highlighting

### ISSUE THREAD

**Issue by enovella** [skylot/jadx#210]
Although the intention of JADX is not to be an advanced source code viewer. The feature of multiple highlighting when double-clicking a word could be very useful to follow the decompiled code.

![2beap](https://user-images.githubusercontent.com/14809754/35116340-643f8f2e-fc8b-11e7-9736-4ef86f03c992.png)

Thanks for listening :)

**Comment by skylot** [comment]
Hm, I done what you ask, but suddenly similar function already was here.
If you single click on word and wait ~2 seconds all occurrences will be highlighted in gray.
So now there are two ways to do same things :) Check [this](https://bintray.com/skylot/jadx/download_file?file_path=jadx-0.7.0-b370-7fe46fb.zip) build

**Comment by enovella** [comment]
Hi,
That's so convenient and kudos for the speed. It was extremely fast :).  Going to test it now.
Thank so much

**Comment by enovella** [comment]
Works like a charm! @skylot  :+1:
