### ISSUE TITLE
[core] Zipbomb Attack Detected?

### ISSUE THREAD

**Issue by hecker7734** [skylot/jadx#2105]
### Issue details

![image](https://github.com/skylot/jadx/assets/91642757/2b72b7c3-1dc5-47ee-92dd-22eb23198d91)

This was from stickwar legacy downloaded from apkpure;
Was this a real zipbomb?
or a decompile issue?

### Jadx version

2023.5.201

**Comment by MrIkso** [comment]
No, i think it a decompile issue. Assets always compressed

**Comment by jpstotz** [comment]
The total size of ~1MB is a bit small for a real ZIP bomb attack. Anyway having a file with a compression ration of ~370, where 2-10 would be a good compression ratio, raises some questions on why the APK contains such a file. 

Another question is if there is only one such file in the APK or multiple. One such file doesn't make an attack, multiple files increase the probability of an attack. Anyway a zip bomb attack may only lead to a crashing app processing the APK or in a bit of HDD usage.

**Comment by hecker7734** [comment]
Even the original APK (extracted from emulator) has this 'zipbomb'
It could just be a way to stop modders or code stealing?
