### ISSUE TITLE
Using the master branch as a library

### ISSUE THREAD

**Issue by iscle** [skylot/jadx#2106]
### Describe your idea

Hi!

I'd like to use the master branch as a library. However, I've tried importing it as a gradle project but does not seem to work.

Is there any specific way to do so? Or, are there any instructions on how to at least build it manually so that it can be imported as a .jar as a workaround?

Thanks!
Iscle

**Comment by skylot** [comment]
@iscle you can use snapshot version like this:
```kotlin
repositories {
    mavenCentral()
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots/")
    google()
}

dependencies {
    implementation("io.github.skylot:jadx-core:1.5.0-SNAPSHOT") {
        isChanging = true
    }
    // ...
}
```
But as soon as I upload snapshots manually it can be outdated, so if you need latest commit feel free to ping me here.

Another way is to use local maven repository, it is useful if you change something:
- run `JADX_VERSION="1.5.0-SNAPSHOT" ./gradlew publishToMavenLocal`
- add `mavenLocal()` to the repository list
- add dependency, same as for snapshot

**Comment by iscle** [comment]
That was it, thanks!

**Comment by iscle** [comment]
@skylot is there any way to edit the wiki to add some info to it as a contributor without being the owner?

**Comment by skylot** [comment]
@iscle wiki editing was restricted to collaborators only, I unchecked that option, so it should be editable now.
