### ISSUE TITLE
[feature] Auto expand and highlight in source list

### ISSUE THREAD

**Issue by ghost** [skylot/jadx#2107]
### Describe your idea

I would like Jadx to auto expand and highlight the class name in source list when I select the node/code from search. For example I double clicked "downloadDispatcher" from search, the list automatically expands and highlight the class name (See below as an example). It makes me a lot easier to navigate

![image](https://github.com/skylot/jadx/assets/127546925/3a55f10e-665b-4f90-94dc-abe9a834b5f2)

Or just highlight the class name to keep the list clean (dnSpy, the C# disassembler, does this way)
![image](https://github.com/skylot/jadx/assets/127546925/37fb7726-6ed8-4144-81df-90aee97e828b)

**Comment by jpstotz** [comment]
Have you tried to enable in menu `View` -> `Always Open Selected File/Class`?
