### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by svilly** [skylot/jadx#2117]
### Issue details

Hi!
Can you say how you compile project (module jadx-gui) in ~30 Mb .exe file. When I compile project or module its compiling in 110Mb .exe file. Guess that I choose wrong task(s) and args

### Jadx version

1.4.7

### Java version

OpenJDK 19.0.2

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
You are comparing apples (Jadx stable version) with peas (latest unstable version) - the next stable version will be ~110MB in size.
