### ISSUE TITLE
Reduce log spam when encountering unknown instructions/constants

### ISSUE THREAD

**Issue by NebelNidas** [skylot/jadx#2133]
### Describe your idea

JADX really struggles with class files targeting Java 11+, and produces an insane amount of log spam (tens of thousands of lines, [here](https://gist.github.com/modmuss50/ff50e7c3b6f21d1743e032b0b6f2e3c9) just the last 10K as an example). Would it be possible to special-case some of these errors for a condensed log output? Like, `WARNING: Class xyz contains Java 11+ bytecode not yet supported by JADX, expect decompilation issues` or similar?

**Comment by skylot** [comment]
I am not sure if I can do something here, there are no categories for errors, so I can't disable only some of them.
In jadx-cli now by default errors not reported, and if you're using jadx as a library you can disable all logs from `jadx.core.utils.ErrorsCounter` class.
Also, I think is better just to fix these errors, so if possible, please open a new issue with sample, so I can fix that issue.

**Comment by skylot** [comment]
The main issue was fixed in #2139.
For other errors, please open separate issues and don't forget to attach sample :slightly_smiling_face:.

**Comment by NebelNidas** [comment]
Thanks :)

> For other errors, please open separate issues

Sure! Can you publish another snapshot in the meantime, so we have easier access to the new fixes and the rename-mappings plugin?

**Comment by skylot** [comment]
> Can you publish another snapshot

Done
