### ISSUE TITLE
[doc] Dead link to access `jadx as a library`

### ISSUE THREAD

**Issue by loganmzz** [skylot/jadx#2135]
### Issue details

README contains:

> ### Use jadx as a library
> You can use jadx in your java projects, check details on [wiki page](https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library)

However, the link is broken. Correct one is: https://github.com/skylot/jadx/wiki/Using-jadx-as-a-library

### Jadx version

Github

### Java version

N/A

### OS

- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
@loganmzz thanks :+1:
I fixed this issue by reverting page title.
Actually, it is good to know that changing page title in GitHub editor will also change file name and break links :thinking:
