### ISSUE TITLE
Add ability to customize code comment style

### ISSUE THREAD

**Issue by NebelNidas** [skylot/jadx#2145]
Currently, `NotificationAttrNode#addCodeComment` adds `// `-prefixed comments to the decompiled source. It would be nice if we were able customize this, e.g. to use the `/* */` multi-line or the `/** */` Javadoc style.

I propose a method signature change to `addCodeComment(String comment, CommentStyle style)` with
```java
public enum CommentStyle {
	/**
	 * <pre>
	 * // comment
	 * </pre>
	 */
	SINGLE_LINE,
	
	
	/**
	 * <pre>
	 * /*
	 * * comment
	 * *&#47;
	 * </pre>
	 */
	MULTI_LINE,
	
	/**
	 * <pre>
	 * /* comment *&#47;
	 * </pre>
	 */
	MULTI_LINE_CONDENSED,

	/**
	 * <pre>
	 * /**
	 * * comment
	 * *&#47;
	 * </pre>
	 */
	JAVADOC,

	/**
	 * <pre>
	 * /** comment *&#47;
	 * </pre>
	 */
	JAVADOC_CONDENSED
}
```

**Comment by skylot** [comment]
Oh, nice suggestion :+1:
One thing is that string passed with `SINGLE_LINE` can have several lines, and we can actually make it multiline with `//` on every line, so it is no longer single line :rofl:

So, maybe we can name comment styles by used chars? Like:
LINE - for `//`
BLOCK - for `/* */`
BLOCK_CONDENSED
JAVADOC
JAVADOC_CONDENSED

**Comment by NebelNidas** [comment]
Oh yes, these names are a lot better 😄

**Comment by NebelNidas** [comment]
Hmm, one thing I haven't thought of yet, how should we handle condensed options containing multiple lines?

**Comment by skylot** [comment]
Well, it will start new line, it is just different from normal version by not having new line at start. I think it is fine.

**Comment by skylot** [comment]
Done. Also added combo box to jadx-gui comment dialog.
Snapshot uploaded. Please check :slightly_smiling_face:

**Comment by NebelNidas** [comment]
Works great, thanks! Here's an example from Enigma:

![image](https://github.com/skylot/jadx/assets/48808497/8e01da67-683f-4120-a74c-971207660c63)

One thing I noticed though is that you made `BLOCK`-style comments not have a preceding ` *` per line, which contradicts [the convention](https://www.oracle.com/java/technologies/javase/codeconventions-comments.html#216) (and most uses I've found online). Apart from that, it does exactly what I need :)

**Comment by skylot** [comment]
Ok, I apply both suggestions, thanks :+1:

Also, I commit implementation for #1945 and #1948, now you can set code indent string and new line string in JadxArgs:
```java
args.setCodeNewLineStr("\n");
args.setCodeIndentStr("\t");
```

**Comment by NebelNidas** [comment]
Thanks! Feels like Christmas 😄
