### ISSUE TITLE
ERROR - JadxOverflowException in pass: RegionMakerVisitor in method: kotlinx.coroutines.flow.FlowKt__DelayKt$fixedPeriodTicker$3.invokeSuspend(java.lang.Object):java.lang.Object,[core] 

### ISSUE THREAD

**Issue by ohyeah521** [skylot/jadx#2148]
### Issue details

jadx.bat  -d  C:\Users\user\Desktop\dump_dex\classes.dex  C:\Users\user\Desktop\dump_dex

Execute the above command through cmd, and then the program gets stuck and cannot return.

```
ERROR - JadxOverflowException in pass: RegionMakerVisitor in method: kotlinx.coroutines.flow.FlowKt__DelayKt$fixedPeriodTicker$3.invokeSuspend(java.lang.Object):java.lang.Object, file: C:\Users\user\Desktop\dump_dex\classes.dex, details: Regions count limit reached
INFO  - progress: 3649 of 3653 (99%)
```

### Jadx version

1.4.7

**Comment by skylot** [comment]
@ohyeah521 please provide sample dex, so I can reproduce and fix this issue.
Also, you can try [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master), maybe issue was already resolved.

**Comment by ohyeah521** [comment]
@skylot    [classes.zip](https://github.com/skylot/jadx/files/14984894/classes.zip)

**Comment by ohyeah521** [comment]
@skylot  i had test lastest unstable build, it's not work.

**Comment by skylot** [comment]
Fixed.
I commit a fix to resolve the issue, which leads to an infinite loop.
