### ISSUE TITLE
Missing Routine Implementations

### ISSUE THREAD

**Issue by fosterbrereton** [skylot/jadx#2151]
### Issue details

During decompilation I am shown three function prototypes for routines in a `public class` that `extends Service`:

```java
/* JADX INFO: Access modifiers changed from: private */
public native int ReturnKey(byte[] bArr, byte[] bArr2);

/* JADX INFO: Access modifiers changed from: private */
public native void decrypt(byte[] bArr, byte[] bArr2, byte[] bArr3);

private native void encrypt(byte[] bArr, byte[] bArr2, byte[] bArr3);
```
However the implementation for these routines are not shown anywhere. While I am seeing decompilation errors, they do not appear to be related to either of these three routines. What am I missing?

### Jadx version

1.4.7

**Comment by skylot** [comment]
@fosterbrereton these are native methods, and you should look for implementation in native libraries.
Simple example for usage of native methods in Java: https://stackoverflow.com/questions/18900736/what-are-native-methods-in-java-and-where-should-they-be-used
Unfortunately, jadx do not support decompilation of native libs, so you should use other decompilers for that.

**Comment by fosterbrereton** [comment]
Okay, thank you for the pointer.
