### ISSUE TITLE
Comment text box not shown

### ISSUE THREAD

**Issue by exp0l0zzz** [skylot/jadx#2155]
<img width="580" alt="image" src="https://github.com/skylot/jadx/assets/95993081/f2c2fcd2-e09e-4479-afb5-21d9d0f05dd5">

There is no way to write comment

**Comment by skylot** [comment]
@exp0l0zzz can you try to resize window to increase height?
Looks like comment text box don't have enough space to show.
I will try to fix this dialog layout.

**Comment by exp0l0zzz** [comment]
<img width="134" alt="image" src="https://github.com/skylot/jadx/assets/95993081/b320d14f-933a-4368-8301-c0df61768ab9">
我怎么删除这个注释？没看到按钮。这是在反编译里

**Comment by skylot** [comment]
> How do I delete this comment? I don't see the button

Comment dialog have a remove button, so you need to open dialog again to remove comment :slightly_smiling_face:

**Comment by exp0l0zzz** [comment]
我看到了，但是我觉得这个地方应该有所改进，我一开始有点糊涂，原来是重新点击 添加注释 按钮 才会出来

**Comment by skylot** [comment]
> I saw it, but I think this place should be improved. I was a little confused at first. It turns out that it only comes out when I click the Add Comment button again.

I agree, "Add comment" to edit/remove is very misleading.
Not sure how better to improve this. Maybe I will change menu entry to "Edit comment" if comment already added.
