### ISSUE TITLE
[gui] jadx-gui failed to start due to the limitation of powershell/pwsh

### ISSUE THREAD

**Issue by Gokr-ble** [skylot/jadx#2159]
### Issue details

Some company may use Group Policy or Domain Policy to restrict employees from launching powershell.exe/pwsh.exe, but in the new version of jadx(1.5.0), it will call pwsh to get LocalAppData/RoamingAppData on Windows, which causes startup failure.
![image](https://github.com/skylot/jadx/assets/44522297/20177d83-95be-4530-a425-e16ed9d52bd1)

### Jadx version

1.5.0

### Java version

17

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
@Gokr-ble jadx uses [dev.dirs:directories](https://github.com/dirs-dev/directories-jvm) library to get application config directory in crossplatform way, and uses powershell only as a fallback way to find path of these folders: [here](https://github.com/dirs-dev/directories-jvm/blob/c123afdba854095f18521ac895afa7fae999b49f/src/main/java/dev/dirs/Util.java#L151)

But jadx just need a config directory :rofl:
I will add additional environment variable so it will be possible to set custom config directory.

**Comment by skylot** [comment]
Done.
Set both env variables `JADX_CONFIG_DIR` and `JADX_CACHE_DIR` to use custom directories.
To test, try [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Comment by Gokr-ble** [comment]
Awesome, Thanks a lot for your effort
