### ISSUE TITLE
Some classes are declared in AndroidManifest.xml, but missing in sources

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#216]
[com.binance.dev_1.4.0.1-36_minAPI17(armeabi,armeabi-v7a,x86)(nodpi)_apkmirror.com.apk.zip](https://github.com/skylot/jadx/files/1671678/com.binance.dev_1.4.0.1-36_minAPI17.armeabi.armeabi-v7a.x86.nodpi._apkmirror.com.apk.zip)

I tested this APK in jadx, apktool and dex2jar, and in all of them I see only ``` com/tencent ``` package. But in AndroidManifest.xml multiple activities are declared in different package, e.g. ``` com.binance.dev.activities.main.MainActivity ```. I thought it might be a broken apk, but I'm able to install this app, and access these activities:
```
adb shell am start -n com.binance.dev/.activities.webview.WebViewActivity
Starting: Intent { cmp=com.binance.dev/.activities.webview.WebViewActivity }
```

Is that a bug in all these tools for reverse-engineering?

**Comment by ddurando** [comment]
This app is packed using the Tencent packer. That is the reason why most of its classes do not appear in the code.
They are still mentioned in the Manifest because when they will be loaded dynamically later, their name needs to be in the manifest to be executed. So I wouldn't say it is a bug

**Comment by skylot** [comment]
So this packer use dynamic class loading from native code and jadx can't help you. Sorry :(
