### ISSUE TITLE
[gui] I only see "Desktop" as available directory

### ISSUE THREAD

**Issue by privacyguy123** [skylot/jadx#2169]
### Issue details

Title says it all - not sure what has caused this but it happened all of a sudden. Java JRE got updated recently.

![image](https://github.com/skylot/jadx/assets/50337995/d1bcef26-a22e-403f-b88c-8c08b6150182)

### Jadx version

1.4.7.302-2807dc50

### Java version

17.0.10

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
This issue is same as #1954 and because I can't reproduce it is hard to fix.
As a workaround, you can check `Use alternative file dialog` in `Other` group in preferences, hope it will help.

**Comment by privacyguy123** [comment]
> This issue is same as #1954 and because I can't reproduce it is hard to fix. As a workaround, you can check `Use alternative file dialog` in `Other` group in preferences, hope it will help.

I don't even see the error outputs described here. Even more strange ...
