### ISSUE TITLE
When you run jadx.cli.JadxCLI in the PowerShell console, additional directories are created in the root directory of the application itself

### ISSUE THREAD

**Issue by denis-komarov** [skylot/jadx#2172]
### Issue details

I run jadx.cli.JadxCLI not with the jadx.bat script, but through my jadx.ps1 script in the PowerShell console which calls java.exe. In this case, the following directories are created **in the root directory of the application** itself:
```powershell
\null\skylot\jadx\cache\scripts
\PowerShell 7.4.2\skylot\jadx\config\plugins\dropins
\PowerShell 7.4.2\skylot\jadx\config\plugins\installed
```
It would be nice to have an environment variable similar to JADX_TMP_DIR to manage these directories.

### Jadx version

1.5.0

### Java version

21.0.2

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
@denis-komarov I just commit requested changes for #2159 issue check https://github.com/skylot/jadx/issues/2159#issuecomment-2086268116 for variable names.
