### ISSUE TITLE
Errors after recompiling same dexes into jar

### ISSUE THREAD

**Issue by privacyguy123** [skylot/jadx#2175]
### Issue details

Attaching file because too much code.

I really can't deduct whether or not these are even something to worry about, let alone understanding what they mean. But I am unsure why decompiling and recompiling the exact same .dexs into a .jar would show these?

### Jadx version

1.5.0

### Java version

21.0.3

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by privacyguy123** [comment]
[JADX.txt](https://github.com/skylot/jadx/files/15213590/JADX.txt)

**Comment by jpstotz** [comment]
Can you please describe what steps you have performed to get Jadx-Gui into this state? 

It seems like you are trying to load an unzipped APK file with multiple dex files. 

Also what do you means by "recompiling same dexes into jar", what are you trying to do?

**Comment by privacyguy123** [comment]
Disregard, I am bein stupid. The original stock .jar also shows exact same errors, so I guess OEM/ROM builder left them in.
