### ISSUE TITLE
Non-deterministic results pt2

### ISSUE THREAD

**Issue by 3mph4515** [skylot/jadx#2178]
### Issue details

I'm using JADX 1.5.0 to decompile the same APK file multiple times and comparing the differences between two folders. Each time, the results vary slightly. This seems to be related to package visibility. Here is an example:

`jadx /Users/andrew/test.apk --comments-level none`

<img width="1640" alt="image" src="https://github.com/skylot/jadx/assets/136313921/60581dbf-b322-4149-9516-0264fdf699e2">
<img width="1635" alt="image" src="https://github.com/skylot/jadx/assets/136313921/1a22e87b-1374-4ee2-af69-91f087ea05b3">
<img width="1495" alt="image" src="https://github.com/skylot/jadx/assets/136313921/7a462525-ddd0-41cd-9f89-20fa1ca6f701">

### Jadx version

1.5.0

**Comment by cw2k** [comment]
Also to me this non-deterministic decompiling results are annoying.
I can't use it to compare two versions of code.

If Jadx each time I decompile the same code gives different result s it renders it nearly useless for the task.

A workaround like what parameter to use so jad is deterministic would greatly help.

**Comment by skylot** [comment]
I think the issue with access modifiers was fixed by PR #2235.
For other issues, please try to set threads count to 1 (`--threads-count` flag in cli).
If this not help, please report such cases (with attached sample) in #1089 or open a new issue.
