### ISSUE TITLE
This error occurred when I was converting the source code of the app into a gradle project.

### ISSUE THREAD

**Issue by MohitKashyapUK** [skylot/jadx#2179]
### Issue details

Jadx version : 1.5.0
Java version : 22.0.1
Java VM      : Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
Platform     : Windows 10 (10.0 amd64)
Max heap size: 4096 MB
Program args : -Xms216m -Xmx4096m -Xms128M -XX:MaxRAMPercentage=70.0 -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true -Djdk.util.zip.disableZip64ExtraFieldValidation=true -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED

java.lang.IllegalStateException: Could not find AndroidManifest.xml
	at jadx.core.export.ExportGradleTask.run(ExportGradleTask.java:40)
	at jadx.core.utils.tasks.TaskExecutor.wrapTask(TaskExecutor.java:166)
	at jadx.core.utils.tasks.TaskExecutor.runStages(TaskExecutor.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

### Jadx version

1.5.0

### Java version

22

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by MohitKashyapUK** [comment]
GUI Version

**Comment by MohitKashyapUK** [comment]
"https://github.com/MohitKashyapUK/android_app_boilerplate.git"

GUI Version without JRE
Installed JRE version "22"

> Can you provide the app you had loaded or at least tell us if you had loaded one APK file, or multiple APK files (split APK app)?

**Comment by jpstotz** [comment]
Does that mean you had compiled that Android project, then loaded the APK into Jadx-GUI and finally used the "Save as gradle project" which triggered the error you have posted?

**Comment by MohitKashyapUK** [comment]
> Does that mean you had compiled that Android project, then loaded the APK into Jadx-GUI and finally used the "Save as gradle project" which triggered the error you have posted?

No, I just pasted the source code into jadx.

**Comment by jpstotz** [comment]
Jadx is a decompiler. Loading source code instead of binary APKs or JAR files into it is in my opinion a bit out of scope. Therefore you are getting this error.

**Comment by MohitKashyapUK** [comment]
> Jadx is a decompiler. Loading source code instead of binary APKs or JAR files into it is in my opinion a bit out of scope. Therefore you are getting this error.

"Alright, but if you had also added this feature, it would have been better."
