### ISSUE TITLE
[gui] Opening apk in 1.5.0 doesn't decompile java/kotlin

### ISSUE THREAD

**Issue by iiasceri** [skylot/jadx#2181]
### Issue details

Just try 1.4.7 and 1.5.0 while opening .apk file.
1.4.7 does decompile then you can carry on with your work and 1.5.0 doesn't.

1.5.0 logs:
```
❯ jadx-gui
INFO  - output directory: learnfrida
INFO  - loading ...
INFO  - Loaded classes: 4715, methods: 39203, instructions: 1067704
INFO  - Found 0 classes in disk cache, time: 1ms, dir: /Users/nick/nickDev/com.learn.frida/packed/learnfrida.apk.cache/code
```
1.4.7 logs:
```
❯ ./jadx-gui
INFO  - Found new jadx version: 1.5.0
 jadx-1.5.0.zip, size: 100.11MB, downloads count: 11766, url: https://github.com/skylot/jadx/releases/download/v1.5.0/jadx-1.5.0.zip, date: 2024-04-20T20:10:58Z
 jadx-gui-1.5.0-no-jre-win.exe, size: 109.38MB, downloads count: 11996, url: https://github.com/skylot/jadx/releases/download/v1.5.0/jadx-gui-1.5.0-no-jre-win.exe, date: 2024-04-20T18:09:24Z
 jadx-gui-1.5.0-with-jre-win.zip, size: 131.42MB, downloads count: 14262, url: https://github.com/skylot/jadx/releases/download/v1.5.0/jadx-gui-1.5.0-with-jre-win.zip, date: 2024-04-20T18:22:09Z
INFO  - Loading project /Users/nick/nickDev/com.learn.frida/packed/learnfrida.apk.jadx
INFO  - output directory: learnfrida
INFO  - loading ...
INFO  - Loaded classes: 4715, methods: 39203, instructions: 1067704
INFO  - Resetting disk code cache, base dir: /Users/nick/nickDev/com.learn.frida/packed/learnfrida.apk.cache
```

### Jadx version

1.5.0

### Java version

17

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by iiasceri** [comment]
I uninstalled jadx-gui 1.5.0 from brew and downloaded 1.4.7 release and now I am sticking with that for now. I know I should be more helpful providing logs but this is a basic functionality its nothing specific.

**Comment by jpstotz** [comment]
Sorry but from the log I don't see what is going wrong. Can you provide the APK file or at least post a screenshot of Jadx-Gui 1.5.0 after loading the APK? 

Just for the records: Do you use macOS Sonoma or something older (arm64/intel)?

**Comment by iiasceri** [comment]
@jpstotz Nevermind the UI confused me it's under the source code now.
