### ISSUE TITLE
[gui] The paths of classes in decompiled code are messed up

### ISSUE THREAD

**Issue by monkeyboss** [skylot/jadx#2192]
### Issue details

The paths of classes in decompiled code are messed up.

### Jadx version

1.5.0

### Java version

11

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by jpstotz** [comment]
Please elaborate what you want to express by your very brief description "The paths of classes in decompiled code are messed up."? 

Please provide e.g. example decompiled code and highlight what problems you have identified.

**Comment by jpstotz** [comment]
No response - closing
