### ISSUE TITLE
[gui] Incorrect package name after decompiled on some classses.

### ISSUE THREAD

**Issue by AiziChen** [skylot/jadx#2194]
### Issue details

Such as a Class named `n` in package `rq5`, so the total name is `rq5.n`, screeshot:
![image](https://github.com/skylot/jadx/assets/7786058/1c99d03b-2688-4474-a07a-83e6617ce41f)

but while I compile this Class in jadx-gui, the package will be renamed to `bv5`, total name become `bv5.n`, screenshot:
<img width="1317" alt="image" src="https://github.com/skylot/jadx/assets/7786058/726333f1-130f-492c-9168-31247f428b44">

### Jadx version

1.5.0

### Java version

21.0.2

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by jpstotz** [comment]
Can you please provide the app where you have encountered this problem? You can append .zip to the end of the APK file name and then upload it here into the issue.

**Comment by AiziChen** [comment]
[classes9.dex.zip](https://github.com/user-attachments/files/15541057/classes9.dex.zip)
@jpstotz Yes, but this APK size is larger than the maximum size limited by GitHub, so I think I can upload the DEX file to you.

**Comment by AiziChen** [comment]
Oh, This is my problem, I mixed up 2 different version of APKs.
