### ISSUE TITLE
[gui] Hide console in windows

### ISSUE THREAD

**Issue by ChineseAStar** [skylot/jadx#2196]
### Issue details

In the latest version, using jadx-gui.bat will pop up a console window, and closing it shortly after will cause the entire program to exit.
Referencing the previous issue, it is suggested to hide this console. https://github.com/skylot/jadx/issues/65#issuecomment-104901107

Refer to jadx-gui/build.gradle.kts line 95:
```kotlin
tasks.existing(CreateStartScripts::class) {
	doLast {
		val newContent =
			windowsScript.readText()
				.replace("java.exe", "javaw.exe")
				.replace("\"%JAVA_EXE%\" %DEFAULT_JVM_OPTS%", "start \"jadx-gui\" /B \"%JAVA_EXE%\" %DEFAULT_JVM_OPTS%")
		windowsScript.writeText(newContent)
	}
}
```
should change to
```kotlin
tasks.startShadowScripts {
	doLast {
		val newContent =
			windowsScript.readText()
				.replace("java.exe", "javaw.exe")
				.replace("\"%JAVA_EXE%\" %DEFAULT_JVM_OPTS%", "start \"jadx-gui\" /B \"%JAVA_EXE%\" %DEFAULT_JVM_OPTS%")
		windowsScript.writeText(newContent)
	}
}
```

For temporary use, can change jadx-gui.bat:
```bat
line 22:
set JAVA_EXE=javaw.exe
line 36:
set JAVA_EXE=%JAVA_HOME%/bin/javaw.exe
line 69:
start "jadx-gui" /B "%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %JADX_GUI_OPTS% -jar "%CLASSPATH%" %CMD_LINE_ARGS%
```

### Jadx version

1.5.0

### Java version

java 21.0.3

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
@ChineseAStar thanks for the fix :+1:
Turns out this was broken since migration to shadow jar in https://github.com/skylot/jadx/issues/1868#issuecomment-1553593985

**Comment by kiber-io** [comment]
The error is still/back in place :(
JADX 1.5.0 (from jadx.zip), Windows 11
