### ISSUE TITLE
[gui] UI not going Full screen

### ISSUE THREAD

**Issue by rew1nter** [skylot/jadx#2202]
### Issue details

Jadx-gui does not go full screen. I have tried to run it as root as well. Not working
![image](https://github.com/skylot/jadx/assets/64508791/c56aec8d-c56b-4641-bdef-31f434a5bf7e)

![image](https://github.com/skylot/jadx/assets/64508791/450bd3c6-e96a-42dc-9335-1e5fbeadf5b1)

### Jadx version

given above

### Java version

given above

### OS

- [ ] Windows
- [X] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
What Linux distribution, window manager and graphic driver do you use? Does the latest stable version behaves the same way?

**Comment by rew1nter** [comment]
Arch. BSPWM. Nvidia 470dkms. Up to date. Yes

**Comment by skylot** [comment]
@rew1nter did you try workarounds mentioned [here](https://wiki.archlinux.org/title/bspwm#Problems_with_Java_applications) and [here](https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing)?

**Comment by rew1nter** [comment]
`wmname` solved the issue thanks
