### ISSUE TITLE
[gui] macos system crash

### ISSUE THREAD

**Issue by sorosunrain** [skylot/jadx#2204]
### Issue details

I've added a jadx-gui quickstart entry to the system shortcut app:
<img width="724" alt="image" src="https://github.com/skylot/jadx/assets/10646353/4854d748-23a2-4bf2-ad74-39648dfbcdff">
<img width="473" alt="image" src="https://github.com/skylot/jadx/assets/10646353/8634e857-e4d1-4454-a64e-6ec96b3b979f">
When I right click on the jar file to execute this command, the GUI opens and operates for a while (searching, viewing classes), odds are the system will get stuck.
Jar size: 88KB
Memory available: 25GB

### Jadx version

1.5.0

### Java version

11.0.2

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by jpstotz** [comment]
Which MacOS versions do you use? 

You wrote "the GUI opens and operates for a while" - what is a while for you? Seconds, minutes, ..? Does this also happen if you don't do anything or is it related to certain commands you execute in Jadx?

**Comment by sorosunrain** [comment]
**Apple M3 Max**, **Sonoma 14.5**.
No problems using it at Terminal app or iTerm2 app, everything works fine. The problem only occurs in Shortcuts app, where after two or three normal jar or apk operations using shortcut commands, the system is unresponsive.

**Comment by sorosunrain** [comment]
It should be a problem with the System Shortcuts app itself, nothing to do with jdx-gui.
