### ISSUE TITLE
[gui] Duplicate JMenuItem in Plugin Menu

### ISSUE THREAD

**Issue by cleanriceking** [skylot/jadx#2206]
### Issue details

In the JadxPlugin interface, within the init method, addMenuAction is used. After opening jadx, click on settings and then close it. When loading an APK file, you will find that the plugin menu contains duplicate JMenuItem entries.

The reason is that the public void addToPluginsMenu(Action item) method in MainWindow does not filter out duplicate JMenuItem entries.

### Jadx version

1.5.0

### Java version

21.0.3

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
Fixed
