### ISSUE TITLE
[feature] Go to Application

### ISSUE THREAD

**Issue by xiaojye** [skylot/jadx#2208]
### Describe your idea

I hope Jadx can add a navigation button for "Go to Application", such as "Go to Main Activity". The reason is that many important analysis cases need to be processed in the Application. If Jadx could have such a navigation button, it would be faster and more convenient to perform, while also improving the user experience. Thank you to the author and all the maintainers for their consideration!

**Comment by iscle** [comment]
Added in #2213, shortcut is Ctrl + Shift + A :)

Wait for the merge and enjoy!
