### ISSUE TITLE
[feature] Is it possible to set the running RAM of jadx-gui at a fixed value

### ISSUE THREAD

**Issue by zzzzfeng** [skylot/jadx#2217]
### Describe your idea

Hi,

When opening a jadx-gui, the running RAM will be select automatically, which is usually influenced by the current RAM left.
If I want the value to be higher(which is enough for the computer), I must close some other software before opening jadx-gui.

So, is it possible to set the running RAM of jadx-gui at a fixed value.

thanks.

**Comment by jpstotz** [comment]
To my knowledge the maximum heap size for Jadx-Gui should only depend on your system RAM size. 

What OS are you on, which Java Runtime do you use and how do you start Jadx-Gui?

**Comment by zzzzfeng** [comment]
It's jadx-gui-1.5.0.exe, bundled jre.
Everytime I started it, the maximum heap size is different as shown in the bottom status bar
