### ISSUE TITLE
[gui] The GUI page displays ghosting.

### ISSUE THREAD

**Issue by ChanChuRen** [skylot/jadx#2225]
### Issue details

When I use jadx-gui-1.5.0-no-jre-win.exe on a 2k resolution screen, I encounter display component ghosting issues. The problem persists even when I switch the screen to 1080p. However, using jadx-1.4.7.zip works fine at 1080p, but ghosting still occurs when switching to 2k resolution. I haven't found similar issues reported. Initially, I thought it was a problem with my running environment, so I switched between several JDK versions, but the issue persisted. I also tried running two other GUI programs written in Java, and they displayed correctly, which makes me very puzzled. I hope to get an answer from you.
![Snipaste_2024-07-24_16-13-40](https://github.com/user-attachments/assets/ff800182-8925-40d8-88fb-321f95bbb0ca)

### Jadx version

1.5.0

### Java version

11.0.16

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
Your screenshot looks a bit like the on ein issue #1993.

As you have already tried different Java versions (I assume you tested versions like 17 and 21) you could also check if the used Jadx theme has an impact on your problem (e.g. using `default`). 

In 1080p and 2k resolution what Windows scale factor do you use (100/125/150/175%)?

**Comment by jpstotz** [comment]
You can also try the latest unstable build https://nightly.link/skylot/jadx/workflows/build-artifacts/master

It uses a newer version of the FlatLaf theme library.

**Comment by ChanChuRen** [comment]
Thank you, I will give it a try.

**Comment by skylot** [comment]
@jpstotz I checked latest unstable build (with JRE 21) and this issue appear on 'default' theme as well as on FlatLaf themes.
Also, I tried JVM flags from https://github.com/skylot/jadx/issues/1993#issuecomment-1979922874 and it resolves the issue :tada:
```
"-Dsun.java2d.noddraw=true"
"-Dsun.java2d.d3d=false"
"-Dsun.java2d.ddforcevram=true"
"-Dsun.java2d.ddblit=false"
"-Dswing.useflipBufferStrategy=True" 
``` 
I will try to investigate these flags and why they help, but at least for now we have a workaround :slightly_smiling_face:
