### ISSUE TITLE
[mappings] NullPointerException when exporting to any mappings format

### ISSUE THREAD

**Issue by jjr90** [skylot/jadx#2226]
### Issue details

**Example APK + project:**
https://drive.google.com/file/d/1auQh998Hm_pjPg7XfV_d9vT5PDXdQBUX/view?usp=sharing

**Affected versions:** release 1.5.0 and unstable (r2212.a8d889d).

**How to reproduce:** Simply open the provided project and attempt to export to any mappings format. A NullPointerException occurs (see log below) and the output file is empty.

Seems related to https://github.com/skylot/jadx/issues/2220#issuecomment-2243494265 , where **his very last exception** (MappingExporter.java:238) is identical to my log below.

This error _doesn't_ happen in jadx 1.4.7, which I used to successfully save the mappings.

```
Jadx version : 1.5.0
Java version : 11.0.9
Java VM      : Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
Platform     : Mac OS X (10.14.6 x86_64)
Max heap size: 11470 MB
Program args : -Xms128M -XX:MaxRAMPercentage=70.0 -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true -Djdk.util.zip.disableZip64ExtraFieldValidation=true -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED

java.lang.NullPointerException
	at jadx.plugins.mappings.save.MappingExporter.exportMappings(MappingExporter.java:238)
	at jadx.gui.plugins.mappings.RenameMappingsGui.lambda$saveInBackground$11(RenameMappingsGui.java:247)
	at jadx.core.utils.tasks.TaskExecutor.wrapTask(TaskExecutor.java:166)
	at jadx.core.utils.tasks.TaskExecutor.runStages(TaskExecutor.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Jadx version

1.5.0 and unstable (r2212.a8d889d)

### Java version

11.0.9

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by jjr90** [comment]
Updated the example archive (I had attached the wrong APK, so some mappings were dangling).

But the error happens regardless...

**Comment by skylot** [comment]
@jjr90 I commit a fix and NPE shouldn't appear anymore.
Anyway, I still not understand a root cause of the issue, so some variables can be missing in mapping.
I will continue to work on improving this plugin and will add some tests to prevent future regressions.

**Comment by jjr90** [comment]
If you tested it on the example, you're welcome to close this. I don't have a Java build system setup, but I can test the nightly later...
