### ISSUE TITLE
[feature] Add a context menu to export resources/classes

### ISSUE THREAD

**Issue by mrexodia** [skylot/jadx#2227]
### Describe your idea

It would be helpful to be able to export individual files by right clicking on them. Currently you have to extract the ZIP by hand to get the native libraries when reversing Android applications for instance.

![image](https://github.com/user-attachments/assets/20ba179d-8e9e-41aa-8a3d-212e8adba3fe)

**Comment by Mino260806** [comment]
I'll take this on

**Comment by mrexodia** [comment]
Thanks was quick, thank you very much! Will try it out when I'm back from vacation next week.
