### ISSUE TITLE
Missing some classes when trying to decompile [core] 

### ISSUE THREAD

**Issue by Laky-64** [skylot/jadx#2232]
### Issue details

It seems to be when some classes are used from only the C++ part, the Java Class is completely missing

This is my command:
```bash
java -cp jadx.jar jadx.cli.JadxCLI --comments-level none --no-replace-consts --no-res --no-inline-anonymous -j 12 test.apk testDir
```

### Provide sample and class/method full name

File:
https://raw.githubusercontent.com/DrKLO/Telegram/master/TMessagesProj/src/main/java/org/telegram/tgnet/TLRPC.java

Class Name:
`TL_auth_importAuthorization `

Apk:
https://install.appcenter.ms/users/drklo-2kb-ghpo/apps/telegram-beta-2/distribution_groups/all-users-of-telegram-beta-2

### Jadx version

1.5.0

**Comment by jpstotz** [comment]
Sorry but I am not able to verify your problem. Decompiling the linked APK with APKtool 2.9.3 there is no occurrence of `TL_auth_importAuthorization` neither as file name of a class not as string in one of the smali classes. Only the file `libtmessages.49.so` contains this string. 

I get the same result when I perform a ZIP content search on the linked APK. Therefore to me it seems that the class `TL_auth_importAuthorization` is not included in the APK. May be it is not used and thus was removed by an APK optimizer like Proguard.
