### ISSUE TITLE
[gui] Missing translation for spanish in the popup.rename property in the Messages_es_ES.properties file

### ISSUE THREAD

**Issue by drset** [skylot/jadx#2254]
### Issue details

The right click contextual menu on open files is missing a translation for the Spanish language.

In the Messages_es_ES.properties file we can find the following line:
**popup.rename=Nimeta ümber**

It should be translated to spanish like this:
**popup.rename=Renombrar**

### Jadx version

1.5.0

### Java version

21.0.1

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
@drset thank you for report!
I commit a fix as you suggested.
Indeed, this line was added in PR #794 and according to Google translator this is actually is an Estonian, so looks like author of that PR mistakenly assume that `ES` in file name means Estonian (actual abbreviation is `ET`) instead Spanish :cry:
