### ISSUE TITLE
[gui] Problem with color

### ISSUE THREAD

**Issue by pixkk** [skylot/jadx#2257]
### Issue details

When i open JADX, i getting this problem with colors: 

![image](https://github.com/user-attachments/assets/b32d74ff-5bcb-4fd4-b7fb-7fb37827de79)
![image](https://github.com/user-attachments/assets/655eca80-5142-4db3-bf6e-ecdaeac8296a)
![image](https://github.com/user-attachments/assets/a1c64e16-eda8-4d7b-968e-2b7e9b92575d)
![image](https://github.com/user-attachments/assets/317a980f-435e-41e6-825e-52dfb8f46056)

It smoothly stays black and white.

### Jadx version

1.5.0

### Java version

16.0.2

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
You can try switching to different theme (Preferences - Appearance -> Theme) and check if the same color problems occur. 

Alternatively you can try switching to a [Jadx version with included Java runtime](https://github.com/skylot/jadx/releases/download/v1.5.0/jadx-gui-1.5.0-with-jre-win.zip) as your Java version is out of support? 

You can also try one of our unstable versions: https://nightly.link/skylot/jadx/workflows/build-artifacts/master

**Comment by pixkk** [comment]
"cross-platform cli and gui bundle" version working fine.
