### ISSUE TITLE
JADX called with python - "Please specify input file" - Only on Linux

### ISSUE THREAD

**Issue by vincentcox** [skylot/jadx#226]
I am trying to call jadx from python, but I don't know what is causing the problem. I double checked all commando's. On windows it gives no error, but on linux (kali) it does. 

The code I use:
```
import os
import subprocess
import sys
cmd = ['jadx/bin/jadx', '-d', '~/jadx_source_code', 'diva-beta2.apk']
jadx_process = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
output_jadx = "--------- JADX OUTPUT BELOW --------- \n "
for line in jadx_process.stdout:
   output_jadx += str(line)
   print(str(output_jadx))
```

[![asciicast](https://asciinema.org/a/tnsVs4kgaZbW9X2i5WKU2Fl66.png)](https://asciinema.org/a/tnsVs4kgaZbW9X2i5WKU2Fl66)

Any idea what is causing this cross platform issue?

**Comment by vincentcox** [comment]
I found the issue. Shell=False fixed it.

**Comment by skylot** [comment]
Yeah you are right, I am also check this, but was too slow :)
Actually shell=True pass cmds directly to shell and it must be a string not array of strings, so this work also:
```python
import subprocess

cmd = 'jadx -d ~/jadx_source_code diva-beta2.apk'
jadx_process = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)

print("--------- JADX OUTPUT BELOW ---------")
while jadx_process.poll() is None:
    l = jadx_process.stdout.readline()
    print(l.decode('ascii'), end='')
print(jadx_process.stdout.read().decode('ascii'), end='')
```
Anyway, thank you for using jadx in your project [StaCoAn](https://github.com/vincentcox/StaCoAn) it is looking great!

**Comment by vincentcox** [comment]
Thanks for the kind words. The project wouldn't exists without JADX, so thank you! :)
