### ISSUE TITLE
[gui] Jump don't work for full class names in constructor call

### ISSUE THREAD

**Issue by mdee5test** [skylot/jadx#2261]
### Describe your idea

In Jadx Gui, assuming we have the following lines of code:

```java
com.package.ShareFileActivity shareActivity;  // Double-Clicking on "ShareFileActivity" works

c10223 = new com.package.ShareFileActivity(this); // Double-Clicking on "ShareFileActivity" does not work.
```

You'll notice that the double-click to jump to class declaration does not work if there's a "new" keyword before the class name. One usually has to search for the package name or manually locate it from the document tree.

It would be better if double-click worked in the "new..." prefixed statements as well. The same issue is present across all instances where the "new" keyword exists. It slows down research time, and reduces efficiency.

**Comment by skylot** [comment]
@mdee5test I commit a fix. Please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Comment by mdee5test** [comment]
Hi @skylot,

Thanks for the fix. I can confirm that it works.
