### ISSUE TITLE
[core] 16-bit resource entry offsets are not supported

### ISSUE THREAD

**Issue by pubiqq** [skylot/jadx#2267]
### Issue details

https://cs.android.com/android/platform/superproject/+/android15-release:frameworks/base/libs/androidfw/include/androidfw/ResourceTypes.h;l=1471-1473

### Jadx version

1.5.0

**Comment by skylot** [comment]
@pubiqq can you share a sample with such flag?

**Comment by pubiqq** [comment]
> can you share a sample with such flag?

android.jar from [Android SDK Platform 35](https://dl.google.com/android/repository/platform-35_r01.zip).
