### ISSUE TITLE
[core] Compact resource entries are not supported

### ISSUE THREAD

**Issue by pubiqq** [skylot/jadx#2268]
### Issue details

https://cs.android.com/android/platform/superproject/+/android15-release:frameworks/base/libs/androidfw/include/androidfw/ResourceTypes.h;l=1547-1549

### Jadx version

1.5.0

**Comment by pubiqq** [comment]
Sample [here](https://github.com/skylot/jadx/issues/2267#issuecomment-2334555118).

**Comment by skylot** [comment]
Fixed. At least sample is parsed without errors now :rofl:

**Comment by pubiqq** [comment]
> Fixed. At least sample is parsed without errors now 🤣

Indeed, albeit not without some problems:

<details><summary>Screenshot</summary>
<p>

![](https://github.com/user-attachments/assets/2dde1723-0e89-4409-a6e9-8a2f6ceec5a4)

</p>
</details> 

I'm going to create an issue about it on Monday, unless you fix it sooner, of course 🤣.

**Comment by skylot** [comment]
@pubiqq looks like these resources have different configs but same qualifiers string, this mean we miss some new config fields. In this sample, we always skip the last 12 bytes in config data, so we need to support these new flags/fields.
I will create a new issue and implement this myself.

PR from ApkTool as a reference: https://github.com/iBotPeaches/Apktool/pull/3206
