### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tasomaniac** [skylot/jadx#227]
Hey, thanks for the awesome decompiler. We are getting `IndexOutOfBoundsException` and this change fixes it already in master. https://github.com/skylot/jadx/commit/1f5cdeb01bd8d7f382815a21fafb0c2d5d0be1bf#diff-ea8a11033057866dfe33a97b0e6df3a2

Can you do a release to include this?

Thanks

**Comment by skylot** [comment]
You can use unstable builds from [here](https://bintray.com/skylot/jadx/unstable/_latestVersion#files).
And I don't think current master branch is stable enough to make release version, because after merging a lot of pull requests lately jadx got many regressions (decoding xmls is the biggest one).

**Comment by tasomaniac** [comment]
Thanks for the quick response. I then realized that there are unstable build. The particular issue that I had is fixed but now I am getting APK invalid error.

The APK I have a from an Android Wear module. I wonder if that's the cause.

**Comment by skylot** [comment]
Can you share this apk so I can reproduce error?

**Comment by tasomaniac** [comment]
Sorry, I cannot share that particular APK directly with you here.
It is basically an Android Wear APK embedded inside a regular APK.

I will try to reproduce it on a separate projects and share with you. But to be honest that is a different issue with the `unstable` 7.0 version. I would create another issue if I can reproduce it on a sample project. For now, let's close this one.
