### ISSUE TITLE
[gui] Zip entries count limit exceeded: 100000

### ISSUE THREAD

**Issue by yygutn** [skylot/jadx#2273]
### Issue details

i tried add args `-DJADX_DISABLE_ZIP_SECURITY=true`, but nothing changed

```
# Add default JVM options here. You can also use JAVA_OPTS and JADX_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xms256M" "-XX:MaxRAMPercentage=70.0" "-Djdk.util.zip.disableZip64ExtraFieldValidation=true" "-Xmx16g" "-DJADX_DISABLE_ZIP_SECURITY=true" "-DJADX_ZIP_MAX_ENTRIES_COUNT=999999"'
```

### Jadx version

jadx-r2260.5d1f0b8-all.jar

### Java version

11

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by jpstotz** [comment]
From what I see in the Jadx code `JADX_DISABLE_ZIP_SECURITY` is not a Java property name (as you have set it) but an ENV variable name.
