### ISSUE TITLE
[feature] Restore switch over string

### ISSUE THREAD

**Issue by skylot** [skylot/jadx#2288]
### Describe your idea

For simple switch over string java compiler generate lots of code, and it will be nice to restore it close to original.
Simple jadx test case:
```java
package jadx.tests.integration.switches;

import org.junit.jupiter.api.Test;

import jadx.tests.api.IntegrationTest;

import static jadx.tests.api.utils.assertj.JadxAssertions.assertThat;

public class TestSwitchOverStrings extends IntegrationTest {

  /**
   * Strings 'frewhyh', 'phgafkp' and 'ucguedt' have same hash code.
   */
  public static class TestCls {

    public int test(String str) {
      switch (str) {
        case "frewhyh":
          return 1;
        case "phgafkp":
          return 2;
        case "test":
          return 3;
        case "other":
          return 4;
        default:
          return 0;
      }
    }

    public void check() {
      assertThat(test("frewhyh")).isEqualTo(1);
      assertThat(test("phgafkp")).isEqualTo(2);
      assertThat(test("test")).isEqualTo(3);
      assertThat(test("other")).isEqualTo(4);
      assertThat(test("unknown")).isEqualTo(0);
      assertThat(test("ucguedt")).isEqualTo(0);
    }
  }

  @Test
  public void test() {
    assertThat(getClassNode(TestCls.class))
        .code()
        .doesNotContain("case -603257287:")
        .containsOne("case \"frewhyh\":");
  }
}
```
Now jadx generate this code for test method:
```java
    public int test(String str) {
      char c = 65535;
      switch (str.hashCode()) {
        case -603257287:
          if (str.equals("frewhyh")) {
            c = 0;
            break;
          }
          if (str.equals("phgafkp")) {
            c = 1;
            break;
          }
          break;
        case 3556498:
          if (str.equals("test")) {
            c = 2;
            break;
          }
          break;
        case 106069776:
          if (str.equals("other")) {
            c = 3;
            break;
          }
          break;
      }
      switch (c) {
        case 0:
          return 1;
        case 1:
          return 2;
        case 2:
          return 3;
        case 3:
          return 4;
        default:
          return 0;
      }
    }
```
Here we can see that compiler generate:
- first switch over string hash code
- one or several equality checks for actual string in case of hash code collision
- second switch (optional) to run actual case's code

> This issue recovers issue #2278, because it was deleted along with draft PRs and author Github account.

**Comment by DataM0del** [comment]
> ### Describe your idea
> 
> For simple switch over string java compiler generate lots of code, and it will be nice to restore it close to original. Simple jadx test case:
> 
> ```java
> package jadx.tests.integration.switches;
> 
> import org.junit.jupiter.api.Test;
> 
> import jadx.tests.api.IntegrationTest;
> 
> import static jadx.tests.api.utils.assertj.JadxAssertions.assertThat;
> 
> public class TestSwitchOverStrings extends IntegrationTest {
> 
>   /**
>    * Strings 'frewhyh', 'phgafkp' and 'ucguedt' have same hash code.
>    */
>   public static class TestCls {
> 
>     public int test(String str) {
>       switch (str) {
>         case "frewhyh":
>           return 1;
>         case "phgafkp":
>           return 2;
>         case "test":
>           return 3;
>         case "other":
>           return 4;
>         default:
>           return 0;
>       }
>     }
> 
>     public void check() {
>       assertThat(test("frewhyh")).isEqualTo(1);
>       assertThat(test("phgafkp")).isEqualTo(2);
>       assertThat(test("test")).isEqualTo(3);
>       assertThat(test("other")).isEqualTo(4);
>       assertThat(test("unknown")).isEqualTo(0);
>       assertThat(test("ucguedt")).isEqualTo(0);
>     }
>   }
> 
>   @Test
>   public void test() {
>     assertThat(getClassNode(TestCls.class))
>         .code()
>         .doesNotContain("case -603257287:")
>         .containsOne("case \"frewhyh\":");
>   }
> }
> ```
> 
> Now jadx generate this code for test method:
> 
> ```java
>     public int test(String str) {
>       char c = 65535;
>       switch (str.hashCode()) {
>         case -603257287:
>           if (str.equals("frewhyh")) {
>             c = 0;
>             break;
>           }
>           if (str.equals("phgafkp")) {
>             c = 1;
>             break;
>           }
>           break;
>         case 3556498:
>           if (str.equals("test")) {
>             c = 2;
>             break;
>           }
>           break;
>         case 106069776:
>           if (str.equals("other")) {
>             c = 3;
>             break;
>           }
>           break;
>       }
>       switch (c) {
>         case 0:
>           return 1;
>         case 1:
>           return 2;
>         case 2:
>           return 3;
>         case 3:
>           return 4;
>         default:
>           return 0;
>       }
>     }
> ```
> 
> Here we can see that compiler generate:
> 
>     * first switch over string hash code
> 
>     * one or several equality checks for actual string in case of hash code collision
> 
>     * second switch (optional) to run actual case's code
> 
> 
> > This issue recovers issue #2278, because it was deleted along with draft PRs and author Github account.

The deleted GitHub account in question:
![image](https://github.com/user-attachments/assets/6f309c33-26fa-44e0-9587-344ae4ab2396)

**Comment by DataM0del** [comment]
@skylot Extra: it seems like GitHub doesn't delete the issue data for suspended accounts (probably for easy recovery), you can see the comments on the issue here via the API link: https://api.github.com/repos/skylot/jadx/issues/2278/comments
Another thing: You can see data from suspended accounts, you can't get ALL of the data like if it wasn't suspended (e.g. repos), but you will get some data (e.g. events: https://api.github.com/users/Real-Packet/events, my original GitHub account: https://api.github.com/users/RealPacket/events).
Anyways, hopefully GitHub won't suspend me for using this problem for good.

**Comment by skylot** [comment]
@DataM0del thanks for letting us know. It was very weird that everything just disappear.
Anyway, I opened this issue just to save a good test case, and now this feature is implemented, so I will close this :slightly_smiling_face:
