### ISSUE TITLE
Jadx library is not working

### ISSUE THREAD

**Issue by Lohita9** [skylot/jadx#2294]
### Issue details

I tried using the latest unstable version of the Jadx library for Android, but it doesn't seem to be working. Please download the debug APK, install it on your phone, open it, click the 'Crash' button, and wait for about a minute. After that, check the classes.dex file, which should be decompiled in the /Android/data/lo.seghra.plus/files directory (the output directory I specified in the code). However, the file is not saved in that location, and I believe the library failed to decompile the classes.dex file.

### Provide sample and class/method full name

[my-debug.zip](https://github.com/user-attachments/files/17278468/my-debug.zip)

### Jadx version

latest unstable version

**Comment by jpstotz** [comment]
@Lohita9 As mentioned in #2291 Jadx doesn't work on Android at the moment and the configuration option to bypass this problem also doesn't work on Android.

**Comment by skylot** [comment]
@Lohita9 I fixed #2291 and also created an example Android app with jadx lib usage, check https://github.com/jadx-decompiler/jadx-lib-android-example repo. Main jadx usage code can be found [here](https://github.com/jadx-decompiler/jadx-lib-android-example/blob/e11a91eb193241fdb7f2435f7713f4a472cb3b66/app/src/main/kotlin/io/github/skylot/jadx/android/example/Decompile.kt#L27-L68).
