### ISSUE TITLE
[gui] CFG modification limit reached.  attached the file.

### ISSUE THREAD

**Issue by kineyed104** [skylot/jadx#2300]
### Issue details

[WebSocket$ThreadReading.zip](https://github.com/user-attachments/files/17340257/WebSocket.ThreadReading.zip)

The following error occurs when decompiling the "Run" method of the attached file's class.

```java
JADX ERROR: JadxRuntimeException in pass: BlockProcessor
        jadx.core.utils.exceptions.JadxRuntimeException: CFG modification limit reached, blocks count: 3963
        	at jadx.core.dex.visitors.blocks.BlockProcessor.processBlocksTree(BlockProcessor.java:64)
        	at jadx.core.dex.visitors.blocks.BlockProcessor.visit(BlockProcessor.java:44)
```

### Jadx version
1.5.0

**Comment by skylot** [comment]
`CFG modification limit reached` issue fixed.
Although there are many other issues preventing correct decompilation, some already have opened issues, so I will close this one.
