### ISSUE TITLE
[core] Project save speed regression

### ISSUE THREAD

**Issue by pubiqq** [skylot/jadx#2302]
### Issue details

The speed of saving projects (`File -> Save all...`) has significantly decreased after https://github.com/skylot/jadx/commit/964bd62d35df610b7a107faba84c26dd2c293f7a (in my case, from ~15 sec to ~1m 20 sec).

**Comment by skylot** [comment]
Fixed.
A solution is to scan and replace patched zip files very early in input files.
Main issue actually is that some jadx code and also plugins API forces to open same zip file several times, to resolve this we need to implement new API to allow traverse files in already opened zip.

Related to PR #2298.
