### ISSUE TITLE
[feature] (Scripts) Run code after a pass

### ISSUE THREAD

**Issue by SeanPesce** [skylot/jadx#2323]
### Describe your idea

Maybe this is already implemented, but I haven't figured out how to do it:

I have a script that runs some code in `insns` of the `jadx.replace` pass:

```kotlin
import jadx.core.dex.instructions.InvokeNode

val jadx = getJadxInstance()

jadx.replace.insns { mth, insn ->
    if (insn is InvokeNode) {
        // Some custom logic runs here
    }
}
```

It works fine, but I want to run some other code after this pass, such that the "epilogue" code only runs once (currently it's running every time `insns` is called, causing a huge performance hit). Essentially, I want something like this:

```kotlin
import jadx.core.dex.instructions.InvokeNode

val jadx = getJadxInstance()

jadx.replace.insns { mth, insn ->
    if (insn is InvokeNode) {
        // Some custom logic runs here
    }
}

jadx.replace.finished {
    // Print summary of changes (and/or other logic)
}
```

Is something like this possible with the current implementation?

**Comment by skylot** [comment]
@SeanPesce you need to force full decompilation to execute action after all classes processed and decompiled:
```kotlin
jadx.afterLoad {
    // force decompilation of all classes
    jadx.decompile.all()

    // all classes decompiled
    // insert you 'finish' code here
}
```
Jadx don't have any 'after all' stage because in jadx-gui classes decompiled on demand and all classes decompilation may not be requested at all.
