### ISSUE TITLE
[feature] Allow plugins to edit BlockNodes

### ISSUE THREAD

**Issue by eybisi** [skylot/jadx#2335]
### Allow plugins to edit BlockNodes

Plugins can't edit block nodes after BlockProcessor run, since blocks are locked. I mention specifically BlockProcessor because it adds very useful data to MethodNode (loops, dominators etc). These information can used to edit control flows For example I've used loops information from method node to find switch cases and manipulated control flow to recover it from obfuscator [link](https://x.com/0xabc0/status/1852141572957081953)

We can move `mth.finishBasicBlocks();` out of BlockProcessor to another visitor lets say BlockFinisher. Then plugins can attach into .before('BlockFinisher') to manipulate blocks. I have a PR ready for this if its okay. 

Also writing document to give general information about visitors for deobfuscation (or general) plugins will be very useful. For example if a deobfuscator plugin does MBA simplification to deobfuscate instructions when it should run? Which visitor gives best information ? I think generic cases for deobfuscation would be instruction editing, control flow editing, string deobfuscation

**Comment by skylot** [comment]
> We can move mth.finishBasicBlocks(); out of BlockProcessor to another visitor lets say BlockFinisher.

Sure, that's a good start.
Also, we need to add some method to "recalculate everything" so custom pass can call it after changing block tree overwise next plugin will get outdated info.

> Also writing document to give general information about visitors

Yeah, I should add some docs on passes, but I am awful at writing, I started many times and still not finished it :rofl:

**Comment by eybisi** [comment]
> Also, we need to add some method to \"recalculate everything\" so custom pass can call it after changing block tree overwise next plugin will get outdated info.

Yes good idea! I'm manually removing unused blocks and calling BlockProcessor again to reassing attributes.

**Comment by skylot** [comment]
@eybisi I have added method to update blocks data:
```java
BlockProcessor.updateBlocksData(mth);
```
Also, jadx libs snapshot updated, hope it works fine :slightly_smiling_face:
