### ISSUE TITLE
Lots of exception while exporting gradle project, logs attached

### ISSUE THREAD

**Issue by CaledoniaProject** [skylot/jadx#234]
Hi there, I'm trying to export a gradle project with jadx. The APK binary can be downloaded at https://github.com/dineshshetty/Android-InsecureBankv2/releases

Then in terminal I do

```
jadx/bin/jadx -e InsecureBankv2.apk > run.log
```

Jadx prints lots of exceptions, attached here
https://pastebin.com/hhC4bUTk

Should I ignore them? I'm using `jadx - dex to java decompiler, version: 0.7.0`

**Comment by A-AFTAHI** [comment]
i'm facing the same issue here lots of warning and errors.

**Comment by sergey-wowwow** [comment]
@CaledoniaProject 
Lots of errors were fixed, but not all. Please report all issues individually if they are not dups (they probably are, since there are only a few popular problems and all of them are filed)
