### ISSUE TITLE
[core] error: invalid method declaration; return type required

### ISSUE THREAD

**Issue by yooo1999** [skylot/jadx#2348]
### Issue details

Windows JADX 1.5.1, JAVA version 23.0.1
When I decompile jar I got :

```
      this.someVar = Platform.xxxxx(new xxxxx(new xxxxx.Provider() {
            AnonymousClass1() {
            }
```

So when I want to compile that java file :
`javac -cp ../some.jar:. myJava.java -g`
I got:

```
error: invalid method declaration; return type required
AnonymousClass1() {
```

### Jadx version

1.5.1

**Comment by skylot** [comment]
Can't fix without sample
