### ISSUE TITLE
[gui] Mouse shortcuts stop working

### ISSUE THREAD

**Issue by nialone** [skylot/jadx#2360]
### Issue details

Shortcut keys "Forward" and "Back" not working in 1.5.1. The version 1.5.0 is normal! Fix It! )

![изображение](https://github.com/user-attachments/assets/99a0fad6-d9ef-41a5-8d45-dd024ec3232d)

### Jadx version

1.5.1

### Java version

16.0.2

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by DataM0del** [comment]
How does it behave? I'm clicking through a few decompiled classes, clicking on one of its fields, methods, etc. & pressing the back key. It seems to be working. Not sure if this is a mouse button issue or what.

**Comment by DataM0del** [comment]
It seems to be an issue with mouse buttons only.

**Comment by alittleba1** [comment]
I had the same problem

**Comment by nialone** [comment]
> It seems to be an issue with mouse buttons only.

There is no reaction at all when clicking the mouse. 
The problem is not with JAVA, it is identical in programs.

**Comment by skylot** [comment]
Fixed. Please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

Regression introduced in 02b69d2.

**Comment by nialone** [comment]
> Fixed. Please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

It's working now. Thx!
