### ISSUE TITLE
Another APK the isn't deobfuscated

### ISSUE THREAD

**Issue by pat-ford** [skylot/jadx#237]
Hi All;
 Great program btw. Here is an apk that is dexguarded and doesn't decompile  cleanly. 
NOTE this is a malware sample, passwd infected DO NOT RUN ON A PHONE
It is an older family so it is't too bad, but...

[dexguardedMalware.zip](https://github.com/skylot/jadx/files/1782642/dexguardedMalware.zip)

**Comment by sergey-wowwow** [comment]
The app is protected by a password, so it's unable to inspect it. More over, you should report more detailed bugs
