### ISSUE TITLE
[feature] reveal in side bar

### ISSUE THREAD

**Issue by RamadhanAmizudin** [skylot/jadx#2371]
### Describe your idea

Hi, i would like to request this feature, the idea is when you do searching, and click the class file, i always need to find the file location in the (left) side bar, it kinda PITA if the apps is heavily obfuscated, it would be great to have feature to right click the file (in code panel), and have option to reveal in side bar.

thank you

**Comment by skylot** [comment]
@RamadhanAmizudin this is already added, check `View -> Sync with editor` menu action or button at toolbar with same icon.
