### ISSUE TITLE
Resources decodes incorrectly when system locale is using comma as decimal separator instead of dot

### ISSUE THREAD

**Issue by S-trace** [skylot/jadx#238]
Version: jadx-0.7.0 built with current GitHub sources
There is a problem with resoucres decoding when "Save as gradle project" is used:
```
diff ru_RU.UTF-8/src/main/res/drawable/login_edit_background.xml C/src/main/res/drawable/login_edit_background.xml
4c4
<     <stroke android:width="0,5dp" android:color="@color/color_edit_button_line"/>
---
>     <stroke android:width="0.5dp" android:color="@color/color_edit_button_line"/>
```
The comma decimal separator in "0,5dp" is rejected by Android Studio.
Temporary workaround for me is running export LC_ALL=C before starting jadx-gui

**Comment by skylot** [comment]
I made a fix. Can you check latest unstable build?

**Comment by S-trace** [comment]
Thank you, latest version works fine for me now.
