### ISSUE TITLE
[gui] variable renaming doesnt work in the middle of the code

### ISSUE THREAD

**Issue by laladlala** [skylot/jadx#2381]
### Issue details

when trying to change the variable name in the middle of the function it doesnt work.
only when mark them from the function arguments or declaration, in the middle of the function or code section its impossible.

Thanks.

### Jadx version

1.5.1

### Java version

23.0.1

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
Fixed.
Variable refs were incorrectly removed after changes from #2116.
