### ISSUE TITLE
Open files based on its magic signature and not the extension

### ISSUE THREAD

**Issue by enovella** [skylot/jadx#239]
Hi,

Many times I see that JADX only opens files with the extension ".apk" regardless if this is an APK file or not. Would it be way better to look into the magic number of this file? 

```
$ hd 087af5aacab8fc8bc7b1dcb7a138c3552d175c74b496056893299bc437422f95 |head -n1
00000000  50 4b 03 04 14 00 08 08  08 00 00 40 21 00 a7 9c  |PK.........@!...|
```

**Comment by sergey-wowwow** [comment]
@enovella any profit to do so? What if it change, it will require to change sources (like now), it will make impossible to drag and drop some files to archive to add or replace some components etc

**Comment by enovella** [comment]
Mainly, I don't usually use the feature of drag&drop that's why I always see more useful parsing by magic number rather than extension.

If you think this is not feasible, let me know and will close the issue.

Cheers

**Comment by sergey-wowwow** [comment]
@enovella I'm actually not sure what would be better for the community :) But the fix won't increase quality, but reduce the number of processable APKs

**Comment by skylot** [comment]
Sorry for late response, but this feature already exists in jadx :)
For jadx-gui in open dialog change file types filter to 'All files' and open files with any extension.
For now if file has zip magic and contains classes.dex it will be processed like apk file.

**Comment by enovella** [comment]
Thanks a lot for the clarification. It works! Great @skylot. No need to do extra changes @sergey-wowwow
