### ISSUE TITLE
Wrong variable names like <set-?> in Kotlin sources

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#242]
Hi, such names are pretty often for decompiled Kotlin codes
```java
    public final void setSwitchToVideo(boolean <set-?>) {
        this.switchToVideo = <set-?>;
    }
```

VLC application is attached. Class is ``` org.videolan.vlc.media.PlayerController ```
[VLC for Android_v3.0.4_apkpure.com.apk.zip](https://github.com/skylot/jadx/files/1822983/VLC.for.Android_v3.0.4_apkpure.com.apk.zip)

**Comment by sergey-wowwow** [comment]
By some reason I cannot find this method in real source, only that one https://code.videolan.org/videolan/vlc-android/blob/3.0.x/vlc-android/src/org/videolan/vlc/media/PlayerController.kt#L106

**Comment by Saylance** [comment]
dex-tools (with dx-23.0.0) + luyten : 
```
    public final void setSwitchToVideo(final boolean switchToVideo) {
        this.switchToVideo = switchToVideo;
```

**Comment by sergey-wowwow** [comment]
@Saylance you mean that you cannot reproduce that?

**Comment by Saylance** [comment]
nono, i can reproduce it with jadx.
i try manyally change dx-1.14 -> dx-23.0.0, but it gives same result (this.switchToVideo = <set-?>;)

**Comment by sergey-wowwow** [comment]
Fixed in type-inference-wip branch
