### ISSUE TITLE
Why don't release?

### ISSUE THREAD

**Issue by AoEiuV020** [skylot/jadx#243]
newest version is 0.6.1 release on Dec 5, 2016 ?

**Comment by sergey-wowwow** [comment]
Use the link from description
> Downloads
latest unstable build: Download

**Comment by AoEiuV020** [comment]
latest release on 2016，but now it is 2018，
Why not release a new version?

**Comment by sergey-wowwow** [comment]
It's released as unstable

**Comment by AoEiuV020** [comment]
No release of the new version will cause people to think that this project has died

**Comment by AoEiuV020** [comment]
you can release 0.7-alpha-1

**Comment by MGaetan89** [comment]
The last commit in from 5 days ago. That doesn't look like a dead project.
