### ISSUE TITLE
Possible to only decompile select files in APK?

### ISSUE THREAD

**Issue by AlanCPSC** [skylot/jadx#245]
Would it be possible to add a "save only select files" as opposed to just "save all"? 

It would really help with my work!

This problem is due to me only ever needing to look at one or two files maximum per APK. But the process to decompile each one takes extremely long (sometimes they don't even finish) https://github.com/skylot/jadx/issues/79

**Comment by sergey-wowwow** [comment]
@AlanCPSC,
Bugs like
> But the process to decompile each one takes extremely long (sometimes they don't even finish)

were fixed in unstable release a few months ago. You could use console version, now the whole decompilation process takes less a minute (usually ~5 secs), tested on dozens of APKs

**Comment by AlanCPSC** [comment]
I am getting an awful lot of warnings and errors while using the console version. Should I be concerned or is this to be expected?

https://i.imgur.com/BXvovaQ.png

**Comment by sergey-wowwow** [comment]
@AlanCPSC 
Yes, it's okay. You can simply hide them by adding ``` > /dev/null ``` on Mac/Linux, or ``` > NIL ``` on Windows

**Comment by AlanCPSC** [comment]
Nevermind, I have solved my problem. Turns out in my haste, I fo
