### ISSUE TITLE
Deobfuscation: Overriding of package-private methods

### ISSUE THREAD

**Issue by pyropeter** [skylot/jadx#246]
There seems to be a bug in the deobfuscator: It seems to assume package-private methods can be overridden from outside the package.

I'm analysing `com.ikea.tradfri.lighting` in version 1.3.0, which can be downloaded here: https://www.apkmonk.com/download-app/com.ikea.tradfri.lighting/5_com.ikea.tradfri.lighting_2017-12-28.apk/

The APK should have the md5sum `84c0a2e7fd802258db6951bb9304f52d`.

Create the following jobf:

    c android.support.v4.b.i = Fragment
    p android.support.v4.b = app

Run jadx. Read `com.ikea.tradfri.lighting/sources/android/support/v4/app/Fragment.java`. You will find the following function:

    private void mo164b() {
        this.f570D = new C0192o();
        this.f570D.m675a(this.f569C, new C01721(this), this);
    }

I am really sure this is `instantiateChildFragmentManager`. [See the code here.](https://android.googlesource.com/platform/frameworks/support/+/master/fragment/src/main/java/android/support/v4/app/Fragment.java#2213)

As you can see, jadx somehow thinks that package-private methods can be overridden. (It even misidentified the method as `private`, which should make it even more obvious it can't be overridden.)

Thanks for making jadx!

**Comment by pyropeter** [comment]
I'm using jadx from GIT commit `2cea653`, one commit before release `0.7.1`.

**Comment by asashour** [comment]
I couldn't understand "package-private methods can be overridden". Where in the output code, it was overridden? Appreciate providing what is expected, vs what is actually done.

Updated link is in: https://android.googlesource.com/platform/frameworks/support/+/cef09fe/v4/java/android/support/v4/app/Fragment.java#2037

**Comment by pyropeter** [comment]
If I am not mistaken, jadx uses the `mo####` naming scheme only for overrideable method names. So it wrongly assumes that the method could be overridden. I would expect:

```
private void m164b() {
    this.f570D = new C0192o();
    this.f570D.m675a(this.f569C, new C01721(this), this);
}
```

**Comment by asashour** [comment]
> If I am not mistaken, jadx uses the `mo####` naming scheme only for overrideable method names. So it wrongly assumes that the method could be overridden. I would expect:

I don't think this is the case, to be investigated, or someone with more knowledge about this area to provide feedback.

**Comment by sergey-wowwow** [comment]
@pyropeter 
Seems that this is an internal system method which is not exposed to user-created child classes. Try to create your own class extending ``` android.support.v4.app.Fragment ``` and override that method:
```java
    @Override
    void instantiateChildFragmentManager() {
    }
```
I see error ``` Method does not override method from its superclass ```. Probably because of that modifiers were changed by the compiler from ``` package-private ``` to ``` private ```, that's why jadx has shown them
