### ISSUE TITLE
jadx.core.utils.exceptions.JadxOverflowException: Regions stack size limit reached

### ISSUE THREAD

**Issue by tangsilian** [skylot/jadx#252]
i also meet this problem in https://github.com/skylot/jadx/issues/146

version：jadx7.0

![image](https://user-images.githubusercontent.com/17559447/38462324-bcafa6d8-3b17-11e8-9590-56a384e6d78f.png)

**Comment by sergey-wowwow** [comment]
Please reopen the ticket with APK attached if you still can reproduce it. The original ticket you’re referring #146 is fixed and closed
