### ISSUE TITLE
Conflicting names

### ISSUE THREAD

**Issue by pyropeter** [skylot/jadx#258]
Jadx sometimes generates conflicting names.

To reproduce:

- Decompile any app
- Open any class containing an attribute and a function with at least one argument.
- Use the name of the function argument as the deobfuscated name of the class attribute
- Redecompile
- Jadx will make no effort to change the function arguments name to remove ambiguity

**Comment by sergey-wowwow** [comment]
@pyropeter 
Can you please attach an example/APK of such code? And I don't actually get the bug from description

**Comment by sergey-wowwow** [comment]
@pyropeter 
I'm closing the issue since no example is provided within a month. Please also note that many issues related to deobfuscation of annotation name were fixed.
