### ISSUE TITLE
Can't decompile one method, always the same

### ISSUE THREAD

**Issue by andrewpros** [skylot/jadx#26]
Hi.
 I tried every known java decompiler and the result is always the same on one method, it just does not decompile., but the method is simple.

In jadx it is always inconsistent code error

    /* JADX WARNING: inconsistent code. */
    /* Code decompiled incorrectly, please refer to instructions dump. */

it is in utils.Api class, apiRequest method, jar file http://www59.zippyshare.com/v/27225685/file.html

Is it really that hard to fix it?

**Comment by MacdroidNilesh** [comment]
Thank you so much it's work successfully.

**Comment by chiragthummar** [comment]
how to run jadx using command line

**Comment by keai4le** [comment]
in the bin directory, ./jadx-gui

**Comment by chiragthummar** [comment]
Thanks

On Mar 4, 2017 3:22 PM, WY <notifications@github.com> wrote:

in the bin directory, ./jadx-gui

**Comment by StayZeal** [comment]
mark
