### ISSUE TITLE
Executing Jadx from php

### ISSUE THREAD

**Issue by A-AFTAHI** [skylot/jadx#262]
i'm trying to use jadx with a web application where i want to upload the apk file from an html form than pass it as an argument to jadx and execute the process from php. the problem is that the process doesn't create the folder wich contain the source and ressources and still output the process information.
i tested with both exec() and shell_exec() functions.

here are my php codes:
upload.php:
<?php
include 'reverse.php';

$target_dir = "uploads/";
$target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]);
$uploadOk = 1;
$FileType = strtolower(pathinfo($target_file,PATHINFO_EXTENSION));
// Check if image file is a actual image or fake image
if(isset($_POST["submit"])) {

    if($_FILES["fileToUpload"]["type"] != "apk" && $FileType != "apk"){
        $uploadOk = 0;
    }
    
}

if ($_FILES["fileToUpload"]["size"] > 100000000) {
        echo "Sorry, your file is too large.";
        $uploadOk = 0;
}

if ($uploadOk == 0) {
    echo "Sorry, your file was not uploaded.";
}
else {
    if (move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $target_file)) {
        echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";
    } 
    else {
        echo "Sorry, there was an error uploading your file.";
    }
}

reverse_jadx($target_file);
?>

reverse.php:
<?php
function reverse_jadx($file)
{
    $command ='/root/Downloads/jadx/build/jadx/bin/jadx '.$file;
    $command = escapeshellcmd($command);
    $output = shell_exec($command);
    echo $output;
}
?>

**Comment by A-AFTAHI** [comment]
<?php
function reverse_jadx($file)
{
    $command ='/root/Downloads/jadx/build/jadx/bin/jadx '.$file;
    $command = escapeshellcmd($command);
    $output = shell_exec($command);
    echo $output;
}
?>

**Comment by sergey-wowwow** [comment]
@A-AFTAHI,
You should ask about execution of shell commands in PHP scripts on StackOverFlow, this section is for reporting Jadx-related bugs
