### ISSUE TITLE
Invalid XML tags in layouts

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#263]
Hi, during decompilation of some apps I noticed the same invalid XML tags
```xml
    <o.ˮ android:id="@+id/lockPattern" android:layout_width="wrap_content" android:layout_height="wrap_content"/>
```
After some githubing I found that it probably should be https://github.com/deed-taimen/android_packages_apps_Settings/blob/3f66d07ab68e4b58cdab3cc8ef55022574d0490e/res/layout/choose_lock_pattern_common.xml#L85 ``` com.android.internal.widget.LockPatternView ``` tag. @skylot is that error of jadx, can you check it please?

APK: https://drive.google.com/open?id=1oLDEexZ2_KlBBKxRK9DvRvehI3oyh3A3
File: ``` res/res/layout/keyguard_screen_unlock_portrait.xml ```

**Comment by sergey-wowwow** [comment]
@skylot 
I asked apktool developer and he considers it to be obfuscation of resources. I created a pull request https://github.com/skylot/jadx/pull/280 which replaces all invalid XML tag and attribute names to randomly generated

**Comment by skylot** [comment]
@sergey-wowwow you saying that we can replace `o.ˮ` with some random string instead of `com.android.internal.widget.LockPatternView` and this xml will be correct and buildable? Or you just want modify this xml to comply xml format rules and make it parseable?

**Comment by sergey-wowwow** [comment]
@skylot 
For now at least parsable. But I guessed that if applications are working with invalid XML tags, they should work with valid but different tags too ¯\_(ツ)_/¯ For now I'm not sure that all invalid tags will be equal to ``` com.android.internal.widget.LockPatternView ```, it might be different for other layout elements

**Comment by skylot** [comment]
Ok. I don't know how this works either, but readable characters is better anyway. I will merge your pull request. Thank you! :)

**Comment by sergey-wowwow** [comment]
@skylot 
Issue should be resolved now. I tested this night a number of different apps and no errors were found regarding XML documents
