### ISSUE TITLE
Jadx forgets to decompile some methods

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#265]
Hi, 
please use the following APK: https://drive.google.com/open?id=1dxd03Yh8jVlG1gMB0p-pKAPzbOlh79j2

Construtor in class ``` jp.naver.line.android.util.bs ``` with arguments ``` Landroid/content/BroadcastReceiver;Ljava/lang/String;Z ``` is not shown in sources, but in smali code (decompiled with apktool) it exists:
```smali
.method public constructor <init>(Landroid/content/BroadcastReceiver;Ljava/lang/String;Z)V
# direct methods
.method public synthetic constructor <init>(Landroid/content/BroadcastReceiver;Ljava/lang/String;)V
    .locals 1

    .prologue
    .line 84
    const/4 v0, 0x1

    invoke-direct {p0, p1, p2, v0}, Ljp/naver/line/android/util/bs;-><init>(Landroid/content/BroadcastReceiver;Ljava/lang/String;Z)V

    return-void
.end method
```

In class ``` jp.naver.line.android.util.br ``` you can find its calls:
```java
bsVarArr[3] = new jp.naver.line.android.util.bs((android.content.BroadcastReceiver) new com.ad.tracking.cpe.agent.MyNetChange(), "android.net.conn.CONNECTIVITY_CHANGE");
```

Doesn't jadx show it if it's synthetic?

**Comment by skylot** [comment]
@sergey-wowwow thanks!
This method was incorrectly matched as synthetic constructor in inner class. Java compiler generates a lot of synthetic methods and jadx try to hide some of them, for examples check [this notes](http://www.benf.org/other/cfr/inner-class-fake-friends.html).
