### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by idb-** [skylot/jadx#269]
Any chance that a setting for realtime searching can be enabled/disabled? It becomes a real pita when you're dealing with a large project, type the first character of the search term, and it immediately begins searching and not allowing you to continue typing. Would be a real help.

**Comment by skylot** [comment]
I commit a fix for search dialog so it shouldn't hang on  typing. Please check [latest unstable](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) version.
