### ISSUE TITLE
Could you remove that search result is limited to 100

### ISSUE THREAD

**Issue by javaeryang** [skylot/jadx#270]
sometime we need to global search a code, but it,s result limited to 100, it makes me can't see all the results.
thank you a lot.

**Comment by jpstotz** [comment]
The limitation to max. 100 results should only apply to jadx 0.6.1 and older. Since 0.7.1 all search results are returned. However for usability reasons the result is split to multiple pages of 100 entries. You can change the shown page using the buttons shown on the bottom on the left side.

**Comment by javaeryang** [comment]
@jpstotz my version is 0.7.0, thank you for your reply.
