### ISSUE TITLE
Elements of enum are not decompiled, but references to them exist

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#272]
Hi,
Contents of the enum class:
```java
package com.linecorp.linepay;

public enum l {
}
```

And contents of the file with references:
```java
package com.linecorp.linepay;

public final /* synthetic */ class c {
    public static final /* synthetic */ int[] a;

    static {
        int[] iArr = new int[l.values().length];
        a = iArr;
        iArr[l.USER_INFO_DIGEST.ordinal()] = 1;
        a[l.TRACKING_TICKET.ordinal()] = 2;
        a[l.COUNTRY_CONFIG.ordinal()] = 3;
        a[l.CARD_BRANDS.ordinal()] = 4;
        a[l.TRANSACTION_CONFIG.ordinal()] = 5;
        a[l.CACHEABLE_CONFIG.ordinal()] = 6;
        a[l.CARDS.ordinal()] = 7;
        a[l.BANK_ACCOUNTS.ordinal()] = 8;
        a[l.USER_INFO.ordinal()] = 9;
        a[l.BALANCE.ordinal()] = 10;
    }
}
```
(the same with deobf option enabled)

Seems that jadx didn't decompile enum elements

APK: https://drive.google.com/file/d/1rOhOZvhN-a6FU4zzfHL1YSBfL6IleT4B/view?usp=sharing

**Comment by sergey-wowwow** [comment]
@skylot 
Decompiled with apktool, the smali file contains all enum members and methods, looks like jadx issue

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks, but I see also some methods in smali code. Are they synthetic?

**Comment by skylot** [comment]
Yes they are synthetic. Enums in java is a lot of compiler generated code, see example here: http://www.benf.org/other/cfr/how-are-enums-implemented.html
