### ISSUE TITLE
Use of never declared variable

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#273]
Hi, ``` url ``` was never declared, but accessed in the fragment:
```java
    private void doIntent(android.content.Intent intent) {
        //....
        } else if (resource.equals("openurl")) {
            url = com.valvesoftware.android.steam.community.views.SteamWebView.extractUrlFromOpenUrlUri(u);
            if (url != null) {
                loadWebViewFragment(url);
            }
        } else if (resource.equals("opencategoryurl")) {
            url = u.getQueryParameter("url");
            if (url != null) {
                loadTabbedWebViewFragment(url);
            }
        }
```

APK: https://drive.google.com/file/d/1731iVIu0J048v_e6Us30vUOxvtxkLNDN/view?usp=sharing
File: ``` com/valvesoftware/android/steam/community/activity/MainActivity.java ```

**Comment by skylot** [comment]
@sergey-wowwow made a fix for this particular case.
Problem was in incorrect variable declaration in the middle of if-else-if chain.

**Comment by sergey-wowwow** [comment]
Thanks! I will test it. BTW can you please fix freezes and deadlocks in the core? Using CLI it’s impossible to get entire sources and anything from resources (because sources are processed first)

**Comment by skylot** [comment]
Ok I will check these issues, but as workaround you can use only one thread and deadlocks will not happen.

**Comment by sergey-wowwow** [comment]
Yea, I’m already restarting decompilation, but it doesn’t work for all cases (as I remember the one with OutOfMemory is not dependent on number of threads)
