### ISSUE TITLE
Ignoring variable name information

### ISSUE THREAD

**Issue by Demon000** [skylot/jadx#276]
Is it possible to add a flag that makes jadx ignore variable name information?

I have 2 jars, one which has variable names and one without them. This makes them really hard to compare since jadx extracts the variable name information automatically.

**Comment by skylot** [comment]
Yes, it possible. I just can disable debug info parsing. Will add additional option to that.

Or, if you want, you can comment 
```java
passes.add(new DebugInfoVisitor());
```
in `jadx-core/src/main/java/jadx/core/Jadx.java` ([link to source](https://github.com/skylot/jadx/blob/5006b3e8371935a94af4b81cdc2869c20d397c1c/jadx-core/src/main/java/jadx/core/Jadx.java#L69)) and rebuild jadx.

**Comment by asashour** [comment]
This is now implemented.
