### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by mugurcagdas** [skylot/jadx#282]
Hello,

I contribute to open source projects to improve myself in the design field. I can design a logo for your project. I appreciate for your feedback.

Kindly waiting your answers

Best Regards,
Mugur Cagdas
Computer Engineer

**Comment by skylot** [comment]
@mugurcagdas great! Feel free to introduce your logo design for jadx.
Also @mingyuan-xia recently proposed his logo in #268 so we can run a small competition :1st_place_medal:
