### ISSUE TITLE
Decompile to bytecode.

### ISSUE THREAD

**Issue by TYZRPVX** [skylot/jadx#283]
Is there a way to decompile dex or jar to bytecode?

**Comment by skylot** [comment]
To disassemble dex to instruction level use `dexdump` from Android SDK, [smali](https://github.com/JesusFreke/smali) or [apktool](https://ibotpeaches.github.io/Apktool/)
For java classes you can use [javap](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javap.html) or all in one tools like [bytecode-viewer](https://github.com/Konloch/bytecode-viewer)
