### ISSUE TITLE
If statements are decompiled weirdly (or just I dont understand it?)

### ISSUE THREAD

**Issue by MPeti1** [skylot/jadx#284]
Hi!
I've came across the situation multiple times where jadx couldn't decompile some part of the code, and for example if statements made the instructions dump weird.
What i mean is that much label in this example:

> /* JADX: method processing error */
/*
Error: java.lang.NullPointerException
*/
        /*
        r1 = this;
        r0 = r1.f22136c;
        if (r0 == 0) goto L_0x0014;
    L_0x0004:
        r0 = r1.f22136c;
        r0 = r0.isShowing();
        if (r0 == 0) goto L_0x0014;
    L_0x000c:
        r0 = r1.f22136c;	 Catch:{ IllegalArgumentException -> 0x0015 }
        r0.dismiss();	 Catch:{ IllegalArgumentException -> 0x0015 }
    L_0x0011:
        r0 = 0;
        r1.f22136c = r0;
    L_0x0014:
        return;
    L_0x0015:
        goto L_0x0011;
        */
        throw new UnsupportedOperationException("Method not decompiled: X.1fB.b():void");

You can see that L_0x0004, L_0x000c and L_0x0011 are not referenced with `goto`. In this case how are these executed?

**Comment by MPeti1** [comment]
I don't have the original code, and apktool cant do anything with that class, it only writes internal error in its file.

**Comment by sergey-wowwow** [comment]
Hi, those are caused by errors during decompilation, this bug is already reported (like here https://github.com/skylot/jadx/issues/218)

**Comment by sergey-wowwow** [comment]
``` --show-bad-code ``` option may help you

**Comment by MPeti1** [comment]
Thanks, I'll try that

**Comment by MPeti1** [comment]
I looked at your bug report and this --show-bad-code makes it much better :D If I use that, will jadx include a message that xy method can be incorrect?

**Comment by sergey-wowwow** [comment]
It will add a comment:
```
    /* JADX WARNING: inconsistent code. */
    /* Code decompiled incorrectly, please refer to instructions dump. */
```

**Comment by MPeti1** [comment]
I used to see this warning, and now i checked and jadx-gui is set to show inconsistent code. What can i do if this happens?

**Comment by MPeti1** [comment]
Sorry but i think it shouldn't be closed. The problem is still here: i got the error with "show inconsistent code" enabled. Sorry for the late reply, and please reopen the issue

**Comment by venki111** [comment]
I'm also facing this error --show-bad-code option worked for only some methods. in some methods it gives
 /* JADX: method processing error */
/*
Error: java.lang.NullPointerException
*/
this comment and weird code
**Note: I used --show-bad-code even though it gives me error**
