### ISSUE TITLE
supporting system applications

### ISSUE THREAD

**Issue by A-AFTAHI** [skylot/jadx#285]
i was trying to decompile some applications and i notice that when i try system applications it said unsuppoted type.

it would be cool if jadx could decompile system applications too

**Comment by benrap** [comment]
Having the same issue when attempting to decompile SystemUI.apk using jadx gui and jadx command line.

**Comment by sergey-wowwow** [comment]
@A-AFTAHI @benrap 
Please reopen the ticket when you have an example. I've pulled ``` SystemUI.apk ``` from my phone, but don't see any issues. The app itself doesn't contain any dex files, that's the reason why jadx keeps sources empty. I also inspected different system apps previously, and also didn't meet any special errors which are reproducible only for system apps

**Comment by skylot** [comment]
@sergey-wowwow some system app contains not `.dex` but optimized `.odex`, `.vdex`, `.oat` or `.art`. These formats changes in almost every new android versions. And jadx don't support them :-(

**Comment by sergey-wowwow** [comment]
@skylot 
Should this ticket be reopened or keep it as a duplicate of https://github.com/skylot/jadx/issues/167?

**Comment by skylot** [comment]
It is a duplicate.
But I don't think jadx will support such formats in the future. Anyone must use external tools to convert them into dex.
