### ISSUE TITLE
Deobfuscator renames com.* packages to p027com.*, but not all

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#286]
Hi,
I've noticed in Bankin app (https://drive.google.com/open?id=1RhnwzWEI2uaTFbfA5BMTUG5GlIQ969rc) that when I supply option ``` --deobf ``` and open ``` sources ``` - ``` com ```, I see only ``` google ``` package, but all other packages starting with ``` com ``` were moved to ``` p027com ```. It seems to be an error. 

Moreover, I will apply a patch which changes class names in ``` AndroidManifest.xml ``` to new ones from the deobfuscation map.

**Comment by skylot** [comment]
Is this still a issue? If you don't like `com` being rename just set --deobf-min to 3.

**Comment by sergey-wowwow** [comment]
@skylot
Thanks, but why it doesn’t rename all ``` com ``` packages in this case? Is it a bug?

**Comment by skylot** [comment]
Ok. I found source of this issue :(
Jadx has class name checker (in RenameVisitor) it renames illegal java names (like starts with number or dollar sign) and executed independently of deobfuscator and even deobfuscation is disabled. So bug was in renamer it don't use pkg alias and overwrites class pkg name.
I don't like this approach were we have two places of renaming, it must be merged.
Anyway I fixed this issue. You can check it.

**Comment by sergey-wowwow** [comment]
Thanks, seems to be fixed!
