### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Darkcast** [skylot/jadx#291]
I get error while building 
Linux kali 4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64 GNU/Linux
[errormsg.txt](https://github.com/skylot/jadx/files/2064339/errormsg.txt)

**Comment by skylot** [comment]
Please double check that you use jdk 8 64 bit or later.

**Comment by Darkcast** [comment]
will it only run on jdk 8 ?

I am runing the following 

root@kali:~/Downloads/jadx# java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Debian-4)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Debian-4, mixed mode)

**Comment by skylot** [comment]
@Darkcast in latest commit I fix build for java 10. You can check it.

**Comment by Darkcast** [comment]
Thank you Captain, as always you rule.
