### ISSUE TITLE
jadx-gui search results unable to be seen without selection when using dark cinnamon theme with Adwaita-dark controls

### ISSUE THREAD

**Issue by borysboyko** [skylot/jadx#297]
![unable to see search results](https://i.imgur.com/2btkomQ.jpg)

As the image above shows, search results cannot be seen with the dark theme I am using. I am not sure if this is the theme's fault or jadx-gui's. Here is my theme selection:

![theme selection](https://i.imgur.com/KBzCTD9.png)

**Comment by skylot** [comment]
@borysboyko thanks! I fixed background colors in search.
Also I made editor theme selector in preferences so you can match window and editor colors.
Check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files)
Some screenshots:
![jadx-dark](https://user-images.githubusercontent.com/118523/41621848-8a257d36-7416-11e8-9e8e-cfbf5e18ea1c.png)
Editor theme in preferences:
![jadx-theme-options](https://user-images.githubusercontent.com/118523/41621953-d02f3060-7416-11e8-8536-de6bd7658fba.png)
If you found some bad colors or other UI issues don't hesitate to report :)

**Comment by borysboyko** [comment]
Wow, that was quick, thanks!
