### ISSUE TITLE
Ignore try/catches when dominators are missing

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#300]
Hi, very often some methods containing try-catch constructions are failed to be decompiled. May you please decompile them again without try-catches? It will allow to receive some sources instead of
```java
            throw new UnsupportedOperationException("Method not decompiled: com.smth.Activity.method():void");
```

**Comment by skylot** [comment]
Hm, you want for any error restart method decompilation with removed catch jumps?
I don't like idea of showing incorrect code, also code removing can break variables analysis and will lead to more errors :(
I will try to experiment with such approach, but I will not give this issue high priority.

**Comment by sergey-wowwow** [comment]
@skylot 
Is that better to file an issue against each case of ``` Method not decompiled ``` error?

**Comment by skylot** [comment]
@sergey-wowwow 
No, it will be a lot of issues and anyway I will need to fix them.
But I understand your point and I will try to implement your request )

P.S. Actually I already use such approach for finally block extractor, if it fail I rerun decompilation without it. And I don't like that it hide many errors which needs to be fixed.

**Comment by sergey-wowwow** [comment]
@skylot 
This behaviour might be useful when ``` --show-bad-code ``` option is enabled
