### ISSUE TITLE
When  open  text search panel,it show that:Index not initialized,search will be disabled!

### ISSUE THREAD

**Issue by luoyesiqiu** [skylot/jadx#303]
![jadx](https://user-images.githubusercontent.com/9801756/42266679-aa8d2648-7fa9-11e8-953b-acec68245f55.png)

**Comment by skylot** [comment]
@luoyesiqiu this issue was fixed recently,  please check [lastest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files).

**Comment by luoyesiqiu** [comment]
@skylot Thanks!
