### ISSUE TITLE
Does jadx-gui automatically rename symbols?

### ISSUE THREAD

**Issue by viniul** [skylot/jadx#307]
I have a java application which is probably obfuscated. However, jadx-gui gives me the following line of code. 
`String callingPackage = getCallingPackage();`
and also: 
`List arrayList = new ArrayList();` 

I have deactivated obfuscation - Are the variable names generated by jadx-gui or do they really come from the java bytecode?

**Comment by skylot** [comment]
@viniul in your example variable names are generated by jadx, because there are no debug information presents, so original local variable names are unknown.
