### ISSUE TITLE
Jadx stuck at Can't detect out node for switch block

### ISSUE THREAD

**Issue by asmirkonjevic1** [skylot/jadx#309]
Hello I'm trying to save decompiled application as gradle project, but it seems like jadx is stuck at trying to decompile one class. I'm getting this in my console.
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]
WARN  - Can't detect out node for switch block: B:16:0x0057 in util.ac.b.ॱ(util.aa.b):byte[]

It just repeats, looks like its stuck in infinite loop. I tried same thing with jadx -d in console.
apk is obfuscated.

**Comment by skylot** [comment]
@asmirkonjevic1 thanks!
I already see somewhere such problem, but can't remember in which apk (
Can you share your apk, so I can reproduce this issue?

**Comment by asmirkonjevic1** [comment]
I would but I can't its banking app on wich I'm doing pen test right now,
I just used unstable build and everything was working fine.
