### ISSUE TITLE
Method not decompiled

### ISSUE THREAD

**Issue by shorts7wound** [skylot/jadx#316]
hi i have been testing with this apk weird that i found a method not decompiled even with --show-bad-code
method in MicrophoneService 
method is RecordLoop

[apkteset.zip](https://github.com/skylot/jadx/files/2199838/apkteset.zip)

**Comment by skylot** [comment]
@shorts7wound this is a known issue reported in #295. Please wait until #295 is fixed.

**Comment by shorts7wound** [comment]
any idea when ?
thanks for getting back to me
