### ISSUE TITLE
 Try/catch wrap count limit reached

### ISSUE THREAD

**Issue by artenie** [skylot/jadx#32]
Hello, 

I stumbled upon an apk which generates the " Try/catch wrap count limit reached" exception for 2 methods:
    com/umeng/analytics/MobclickAgent.java
    com/umeng/common/net/j.java

Also, other errors are present in:
    com/umeng/common/b.java
    com/umeng/common/net/DownloadingService.java

This has been run with --show-bad-code.

The link to the apk: 
http://www37.zippyshare.com/v/44023399/file.html

Thank you.

**Comment by sergey-wowwow** [comment]
I've found the SDK (http://www.java2s.com/Code/Jar/u/Downloadumengsdkjar.htm), but provided classes are decompiled successfully
