### ISSUE TITLE
Decompile error - NullPointerException

### ISSUE THREAD

**Issue by and7ey** [skylot/jadx#320]
I am getting multiple `Error: java.lang.NullPointerException`, when trying to decompile app.
Is there any way to get it fixed?

Smali: https://pastebin.com/AW6NLc1n
Java: https://pastebin.com/7nGxJfLn
App details: https://pastebin.com/jQ6FUzf7

**Comment by sergey-wowwow** [comment]
@skylot 
The links now not active anymore. Should we close the issue?
