### ISSUE TITLE
don't auto start searching when input in global-search-window(Ctrl+Shift+F)

### ISSUE THREAD

**Issue by aj3423** [skylot/jadx#322]
In Ctrl+Shift+F window, any input can start searching, it causes the process hang when the apk is a bit large and the input is simple. For example, after input an 'a', it starts searching and freezes the window forever.

The best would be using background thread to do the job and not freeze the window, or just not automatically start searching.

**Comment by jpstotz** [comment]
AFAIR jadx does not immediately performs a search, it waits about half a second (don't remember the exact value) and then performs the search if no more characters are entered. Therefore if you don't want to search for `a` don't stop typing unless your search term is complete.

**Comment by aj3423** [comment]
Yes currently there is 'a second' delay which helps a lot. But still there is some uncertain condition like: type an 'a' and then thinking about search something else, then 'a second' passed, the process dead, it may take much time to re-index an apk of 50mb. 
This functionally is useful for small apk, it would be great if it can be turned on/off in setting.

**Comment by aj3423** [comment]
I tried the latest build, seems the problem is solved! 
Thanks!
