### ISSUE TITLE
Decompile for proguard

### ISSUE THREAD

**Issue by xoceunder** [skylot/jadx#329]
how can I decompile apk with proguard and get all the code

**Comment by jpstotz** [comment]
That depends on what you define as "all the code". 

Proguard has two main functions: 

1. Remove unused/specific code parts (e.g. Logging calls)

Of course Jadx can't decompile code that has been removed by Proguard. Code that is not included in the APK can't be decompiled - obviously.

2. Obfuscate (rename classes methods, move classes to one package)

Jadx can in general decompile Proguard obfuscated classes and methods. However usually the class and method names are gone and therefore you only see the class- and method names generated by Proguard or if you have enabled deobfuscation in Jadx new names are generated which are easier to distinguish.

Therefore if you define "all the code" as all classes and methods with their original (non-obfuscated) name the answer is no.

**Comment by xoceunder** [comment]
This application is trying to decompile

https://www.dropbox.com/s/kdfyptjdalw6hxf/IPTVSmartersPro151.apk?dl=0

**Comment by xoceunder** [comment]
@jpstotz help

**Comment by jpstotz** [comment]
I am sorry but I am not sure what you expect. You posted your question and I answered it. Then you posted a link to an APK - why? If you want to use Jadx to decompile it to it. If you encounter problems feel free to write again. 
Anyway this is an issue tracker, not a forum, therefore please post your problem report. Otherwise please close this issue.

**Comment by xoceunder** [comment]
my problem is that it does not decompile the apk

**Comment by jpstotz** [comment]
I am sorry, but "does not decompile" is not very detailed problem report. 
Please consider the general guidelines for creating a bug report: https://sqa.stackexchange.com/a/2912/24731

**Comment by jpstotz** [comment]
Enable the deobfuscation in jadx and then close jadx. You will see a ".jobf" file next to the APK files that can be edited in any text editor. The file format is obvious.

Once you are done, start Jadx again with enabled deobfuscation and it will use the modified .jobf file with your custom mapping.

**Comment by AaronWallace** [comment]
What if I have a proguard mapping file?

For example, I build my release apk to MyApp-release.apk with corresponding mapping.txt file.

Then, I want to open MyApp-release.apk in jadx using the mapping.txt file that was generated by proguard. Is that possible? The jobf format and proguard mapping.txt files use obviously different formats.

**Comment by sergey-wowwow** [comment]
@AaronWallace 
It's a very limited case, so I would recommend to write your own tool which converts ``` mapping.txt ``` format to ``` jobf ```

**Comment by ttoommbb** [comment]
> @AaronWallace
> It's a very limited case, so I would recommend to write your own tool which converts `mapping.txt` format to `jobf`

Need this tool as well. I'll be grateful if someone wrote this script and share it to me.

**Comment by skylot** [comment]
@ttoommbb there is open issue for that feature: #97, please use it for check progress.

**Comment by pjessop** [comment]
Z~”¿AZ|}??Q$### 











V

VC








-
