### ISSUE TITLE
could not create the virtual machine.

### ISSUE THREAD

**Issue by aone** [skylot/jadx#331]
could not create the virtual machine.

**Comment by skylot** [comment]
@aone please double check that you are using 64-bit java version, jadx set max memory heap to 4GB by default and this only possible on 64-bit java.

**Comment by godwinnnnn** [comment]
![image](https://github.com/skylot/jadx/assets/126738054/1d6eb424-c018-492d-aa60-2a5ff0721938)
i think i am using the 64bit java version,but it still happens ,when i double click this file "jadx-gui.bat". it prompt out as below.
and i also think my java path setting is correct , could it be something else that may cause this problem ,thx.
![image](https://github.com/skylot/jadx/assets/126738054/94875d97-f8eb-4c93-bf8b-550a02e30466)

**Comment by jpstotz** [comment]
@godwinnnnn Java SE Development Kit 8, Update 151 (JDK 8u151) was released October 17, 2017, don't you think it would be a good idea to update it? Latest version is Java 8u381. 

Or better directly switch to Java 17, next Jadx release will no longer work with Java 8 and all other Java versions between 8 and 17 are already EOL.
