### ISSUE TITLE
Deobfuscation Minimum String Length

### ISSUE THREAD

**Issue by sraboy** [skylot/jadx#332]
I recommend reverting the default deobfuscation minimum name length to 3. A lot of classes/interfaces (e.g., `Thread` and `Runnable`) have `run()` methods. An alternative option could be to exclude certain words.

Ref 6d984c0407cd6b252732869c504c997253dda13c ([here](https://github.com/skylot/jadx/blob/6d984c0407cd6b252732869c504c997253dda13c/jadx-cli/src/main/java/jadx/cli/JadxCLIArgs.java#L67))

**Comment by skylot** [comment]
@sraboy agree, I also don't like renaming packages like `com`, `org`.
