### ISSUE TITLE
Parameter (this) in method invocation is missed

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#334]
Hi, enable deobfuscation and open ``` com.p184e.p185a.p186a.EncryptedPreferences ```, look at method
```java
        /* renamed from: a */
        public com.p184e.p185a.p186a.EncryptedPreferences mo18133a() {
            return new com.p184e.p185a.p186a.EncryptedPreferences();
        }
```
but there is only one constructor of ``` EncryptedPreferences ```:
```java
    private EncryptedPreferences(com.p184e.p185a.p186a.EncryptedPreferences.C2190a c2190a) {
```

So the first method should be decompiled as
```java
        public com.p184e.p185a.p186a.EncryptedPreferences mo18133a() {
            return new com.p184e.p185a.p186a.EncryptedPreferences(this);
        }
```

APK: https://play.google.com/store/apps/details?id=com.forexfs.platform

**Comment by skylot** [comment]
@sergey-wowwow fixed. The problem was in an incorrectly replaced synthetic constructor.

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks!
