### ISSUE TITLE
Access to inexistent field (but existent in a child class)

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#346]
Hi, 
I've noticed a reference to an inexistent field in ``` com.valvesoftware.android.steam.community.SteamDBDiskCache ```:
```java
    public void Write(String uri, byte[] data) {
        IDataDiskAccess w = new DataDiskAccessByteArray();
        w.m_data = data;
        Write(uri, w);
    }
```
But field ``` m_data ``` is declared in ``` DataDiskAccessByteArray ```, but not ``` IDataDiskAccess ```. It probably calculated class of ``` w ``` based on the format parameter of ``` Write(...) ``` method, but didn't consider field accesses

APK: https://drive.google.com/open?id=1FxmWm2ho-Bj6AbWxr_SdWjNxZh14cxdY

**Comment by sergey-wowwow** [comment]
@skylot Is that possible to declare variables always with the child class, but not a base?
For example, this exists pretty often
```java
Base obj = new Derived();
```
but should be changed to
```java
Derived obj = new Derived();
```
it shouldn't break anything, but fix a lot of currently existing bugs

**Comment by skylot** [comment]
@sergey-wowwow this is a type inference issue and right now I am working on a new algorithm which should fix such issues. I hope I finish it soon :)

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks, fixed in the ``` type-inference-wip ``` branch!
