### ISSUE TITLE
JADX WARNING: Missing block: B:17:0x00c4, code:             if (r14 == false) goto L_0x0016;

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#348]
Hi,jadx-gui-0.7.2-unstable-b496-f9e7a29.exe show 27  "JADX WARNING: inconsistent code. "   ,but new version: jadx-gui-0.7.2-unstable-b512-7492889 has 192 displays JADX WARNING: Missing block...
Link  https://pan.baidu.com/s/1-IHqED4HrP50TAITxU2NLQ

**Comment by sergey-wowwow** [comment]
@zgfflc @Mingyueyixi @sleeyax 
Please provide exact classes/methods (many errors already have been fixed causing such issues)
