### ISSUE TITLE
Second mode of line numbering in class viewer?

### ISSUE THREAD

**Issue by MPeti1** [skylot/jadx#355]
While I wondered how can [this](https://imgur.com/7PUFimi) happen, I noticed that the class viewer has a [second mode](https://imgur.com/hAFm5bt) of line numbering. How is this working? it's based on the line statements in the dex? But what are these big spaces between them?

An other question is why are the methods scattered in the code like in the first picture?

**Comment by skylot** [comment]
@MPeti1
1. These line numbers read from debug section of dex and must represent an original lines in the source code.
2. There are a lot of reasons for big spaces between methods: it can be a lot of comments in original source, different code formatting style, also it can be fake lines number inserted by obfuscators or even some errors in jadx.

**Comment by MPeti1** [comment]
So if I try to arrange the code like the line numberings of jadx's viewer, it could be used for debugging?
