### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by jp1017** [skylot/jadx#363]
what's this? v0.8.0, only the jadx-dui.exe file.

![image](https://user-images.githubusercontent.com/7868514/46185400-33bf5080-c30c-11e8-8cf1-ca4f4e8c2edd.png)

**Comment by Code2Life** [comment]
same issue

**Comment by Code2Life** [comment]
seems to be i18n problem, changing language could be a temporary solution~
![image](https://user-images.githubusercontent.com/14833440/46721148-ebf1df00-cca4-11e8-80dd-3315faaad913.png)

**Comment by jp1017** [comment]
Thanks for https://github.com/skylot/jadx/pull/386
