### ISSUE TITLE
[BUG] do keyword

### ISSUE THREAD

**Issue by ytrewqytrewqytrewqytrewq1** [skylot/jadx#364]
`public static final int dn = 2131755405;
 public static final int do = 2131755406;
public static final int dp = 2131755407;`

in jadx-gui if a variable is named "do" it is highlighted as the java keyword "do", bold and blue 
![image](https://user-images.githubusercontent.com/32385661/46197319-c14d7100-c309-11e8-8643-644da606288e.png)

**Comment by skylot** [comment]
@ytrewqytrewqytrewqytrewq1 fixed for fields and method names. Thanks!
