### ISSUE TITLE
Find usage

### ISSUE THREAD

**Issue by S-trace** [skylot/jadx#370]
In jadx-0.8.0-b547-2de86b6 when I right-click on private method and select "Find usage", jadx-gui started to decompile all code of the apk, but this is unnecessary, because private methods is only accessible from class they belongs, which was already decompiled at that time.

Maybe, this thing should be optimized?
Thank you.

**Comment by S-trace** [comment]
In jadx-0.8.0-b547-2de86b6 when I right-click on private method and select "Find usage", jadx-gui started to decompile all code of the apk, but this is unnecessary, because private methods is only accessible from class they belongs, which was already decompiled at that time.

Maybe, this thing should be optimized?
Thank you.

**Comment by skylot** [comment]
@S-trace as I remember, vm not check access modifiers at runtime so some obfuscators can make all methods private and an application will still work.

**Comment by S-trace** [comment]
Is private virtual methods is possible in dex bytecode? 
I used to think that private methods is always direct

**Comment by skylot** [comment]
I mean that access modifiers at runtime are just metadata, and checked only for reflection access.
So I think it is possible, but I need to check this to be sure :)

**Comment by S-trace** [comment]
If so, maybe there should become optional (☑ Respect bytecode access modifiers), unchecking which will lead all direct methods to become private (ignoring access modifiers in bytecode), all virtual methods to become public, and all synthetic methods to become regular methods, to defeat such way of obfuscation?

**Comment by skylot** [comment]
@S-trace fixed in latest commit, see PR #439 for description.
