### ISSUE TITLE
BUG in deobfuscation 

### ISSUE THREAD

**Issue by ytrewqytrewqytrewqytrewq1** [skylot/jadx#373]
Jadx during the deobfuscation process modifies the package com.myapp.ui.activities in com.myapp.p071ui.activities . maybe ui and other packages should be whitelisted (e.g. ai, ml, ip)

**Comment by LynxKik** [comment]
`ui` could be a proguard generated name but we human know It's not. Maybe a blacklisting feature would be nice where you can stop certain names from being deobfuscated
