### ISSUE TITLE
Support encoding with encoding table please.

### ISSUE THREAD

**Issue by klikpaspor** [skylot/jadx#381]
i'm have issue decompile my apk, because when decompile using jadx the encoding like windows 1525 is detect unidentified charcter table. And is make same mistack when decompile because i think jadx remove same class example like i have MyCalass and myclass its same name but the file its not same and its diffrent class when the jadx remove same duplicated class on block blablabla is will be error on another class or block is ithink. So i'm request can u add some endcoding table support and some options with out remove duplicated class file or method. I think is better to handle the error. And once again fix the generator R and make support java.lang.RuntimeException is cannot merge I and Z when convert from smali to java is cannot merge I and Z

example code : 

`invoke-interface { v1, v2 }, Ljava/util/Set;->add(Ljava/lang/Object;)Z
move-result v1
invoke-static { v0, v1 },  // v1 is boolean but used as integer
             Landroid/preference/MultiSelectListPreference;->access$076(Landroid/preference/MultiSelectListPreference;I)Z`

and change to : 

`invoke-interface { v1, v2 }, Ljava/util/Set;->add(Ljava/lang/Object;)Z
move-result v1
if-eqz v1, :LZERO
    const v1, 1
    goto :Lend
:LZERO
    const v1, 0
:Lend
invoke-static { v0, v1 },  // v1 is boolean but used as integer
             Landroid/preference/MultiSelectListPreference;->access$076(Landroid/preference/MultiSelectListPreference;I)Z`

i think that it.so when is not corrected my opinion please correct it.

Thank You.

**Comment by skylot** [comment]
@klikpaspor sorry, but it is really hard to understand what you are asking for. It seems like you mix several issues in one, but don't give a proper explanation and examples for any of your issues.
For describe a problem you can use screenshots with incorrectly decompiled code if it is hard to explain in words, also don't forget to attach an apk or dex file so I can reproduce the issue.
