### ISSUE TITLE
Does JADX support the Android D8 and R8 engine?

### ISSUE THREAD

**Issue by duanjason** [skylot/jadx#382]
This is more a question than a defect. Does JADX support the Android D8 and the future R8 engine? If not in the current code, any plan to support them?

**Comment by skylot** [comment]
@duanjason what type of support do you expect? 
`d8` is just replacement for `dx` without any breaking changes. It can help in support for Java 8 language features, but this is not top priority now. Anyway, I will replace builtin `dx` library in near future with `d8` because `dx` is deprecated now.

**Comment by duanjason** [comment]
Hi @skylot  

Did you close this item by accident?

**Comment by skylot** [comment]
No. I answer your question and there are no issues to fix. Also, replace dx lib is not really necessary for now. So I close it.

**Comment by duanjason** [comment]
@skylot Is there a plan in place to replace the dx with d8? If so, when will it be?
