### ISSUE TITLE
Abstract method is public, override method is protected

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#387]
Hi. Class ``` cn.wps.moffice.main.framework.BaseActivity ``` declares an abstract ``` public ``` method
```java
    public abstract defpackage.fyr createRootView();
```
But ``` cn.wps.moffice.common.scanqrcode.BaseWebViewActivity ``` implements the same method with ``` protected ``` modifier
```java
    protected defpackage.fyr createRootView() {
        return aUs();
    }
```
(please note that ``` public abstract class BaseTitleActivity extends cn.wps.moffice.main.framework.BaseActivity ```, so ``` BaseWebViewActivity ``` is a child class of ``` BaseTitleActivity ```, which is a child of ``` BaseActivity ```)

APK: https://drive.google.com/file/d/1f3hZLQHZAGGTmLoLyyVnhwh7jLbEAHR4/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow this issue is an example of a problem discussed [here](https://github.com/skylot/jadx/issues/370#issuecomment-432782554).
To fix it jadx need to make a lot of different checks for access modifiers or just make all virtual methods public like @S-trace suggested [here](https://github.com/skylot/jadx/issues/370#issuecomment-432852534). I think I will implement second option with switch in preferences.

**Comment by sergey-wowwow** [comment]
@skylot, won’t it break anything else?

**Comment by sergey-wowwow** [comment]
@skylot 
Can you please implement that option? Seems that those errors are popular

**Comment by sergey-wowwow** [comment]
@skylot 
It ruins method search in tons of places, since virtual methods are widespread, and it could be called the most dangerous bug :/

**Comment by skylot** [comment]
@sergey-wowwow I made a fix in `issue-387` branch and also open PR #439 with description. Can you check/review it? It changes many methods, but I hope it will not break anything :)

**Comment by sergey-wowwow** [comment]
https://drive.google.com/file/d/1CRJq5WoMD3QrXhZBtvKl5Pa-34EoZUq5/view

I updated jadx and the issue seems still present.

Please check classes ``` com.google.firebase.messaging.FirebaseMessagingService ```
```java
    protected final android.content.Intent zzn(android.content.Intent intent) {
        return com.google.firebase.iid.zzq.zzcge().zzcgf();
    }
```

and ``` com.google.firebase.iid.zzn ```
```java
    public android.content.Intent zzn(android.content.Intent intent) {
        return intent;
    }
```

**Comment by sergey-wowwow** [comment]
Oh wait, I used wrong branch

**Comment by sergey-wowwow** [comment]
Seems that all cases are fixed! Thanks!
Will it be merged to master and wip?

**Comment by sergey-wowwow** [comment]
@skylot 
Right now I'm scarred that protected overridden methods from Android Framework will be marked as public. How do you think, is that possible?

**Comment by sergey-wowwow** [comment]
Oh yea, if you open any activity in an app, you will see
```java
    /* Access modifiers changed, original: protected */
    public void onCreate(android.os.Bundle bundle) {
```
https://developer.android.com/reference/android/app/Activity.html#onCreate(android.os.Bundle)

**Comment by skylot** [comment]
@sergey-wowwow 
Yes, they will be public because they are virtual. Why this is bad?

**Comment by sergey-wowwow** [comment]
Because since they're marked as public their signatures will be different. Such code
```java
Activity activity = ...;
activity.onCreate(null);
```
will search for a method with name ``` onCreate ``` declared in ``` android.app.Activity ``` class, so it always will invoke the empty method, but not a virtual one

**Comment by skylot** [comment]
No, VM will search method in virtual table of instance class. The only difference between public and protected is the possible call scope and not how to invoke it.
Or I don't understand your concern :(

**Comment by sergey-wowwow** [comment]
@skylot 
I mean this code won't be compilable anymore, but if it would be, it will can the empty method

**Comment by skylot** [comment]
This code compiles and prints "B":
```java
public class TestCls {
	public static class A {
		protected void call() {
			System.out.println("A");
		}
	}

	public static class B extends A {
		@Override
		public void call() {
			System.out.println("B");
		}
	}

	public static void main(String[] args) {
		A obj = new B();
		obj.call();
	}
}
```
If `A` and `B` put in different packages `obj.call()` will not compile because of protected modifier in A. And such invoke can't exists in app.
So protected calls can be used only in app class (`B`), like this:
```java
public class TestCls {
	public static class A {
		public A() {
			call();
		}

		protected void call() {
			System.out.println("A");
		}
	}

	public static class B extends A {
		public B() {
			call();
		}

		@Override
		public void call() {
			System.out.println("B");
		}
	}

	public static void main(String[] args) {
		new B();
	}
}
```
And this also prints only "B" (twice actually). Here `A` and `B` can be in different packages, result will be same.

**Comment by sergey-wowwow** [comment]
@skylot 
Oh wait, it really works!

Sorry for disturbing you :)
