### ISSUE TITLE
[FEATURE REQUEST] Allow jadx to work on .smali files directly

### ISSUE THREAD

**Issue by S-trace** [skylot/jadx#391]
Hello.

When patching applications i often run smali a path/to/file.smali and then run jadx-gui out.dex to check is patched code correct or not.
Is it possible to allow jadx/jadx-gui to assemble .smali file to .dex and then decompile it to simplify this workflow?

Thank you.

**Comment by qssq** [comment]
hope keep smali donnot delete

**Comment by LynxKik** [comment]
Jadx is a dex to java decompiler for that you need to use ApkTool.

**Comment by mingyuan-xia** [comment]
as you have siad, it is a better off a scripting job combining multiple tools than implementing that in jadx.
