### ISSUE TITLE
Read CPP APK

### ISSUE THREAD

**Issue by tolgatasci** [skylot/jadx#392]
dear friends,
I need to read cpp in apk file. Because a property is hidden here.

`public static native String test();`

**Comment by sergey-wowwow** [comment]
It's compiled and located in one of the attached ``` .so ``` libraries. You have to decompile this native library using other decompilers like IDA.Pro

**Comment by tolgatasci** [comment]
sergey how to Read .so files ?

**Comment by sergey-wowwow** [comment]
![2018-11-17_06-39-46](https://user-images.githubusercontent.com/15173437/48656259-b2df2400-ea33-11e8-850e-a6039fa397fe.jpg)
