### ISSUE TITLE
Resource ids are missing

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#394]
Hi, apk is https://drive.google.com/file/d/18oqTR1m17f9lr9CyX9Zp8IesYn7gZyoU/view?usp=sharing
If you open ``` res/res/values/strings.xml ``` you will see that string ids were missed everywhere:
```xml
    <string name="">Redo</string>
    <string name="">Text</string>
    <string name="">Undo</string>
```
I believe it's an obfuscation trick, but it probably could be somehow fixed?

**Comment by sergey-wowwow** [comment]
I've noticed that without flag ``` --no-replace-consts ``` it works fine

**Comment by LynxKik** [comment]
Hi, What is happening here is the names are actually empty so apk tool just replaces the name with their public id. You could generate random names for them to fix it.

**Comment by sergey-wowwow** [comment]
@skylot 
Sorry, didn't notice your comment. I think yes, why not :D I will fix it and submit a PR

**Comment by asashour** [comment]
A potential fix is in `ResTableParser.parseEntry()`,

```
+		if (keyName.isEmpty()) {
+			keyName = "key" + keyCounter++;
+		}
		ResourceEntry ri = new ResourceEntry(resRef, pkg.getName(), typeName, keyName);

```
