### ISSUE TITLE
App is detected as virus by quote a few antiviruses

### ISSUE THREAD

**Issue by matejdro** [skylot/jadx#398]
Here is analysis for 6d59f7716599fec52c440d8a2f40caddf47f6d6e:

https://www.virustotal.com/#/file/8fcd7bdb311d9ac2d92eeb22d8c74f3d8fc6775d9374aa2c18e9a73deda23d64/detection

**Comment by sergey-wowwow** [comment]
@matejdro 
Which app? Jadx? I see that it states ``` File name | apkchanger.exe ```

**Comment by matejdro** [comment]
Really sorry, I made issue to the wrong repo.
