### ISSUE TITLE
Use of a not declared variable

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#400]
Hi, method ``` com.ei.webservice.utils.WebServiceUtils.getCompleteURL(String baseUrl, String computeUrl, List<NameValuePair> resourcesIds) ```, at the end of that method you can notice the following part of code
```java
            for (int i = resourcesIds.size() - 1; i >= 0; i--) {
                id2 = (NameValuePair) resourcesIds.get(i);
                int pos = urlRessourcesList.indexOf(id2.getName());
                if (pos > -1) {
                    urlRessourcesList.add(pos + 1, id2.getValue());
                } else {
                    urlRessourcesList.add(0, id2.getName());
                    urlRessourcesList.add(1, id2.getValue());
                }
            }
```
where ``` id2 ``` is used, but never declared (verified on the both branches)

APK: https://drive.google.com/file/d/1ZI4umFVxsIvGQWmhWYh3ww0rDYQGLO2K/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow this is also fixed in latest commits of `type-inference-wip` branch
