### ISSUE TITLE
type-inference-wip branch: broken type inference 

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#403]
Hi,
I noticed a few cases of broken type inference in the new approach.
Method ``` com.paypal.android.foundation.biometric.FoundationBiometric.init(android.content.Context context, boolean z, boolean z2) ```
```java
        if (iAppSDK == null && z2) {
            int canAttemptUAFInit = canAttemptUAFInit(context); // this method returns short
```

Method ``` com.paypal.android.foundation.core.appsupport.ConfigImpl.unpackageAndSaveServerConfiguration(org.json.JSONObject jSONObject, boolean z) { ```
```java
                                java.lang.Object sb5 = sb4.toString(); // should be java.lang.String
```

Method ``` com.paypal.android.foundation.core.data.DataTransceiverDebugConfig.logResponse(com.paypal.android.foundation.core.data.DataTransaction dataTransaction) { ```
```java
                if (responseObject instanceof com.paypal.android.foundation.core.model.ServiceResponse) {
                    com.paypal.android.foundation.core.model.ServiceResponse serviceResponse = (com.paypal.android.foundation.core.model.ServiceResponse) responseObject;
                    java.lang.Object correlationId = serviceResponse.getCorrelationId(); // should be java.lang.String
```

Method ``` com.paypal.android.foundation.core.security.BaseSecureKeyWrapper.getPublicKeyForEncryption(@android.support.annotation.NonNull java.lang.String str) {
     ```
```java
        } catch (java.lang.Object e) { // << in master it's catch (java.lang.Exception e)
            f12878L.error("Exception in retrieving Public key", e);
            com.paypal.android.foundation.core.CommonContracts.ensureShouldNeverReachHere();
            return null;
        }
```

APK: https://drive.google.com/file/d/1pdmRyrp6rDEoYsTJn5RLhv39xXRq5Ksh/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow all cases fixed in the latest commits
