### ISSUE TITLE
native libraries are not extracted on 8.0

### ISSUE THREAD

**Issue by thelittlefireman** [skylot/jadx#412]
hi,
When i used jadx.bat or on jadx-gui file > save as gradle project : native library are not extracted/saved in the target folder.

Thanks 
Thomas

**Comment by sergey-wowwow** [comment]
Seems to be fixed in https://github.com/skylot/jadx/pull/375
I just retested it and in my test apk all native libs were saved. Please reopen the issue if you still experience such bugs
