### ISSUE TITLE
Use $ character as separator of inner classes in .jobf file

### ISSUE THREAD

**Issue by unoexperto** [skylot/jadx#415]
Could you please use `$` character as separator of inner classes in .jobf file instead of dot ?

```
c android.support.constraint.solver.widgets.d = Rectangle
c android.support.constraint.solver.widgets.e = Snapshot
c android.support.constraint.solver.widgets.e.a = C0008a
c android.support.constraint.solver.widgets.f = WidgetContainer
```

That way it would allow me to distinguish between class `a` in package `android.support.constraint.solver.widgets.e` and subclass `a` in class `e` in package `android.support.constraint.solver.widgets`.

I can provide PR if you're ok with proposed change.

I see somewhat related issue here https://github.com/skylot/jadx/issues/179

**Comment by skylot** [comment]
@unoexperto thank you for this issue! It is serious error to use not raw (without $) class names as a key for search because this can lead to name clash, like for classes with names:
```java
a.b$c
a.b.c
```
I fixed this in latest commit, please check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion).

**Comment by unoexperto** [comment]
@skylot Could you please also comment why methods are not renamed in resulting .java files even though I see them in `jobf` file ?

For example

```
m jp.line.android.sdk.login.LineLoginFuture.ProgressOfLogin.<clinit>()V = m22686<clinit>
m jp.line.android.sdk.login.LineLoginFuture.ProgressOfLogin.<init>(Ljava/lang/String;III)V = m22687<init>
```
![image](https://user-images.githubusercontent.com/1280853/50372631-0caead00-05e3-11e9-868b-7f3e164b64f0.png)

My settings are
![image](https://user-images.githubusercontent.com/1280853/50372614-ba6d8c00-05e2-11e9-93c4-d00043442139.png)

**Comment by skylot** [comment]
@unoexperto sorry, I forget to fix classes in methods :(

**Comment by skylot** [comment]
@unoexperto name length settings used like this: `shouldRename = len < minLength || len > maxLength`. So for minLength = 2 all methods with name length = 1 will be renamed.
About not renamed parts in `.jobf`: mapping contains all classes even not renamed to allow rename it by editing file and it easier if that line already exists.

**Comment by unoexperto** [comment]
@skylot I see. But how would app that uses `.jobf` know what to rename and what not ? That complicates automated syncronization of sources generated by jadx and other apps. Perhaps you could provide extra column in each line that indicates if rule was used or not ?

**Comment by skylot** [comment]
@unoexperto Hm, actually I don't see any not renamed items in jobf file. Looks like I totally forget how it works (((

**Comment by skylot** [comment]
@unoexperto anyway I commit fix for methods and fields. I hope it helps

**Comment by unoexperto** [comment]
Thanks! I'll close this issue.
