### ISSUE TITLE
Save/Restore Session

### ISSUE THREAD

**Issue by aj3423** [skylot/jadx#416]
It takes several days to analyze a complicated apk, but all analysis(tab opened/back/forward) are gone after JADX closed.
My current solution to keep the session is that keep my computer awake and never shut down :-)
It'll be great if there is a save/load feature to restore everything to when it was closed.

**Comment by sergey-wowwow** [comment]
@aj3423 
Didn't you try to use ``` jadx ```, but not ``` jadx-gui ``` to dump sources and then use source code editors like Sublime to save opened tabs?

**Comment by aj3423** [comment]
@sergey-wowwow 
Pretty good idea. I'll try this.
