### ISSUE TITLE
Another logo/icon proposal

### ISSUE THREAD

**Issue by ethanblake4** [skylot/jadx#420]
I saw #282 and #268 and decided to try my own hand at a logo!

![jadx logo](https://user-images.githubusercontent.com/9874748/50545375-15951500-0bc7-11e9-88e7-e8ab4eed874e.png)

Let me know if you like it and I'll send the SVG.

**Comment by jpstotz** [comment]
Hi ethan,

IMHO the icon looks quite good. Not sure what skylot thinks about it.

I would like to check how the icon looks when it has been scaled down to e.g. 16x16 pixels. Scaling the provided png does not make sense even for tests as this ends up in pixel mash...
Could you please provide the SVG image somehow?

**Comment by xDragonZ** [comment]
First thing come to my mind is jetbrains.com :sweat_smile:

**Comment by ethanblake4** [comment]
Thanks @jpstotz and @xDragonZ . I've revised the icon to make it a bit less Jetbrains-y and more clear at 16x16. I've attached the SVG.
![logo](https://user-images.githubusercontent.com/9874748/50710713-9c5f4d00-1020-11e9-8f19-f202ec0c4448.png)
![logo small](https://user-images.githubusercontent.com/9874748/50710722-a3865b00-1020-11e9-822c-0f448b773d02.png)

[jadxlogo.svg.zip](https://github.com/skylot/jadx/files/2728532/jadxlogo.svg.zip)

**Comment by skylot** [comment]
@ethanblake4 thanks! This is nice logos. Actually, I prefer the first variant, but I agree it is way too similar to JetBrains products.
I will prepare PR using the second variant, so we can see how it will appear in the app.

**Comment by EvgenySamarin** [comment]
> I saw #282 and #268 and decided to try my own hand at a logo!
> 
> ![jadx logo](https://user-images.githubusercontent.com/9874748/50545375-15951500-0bc7-11e9-88e7-e8ab4eed874e.png)
> 
> Let me know if you like it and I'll send the SVG.

Thx, i will use it for my copy Jadx for icon of shortcut on Ubuntu
