### ISSUE TITLE
Problem with multi-exception catch blocks

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#421]
Jadx currently has problems with catch blocks that catch more than one exception like this one:
```java
    @TargetApi(Build.VERSION_CODES.O)
    public void test() {
        try {
            System.out.println("Test");
        } catch (ProviderException | DateTimeException e) {
            throw new RuntimeException(e);
        }
    }
```
See the attached minimal example app (in the `MainActivity` class):
[app-debug.apk.zip](https://github.com/skylot/jadx/files/2721079/app-debug.apk.zip)

Note: Even if Android Studio only allows such code if minSdk is 26 or higher or the method is annotated like my example I have seen Android apps with minSdk 15 that use such code without annotation (e.g. Whatsapp).

**Comment by skylot** [comment]
@jpstotz can you suggest how to better restore such code?
Possible options:
1. multi-exception catch block (like in your example), but it will not compile back for older minSdk
2. with separate catch block and duplicated code, will compile but too verbose:
```java
    public void test() {
        try {
            System.out.println("Test");
        } catch (ProviderException e) {
            throw new RuntimeException(e);
        } catch (DateTimeException e) {
            throw new RuntimeException(e);
        }
    }
```
3. or add preference to set target for generated code and allow to switch beetween above options

**Comment by jpstotz** [comment]
My personal preference would be to re-generate the multi-exception catch block as it is the original code. Additionally readability is much better especially if the catch block becomes larger or the number of catched exceptions is higher than two.

From what I have read on StackOverflow multi-exception catch block works on Android since API 19, I don't know why Android Studio limits it to 26+. That some people may run into issues when trying to re-compile the Jadx generate decompiled project is a draw-back caused by the original source, not by Jadx. 

Anyway I am fine with any of those three options. Just implement the option that you prefer respectively requires the least effort.

**Comment by skylot** [comment]
@jpstotz I added support for multi-exceptions in a catch block. Only simple cases for now.

**Comment by jpstotz** [comment]
@skylot Thank you very much.
