### ISSUE TITLE
Jadx Python Binding

### ISSUE THREAD

**Issue by romainthomas** [skylot/jadx#424]
Hello @skylot 

First, thank you for your awesome work with Jadx. I didn't know where to contact you so feel free to close the issue as soon as to get this message.

It's just to to let you know that I did Python binding for Jadx. Here is the repo: https://github.com/romainthomas/pyjadx and you can install it with: 

```console
pip install [--user] pyjadx
```
The current version only work on Linux and OSX but I plan to support Windows

**Comment by skylot** [comment]
@romainthomas great work, thank you!
I added a link to your project to [readme](https://github.com/skylot/jadx#related-projects).
