### ISSUE TITLE
Decompiling Kotlin APKs

### ISSUE THREAD

**Issue by A-AFTAHI** [skylot/jadx#438]
Hi, I was trying to get the source code of a Kotlin APK using Jadx but the process stops after a few seconds.
here is the whole output:

INFO  - output directory: app-debug
INFO  - loading ...
INFO  - Can't find 'R' class in app package: ci.nsiaassurances.auto
INFO  - App 'R' class not found, put all resources ids to : 'ci.nsiaassurances.auto.R'
INFO  - processing ...
WARN  - No exception handlers in catch block, method: com.android.tools.ir.server.MonkeyPatcher.pruneResourceCache(java.lang.Object, java.lang.String):boolean
WARN  - Several 'all' handlers in try/catch block in com.android.tools.ir.server.MonkeyPatcher.monkeyPatchExistingResources(android.content.Context, java.lang.String, java.util.Collection):void
WARN  - No exception handlers in catch block, method: com.android.tools.ir.server.Server.handleHotSwapPatch(int, com.android.tools.ir.runtime.ApplicationPatch):int
INFO  - done

Any ideas?
thanks,

**Comment by jpstotz** [comment]
Which version of Jadx do you use? If you are using 0.8.0 try the latest [unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files).

**Comment by skylot** [comment]
@A-AFTAHI your description is useless, I don't see any issues or errors. At least mention any expected results and what is going wrong, also it is very useful to attach apk file to reproduce the issue.

**Comment by Shu-Ji** [comment]
I have the same problem:

I use the latest jadx: https://bintray.com/skylot/jadx/unstable/v0.9.0-b1062-b1588583#files

```
$ ./jadx-gui
INFO  - output directory: myapp
INFO  - loading ...
INFO  - Can't find 'R' class in app package: com.xx.authenticator
INFO  - App 'R' class not found, put all resources ids to : 'com.xx.authenticator.R'
```
And in jdax, there is only R class decompiled:

![image](https://user-images.githubusercontent.com/1127594/58685548-b5d9aa80-83ae-11e9-96b0-0591490d73ba.png)
