### ISSUE TITLE
v0.9.0 chinese display error!

### ISSUE THREAD

**Issue by shouyong** [skylot/jadx#442]
macos  10.13.6

v0.8.0:
![image](https://user-images.githubusercontent.com/37922155/52691305-7e7bf500-2f9b-11e9-80ba-fe36180ad358.png)
=================================================
v0.9.0
![image](https://user-images.githubusercontent.com/37922155/52691345-9489b580-2f9b-11e9-98d2-02c07163336f.png)

**Comment by skylot** [comment]
@shouyong which font do you use? Can you try to change it?
For me, default font bundled with jadx ([Hack](https://github.com/source-foundry/Hack#hack)) works good and can show chinese characters. But I don't check it on macOS only on Linux and Windows, sorry :(

**Comment by mancong** [comment]
Chinese mode file navigation window is all □

**Comment by skylot** [comment]
Can anyone check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files)?
I have reset default font to system font as it was before, hope it will help.
Anyway, you can always change font to one which supports your language.
