### ISSUE TITLE
Snapshot or session file to restore for analysis multiple times

### ISSUE THREAD

**Issue by jkryanchou** [skylot/jadx#444]
I prefer jadx-gui to analysis apk-decompiled than export to gradle project. While it need to decompile again and again when reopen jadx-gui. Is there any solution or method to save the decompiled results to session or snapshot file. and load it multiple times for analysis.

**Comment by skylot** [comment]
@jkryanchou no for now. But I will definitely implement this soon, mostly to solve high memory usage.
Jadx will dump decompilation result on disk and not store them all in memory, but I am still not sure how to make fast and memory efficient search index for that :(

**Comment by jkryanchou** [comment]
@skylot OK, got it. Wish it release soon.
