### ISSUE TITLE
Language Missing

### ISSUE THREAD

**Issue by dbzdivik** [skylot/jadx#445]
Hi,
Love this tool.. Currently i'm trying to decry-pt an app but Jadx wasn't able to reverse Hindi Language,
Just Square Boxes..

![image](https://user-images.githubusercontent.com/7036189/52914418-e610a800-32ed-11e9-83ad-13f356fbf6ce.png)

**Comment by skylot** [comment]
@dbzdivik can you try to change font to one which supports these characters?
Look like default font used by jadx not support unicode at all :(

**Comment by dbzdivik** [comment]
@skylot Will Check btw Android Studio was able to de-compile correct Text..
Also One More Issue in with Preference Menu

![image](https://user-images.githubusercontent.com/7036189/52914553-c7131580-32ef-11e9-813e-6aaa2befb3e0.png)

**Comment by skylot** [comment]
@dbzdivik can you check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files)?
I have reset default font to system font as it was before, hope it will help. Anyway you can always change font to one which supports your language.
