### ISSUE TITLE
type-inference-wip: jadx adds casts to generic types which don't exist in current scope

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#448]
Hi,
file ``` com/paypal/android/foundation/account/model/MutableAccountIdentificationInfo.java ```:
```java
    public MutableAccountIdentificationInfo(com.paypal.android.foundation.account.model.AccountIdentificationInfo accountIdentificationInfo) {
        super((T) accountIdentificationInfo);
    }

    public MutableAccountIdentificationInfo(com.paypal.android.foundation.account.model.MutableAccountIdentificationInfo mutableAccountIdentificationInfo) {
        super((MT) mutableAccountIdentificationInfo);
    }
```

and class declaration
```java
public class MutableAccountIdentificationInfo extends com.paypal.android.foundation.core.model.MutableDataObject<com.paypal.android.foundation.account.model.AccountIdentificationInfo, com.paypal.android.foundation.account.model.MutableAccountIdentificationInfo> {
```

So classes ``` T ``` and ``` MT ``` don't exist (but exist in the super class as generics, but it's not applicable here)

APK: https://drive.google.com/file/d/16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG/view?usp=sharing

**Comment by sergey-wowwow** [comment]
@skylot 
It must be the last issue of new type inference approach, I didn’t meet any other errors

**Comment by skylot** [comment]
@sergey-wowwow I made a fix, but only for this exact case, general fix is hard, hope this will help.

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks! It fixes a lot of issues!
