### ISSUE TITLE
Reference to a non-existed type (inner class) in a synthetic constructor

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#450]
Hi, 
File ``` com/paypal/android/p2pmobile/wallet/Wallet.java ```
```java
        /* synthetic */ Params(com.paypal.android.p2pmobile.wallet.Wallet.Params.Builder builder, com.paypal.android.p2pmobile.wallet.Wallet.C09651 c09651) {
            this(builder);
        }
```
but class ``` com.paypal.android.p2pmobile.wallet.Wallet.C09651 ``` is missing, that's why reference to the constructor
```java
            public com.paypal.android.p2pmobile.wallet.Wallet.Params build() {
                return new com.paypal.android.p2pmobile.wallet.Wallet.Params(this, null);
            }
```
is not being found :(

APK: https://drive.google.com/file/d/16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG/view?usp=sharing

**Comment by asashour** [comment]
This should be closed.

**Comment by sergey-wowwow** [comment]
@asashour @skylot 
Please check the same app, file ``` com/paypal/android/p2pmobile/onboarding/activities/OnboardingAddressLookupActivity.java ```
```java
    class OnboardingAddressLookUpAdapter extends InitialAnimationRecyclerViewAdapter<ViewHolder> {
        //...

        /* synthetic */ OnboardingAddressLookUpAdapter(OnboardingAddressLookupActivity onboardingAddressLookupActivity, C28681 c28681) {
            this();
        }
```
here class ``` C28681 ``` also doesn't exist

**Comment by sergey-wowwow** [comment]
The same in ``` com/paypal/android/p2pmobile/benefits/fragments/BenefitsFragment.java ```
```java
package com.paypal.android.p2pmobile.benefits.fragments;

public class BenefitsFragment extends com.paypal.android.p2pmobile.common.fragments.WebViewWithTokenFragment {

    class BenefitsInterface {
        private BenefitsInterface() {
        }

        /* synthetic */ BenefitsInterface(com.paypal.android.p2pmobile.benefits.fragments.BenefitsFragment benefitsFragment, com.paypal.android.p2pmobile.benefits.fragments.BenefitsFragment.C23451 c23451) {
            this();
        }
```
``` com.paypal.android.p2pmobile.benefits.fragments.BenefitsFragment.C23451 ``` is unresolved

**Comment by asashour** [comment]
With latest build, the code is:

`/* synthetic */ OnboardingAddressLookUpAdapter(OnboardingAddressLookupActivity onboardingAddressLookupActivity, OnboardingAddressLookupActivity.1 r2) {
`

or 

`/* synthetic */ OnboardingAddressLookUpAdapter(OnboardingAddressLookupActivity onboardingAddressLookupActivity, OnboardingAddressLookupActivity.AnonymousClass1 anonymousClass1) {
`

depends on decompilation settings.

**Comment by sergey-wowwow** [comment]
But anyway the parameter type class is missing, right?

**Comment by asashour** [comment]
> But anyway the parameter type class is missing, right?

Yes, the parameter type is missing.

However, the method is `synthetic` and contains a single call `this()`. I am not sure if this should be completely removed, or it should be something else.

**Comment by skylot** [comment]
I check this case, and as always, there are two issues at once:
1. Different checks for mark class as anonymous: in `ClassModifier.markAnonymousClass` and in `ModVisitor.processAnonymousConstructor`. So one check hide class but other think this class is not anonymous and continues to use it
2. jadx incorrectly process anonymous classes without default constructor, so this case:
```java
public Thread test(Runnable run) {
	return new Thread(run) {
		@Override
		public void run() {
			System.out.println("run");
			super.run();
		}
	};
}
```
decompiles to:
```java
public Thread test(Runnable run) {
    return new Thread(run) {
       AnonymousClass1(Runnable x0) {
          super(x0);
       }

       public void run() {
          System.out.println("run");
          super.run();
       }
    };
}
```
I will fix these issues :)

**Comment by asashour** [comment]
The code is correctly decompiled now.
