### ISSUE TITLE
Minus is invalid for class name identifier

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#453]
Hi,
It's everywhere, but you can open ``` com/yahoo/mobile/client/android.ecauction/runnable/AbsDeepLinkRunnable.java ```
and see
```java
    private void m7748i() {
        com.yahoo.mobile.client.share.util.UiThreadUtils.m16125a(new com.yahoo.mobile.client.android.ecauction.runnable.C1771-$$Lambda$AbsDeepLinkRunnable$Z7Ooc8uplOABudqb1Do3o1Txf2M(this), 80);
    }
```
but that expression actually means
1. ``` new com.yahoo.mobile.client.android.ecauction.runnable.C1771() ```
2. ```- ```
3. ``` $$Lambda$AbsDeepLinkRunnable$Z7Ooc8uplOABudqb1Do3o1Txf2M(this) ```

Can you please replace minuses in class name identifiers to e.g. ``` _ ```

APK: https://drive.google.com/file/d/1SMad5tO9zJevfaYYfNSzokLzpDkeHra9/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow I add removing of all invalid chars in class names.
