### ISSUE TITLE
setting page can not scroll to bottom

### ISSUE THREAD

**Issue by DesLin** [skylot/jadx#454]
description: setting page can not scroll to bottom
version: 0.9.0
machine: MacBook Pro (Retina, 13-inch, Early 2015)
os: MacOS Mojave 10.14.3 (18D109)
<img width="421" alt="setting" src="https://user-images.githubusercontent.com/3025666/53214416-769d0e80-3687-11e9-8e84-97297da43906.png">

**Comment by skylot** [comment]
@DesLin this issue already fixed in [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files).

**Comment by jpstotz** [comment]
@skylot From a long-term perspective it may be better to introduce multiple tabs here instead of scrolling or do you disagree?

**Comment by skylot** [comment]
@jpstotz I agree, tabs will be good or maybe categories list at left like in idea or [here](https://github.com/dlemmermann/PreferencesFX#preferencesfx), it is hard to decide ))
