### ISSUE TITLE
Missing app package class when decompile apk 

### ISSUE THREAD

**Issue by mdtuyen** [skylot/jadx#456]
I tried decompile apk file. However, I found that the entire data in the app's package has been lost.

This is similar when I try to extract with the apk tool.

Here is apk link: [apk](https://d-01.winudf.com/b/apk/Y29tLnlvdWRhby50cmFuc2xhdG9yXzU2MTgwMF83NzJjOThkNQ?_fn=RGVhciBUcmFuc2xhdGUg4oCUIGZyZWUgRW5nbGlzaCB0cmFuc2xhdGlvbl92My44LjBfYXBrcHVyZS5jb20uYXBr&_p=Y29tLnlvdWRhby50cmFuc2xhdG9y&as=7e15c486f13d04eb5935bd025ef74bbf5c749d1b&c=1%7CTOOLS%7CZGV2PVlvdWRhby5jb20mdD1hcGsmdm49My44LjAmdmM9NTYxODAw&k=0634305456b3dc2a58343c2e360d6ebe5c77f403)

**Comment by jpstotz** [comment]
What do you mean with _"the entire data in the app's package has been lost"_? 

Can you give an example?

Note that the APK file you mentioned is heavily obfuscated. Therefore you won't find plain text Strings or method names, however this is not the fault of Jadx or apktool.

**Comment by mdtuyen** [comment]
@jpstotz 
You can see that all the activity classes specified in Manifest are not found after decompile.

**Comment by jpstotz** [comment]
@mdtuyen As I said the APK file and therefore the DEX file is heavily obfuscated. On dex level only 62 classes are visible. That is a pretty low class count for an 9 MB DEX file. I assume it contains an additional encrypted DEX file that is loaded at runtime. Such mechanisms can't be automatically reversed by a static tool like Jadx. 

If you want the dex code you may be successful extracting the classes at runtime using for example Frida.
 
From my perspective this issue can't be solved -> issue can be closed.

**Comment by skylot** [comment]
@jpstotz thank you for the explanation! I am closing this issue.
