### ISSUE TITLE
Static variable names collide with local names

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#458]
Hi, file ``` com/paypal/android/foundation/paypalcore/FoundationPayPalCore.java ```
```java
    public static void setAuthenticationManager(com.paypal.android.foundation.paypalcore.AuthenticationManager authenticationManager) {
        com.paypal.android.foundation.core.CommonContracts.requireNonNull(authenticationManager);
        authenticationManager = authenticationManager; // <<<
    }
```

I believe that static assignment should be changed to 
```java
        FoundationPayPalCore.authenticationManager = authenticationManager;
```

APK: https://drive.google.com/open?id=16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG

**Comment by skylot** [comment]
I have fixed that in type-inference-wip branch by forbidding fields names using in methods as vars, so `authenticationManager` parameter will have a different name (`authenticationManager2` actually). I can copy this solution to master if you want.
Also, do you think that add class to all static field access is a good idea? Now class name added only if it not equal current class. I think it will be easier to understand that it is field access.

**Comment by sergey-wowwow** [comment]
@skylot 
Sorry, forgot that I already reported similar thing against WIP branch :) It's fixed over there.
> Also, do you think that add class to all static field access is a good idea?

It was a suggestion how to fix it :) But since it's already fixed, don't mind :D
