### ISSUE TITLE
Use of register names instead of variables

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#459]
Hi,
file ``` com/paypal/android/foundation/interapp/presentation/activity/SinglePaymentWebActivity.java ```
```java
    private java.lang.String getCheckoutUrl(android.net.Uri uri, boolean z) {
        //...
        java.lang.StringBuilder stringBuilder = new java.lang.StringBuilder(r0);
        stringBuilder.append("://");
        stringBuilder.append(r1);
        //...
    }
```
registers are used, but not ``` uri.getScheme() ``` and ``` uri.getHost() ```

APK: https://drive.google.com/open?id=16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG

**Comment by skylot** [comment]
Hm, this type of issues already fixed in type-inference-wip branch and I don't want to fix them in master.
So I can suggest using a type-inference-wip branch, issues #457 and #458 also fixed in that branch.
