### ISSUE TITLE
synchronized statement - inconsistent code

### ISSUE THREAD

**Issue by jmue** [skylot/jadx#46]
the following snipped generates inconstent code warning:

    static class MyException extends Exception {
        MyException() {
        }

        MyException(String msg, Throwable rootCause) {
            super(msg);
        }
    }

    static class MyThread extends Thread {

        MyException e = null;

        MyThread()
        {
            super();
        }

        public void run()
        {
            synchronized (this)
            {
                try
                {
                    throw new MyException();
                }
                catch (MyException e)
                {
                    this.e = e;
                }
                catch (Exception x)
                {
                    this.e = new MyException("MyThread", x);
                }
            }
        }
    }

**Comment by riboribo** [comment]
I have some code that regenerates an R.java file like:

    // Autogenerated file.  Regenerated from .apk file resources.arsc file by JADX

    package com.sizzle.carPrice;

    public final class R {
      public static final class string {
	public static final int accuracy_low = 0x7f0a0005;  // "Low (40m)"
	public static final int accuracy_low_imperial = 0x7f0a0006;  // "Low (44yd)"
	public static final int accuracy_medium = 0x7f0a0007;  // "Medium (20m)"
	public static final int accuracy_medium_imperial = 0x7f0a0008;  // "Medium (22yd)"
	public static final int activity = 0x7f0a0009;  // "Activity"
	public static final int add_car = 0x7f0a000a;  // "Add"
	public static final int add_car_title = 0x7f0a000b;  // "Select car type"
      } // end of string class

      public static final class id {
	public static final int fallback_dialog_label_none = 0x7f080000;
	public static final int fallback_dialog_title = 0x7f080001;
      } // end of id class

      public static final class dimen {
	public static final int app_defaultsize_h = 0x7f070000;  // "598.0dip"
	public static final int app_defaultsize_w = 0x7f070001;  // "632.0dip"
      } // end of dimen class

      public static final class integer {
	public static final int defaultVersion = 0x7f090000;  // "20"
      } // end of integer class

      public static final class color {
	public static final int black = 0x7f060000;  // "#ff000000"
	public static final int black_50_opacity = 0x7f060001;  // "#80000000"
	public static final int error = 0x7f060002;  // "#ffb30400"
      } // end of color class
    } // end of R class

and replaces the large integers with references like:  R.string.accuracy_low and displays the text of the string as a comment after the code (to make understanding easier).  Skylot, are you working on that?
