### ISSUE TITLE
Problem on methods with Java 8's lambda expressions.

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#467]
![image](https://user-images.githubusercontent.com/35992798/54430106-7ce34f80-4748-11e9-9f1e-c1ab30d01ffunctions
As you can see in the image jadx doesn't properly work with Java 8's lambda functions. Is this something wrong with Jadx or Java compiler that compiles the methods which have lambda expressions like this?

Are there any possibilities to eliminate this on feature?

**Comment by redmi111** [comment]
![image](https://user-images.githubusercontent.com/35992798/54430254-072bb380-4749-11e9-89b3-d2a6b10020af.png)

**Comment by jpstotz** [comment]
@redmi111 I am sorry but I don't see in the image that jadx doesn't properly. The shown code looks like a regular Lambda class generated by the Java compiler. It does not look pretty but that is the code that is executed.

Or are you referring to one specific issue I did not recognize at the first glance?

**Comment by redmi111** [comment]
I'm just referring the weirdly named classes with $$

**Comment by redmi111** [comment]
![image](https://user-images.githubusercontent.com/35992798/54430666-47d7fc80-474a-11e9-8a63-987455c0a765.png)
deobfuscate option seems to be doing somewhat Good. but anyways why methods are being decompiled as classes. I suspect the way it was(APK) compiled.

**Comment by skylot** [comment]
@jpstotz looks like @redmi111 expected classes to be inlined, jadx can do that, but in this case, some check failed and class not inlined.
@redmi111 can you share this apk, so I can reproduce it?

**Comment by redmi111** [comment]
[](https://we.tl/t-97DbAUzxz0 )Here's the link to APK which have this issue.

**Comment by skylot** [comment]
@redmi111 because this is not real lambda methods from java 8, android compiler desugar them and lambdas became just anonymous classes, so such bytecode can run on old android versions, see [here](https://developer.android.com/studio/command-line/d8#j8) for details.

**Comment by redmi111** [comment]
Do you know any workaround to overcome this?

**Comment by skylot** [comment]
@redmi111 I made class inlining for some cases. Please check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files).
Future improvements:
* Inline classes used by `INSTANCE` static field
* Remove synthetic fields in inlined classes if the field type is not outer class
* Inline `lambda$*` methods

**Comment by redmi111** [comment]
Thank You I will try it out.

**Comment by redmi111** [comment]
![image](https://user-images.githubusercontent.com/35992798/54484298-57119400-4889-11e9-9b24-4c5bec159028.png)
Here's the before vs after. Huge improvement. Thank you for your prompt help.

**Comment by redmi111** [comment]
![image](https://user-images.githubusercontent.com/35992798/54485620-ee82e100-48a1-11e9-8d8e-1d19af16026f.png)
Having this small issue. It's not a big deal 'cause I could take reference from the stable version. I hope this will get fixed on feature versions.

**Comment by skylot** [comment]
@redmi111 I made a fix for that NPE issue. Thank you for report!

**Comment by asashour** [comment]
I guess this should be closed

**Comment by skylot** [comment]
Work on improving "desugared" lambdas will continue in issue #523.
