### ISSUE TITLE
Stop responding because of using too high ram

### ISSUE THREAD

**Issue by derodevil** [skylot/jadx#469]
I have an apk file with 36MB in size. I try to open the file and it works. When I click 

> Text search

 button it runs well until the process of indexing. Then it stops responding in 90% indexing progress. I see it uses more than 4GB of ram where it's the limit (maybe). My laptop has 8GB of ram.

**Comment by jpstotz** [comment]
There are only two options when Jadx is running out of RAM:

1. Open the preferences dialog and add packages you want to exclude from decompiling. The more classes you exclude the more you save.

2. Assign more RAM to Jadx
See https://github.com/skylot/jadx#troubleshooting

If you are on Windows and using `jadx-gui.exe` you can create a file next to the exe file named `jadx-gui.l4j.ini` and the content `-Xmx6g`. This will increase the memory available to Jadx.

@skylot What do you think of making a Wiki page for all the memory related Q&A? Editing the Readme.md via PR is IMHO a large overhead.

**Comment by skylot** [comment]
@jpstotz nice idea! I add [this page](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A), you can try edit it :+1:

**Comment by ahmsabryy** [comment]
> 

I do all the steps you said, but still Jadx running with 1 giga RAM.

**Comment by jpstotz** [comment]
@ahmsabryy Yes Jadx requires more than 1GB RAM that is expected. Even if you configure `Code cache` and `Usage cache` to DISK Jadx will require a significant amount of RAM. 1-3 GB RAM are expected. The old Jadx versions, this issue belongs to, had even more RAM usage, depending on the APK to load up to 12GB RAM were required.

Newer versions of Jadx configured to use disk for caching doesn't need that much RAM, but the recommended system to use Jadx is still 8GB RAM.

**Comment by ahmsabryy** [comment]
OK i understand what u said but i still have a problem to try to make the jadx running more than one ram but i can't so
 What is the Solution now 

> @ahmsabryy Yes Jadx requires more than 1GB RAM that is expected. Even if you configure `Code cache` and `Usage cache` to DISK Jadx will require a significant amount of RAM. 1-3 GB RAM are expected. The old Jadx versions, this issue belongs to, had even more RAM usage, depending on the APK to load up to 12GB RAM were required.
> 
> Newer versions of Jadx configured to use disk for caching doesn't need that much RAM, but the recommended system to use Jadx is still 8GB RAM.

**Comment by jpstotz** [comment]
Please post more details about your system, especially OS + version and available RAM in your system. 

The easiest way would be to create a  "Sample error report" (see Jadx help menu) and post at least the first 6 lines.

**Comment by ahmsabryy** [comment]
> 

Processor	Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz   3.20 GHz
Installed RAM	8.00 GB
System type	64-bit operating system, x64-based processor
Windows 10 pro

**Comment by jpstotz** [comment]
@ahmsabryy And what Jadx version do you use? What have you configured for `Code cache´ and `Usage cache`?

**Comment by ahmsabryy** [comment]
@jpstotz 
Jadx VERSION : 1.4.7 
![gittt](https://github.com/skylot/jadx/assets/50390746/405fa393-da05-4393-b925-d85ba29862e9)
 the .ini file has "-Xmx8g"

**Comment by skylot** [comment]
@ahmsabryy you should rename `jadx-gui.l4j.ini` to `jadx-gui-1.4.7-no-jre-win.l4j.ini` (i.e. same base file name as exe)

**Comment by ahmsabryy** [comment]
@skylot @jpstotz 
i renamed the file and still Jadx open 
![hub](https://github.com/skylot/jadx/as
![hub1](https://github.com/skylot/jadx/assets/50390746/bed98bde-eb48-47d4-a8c2-252c3c965511)
sets/50390746/312496bd-388e-4d12-ac01-ea909c5f2fb5)
with GB ram

**Comment by ahmsabryy** [comment]
> 
![hub](https://github.com/skylot/jadx/assets/50390746/291be1b0-4f80-4d36-a338-db8dd7655405)

**Comment by ahmsabryy** [comment]
> @ahmsabryy can you check if you have anything java related in system environment variables? Because by default, jadx sets minimum 4GB, so 1GB can be only set manually.

Can u suggest places to check it ?

**Comment by skylot** [comment]
> Can u suggest places to check it ?

I mean system variables in `System properties->Advanced tab->Environment variables`, same as in this guide: https://explainjava.com/set-java-path-and-java-home-windows/

**Comment by jpstotz** [comment]
@ahmsabryy I strongly recommend that finally post a full sample error report (see help menu of Jadx) that would answer a lot of our questions and help us to identify the root cause. My assumption that you are using a non-standard or outdated Java Runtime which causes this issues. The sample error report would contain all the necessary details... 

BTW: Setting the max heap size to 8GB on a system with 8GB RAM is as far as I know not possible. Windows requires at least 2GB on its own. Java may even ignore this setting because it is impossible.

**Comment by itis911** [comment]
@jpstotz After a lot of research on the reason for the descent of the ram in Java programs, I came to the conclusion that it is there in the system variables as a _JAVA_OPTIONS and its value is -Xmx1024M, so any Java program will have the maximum heap size of 1024 megabytes, so I change it.
