### ISSUE TITLE
Does not find Java on Windows

### ISSUE THREAD

**Issue by nick-morhun** [skylot/jadx#471]
I downloaded release v0.9.0 (exe and zip) and it will not launch on Windows 10 x64..
It cannot find my Java installation. I have JRE 1.8.201 x86 installed.

**Comment by skylot** [comment]
@nick-morhun make sure you have `javaw.exe` in `PATH` environment variable or setup `JAVA_HOME` variable.
Also, you can manually edit `jadx-gui.bat` and at `set JAVA_EXE=javaw.exe` specify the full path to exe.
And as soon as jadx by default set max memory usage to 4GB you will need JRE x64 installed.

**Comment by nick-morhun** [comment]
So maybe it needs x64 JRE?

**Comment by jpstotz** [comment]
Yes you need 64bit for running jadx-gui.exe. 

Usually you are redirected to the 64 bit Java version the web page has detected that your system is 64bit capable. May be your web browser hides this information and therefore you only get the 32 bit version.

Anyway I would switch to 64 bit Java, no one needs nowadays the 32 bit version anymore. Personally I would recommend to use Java 11.

**Comment by skylot** [comment]
@nick-morhun I made a bundle with included JRE 11 x64 for jadx version 0.9.0.
Download from release page: [jadx-gui-0.9.0-with-jre-win.zip](https://github.com/skylot/jadx/releases/download/v0.9.0/jadx-gui-0.9.0-with-jre-win.zip)
After unpack just double click `jadx-gui.bat`.

P.S. [Here](https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=hotspot#x64_win-jre) a nice intallation guide and a link to download OpenJDK 11 x64 JRE bundle.

**Comment by nick-morhun** [comment]
Thank you very much.
