### ISSUE TITLE
[help/question] Help with implementing Android lambda de-sugaring

### ISSUE THREAD

**Issue by HellPie** [skylot/jadx#472]
I have written some basic code that re-sugars lambdas to a certain extent. So far the code is only supposed to recognize an anonymous class which was desugared from a lambda because Android prefixes them all as `-$$Lambda$`, after that the code drops the last part of the class name, which on Android is the MD5 hash of the source code that the lambda originally contained at compile time, prefixed with a `$` to separate it from the central part, which is in the form `ClassName$OptionalSubClassName$MaybeMore$optionalMethodName`. The code fallbacks whenever that part is missing and doesn't handle well Proguard/R8 minified classes due to how I handle the part relative to the `methodName`, but I have worse issues going on at the moment.

So far I managed to get the code to work, but it only works partially, the system renames classes based on the interface they implement, nests them under the class that invokes them, but here lies the issue:
Lambda classes are not inner classes and I rename them in https://github.com/skylot/jadx/blob/master/jadx-core/src/main/java/jadx/core/dex/visitors/RenameVisitor.java#L76 by switching to my code if the name contains `$$Lambda$` and doing all the messy renaming job. This results in the following issue, which I don't really know how to fix since I don't know well how JaDx works, it's my first time working on it.

![image](https://user-images.githubusercontent.com/2611921/54473945-f88fdb80-47de-11e9-8700-dc1221e2d2c6.png)

**Comment by HellPie** [comment]
I just realized lambda inlining has been implemented and merged 15 hours ago, my approach was a more "complex" idea to:
- create a class for the interface implementation
- move the lambda code inside it
- inline the class at a later date by actually writing it as a lambda

But since the current implementation is much cleaner, I'm closing this issue and dropping my plans.

**Comment by skylot** [comment]
@HellPie I really appreciate your efforts to improve jadx! Thank you!
But next time before writing a lot of code I suggest opening issue with your thoughts and plans so I can help with implementation and also for work coordination.

**Comment by HellPie** [comment]
I was planning to open a PR, but first I wanted to know if it was actually possible to implement what I wanted. I didn't waste a lot of time on it. I'm partly happy to see I can stop worrying about it because the current implementation is so much cleaner than mine.
