### ISSUE TITLE
public class 48 ?

### ISSUE THREAD

**Issue by zaoqi** [skylot/jadx#473]
It generated `public class 48 ...`

**Comment by skylot** [comment]
@zaoqi please check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files). If this issue still exists, then share apk sample and full class name with such issue, so I can reproduce it.

**Comment by sergey-wowwow** [comment]
I didn't notice such errors last time in number of apps, so I'm closing this

**Comment by zaoqi** [comment]
@sergey-wowwow 

It was generated when the file like a$48.class was decompiled at the time.
