### ISSUE TITLE
test: NotYetImplemented

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#491]
In other projects, there is a concept of `NYI`, in which a test case is known to fail, and actually is executed. If the test fail (as expected), then the build is green, and if the test passes (surprise!), then the build fails, so the corresponding issue/notes should be updated.

This would help anyone should has a case, to actually commit it as `@NotYetImplemented`.

Before going there, should we also upgrade JUnit to 5, or not?

**Comment by skylot** [comment]
Maybe be you are right, but there are not many people who want to commit anything, also making good test is not so easy. By "good test" I mean minimal test which reproduces only one issue and just copy whole method with error into smali code doesn't make it a "good test".
For me, issue with attached sample is enough to write test and fix a bug.

About JUnit 5: I can upgrade and it is not hard, but for now, I don't see a lot of benefits from doing so. And I will better spend time for bug fixing.

**Comment by asashour** [comment]
The reason for JUnit 5 is to spare the effort of reimplementing NYI when we later upgrade.

No worries about the time, I would take care of both.
