### ISSUE TITLE
Annotation names are kept not deobfuscated

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#504]
Hi, please check ``` com.mercadolibre.android.security.biometrics_ui.C6054a ```, when deobf option is enabled, the following annotations are generated
```java
    @com.google.gson.p122a.C3190c(a = "fingerprint_status")
```
but it was renamed to ``` mo13634a ```
```java
public @interface C3190c {
    /* renamed from: a */
    java.lang.String mo13634a();
```

APK: https://drive.google.com/file/d/1Z0jvmIFuzSnkMapbiV2SRjB4KYHOO_qm/view?usp=sharing

**Comment by asashour** [comment]
I am trying to look into this, and I have a question:

In `AnnotationGen`, how to get a reference to the `ClassNode` of the annotation? There is a reference to the `MethodNode` of the usage of the annotation, with the annotation type as String.

In other words, how to get `ClassNode` from a String in `ObjectType`.

**Comment by skylot** [comment]
@asashour I already almost fixed that, but encounter another error :(

About your question:
```java
	Annotation a;
	ClassNode annCls = cls.dex().resolveClass(a.getType());
```

**Comment by skylot** [comment]
Fixed in master branch.
