### ISSUE TITLE
Enum class processing for obfuscated code

### ISSUE THREAD

**Issue by NeoSpb** [skylot/jadx#51]
[This](https://github.com/skylot/jadx/commit/883429fa47969b7af92fab33529ee242ed0f447d) fix was greate. But there is new issue, that in the generated code used field with not aliased name.

For example:
```
enum Example {
    ITEM1,
    ITEM2
}
```
and somewhere in the code we can found
```
Example.b
```

I made the fix, that processes the **SPUT** instruction and creates link with restored field name and the "real" enum class field (also I added *FieldInfo* caching). But there I found issue in the architecture that code generator worked before all resolve is done. So we get some code before restore the field name and some after.

I can make a patch that provides a workaround (2-pass like deobfuscator) to resolve this issue.

In the future, I think there is need to change the architecture to make some steps before generate the code. But this is not my privilege, I think so.

What do you think?

**Comment by skylot** [comment]
Yes, you are right )
Last several days I was to trying to refactor deobfuscator for make it 1-pass visitor which starts after all other visitors but before codegen and face same problem as you. In 'development' branch I pushed solution then deobfuscator runs just after loading stage, but it looks ugly (

I can run codegen after all visitors for all classes, or just change visitors run sequence (run one visitor on all classes, next another visitor run on all classes ... ) but this approach need much more memory and it will be less effective to run processing in several threads.
(In current approach every class processed independently (in different threads) and on finish class data unloaded from memory, all cross class information prepared on loading stage but before visitors processing.)

So, I will try to decide which approach is better and collect other possible cases similar to this issue (looks like jadx.core.dex.visitors.ClassModifier also has this issue).

**Comment by NeoSpb** [comment]
Great! I will wait your solution =)

**Comment by skylot** [comment]
I decided to build list of dependencies for every class and process all that dependency classes before codegen pass. You can review this in 'experimental' branch.
Dependencies are collected in  jadx.core.dex.visitors.DependencyCollector class, for now it not collect all possible dependencies but only some of them, so if you change any class in visitor make sure this will be added to dependencies list (fix 'processInsn' method if needed).
This code not yet complete and I will try to make some tests, so If you find any issues please tell me )
