### ISSUE TITLE
String constructor with byte array

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#530]
As deduced from #529, there is also a potential to make String constructor beautiful.

```
	public static class TestCls {
		public String tag = new String(new byte[] {'a', 'b', 'c'});
	}

	@Test
	public void test() {
		ClassNode cls = getClassNode(TestCls.class);
		String code = cls.getCode().toString();

		assertThat(code, containsOne("abc"));
	}

```

**Comment by asashour** [comment]
I am trying to fix this, but I counter issue, the corresponding output could be something like:

    new String("abc".getBytes(), StandardCharsets.UTF_8);

And I don't know how to construct a MethodInfo the the String(byte[]) constructor if it is not found in `dex`.

**Comment by skylot** [comment]
Looks like you need to implement it youself. Add to `MethodInfo` class something like this:
```java
public static MethodInfo externalMth(ClassInfo declaredCls, String name, List<ArgType> args, ArgType retType) {
```

**Comment by sergey-wowwow** [comment]
Seems that it would be better to begin from constant concatenations like
```java
String value = "a" + "b";
```
sometimes ``` "a" ``` could be a ``` static final String SMTH = "a"; ``` value, and when ``` --no-replace-consts ``` option is enabled, the given output will be generated. But it's nicer to see 
```java
String value = "ab";
```

**Comment by asashour** [comment]
> Seems that it would be better to begin from constant concatenations like
> 
> ```java
> String value = "a" + "b";
> ```
> 
> sometimes `"a"` could be a `static final String SMTH = "a";` value, and when `--no-replace-consts` option is enabled, the given output will be generated. But it's nicer to see
> 
> ```java
> String value = "ab";
> ```

I guess this is a different case, since constants are usually `String`, but the one is question is a `byte array`.
