### ISSUE TITLE
References to not existing classes (deobfuscator doesn't rename outer class names)

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#532]
Hi, 
Open class ``` com.paypal.merchant.client.features.webview.PPBWebViewActivity ```
```java
public class PPBWebViewActivity extends p000.C5744Dy {
```
then open ``` p000.C5744Dy ```
```java
/* renamed from: Dy */
public abstract class C5744Dy extends p000.C1430y {
```
and finally open ``` p000.C1430y ```
```java
/* renamed from: y */
public class C1430y extends p000.Hh implements p000.C1439z, p000.je.C1314a, p000.C1331n {
```
class ``` p000.je.C1314a ``` doesn't exist as tons of other classes referenced by ``` p000.**.C***** ```

Actually that interface was moved to
```java
package p000;

/* renamed from: je */
public final class C5243je implements java.lang.Iterable<android.content.Intent> {
    //...

    /* renamed from: je$a */
    public interface C1314a {
        android.content.Intent getSupportParentActivityIntent();
    }
```

Please use this APK: https://drive.google.com/file/d/1_8--CfspEnugSTGjF3Krkt4r3SEV6vq7/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow I can't reproduce this issue on latest master, maybe it was fixed in #474?
Can check it again.

**Comment by sergey-wowwow** [comment]
@skylot
No, even in jadx-gui Search feature shows not deobfuscated class names (when deobfuscation is enabled) for the given example

**Comment by sergey-wowwow** [comment]
@asashour,
Can you please check it too, it that reproducible on your side?

**Comment by asashour** [comment]
It works fine with me:

The implemented interface is an inner class, check the the import statements of the my `C2658y`

```
import p000.C2885Dy;
public class PPBWebViewActivity extends C2885Dy {
```

```
/* renamed from: Dy */
public abstract class C2885Dy extends C2658y {
```

```
import p000.C2198je.C2199a;
public class C2658y extends C0234Hh implements C2690z, C2199a, C2305n {
```


```
/* renamed from: je */
public final class C2198je implements Iterable<Intent> {

    ...

    /* renamed from: je$a */
    public interface C2199a {
        Intent getSupportParentActivityIntent();
    }

```

**Comment by sergey-wowwow** [comment]
Hm, I'm using MacOS and it still fails. When I come back from a vacation I will recheck on Windows. But isn't it reasonable to don't check system environment is that case sensitive or not, and all such stuff to make Jadx more predictable on all OS?

**Comment by sergey-wowwow** [comment]
That's weird, but it's also reproducible on Windows (I entirely deleted jadx, cloned from the repository and built it again). When I enabled ``` Use import statements ``` the following code was generated
```java
package p000;
//...
import p000.je.C1314a; /* imports itself! */

/* renamed from: je */
public final class C5244je implements Iterable<Intent> {
    //...

    public interface C1314a { /* "imported" class is declared */
        Intent getSupportParentActivityIntent();
    }

```

**Comment by asashour** [comment]
What is your GUI config? Mine is far below.

I can see some strange behavior, with those config:

```
import defpackage.je.a;

/* renamed from: y */
public class C0589y extends Hh implements C0612z, a, C0324n {
```

However, I can't find `defpackage.je` class at all.

But if deobfuscation is enabled, it is fine.

![image](https://user-images.githubusercontent.com/2410127/56454812-fe895700-635e-11e9-94c1-34b9fca3e00e.png)

**Comment by sergey-wowwow** [comment]
@skylot @asashour 
I've found out that the issue is not reproducible when ``` --deobf-min ``` is set to default value 3. But when to 2, the bug appears

**Comment by sergey-wowwow** [comment]
@skylot 
Can you please look at this one again? It really breaks all class hierarchy and makes impossible to resolve relations among classes :(

**Comment by skylot** [comment]
@sergey-wowwow ok, I will look at it again.

**Comment by skylot** [comment]
@sergey-wowwow I made a fix, hope it helps.
Commit looks like a refactoring because current work with aliases is mind blowing and must be reimplemented somehow :(

**Comment by sergey-wowwow** [comment]
@skylot 
Looks like it doesn't help :( When I open ``` com.paypal.merchant.client.features.webview.PPBWebViewActivity ``` class generated by jadx-cli, I see
```java
public class PPBWebViewActivity extends p000.Dy {
```
but ``` p000.Dy ``` is unresolved type.
Arguments:
```
--no-replace-consts --show-bad-code --threads-count 8 --deobf --deobf-min 2 --no-imports --deobf-rewrite-cfg
```

But the code generated by jadx-gui didn't change by some reason (both versions have flag set to rewrite the jobf file)
Settings:
![2019-04-22_22-31-09](https://user-images.githubusercontent.com/15173437/56521704-6356d400-654e-11e9-841c-acb9d55374d7.jpg)

**Comment by skylot** [comment]
Made new commit, this time reimplement all class alias processing especially for inner classes.
Hope it helps, but new issues can occur because of big changes :(

Also in other commit I disable filesystem case-sensitivity detection and by default jadx treat FS as case-insensitive, and if someone want to change this value - option added to cli and gui.

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks a lot! Now it's not reproducible anymore and made my life much easier :)
