### ISSUE TITLE
primitive unnecessary cast

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#538]
Consider the below examples:

    new byte[]{10, 11, 12}

and

    byte[] arr = new byte[3];
    arr[2] = 10;

Currently, they are being generated as:

    new byte[]{(byte) 10, (byte) 11, (byte) 12}

and

    byte[] arr = new byte[3];
    arr[2] = (byte) 10;

This should be also fixed for other primitive types.

**Comment by skylot** [comment]
@asashour I know I made such cast on purpose, but now I don't remember why :(
Maybe because of issues in previous Java versions. Anyway, if tests are pass we are good :)
