### ISSUE TITLE
Wrong variable initialization

### ISSUE THREAD

**Issue by jmue** [skylot/jadx#54]
The method-result of type String is initialized with boolean value 'true' after decompilation.

    String getDisplayNameFromUri(Context context, Uri contentUri) {
        Cursor cursor = null;
        try {
            String[] projection = {OpenableColumns.DISPLAY_NAME};
            cursor = context.getContentResolver().query(contentUri, projection, null, null, null);
            int column_index = cursor.getColumnIndexOrThrow(OpenableColumns.DISPLAY_NAME);
            cursor.moveToFirst();
            return cursor.getString(column_index);
        } finally {
            if (cursor != null) {
                cursor.close();
            }
        }
    }

**Comment by skylot** [comment]
Thank you!
For resolve this issue I fix so many bugs in jadx )
