### ISSUE TITLE
jadx-gui :JADX ERROR: UnsupportedOperationException in pass: BlockProcessor

### ISSUE THREAD

**Issue by Misschihiro** [skylot/jadx#542]
hi when use jadx-gui, it has some erros:
![image](https://user-images.githubusercontent.com/17743767/55223542-61e50500-5249-11e9-8de3-0c3335a92f19.png)
can you look it? what should I do? thanks

**Comment by asashour** [comment]
Please provide the APK file, so others can reproduce the issue.

**Comment by sergey-wowwow** [comment]
I didn't notice such errors last time in numbers of apps, so I'm closing this
