### ISSUE TITLE
Categorization of issues

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#569]
Whenever reading an issue, appreciate providing categorization. And if someone has some time, the old ones should also be quickly categorized, specially for:

- No-reply
- Question
- Bug

- GUI
- CLI

**Comment by skylot** [comment]
@asashour do you have permissions to add labels to issues?

**Comment by asashour** [comment]
No, I don't.

**Comment by skylot** [comment]
I see, GitHub doesn't allow to give partial permissions.
I will add you as a collaborator, so you can edit labels, closing issues, etc.
But please don't push directly to master, only use pull requests, ok?

**Comment by asashour** [comment]
Thanks, ok.

I won’t close issues or push to the repository.
