### ISSUE TITLE
Add options to disable "renaming"

### ISSUE THREAD

**Issue by skylot** [skylot/jadx#570]
This issue discussion started in #158.
Sometimes it is useful to view names "as-is" without any modifications.
So jadx must have an option for that.

For now, jadx has many "renaming" types besides deobfuscation:
* to support system case sensitivity
* to make valid java identifiers (to make code compilable)
* to remove not "printable" characters 
"printable" - here means only Latin chars (32 to 126 codes in [ascii table](http://www.asciitable.com/))

Options must allow to disable/enable such types separately:
* In `JadxArgs` it must be enum set (full set is default)
* In jadx-cli list of lower case enum names with comma separator, plus shortcuts like `all` and `none`
Examples: `--rename-flags case,valid,printable` or `--rename-flags all`
* In jadx-gui in must be several checkboxes under common label.
And if some options is disabled before source export warning notification about changing names can be shown.

**Comment by asashour** [comment]
Should these settings apply to fields and methods as well?

**Comment by skylot** [comment]
@asashour yes, this must be done for fields and methods.
