### ISSUE TITLE
Class not found - classpath problem?

### ISSUE THREAD

**Issue by smarek** [skylot/jadx#58]
Hello,

something like this usually pops out on me, running jadx/jadx-gui.
```
WARN  - Class not found: android.app.SharedElementCallback
WARN  - Class not found: android.transition.Transition$EpicenterCallback
WARN  - Class not found: android.transition.Transition$EpicenterCallback
WARN  - Class not found: android.media.VolumeProvider
WARN  - Class not found: android.media.session.MediaController$Callback
WARN  - Class not found: android.media.session.MediaSession$Callback
WARN  - Class not found: android.print.PrintDocumentAdapter
WARN  - Class not found: android.print.PrintDocumentAdapter
WARN  - Class not found: android.view.View$OnApplyWindowInsetsListener
WARN  - Class not found: android.view.View$OnApplyWindowInsetsListener
```

Is this something we can fix with classpath or possibly upgrading dependency `jadx-core/clsp-data/android-4.3.jar` to newer version?

If so how do you generate/update `core.jcst` in said JAR to newer SDK version (such as 21/22) ?
Thank you

**Comment by skylot** [comment]
Hello,
I use classpath data (actually this is only classes hierarchy) for type inference, but in most case this additional information is not needed, so these warnings can be ignored.

Anyway if you want to generate your own class data you can run 
```
java -classpath "lib/*" jadx.core.clsp.ConvertToClsSet out.jcst dex-libs-dir
```
in `dex-libs-dir` must be places all android framework dex files,
file list depends on android version and manufacturer, for example:
```
android.policy.dex
apache.xml.dex
bountycastle.dex
core.dex
core-junit.dex
ext.dex
framework.dex
javax.obex.dex
services.dex
```
After that you must replace existing core.jcst
Note: ConvertToClsSet can directly generate result jar file, but looks like this functionlity is broken for now (

So, as you requested I will update clsp file to Android 5.1 and fix ConvertToClsSet and may be make a run script for ease use.

**Comment by smarek** [comment]
Thank you very much for in-depth response and updating clsp definitions, I'll wait.
