### ISSUE TITLE
Decompilation Error

### ISSUE THREAD

**Issue by JerryCheng1** [skylot/jadx#587]
Hi,
i was decompiling a dex from boot.oat and it return some decompilation errors and i was wondering if someone could explain the source of these error and why they are happening. Are those source encrypted?

I got this inside the part of output code:
https://github.com/JerryCheng1/sharp_telephony-common/blob/master/F827G/com/android/internal/telephony/RIL.java#L1189-L1418

Here is dex file from boot.oat
[telephony-common.zip](https://github.com/skylot/jadx/files/3071649/telephony-common.zip)

Best Regards,
Jerry

**Comment by asashour** [comment]
Generally, those errors mean Jadx is not able to correctly decompile them.

You can help in isolating small [test cases](https://github.com/skylot/jadx/blob/master/jadx-core/src/test/java/jadx/tests/integration/arith/TestFieldIncrement.java), so they can be fixed one at a time.

**Comment by JerryCheng1** [comment]
Thanks
