### ISSUE TITLE
Jadx adds invalid assignments

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#591]
Hi, I've noticed that if a declaration parameter type in a method contains wildcards, fact parameter will be casted to that type. Example, class ``` com/paypal/android/p2pmobile/instorepay/activities/NFCActivationDoneActivity.java ```
```java
    public void onPostResume() {
        super.onPostResume();
        EventBus.getDefault().removeStickyEvent((Class<T>) /* error */ PostActivationCompletedActivityEvent.class);
```
Declaration
```java
    public <T> T removeStickyEvent(java.lang.Class<T> cls) {
```

APK: https://drive.google.com/file/d/16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG/view?usp=sharing

**Comment by asashour** [comment]
I am afraid I couldn't find the package `com/paypal/android/p2pmobile/instorepay`, and no files found with name `NFCActivationDoneActivity`.

Also, the below test succeeds:

```
public class TestGenerics7 extends IntegrationTest {

	public static class TestCls {

		public void test() {
			new TestCls().declare(String.class);
		}

		public <T> T declare(Class<T> cls) {
	    	return null;
	    }
	}

	@Test
	public void test() {
		getClassNode(TestCls.class);
	}
}

```

**Comment by asashour** [comment]
The APK is in #450

**Comment by sergey-wowwow** [comment]
@asashour,
Thanks, I’ve updated the first post
