### ISSUE TITLE
Invalid casts among primitive types

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#596]
Hi, in some cases casts are invalid. For example in class ``` com/paypal/android/foundation/presentation/model/ConsentUriParams.java ``` type ``` boolean ``` is converted to ``` byte ``` using explicit cast
```java
    public void writeToParcel(android.os.Parcel parcel, int i) {
        parcel.writeByte((byte) this.showConsent);
        parcel.writeByte((byte) this.showOneTouch);
```
but the following code should be generated instead
```java
    public void writeToParcel(android.os.Parcel parcel, int i) {
        parcel.writeByte(this.showConsent ? 1 : 0);
        parcel.writeByte(this.showOneTouch ? 1 : 0);
```
APK: https://drive.google.com/file/d/16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG/view?usp=sharing

**Comment by sergey-wowwow** [comment]
@asashour 
Was it fixed by the PR? I see that the given test case still fails

**Comment by asashour** [comment]
I have rechecked from the GUI and now the code generated is:

```
public void writeToParcel(Parcel parcel, int i) {
    parcel.writeByte(this.showConsent ? (byte) 1 : 0);
    parcel.writeByte(this.showOneTouch ? (byte) 1 : 0);
    parcel.writeString(this.secureIdToken);
    parcel.writeString(this.challengeUri);
    parcel.writeString(this.consentData.toString());
}
```

**Comment by asashour** [comment]
I hope you are checking with the PR branch, not with `master`, since it is not merged yet.

**Comment by sergey-wowwow** [comment]
@asashour 
Seems to be not completely fixed, file ``` com/paypal/android/foundation/cashin/model/PayPalCashRetailerDetail.java ```
```java
    public void writeToParcel(android.os.Parcel parcel, int i) {
        //...
        parcel.writeInt(this.lastVisited); // declaration: private boolean lastVisited
    }
```

**Comment by skylot** [comment]
Haha, this is funny, in this method cast don't even added, bytecode just use boolean as int.
@sergey-wowwow thanks for sample, I have waited it for a long time ))
I think this issues must be catch by type inference and cast must be inserted and later cast will replaced with ternary using @asashour PR.

**Comment by sergey-wowwow** [comment]
@skylot 
Always welcome to fix my bugs! :D

**Comment by asashour** [comment]
I went into `TypeInferenceVisitor` and have to say I am lost. The logic is mainly to compare types and decide which one to set, but there is no place/example of inserting `InsnNode`s

**Comment by skylot** [comment]
In `TypeInferenceVisitor` already collected all usages of variable, so I think it must be easy to find this case. Also, current type inference specially adjusted for such cases and type errors with primitive types just omitted, this also must be fixed.
And actually there is [one place](https://github.com/skylot/jadx/blob/633ccc7ea79ab7cda71e0756e87f5467eac62023/jadx-core/src/main/java/jadx/core/dex/visitors/typeinference/TypeInferenceVisitor.java#L302) with inserting instruction and case is very similar.

> The logic is mainly to compare types and decide which one to set

Haha, this is a definition of ["type inference" ](https://en.wikipedia.org/wiki/Type_inference):
> Type inference refers to the automatic detection of the data type of an expression in a programming language.
