### ISSUE TITLE
(Inlined anonymous classes) Jadx adds invalid method references from anonymous classes

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#598]
Hi,
in class ``` com/paypal/android/foundation/compliance/fragment/ComplianceWebViewFragment.java ``` the following code is generated
```java
private WebViewClient webViewClient = new WebViewClient() {
        //...

        public void onReceivedSslError(WebView webView, final SslErrorHandler sslErrorHandler, SslError sslError) {
            ComplianceWebViewFragment.f13478L.debug("Received SSL error opening URL on WebView", new Object[0]);
            if (FoundationCore.appInfo().isDebuggable()) {
                WebViewUtil.showDialogOnSslError(sslErrorHandler, ComplianceWebViewFragment.this.getActivity(), new WebViewUtil.DialogOnSslErrorHandler() {
                    public void cancel() {
                        /* invalid code! */ ComplianceWebViewFragment.C16524.this.m10253a(sslErrorHandler);
                    }
                });
            } else {
                m10253a(sslErrorHandler);
            }
        }

        //....
    };
```
The given class is anonymous, ``` ComplianceWebViewFragment.C16524.this. ``` should be removed, since ``` ComplianceWebViewFragment.C16524 ``` is unresolved expression

APK: https://drive.google.com/file/d/16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow looks like there many issues with inlined anonymous classes. Maybe we can add option to disable inlining and removing of anonymous classes this will produce verbose but compilable code.
What do you think? Will this option help you?

**Comment by sergey-wowwow** [comment]
@skylot 
I think it's a good idea. But isn't it better to add checks for each of all such cases? I reported everything I found, so there are probably no other issues with inlined anonymous classes

**Comment by sergey-wowwow** [comment]
@skylot 
Seems there are really more bugs I expected (e.g. #604). Let's introduce that feature?
