### ISSUE TITLE
Sometimes generic types are not parametrized

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#600]
Hi, I've noticed that sometimes generic types are not parametrized, it causes errors in enhanced loops. Example (but without error, since it's the most simple case I found) in class ``` com/paypal/android/p2pmobile/p2p/sendmoney/activities/SendMoneyFlowActivity.java ```
```java
    public void onConfirmFundingMixSelection() {
        java.util.List cardContingencies = getCardContingencies();
        //...
```
but here is a declaration of the method
```java
    private java.util.List<com.paypal.android.foundation.p2p.model.SendMoneyContingency> getCardContingencies() {
```

I believe the following code should be generated instead
```java
    public void onConfirmFundingMixSelection() {
        java.util.List<com.paypal.android.foundation.p2p.model.SendMoneyContingency> cardContingencies = getCardContingencies();
        //...
```
because if that method contains a loop, it would be decompiled to
```java
    public void onConfirmFundingMixSelection() {
        java.util.List cardContingencies = getCardContingencies();
        for(com.paypal.android.foundation.p2p.model.SendMoneyContingency /* error:  sendMoneyContingency should be java.lang.Object */ sendMoneyContingency : cardContingencies) {
                //...
```

APK: https://drive.google.com/file/d/16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG/view?usp=sharing

**Comment by sergey-wowwow** [comment]
You may see a real error in class ``` com/paypal/android/p2pmobile/p2p/sendmoney/SendMoneyCountries.java ```
```java
        this.mCountryMap = new java.util.HashMap(this.mCountries.size());
        for (android.support.v4.util.Pair pair : this.mCountries) {
            this.mCountryMap.put(pair.first, pair.second);
        }
```
because type of ``` pair.first ``` and ``` pair.second ``` is ``` java.lang.Object ```, but declaration of ``` mCountryMap ``` is
```java
    private java.util.Map<java.lang.String, java.lang.String> mCountryMap;
```

**Comment by asashour** [comment]
Test in https://github.com/skylot/jadx/blob/master/jadx-core/src/test/java/jadx/tests/integration/generics/MissingGenericsTypesTest.java

**Comment by sergey-wowwow** [comment]
First bug is fixed, but in `com/paypal/android/p2pmobile/p2p/sendmoney/SendMoneyCountries.java` not

**Comment by sergey-wowwow** [comment]
Fixed!
