### ISSUE TITLE
jobf doesn't preserve changes

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#609]
When opening an `.apk`, and changing records in its generated `.jobf`, I expect those renamings to be used again. Instead the .jobf is overwritten with default deobfuscation values.

Steps:
1. Open .apk in GUI and close it
2. Edit the first record to rename e.g. `C0000R` to `C1234R` or to even `R`
3. Open the .apk again and close it
4. The first record should not be reset to `C0000R`

**Comment by skylot** [comment]
@asashour please check that option `Force rewrite deobfuscation map file` is disabled

**Comment by asashour** [comment]
I see, but I wonder why it is enabled by default?

Also, when the user want to override the map file, he can simply delete it.

**Comment by skylot** [comment]
As I remember I enable it by default because after fixing some issues in deobfuscator people continue to complain about not fixed issue (incorrect renaming was saved). Also, I don't think many people trying to edit this file :)
