### ISSUE TITLE
sync with editor auto on or off

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#610]
The behavior of `sync with editor` should be changed so that:

- It is either always `on` or always `off` (similar to `deobfuscation` button, always on or always off)
- When `on`, then any change in the tabbed pane is auto selected in the tree view, and vice versa
- When `off`, then the auto selection is disabled.

**Comment by skylot** [comment]
@asashour you want to make it like in Eclipse, but currently it works like in IntelliJ Idea and I like it this way.
So, looks like we need one more opinion ))

**Comment by jpstotz** [comment]
I am mostly an Eclipse user however I prefer the sync mode used by Jadx and IntelliJ.

In general I prefer functions that are triggered manually instead of automatically working functions that usually do what they want and not what I want.

**Comment by asashour** [comment]
Clear! I didn’t know the behavior is intended, thanks for quick reply. It is always better to ask before implementing :)
