### ISSUE TITLE
Support hyperlink in code area

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#614]
Since `RSyntaxTextArea` is used, we can implement [LinkGenerator](http://javadoc.fifesoft.com/rsyntaxtextarea/org/fife/ui/rsyntaxtextarea/LinkGenerator.html), so when the user clicks on a class name, that class in opened in a new tab (if not already open).

**Comment by asashour** [comment]
It is already implemented!!!

Come on guys, this should be more intuitive, to know at least it exists :)

**Comment by skylot** [comment]
I though `Ctrl+click` is intuitive enough because it used in every IDE :)
For show existent of this feature we can add `Go to declaration` action to `Navigation` and editor popup menu with shortcut `Ctrl+B` (like in Idea). Also, we can add `Find usage` action in same way.
