### ISSUE TITLE
Incorrect renaming when "only printable" is used

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#622]
As hinted in https://github.com/skylot/jadx/issues/584#issuecomment-486041365.

> 5. When "printable" is the only selected rename option, fields are renamed (although not fully printable), while classes are not.

I am expecting all classes/fields/methods to be printable ASCII.

However:

- Classes are not renamed
- Fields are renamed, but still pertaining the original not-printable suffix, this suffix should be removed.
- Methods are renamed, but still pertaining the original not-printable suffix, this suffix should be removed.

![image](https://user-images.githubusercontent.com/2410127/56627800-9fba2b00-6647-11e9-93c1-913b35944529.png)

**Comment by skylot** [comment]
In commit 19c5725 added removing not printable chars after deobfuscator.
In 31a02a7 fixed class name if all chars was removed.
