### ISSUE TITLE
Improper renaming comment

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#623]
When no renaming flag set, and using the APK in #584.

```
package io.fabric.sdk.android.services.common;

public class CommonUtils {
    public static final Comparator<File> ˋ = new Comparator<File>() {
        /* renamed from: ॱ */
        public int compare(File file, File file2) {
            return (int) (file.lastModified() - file2.lastModified());
        }
    };
```

This "renamed from" comment has two issues:
- It should not be in the method comments, but it should be at the class-level.
- It shouldn't exist at all, since there is no remaining happened.

**Comment by skylot** [comment]
Fixed in 19c5725
Now with all disable rename options code looks like this:
```java
    public static final Comparator<File> ˋ = new Comparator<File>() {
        public /* synthetic */ int compare(Object obj, Object obj2) {
            return ॱ((File) obj, (File) obj2);
        }

        public int ॱ(File file, File file2) {
            return (int) (file.lastModified() - file2.lastModified());
        }
    };
```
Cause of issue was renaming method after removing its synthetic wrapper. Now such wrappers not remove if `rename valid` is disabled.
