### ISSUE TITLE
Testing for bits in int

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#628]
I just noticed that jadx creates wrong code when it comes to if cases that test an `int` variable if certain bits are set or not.

A very good example is the Apache Cordova library:
https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/engine/SystemWebViewClient.java#L232

```
// original code
String packageName = parentEngine.cordova.getActivity().getPackageName();
PackageManager pm = parentEngine.cordova.getActivity().getPackageManager();
appInfo = pm.getApplicationInfo(packageName, PackageManager.GET_META_DATA);
if ((appInfo.flags & ApplicationInfo.FLAG_DEBUGGABLE) != 0) { // <-- this line
```

The output of jadx for this decompiled code however is something different (especially the last line):

```
// jadx decompiled code (current master branch)
if (this.parentEngine.cordova.getActivity().getPackageManager().getApplicationInfo(
    this.parentEngine.cordova.getActivity().getPackageName(), 128).
    flags != false && 2 != false) {
```
Note that `ApplicationInfo.FLAG_DEBUGGABLE = 0x2` and if I take `0` instead of `false` all the relevant parts are there, however the applied operations are totally wrong.

An APK that contains this code without obfuscation is this one:
https://apkpure.com/de/cordova-showcase/br.com.marcioggs.cordovashowcase

**Comment by jpstotz** [comment]
@asashour Thanks Ahmed for the fix. In the end you were so fast that implementing the test case and fixing the code took you less than I needed to prepare and write the issue.

**Comment by asashour** [comment]
> @asashour Thanks Ahmed for the fix. In the end you were so fast that implementing the test case and fixing the code took you less than I needed to prepare and write the issue.

Haha, actually because I was the reason of the issue, and knowing where the triggering code is :)
