### ISSUE TITLE
Support for (specific?) AAR files 

### ISSUE THREAD

**Issue by polishcode** [skylot/jadx#631]
I found out that this commit:

SHA-1: 79ccaadaff18de7443491dbc333e71cfa6e3e3d5
* fix: handle big .jar files (using multi-dex option) (#390) (PR #568)

breaks decompilation for AAR libraries that I use. The result is that when loading those libraries into jadx, after a split-second it shows just empty "Source code" folder.

Unfortunately I cannot share with you the specific AARs. Is there any other way I can contribute to fixing this?

**Comment by asashour** [comment]
Thanks for pointing this out, PR #632 has been raised, by testing with the .aar in https://bintray.com/jbaruch/android/gradle-aar-example#files/com/bintray/example/gradle-aar-example/1.0

Please test it and provide your feedback.

**Comment by polishcode** [comment]
Works for me now. Thank you for swift response.
