### ISSUE TITLE
Disable anonymous class inline

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#633]
Hi, please introduce a feature to disable anonymous class inline to avoid bugs https://github.com/skylot/jadx/issues/579, https://github.com/skylot/jadx/issues/598, https://github.com/skylot/jadx/issues/604 and maybe https://github.com/skylot/jadx/issues/608

**Comment by skylot** [comment]
Done! Cli option is `--no-inline-anonymous`.

**Comment by sergey-wowwow** [comment]
@skylot thanks! How do you think, should I close those issues because they could be fixed by supplying ``` --no-inline-anonymous ```?

**Comment by skylot** [comment]
These issues must be fixed anyway. Disable inlining is just workaround and produces very verbose code :(

**Comment by asashour** [comment]
Honestly, I hope someday we remove this option.
