### ISSUE TITLE
GUI preferences should have two parts

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#642]
Currently, the preferences are long list all in one vertical layout, and we seem to add more and more options, e.g. `no-inline-anonymous` or `white-listed packages not to be renamed`.

I guess it would be much better if we have a 'menu/list' on the left side, and when the user selects one of them, only those relevant settings are displayed.

**Comment by jpstotz** [comment]
We had a short discussion on that topic some time ago: https://github.com/skylot/jadx/issues/454#issuecomment-466521147
