### ISSUE TITLE
Fields collide with package names

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#647]
Hi, I've noticed a bug that prevents resolving references to types/packages.

Example in class ``` flow.FlowDelegate ```
```java
private final flow.Flow flow;
```
```java
private static flow.History selectHistory(android.content.Intent intent, flow.History saved, flow.History defaultHistory, flow.StateParceler parceler2) {
    if (intent.hasExtra(HISTORY_KEY)) {
        return flow.History/*error here*/.from(intent.getParcelableExtra(HISTORY_KEY), parceler2);
```
I get an error for expression ``` flow.History ``` ``` Cannot make a static reference to the non-static field flow ```

APK: https://drive.google.com/file/d/1VutiAXM19oi8sdfjB0u2lveD8Uz-uCQP/view?usp=sharing

May you please introduce a feature that prevents collides among field and package names? Thanks!

**Comment by asashour** [comment]
This happens when `User Imports Statements` is disabled.

I am not sure if we should check if there is a static reference used in the class before deciding to rename a field.

**Comment by asashour** [comment]
Another hint, #648 would hide this particular test case.

**Comment by sergey-wowwow** [comment]
@asashour 
I like different approach to simply store all packages and class names (globally or from current scope), and rename fields (e.g. change ``` flow ``` to ``` flow1 ```) when it potentially collides with something

**Comment by sergey-wowwow** [comment]
@asashour 
More over it's not about static/not static methods, the same happens also with non-static methods, example is in the same class
```java
    public void onNewIntent(android.content.Intent intent) {
        flow.Preconditions/*error*/.checkArgument(intent != null, "intent may not be null", new java.lang.Object[0]);
        if (intent.hasExtra(HISTORY_KEY)) {
            this.flow.setHistory(flow.History.from(intent.getParcelableExtra(HISTORY_KEY), this.parceler), flow.Flow.Direction.REPLACE);
        }
    }
```
Error is ``` Preconditions cannot be resolved or is not a field ```

**Comment by asashour** [comment]
> @asashour
> I like different approach to simply store all packages and class names (globally or from current scope), and rename fields (e.g. change `flow` to `flow1`) when it potentially collides with something

Yes, that would be the way, to store all used variables in scope.

>More over it's not about static/not static methods, the same happens also with non-static methods, example is in the same class

I have to say, these are all static methods (`Predonditions.checkArgument`, `History.from`) or fields (`Flow.Direction.REPLACE`), but there is no instance methods.

**Comment by skylot** [comment]
I made field renaming if it collides with any root package. It is a little overkill through :)
@sergey-wowwow can you check this change?

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks! But I see that local variables still collide with root packages, example is in the same class
```java
    public static flow.FlowDelegate onCreate(flow.FlowDelegate.NonConfigurationInstance nonConfigurationInstance, android.content.Intent intent, android.os.Bundle savedInstanceState, flow.StateParceler parceler2, flow.History defaultHistory, flow.Flow.Dispatcher dispatcher2) {
        boolean z;
        flow.Flow flow; // local variable
        if (parceler2 != null) {
            z = true;
        } else {
            z = false;
        }
        flow.Preconditions.checkArgument(z, "parceler may not be null", new java.lang.Object[0]);
        if (nonConfigurationInstance != null) {
            flow = nonConfigurationInstance.f590flow;
        } else {
            flow.History savedHistory = null;
            if (savedInstanceState != null && savedInstanceState.containsKey(HISTORY_KEY)) {
                // flow.History.from -- collide
                savedHistory = flow.History.from(savedInstanceState.getParcelable(HISTORY_KEY), parceler2);
            }
            flow = new flow.Flow(selectHistory(intent, savedHistory, defaultHistory, parceler2));
        }
        flow.setDispatcher(dispatcher2);
        return new flow.FlowDelegate(flow, dispatcher2, parceler2);
    }
```

**Comment by skylot** [comment]
Oh, I see. I totally forgot about local variables :(
Thanks!

**Comment by skylot** [comment]
Commit to avoid local variables collision added :)

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks, everything is fixed!
