### ISSUE TITLE
Run jadx-gui.bat show a windows console and jadx application

### ISSUE THREAD

**Issue by micstart** [skylot/jadx#65]
when run  jadx-gui.bat, It's show a windows console and jadx application.
Why not use below command only show jadx applition? The command is:
start "" javaw.exe %DEFAULT_JVM_OPTS% %JAVA_OPTS% %JADX_GUI_OPTS%  -classpath "%CLASSPATH%" jadx.gui.JadxGUI %CMD_LINE_ARGS%

**Comment by jpstotz** [comment]
Starting with the next version of jadx-gui you don't need the script anymore. Instead you can simply execute the JAR file jadx-gui-0.x.x.jar by double-click or via command-line: `javaw.exe -jar jadx-gui-0.6.1.jar`.

See https://github.com/skylot/jadx/pull/63#event-306427360 for details.

**Comment by skylot** [comment]
Ok, I understand that in most cases logs not needed, but sometimes logs can provide additional information, for example: exception stacktrace.
So I will make additional window in jadx-gui for view internal logs and hide current console window.

**Comment by asashour** [comment]
I guess this should be closed
