### ISSUE TITLE
Jadx decompilation error on seC.dujmehn.qdtheyt.apk

### ISSUE THREAD

**Issue by romainthomas** [skylot/jadx#666]
Hello,

I came across this sample: [seC.dujmehn.qdtheyt](https://koodous.com/apks/bd8cda80aaee3e4a17e9967a1c062ac5c8e4aefd7eaa3362f54044c2c94db52a) - sha256: `bd8cda80aaee3e4a17e9967a1c062ac5c8e4aefd7eaa3362f54044c2c94db52a`. 

It looks most of the classes can't be decompiled.
Here for examples: `seC.dujmehn.Cutyq.e`:

![jadx](https://user-images.githubusercontent.com/7450402/57977629-9fba0a80-79fc-11e9-9cec-f79d27407795.png)

Tested with Jadx master branch - commit: 75a67140

**Comment by skylot** [comment]
@romainthomas fixed! Thanks for nice sample.

**Comment by romainthomas** [comment]
Thank you!
