### ISSUE TITLE
Compare apks

### ISSUE THREAD

**Issue by AlleSchonWeg** [skylot/jadx#674]
Hi,

it is possible to open two apk's, decompile and show the differences in java code? I want to know the changes from version 1 to version 2.
Thank you

**Comment by jpstotz** [comment]
You can open each APK in Jadx and save all sources (Menu File -> Save All) to file system. Then use a file diff tool like KDiff3 to compare the two source directories. 

Note that comparing will only work on APKs that are not obfuscated. On Obfuscated APKs the class names are randomly generated, therefore comparing will only work for non-obfuscated classes.
