### ISSUE TITLE
Unable to open jar with certain classes in it

### ISSUE THREAD

**Issue by andrewleech** [skylot/jadx#680]
Hi, I've been using jadx for some time to help in an open source project I maintain, regularly updating it to your latest unstable builds. Huge fan, thanks for all the hard work. 

For a little while now, it's stopped being able to open a jar with certain classes in it. 
I've finally narrowed it down and deleted most everything else out of the jar, with just a couple of particular class files left it fails to open. 
When trying to open this jar, the navigator pane on the left shows the jar name, then "Source code" folder under it, but nothing else. the "Source code" folder shows empty. No error message is given.

Currently testing on jadx-gui-0.9.0-b1062-b1588583

Here's a copy of the trimmed down jar in case you'd like a look (jar renamed to zip)
[Hud.navdy - com.navdy.service.file.zip](https://github.com/skylot/jadx/files/3249609/Hud.navdy.-.com.navdy.service.file.zip)

Thanks again!

**Comment by jpstotz** [comment]
Jadx works on Android Jex code, for displaying Java classes these classes are converted to Android dex code. And this conversion fails for the class `FileTransferSession`:

```
WARN  - dx message: Uncaught translation error:
com.android.dx.cf.code.SimException: local 0004: invalid
	at com.android.dx.cf.code.OneLocalsArray.throwSimException(OneLocalsArray.java:255)
	at com.android.dx.cf.code.OneLocalsArray.get(OneLocalsArray.java:165)
	at com.android.dx.cf.code.BaseMachine.localArg(BaseMachine.java:219)
	at com.android.dx.cf.code.Simulator$SimVisitor.visitLocal(Simulator.java:620)
	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:349)
        [..]
...at bytecode offset 00000019
locals[0000]: Lcom/navdy/service/library/file/FileTransferSession;
locals[0001]: Landroid/content/Context;
locals[0002]: Lcom/navdy/service/library/events/file/FileType;
locals[0003]: Ljava/lang/String;
locals[0004]: <invalid>
locals[0005]: Lcom/navdy/service/library/file/FileTransferSession;
stack[top0]: Lcom/navdy/service/library/file/FileTransferSession;
...while working on block 0018
...while working on method initTestData:(Landroid/content/Context;Lcom/navdy/service/library/events/file/FileType;Ljava/lang/String;J)Lcom/navdy/service/library/events/file/FileTransferResponse;
...while processing initTestData (Landroid/content/Context;Lcom/navdy/service/library/events/file/FileType;Ljava/lang/String;J)Lcom/navdy/service/library/events/file/FileTransferResponse;
...while processing com/navdy/service/library/file/FileTransferSession.class
```

The problem is that the conversion is done by the `dx.jar`, a library provided by Google which is just used by Jadx.

May be you should use JD-GUI instead for decompiling your Java code.

**Comment by andrewleech** [comment]
Hi,
That's interesting, because it used to decompile fine with jadx. I'm not sure what version that was though, I haven't really kept track of the versions as I use them. Google must have had a regression in their tool. Thanks for the explanation!

I'm not blocked by this, nor am I expecting a fix necessarily.  
I just thought I'd post it as a reproducible failure case on the chance it might be useful.

I don't need to resort to jd-gui, your tools is by far the most accurate compared to all I've tried (quite a lot). 
It works great for the other hundreds of classes I've been working with decompiled versions of over the last year or so (https://gitlab.com/alelec/navdy/navdy-display-Hud-java/blob/08001c6cc3c40887dbc9e0b72c01ef4e73900b1f/libs/Hud.jar)

**Comment by skylot** [comment]
Unfortunately `dx` will not be supported anymore because it was replaced by `d8`. And `d8` works well on your sample. So you can use it for convert your jar to dex and after open result dex in jadx.

I can embed `d8` into jadx but I don't like size of dependencies (jadx zip bundle will be 35M instead current 14M) and also I can't use it like library for parsing dex (main purpose of using `dx`), because now there are no good and stable API for it :(
