### ISSUE TITLE
Simplify adding a space method

### ISSUE THREAD

**Issue by MihaiSeptD** [skylot/jadx#684]
In JCommanderWrapper method addSpaces can be most compact.
```java
private static void addSpaces(StringBuilder str, int count) {
    str.append(String.format("%" + count + "s", ""));
}
```

**Comment by skylot** [comment]
@MihaiSeptD 'compact' is not always better, there are also 'performance' and 'readability'.
Your suggestion is worst by performance and not quite readable.
