### ISSUE TITLE
Not finding JAVA path in windows batch script

### ISSUE THREAD

**Issue by tvalle** [skylot/jadx#686]
Commenting here because the jadx-gui.bat file doesn't seem to be in the repo, so I couldn't send a pull request.
On the bundle with the JRE, I was having an issue with the path not being found, after messing with it I discovered the problem:

Instead of:
```
19 set JAVA_HOME="%APP_HOME%\jre"
20 set JAVA_EXE=%JAVA_HOME%\bin\javaw.exe
```

It should be:
```
19 set JAVA_HOME="%APP_HOME%\jre"
20 set JAVA_EXE="%JAVA_HOME%\bin\javaw.exe"
```

On line 19 it was making the expansion all right but when it passed down to 20 because it didn't have double quotes both cmd and powershell were unable to find the path because mine had spaces in it.

**Comment by skylot** [comment]
@tvalle thanks! I apply your fix in release bundle and in master branch.
