### ISSUE TITLE
decompilation error

### ISSUE THREAD

**Issue by AnuTiger** [skylot/jadx#689]
Hi, I'm trying to decompile an APK but it's giving lots of errors. (also tried with `--show-bad-code`)

[app](https://github.com/AnuTiger/UNKNOWN/blob/master/app.zip)

some classes for ex:
`com.app.action.a`, `com.app.g.a` etc

**Comment by sergey-wowwow** [comment]
I see errors
```
    /* JADX WARNING: Removed duplicated region for block: B:63:0x034f A[Catch:{ Throwable -> 0x03bb }] */
    /* JADX WARNING: Removed duplicated region for block: B:64:0x035d A[Catch:{ Throwable -> 0x03bb }] */
```
but they are dups of already reported bugs
