### ISSUE TITLE
Unknown data types only on some methods

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#691]
![image](https://user-images.githubusercontent.com/35992798/59583794-ff89fb00-90f9-11e9-80d7-0f94b3172d8d.png)
As on the above image, I'm just seeing ??? symbols instead data types. Is there any way to fix it?, I'll attach the APK here if you want to test.

**Comment by redmi111** [comment]
![image](https://user-images.githubusercontent.com/35992798/59585184-842a4880-90fd-11e9-9f70-40f33dd54b52.png)
It's fine on jadx-gui-0.7.2-unstable-b479-9752ec2

**Comment by sergey-wowwow** [comment]
Closing as resolved
