### ISSUE TITLE
No execute permission on V1.0.0 zip

### ISSUE THREAD

**Issue by fashioncj** [skylot/jadx#696]
I try to update jadx version on brew. But the version 1.0.0 release package  contains some permission error.
The file 
bin/jadx
bin/jadx-gui
without execute permission.
Detail info:
https://github.com/Homebrew/homebrew-core/pull/41282

**Comment by skylot** [comment]
@fashioncj thank you for a report. I reupload zip bundle, so issue must be fixed.
