### ISSUE TITLE
[core] Code restructure failed: missing block

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#699]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
 (for example `JadxRuntimeException: Can't find immediate dominator for block`)
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
Class ``` com.grab.rewards.models.RewardCta ```
```java
    /* JADX WARNING: Code restructure failed: missing block: B:8:0x0024, code lost:
        if (p343e.p345f.p347b.C5608m.m19673a((java.lang.Object) r2.smartlink, (java.lang.Object) r3.smartlink) != false) goto L_0x0029;
     */
    public boolean equals(java.lang.Object obj) {
        if (this != obj) {
            if (obj instanceof com.grab.rewards.models.RewardCta) {
                com.grab.rewards.models.RewardCta rewardCta = (com.grab.rewards.models.RewardCta) obj;
                if (p343e.p345f.p347b.C5608m.m19673a((java.lang.Object) this.launch, (java.lang.Object) rewardCta.launch)) {
                    if (p343e.p345f.p347b.C5608m.m19673a((java.lang.Object) this.download, (java.lang.Object) rewardCta.download)) {
                    }
                }
            }
            return false;
        }
        return true;
    }
```
I have a lot of errors in important methods, but they are super big, so I hope sometimes they will be fixed via such reports :)

APK: https://drive.google.com/file/d/1i1EnqbUDbJ68upS_YbDfj0iNwC1MUep2/view?usp=sharing

**Comment by sergey-wowwow** [comment]
https://github.com/skylot/jadx/issues/563#issuecomment-492947314 fixed, but second one not

Class ``` com.valvesoftware.android.steam.community.fragment.TabbedSteamWebViewFragment ```
```java
    /* JADX WARNING: Code restructure failed: missing block: B:3:0x000f, code lost:
        if (r0 != null) goto L_0x0013;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public void onResume() {
        java.lang.String str;
        super.onResume();
        android.os.Bundle arguments = getArguments();
        if (arguments != null) {
            str = arguments.getString("category");
        }
        str = null;
        getCategoryUrlInfo(str);
    }
```
APK: https://drive.google.com/file/d/1bsUQZ61P9zJTXz_aFDFQBkbCUYp6eEOU/view?usp=sharing

**Comment by LucienMP** [comment]
Similar issues with another APK, tried latest build jadx-gui-1.0.0-b1130-c0194d02
APK:  https://drive.google.com/open?id=17mhxKPy3T4xBtP2cDOyr8JbfPY_vVnva

**Comment by sergey-wowwow** [comment]
@skylot 
Maybe you can fix this one or https://github.com/skylot/jadx/issues/720 before https://github.com/skylot/jadx/issues/662? Last commits fixed the most of such things, but not all, and such errors break method structure :(

**Comment by sergey-wowwow** [comment]
@skylot 
Is that one super hard? I see a lot of bugs with ``` Code restructure failed: missing block ``` in huge important methods, but you probably won't pass to much time to inspect them, so I try to reproduce them via such small bugs

**Comment by sergey-wowwow** [comment]
@skylot 
Has the issue been fixed in the last commit? I still see the same codes

**Comment by skylot** [comment]
@sergey-wowwow 
Sorry, still not fixed.
I fix return instructions duplication for the first case.
Second case needs to implement assign inlining inside complex 'if' conditions (see [this test](https://github.com/skylot/jadx/blob/0911b2dc2fdc00ccde112b556935bd63ac8c0f08/jadx-core/src/test/java/jadx/tests/integration/conditions/TestConditions19.java#L21) as example).

Anyway, I want to mention that `Code restructure failed: missing block` is not a specific issue it can be any decompilation issue which leads to missing code in the method. This warning printed by check executed after decompilation and can be triggered by many issues, thats why it occurs very often. Also, that check is the main reason why `show inconsistent code` option was added - because this check can wrongly trigger warning :(

**Comment by skylot** [comment]
@sergey-wowwow I add assign inlining to fix the last case. This inlining is a little too aggressive for now, but I think it is better than error.
