### ISSUE TITLE
[core] Missing catch/finally statement for try

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#703]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
 (for example `JadxRuntimeException: Can't find immediate dominator for block`)
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
Class ``` com.paypal.android.p2pmobile.wallet.BaseWalletHandles ```
```java
    public com.paypal.android.p2pmobile.wallet.managers.IWalletOperationManager getWalletOperationManager() {
        synchronized (com.paypal.android.p2pmobile.wallet.WalletModel.class) {
            try {
                if (this.mWalletOperationManager == null) {
                    this.mWalletOperationManager = com.paypal.android.p2pmobile.wallet.managers.WalletOperationManager.newInstance();
                }
            } // the rest is missing
        }
        return this.mWalletOperationManager;
    }
```
APK: https://drive.google.com/file/d/1CSo_sZ71WsM3WvGw2VzG7xnkqpUO3GSJ/view?usp=sharing

**Comment by sergey-wowwow** [comment]
Could be more simple example ``` com.paypal.android.p2pmobile.p2p.common.eligibility.EligibilityCache ```
```java
    public synchronized com.paypal.android.p2pmobile.p2p.common.eligibility.EligibilityResult getEligibilityResult() {
        try {
        }
        return this.mEligibilityResult;
    }
```

**Comment by sergey-wowwow** [comment]
@skylot 
Can you please prioritize this one? It corrupts code inside ``` try ``` statement :(

**Comment by skylot** [comment]
Fixed. I hope :)
