### ISSUE TITLE
[core] Constructor and super constructor invocations should be first statements (update)

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#704]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
 (for example `JadxRuntimeException: Can't find immediate dominator for block`)
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
Original thread: https://github.com/skylot/jadx/issues/685

Can you place (super) constructor call on the first place? I've noticed that anonymous classes are changed to inner classes, but used external variables are not accessible anymore. Example (class ``` 
com.paypal.android.p2pmobile.wallet.common.fragments.ThreeDsWebViewFragment$C35854 ```)
```java
    /* renamed from: com.paypal.android.p2pmobile.wallet.common.fragments.ThreeDsWebViewFragment$4 */
    class C35854 extends android.os.CountDownTimer {
        final /* synthetic */ java.lang.String val$password; // <<< is not initialized anymore

        /* JADX WARN: Illegal instructions before constructor call commented (this can break semantics) */
        C35854(long j, long j2, java.lang.String str) {
            // this.val$password = str;
            super(j, j2);
        }
```
APK: https://drive.google.com/file/d/1CSo_sZ71WsM3WvGw2VzG7xnkqpUO3GSJ/view?usp=sharing

**Comment by sergey-wowwow** [comment]
@skylot 
You already added code to process ternary ops, can you do the same for string concats? Example in the same APK, class ``` com.paypal.android.foundation.activity.operation.ActivityDetailsRetrieveOperation ```
```java
    protected ActivityDetailsRetrieveOperation(ActivityItem.Id id, ActivityDetailsRequestParamsHelper activityDetailsRequestParamsHelper) {
        // StringBuilder sb = new StringBuilder();
        // sb.append("activity-details/");
        // sb.append(id.getValue());
        super(sb.toString(), ActivityItem.class, activityDetailsRequestParamsHelper);
        this.f13703a = id.getActivityType();
    }
```
it could be changed to 
```java
        super("activity-details/" + id.getValue(), ActivityItem.class, activityDetailsRequestParamsHelper);
```
or
```java
        super(new StringBuilder().append("activity-details/").append(id.getValue()).toString(), ActivityItem.class, activityDetailsRequestParamsHelper);
```

**Comment by sergey-wowwow** [comment]
And also variable declarations are still kept before constructor calls, file ``` com/paypal/android/foundation/core/model/MutableDataObject.java ```
```java
    public MutableDataObject(android.os.Parcel parcel) {
        org.json.JSONObject jSONObject;
        org.json.JSONObject jSONObject2;
        this();
```

**Comment by skylot** [comment]
All cases fixed.
And now instead of commenting code I just move constructor call to the top of the method.
