### ISSUE TITLE
[core] Use of type variables in children classes

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#706]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
 (for example `JadxRuntimeException: Can't find immediate dominator for block`)
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
File ``` com/paypal/android/p2pmobile/onboarding/components/NameComponent.java ```
```java
    public void initView(@NonNull Context context, @NonNull ComponentItem componentItem) {
        super.initView(context, componentItem);
        List<W> /* <<< */ fieldWrappersByFieldType = getFieldWrappersByFieldType(FieldItem.Type.NAME, FieldItemTextInputLayoutWrapper.class);
        if (fieldWrappersByFieldType == null || fieldWrappersByFieldType.isEmpty()) {
            throw new IllegalArgumentException("FieldItemTextInputLayoutWrapper is not initialized properly");
        }
        for (W w : fieldWrappersByFieldType) { // <<<<
            w.onViewAdded();
            addView(w.getView());
        }
    }
```
you see that ``` W ``` is used which is declared in its super class
```java
public class Component<T, W extends FieldWrapper> extends LinearLayout {
```
but in current class the type variable doesn't exist anymore
```java
public class NameComponent extends Component<String, FieldItemTextInputLayoutWrapper> {
```
APK: https://drive.google.com/file/d/1CSo_sZ71WsM3WvGw2VzG7xnkqpUO3GSJ/view?usp=sharing

**Comment by skylot** [comment]
Not reproducible anymore.
