### ISSUE TITLE
[core] Use of null without cast

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#707]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
The most simple test case is in file ``` com/paypal/android/p2pmobile/liftoff/cashout/usagetracker/CashOutTrackerHelper.java ```
```java
    private void trackWithKey(@android.support.annotation.NonNull java.lang.String str, com.paypal.android.p2pmobile.liftoff.cashout.model.FlowSession flowSession) {
        trackWithKey(str, flowSession, null);
    }
```
This call is ambiguous and in such cases method binding keeps unresolved :(

APK: https://drive.google.com/file/d/1CSo_sZ71WsM3WvGw2VzG7xnkqpUO3GSJ/view?usp=sharing

**Comment by skylot** [comment]
Fixed!

**Comment by sergey-wowwow** [comment]
Thanks :)
