### ISSUE TITLE
[core] null is assigned to boolean

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#709]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
File ``` com/paypal/android/foundation/core/util/ResourceUtil.java ```
```java
    public static String getStringFromRawResource(Context context, int i) {
        String next;
        CommonContracts.requireNonNull(context);
        boolean z = null; // <<<
```
And later in the same method
```java
        } finally {
            if (z != null) {
                try {
                    z.close(); // calling a methods of type boolean
```
APK: https://drive.google.com/file/d/1CSo_sZ71WsM3WvGw2VzG7xnkqpUO3GSJ/view?usp=sharing

**Comment by skylot** [comment]
Fixed. Cause of issue was incorrect finally block detection :(

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks! Hopefully some day all of such detections will be fixed :)
