### ISSUE TITLE
Nested anonymous classes variable assignment fails code generation

### ISSUE THREAD

**Issue by arteme** [skylot/jadx#71]
Consider the following example code:
```java
	// a basic abstract class for nesting example
	public static abstract class BasicAbstract {
		public abstract void doSomething();
	}

	public static class TestCls {
		private BasicAbstract inner;

		public void simpleAnonymous() {
            inner = new BasicAbstract() {
                @Override
                public void doSomething() {
                    inner = null;
                }
            };
		}
	}
```
Code gets generated correctly here. Now let's add another level of anonymous class:
```java
	// a basic abstract class for nesting example
	public static abstract class BasicAbstract {
		public abstract void doSomething();
	}

	public static class TestCls {
		private BasicAbstract outer, inner;

		public void nestedAnonymous() {
			outer = new BasicAbstract() {
				@Override
				public void doSomething() {
					inner = new BasicAbstract() {
						@Override
						public void doSomething() {
							inner = null;
						}
					};
				}
			};
		}
	}
```
Code generation fails. You can see that `inner = null` doesn't get generated correctly. Instead, it gets a whole new copy of `inner = new BasicAbstract() ...` with a lot of recursion of the same.

As far as I can tell, this is a regression from version 0.6.0, where anonymous classes were never transplanted into their original place, but instead left as external `class AnonymousClassN { ... }` definitions.

**Comment by skylot** [comment]
The error was in synthetic method inliner.
Decompiled code with disabled MethodInlinerVisitor: 
```java
public class TestCls {
    private BasicAbstract inner;
    private BasicAbstract outer;

    public static abstract class BasicAbstract {
        public abstract void doSomething();
    }

    static /* synthetic */ BasicAbstract access$002(TestCls x0, BasicAbstract x1) {
        x0.inner = x1;
        return x1;
    }

    public void test() {
        this.outer = new BasicAbstract() {
            public void doSomething() {
                TestCls.access$002(TestCls.this, new BasicAbstract() {
                    public void doSomething() {
                        TestCls.access$002(TestCls.this, null);
                    }
                });
            }
        };
    }
}
```
And both calls of `access$002` was incorrectly replaced with first call argument: 
```java
 TestCls.this.inner = new BasicAbstract() { ...
```

**Comment by arteme** [comment]
Once again, thank you for a blazing fast fix, it does indeed generate correct code for the sample above.

However, after this fix I have a problem, which I can't seem to isolate into a small test case. Take a look at https://github.com/danielesegato/android-support-library-archive/blob/master/v4/android-support-v4.jar and the decompile of `android.support.v4.view.ViewPager` class. The class has multiple constructors with different arguments with the constructor body largely repeated. The first constructor has the following statement:
```
        this.mEndScrollRunnable = new Runnable() {
            public void run() {
                ViewPager.this.setScrollState(ViewPager.SCROLL_STATE_IDLE);
                ViewPager.this.populate();
            }
        };
```
while all following constructors have the following:
```
        this.mEndScrollRunnable = /* anonymous class already generated */;
```

**Comment by arteme** [comment]
Okay, actually, the source for that class (https://github.com/danielesegato/android-support-library-archive/blob/master/v4/src/java/android/support/v4/view/ViewPager.java) shed light on what was going on.

Unlike the decompile, the original source initializes `mEndScrollRunnable` at declaration time, not in the constructor, which triggers the problem. Here is a test:
```java
	public static class TestCls {

		public interface BasicAbstract {
			void doSomething();
		}

		private BasicAbstract x = new BasicAbstract() {
			@Override
			public void doSomething() {
				y = 1;
			}
		};
		private int y = 0;

		public TestCls() {
		}

		public TestCls(int z) {
		}
	}
```
