### ISSUE TITLE
Feature request: Exclude class paths

### ISSUE THREAD

**Issue by clviper** [skylot/jadx#713]
Hi there,

First of all thank you for this great project. Sometimes people forget the effort that is required to make available for free our work.

It would be nice to be possible to exclude certain class paths in the Class Search feature. This is particularly useful for example when searching for particular code, but end up it a lot of noise, because of the hits the search returns for example in classes that are related to the framework itself. 

One possible implementation would be a field where we can define a regex for classes to exclude during the search or a local exclusion file that can be configured with that information.

Cheers,

**Comment by jpstotz** [comment]
Jadx can already exclude packages from being decompiled and indexed. This will also affect the search results: find spots in classes that belong to excluded packages can not be found.

However AFAIR this is a global Jadx setting which affects every loaded APK file.

**Comment by clviper** [comment]
Oh. I totally missed that setting in the Preferences. That suits my needs. Thank you for the feedback.
