### ISSUE TITLE
very slow after opening class that have big byte array

### ISSUE THREAD

**Issue by HaCkErNiCe** [skylot/jadx#714]
some APK's (and // protected by DexProtector)  in decryptions class have very big byte array.
if i want to open this class with jadx, It freezes
you can check class "co.palang.QuizOfKings.ProtectedCoronaApplication" in QuizOfKings game(download from googleplay)

**Comment by jpstotz** [comment]
If the UI is not capable o handle such large data you can still decompile the APK to sources using jadx on the command-line.

Afterwards you can check if any of your editors is capable to displays the large files.

**Comment by HaCkErNiCe** [comment]
@jpstotz i did what you said, open this class with Notepad++ not freezes my pc, just little slow, on scrolling.
but jadx fully freeze

**Comment by jpstotz** [comment]
The common Java UI components are not designed to handle extreme situations. This applies to most Java AWT/Swing gui components as well as SWT components. 

Therefore Jadx can only use or not use those components. Furthermore exchanging central components like the source code viewer would cause significant amount of time as a lit of jadx functionality depends upon it.

If you are a Java developer feel free to make your own tests and provide improvements to jadx and/or any of the components Jadx uses (like [RSyntaxTextArea](https://github.com/bobbylight/RSyntaxTextArea) which is used a source code viewer).

**Comment by skylot** [comment]
I just run the profiler and found that problem in line numbers rendering. Then disabled, code viewer works fine and not freeze. And that not RSyntaxTextArea fault, this component was added by me :(
I will try to optimize it or adjust condition to disable it as I did previously [here](https://github.com/skylot/jadx/blob/d89ec67888fc86a82eb7d26d06a4689f8499f321/jadx-gui/src/main/java/jadx/gui/ui/codearea/CodePanel.java#L56).

**Comment by HaCkErNiCe** [comment]
Thank you, good luck

**Comment by skylot** [comment]
Fixed! Can anyone check the [latest build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) to confirm the fix?

**Comment by JorgeTebruski** [comment]
Now works  fine.

**Comment by HaCkErNiCe** [comment]
Yeeah works fine
