### ISSUE TITLE
[core] Use of registers in enum declarations

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#716]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
Example code
```java
package com.paypal.android.p2pmobile.activityitems.model;

public enum AccountFilterType {
    ALL_TRANSACTIONS(java.lang.Integer.valueOf(0)),
    PAYPAL_CASH(r3), // <<<
    PAYPAL_CASH_PLUS(r3);
```

APK: https://drive.google.com/file/d/1fCN9PXu8Zw4Kdnhgd0_qmzEvgWLfEU-9/view?usp=sharing

**Comment by skylot** [comment]
Fixed by deboxing commit: fd7d08c
