### ISSUE TITLE
[core] Logic  error when break to label.

### ISSUE THREAD

**Issue by xpoy1** [skylot/jadx#722]
Jdax decompiled:

                    if (!TextUtils.isEmpty(a2)) {
                        int length = a2.length();
                        if (length > 16) {
                            this.f2574c = a2.substring(0, 16);
                            this.f2575d = a2.substring(length - 16);
                            q.c(f2572a, "[] check ok resp=" + Resp + " authKey:" + this.f2574c + " IV:" + this.f2575d);
                            m2302w();
                        }
                    }
                    this.f2574c = "blabalbala";
                    this.f2575d = "blabalbalabb";
                    q.c(f2572a, "[] check ok resp=" + Resp + " authKey:" + this.f2574c + " IV:" + this.f2575d);
                    m2302w();

FernFlower decompiled:

             if (var6.length > 0) {
                  label22: {
                     String var7 = ablabala.d.a(var6);
                     if (!TextUtils.isEmpty(var7)) {
                        int var5 = var7.length();
                        if (var5 > 16) {
                           this.c = var7.substring(0, 16);
                           this.d = var7.substring(var5 - 16);
                           break label22;
                        }
                     }

                     this.c = "blabalbala";
                     this.d = "blabalbalabb";
                  }

                  q.c(a, "[] check ok resp=" + var1 + " authKey:" + this.c + " V:" + this.d);
                  this.w();

org.telegram.b.c
public boolean a(HandshakeResp var1)
[issue dex](https://c-t.work/s/78f8a494220d4b)

**Comment by skylot** [comment]
@xpoy1 this issue is similar to second case in #699. 
And after implementing assign inlining example code looks like this:
```java
                    String a3 = org.sugram.foundation.cryptography.d.a(a2);
                    if (TextUtils.isEmpty(a3) || (length = a3.length()) <= 16) {
                        this.c = ",.<>{}:*&^%$#@!~";
                        this.d = ",.<>{}:*&^%$#@!~";
                    } else {
                        this.c = a3.substring(0, 16);
                        this.d = a3.substring(length - 16);
                    }
                    q.c(a, "[handshakeCallback] check ok resp=" + handshakeResp + " authKey:" + this.c + " authKeyIV:" + this.d);
                    w();
```
