### ISSUE TITLE
[core] Primitive is compared with null

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#723]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
> But regressions are expected, feel free to report :)

Probably it's a regression one :)

File ``` com/paypal/android/p2pmobile/activityitems/model/ActivityItemsModel.java ```
```java
    /* JADX WARNING: Incorrect type for immutable var: ssa=java.lang.Long, code=long, for r6v0, types: [java.lang.Long] */
    public boolean hasValidItem(com.paypal.android.foundation.activity.model.ActivityItem.Id id, long j) {
        if (j == null) { // <<<
            j = 900000L;
        }
        android.util.Pair pair = (android.util.Pair) this.mItemLruCache.get(id);
        if (pair == null) {
            return false;
        }
        if (java.lang.Long.valueOf(((java.lang.Long) pair.first).longValue() + /* >>> */j.longValue()).longValue() > java.lang.Long.valueOf(android.os.SystemClock.uptimeMillis()).longValue()) {
            return true;
        }
        return false;
    }
```
APK: https://drive.google.com/file/d/1fCN9PXu8Zw4Kdnhgd0_qmzEvgWLfEU-9/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow in this case jadx was incorrectly change type of method parameter from `Long` to `long`. I commit a fix for that.
Also, this method is a nice sample to show how many boxing (and unboxing) methods can be removed:
```java
public boolean hasValidItem(Id id, Long l) {
    if (l == null) {
        l = 900000L;
    }
    Pair<Long, ActivityItem> pair = this.mItemLruCache.get(id);
    if (pair == null) {
        return false;
    }
    return pair.first + l > SystemClock.uptimeMillis();
}
```
Anyway, now jadx only replace boxing of constants, like: `Long.valueOf(900000)` to `900000L`.
