### ISSUE TITLE
[core] Use of null without cast 2

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#724]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
File ``` com/paypal/android/p2pmobile/p2p/sendmoney/activities/ChangeShippingAddressActivity.java ```
```java
    public void onNotApplicableSelected() {
        if (this.mCurrentAddress == null) {
            super.onBackPressed();
            return;
        }
        this.mFlowManager.getUsageTracker().track("shippingaddress|selectednoshipping");
        android.content.Intent intent = new android.content.Intent();
        intent.putExtra("result_address", null); // <<<, putExtra(...) has multiple implementations
        setResult(-1, intent);
        finish();
    }
```
APK: https://drive.google.com/file/d/1fCN9PXu8Zw4Kdnhgd0_qmzEvgWLfEU-9/view?usp=sharing

**Comment by sergey-wowwow** [comment]
@skylot 
Can you fix it please?

**Comment by skylot** [comment]
@sergey-wowwow I made a temporary workaround for this issue: all null args will be cast to target type.
Hope this will help.

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks, perfect now!
