### ISSUE TITLE
[core] Change class modifiers if used outside the package

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#729]
**Checks before report**
- [+] check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- [+] search existing issues by exception message
- [+] check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki

**Describe error**
Hi, I've noticed a lot of classes (which in their past life were lambdas/anonymous classes) placed to different package, but have package-private modifiers. Example is in file ``` com/paypal/android/sdk/contactless/reader/tlv/TLVTransformer.java ```
```java
    public static final TLVTransformer<String> TO_HEX_STRING_NO_WHITESPACE = new p000.C3854Zg();
```
and
```java
package p000;

/* renamed from: Zg  reason: case insensitive filesystem */
class C3854Zg implements TLVTransformer<String> {
```

Can it be changed to ``` public ``` (as a part of ``` --respect-bytecode-access-modifiers ``` argument)?

APK: https://drive.google.com/file/d/1AH04tuU-rwCGpznW5IrjlunnxApQGnLo/view?usp=sharing

**Comment by sergey-wowwow** [comment]
@skylot 
Can you fix this please? It appears that the bindings are not being resolved if a part of parent expression is not accessible in current scope (e.g. `new InaccessibleClass().method()`, so reference to `method()` won't be resolved, and this creates a lot of problems)

**Comment by skylot** [comment]
@sergey-wowwow 
I made a fix in `dex-input-refactor` branch. In this branch, I made a new dex parser which allows instructions fast scan to collect usage info.

**Comment by sergey-wowwow** [comment]
Thanks! But please check class `okhttp3.CertificatePinner$Builder`
```java
        @org.jetbrains.annotations.NotNull
        public final okhttp3.CertificatePinner build() {
            return new okhttp3.CertificatePinner(kotlin.collections.CollectionsKt___CollectionsKt.toSet(this.pins), null);
        }
```
In this case class `kotlin.collections.CollectionsKt___CollectionsKt` is package-private

And similar thing in class `com.google.android.gms.common.api.internal.zabo`
```java
    private final /* synthetic */ com.google.android.gms.common.api.internal.GoogleApiManager.zac zajg;
```
in this case inner class `com.google.android.gms.common.api.internal.GoogleApiManager.zac` is declared as `private`:
```java
    private class zac implements com.google.android.gms.common.api.internal.zach, com.google.android.gms.common.internal.BaseGmsClient.ConnectionProgressReportCallbacks {
```

APK: https://drive.google.com/file/d/1qC3tlWs9AtPBpyS6iU9kcSphLryfJOxi/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow another fix, same branch.

**Comment by sergey-wowwow** [comment]
@skylot 
Please check different APK, there are a few cases where the bug still exists
Class `com.grab.payments.ui.wallet.creditcard.C36875l` (`com.grab.payments.ui.wallet.creditcard.l`)
```java
        public void onSuccess(com.stripe.android.model.Source source) {
            if (source != null) {
                com.stripe.android.model.StripeSourceTypeModel sourceTypeModel = source.getSourceTypeModel(); // <<<
```
class `com.stripe.android.model.StripeSourceTypeModel` is package-private

and

class `net.rtccloud.sdk.User`
```java
                    u.displayName = builder.displayName();
                    u.extras.putAll(builder.extras());
                    return u;
```
fields `displayName` and `extras` are private and inaccessible in this scope

APK: https://drive.google.com/file/d/1Umqt8wXZTm4sBqsvzjEFq-97qC-i8l-b/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow I made a fix for the first case. In the second case variable `u` must be `User` type or at least cast to it to match bytecode. I will try to fix that in the next commit.

**Comment by skylot** [comment]
@sergey-wowwow commit a fix for second case.
Also, I merged `dex-input-refactor` into master, so fix also in master now.
