### ISSUE TITLE
Can't jump to class when holding [command] in MacOS

### ISSUE THREAD

**Issue by miaochiahao** [skylot/jadx#734]
Hi, I'm using jadx the latest version on MacOS Mojave. On my windows machine, when I hold ctrl and click on a class, it jumps into the definition of class. But It won't happen on my Mac.
I hold command and click on a class, nothing happens.
Any idea?

**Comment by sergey-wowwow** [comment]
Use also ``` control ``` button

**Comment by igottime** [comment]
@bagipro use control buttton will bring up context menu. how to sovle it
