### ISSUE TITLE
[feature] Reduce logs

### ISSUE THREAD

**Issue by superpoussin22** [skylot/jadx#735]
The idea is to reduce the logs of jadx cli 

it's doable with an xml file containing : 
`    
<configuration> <root level="OFF"> </root> </configuration>`

then the scripts must be modified : 

For linux and mac 
`DEFAULT_JVM_OPTS="\"-Xms128M\" \"-Xmx4g\" \"-XX:+UseG1GC\" \"-Dlogback.configurationFile=${APP_HOME}/bin/jadx.xml\""
`
and for windows : 
`set DEFAULT_JVM_OPTS="-Xms128M" "-Xmx4g" "-XX:+UseG1GC" "-Dlogback.configurationFile=%APP_HOME%/bin/jadx.xml"`

**Comment by skylot** [comment]
@superpoussin22 thanks for this solution, but for me, it looks like a workaround.
So I decided to make it more configurable and add options for control log level to jadx cli:
```
--log-level        - set log level, values: QUIET, PROGRESS, ERROR, WARN, INFO, DEBUG, default: PROGRESS
-q, --quiet        - turn off output (set --log-level to QUIET)
-v, --verbose      - verbose output (set --log-level to DEBUG)
```
By default jadx will output only "progress" info like:
```
INFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 1
```
And if you want you can disable output completely using `-q` or `--quiet` option

Also, your solution with custom log config via `-Dlogback.configurationFile=` will continue to work. For this, I add detection of such configuration and if found jadx will ignore any log-level options.

As always you can check these changes in [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files)

**Comment by superpoussin22** [comment]
tjanks @skylot, that's perfect
