### ISSUE TITLE
Facebook apk is getting extracted for a long time through command line.

### ISSUE THREAD

**Issue by prasanth-vegabird** [skylot/jadx#746]
Hi, 
I tried to extract the apk of facebook using below command. Its running for long time. But I am getting results immediately if  I use jadx-gui. I think some attributes needs to be added when i run through command line. Can you please help me to solve this issue?
command is "jadx facebook.apk"
![Capture](https://user-images.githubusercontent.com/54832816/64149636-034d3400-ce44-11e9-931b-f6f2b4c10e32.PNG)

**Comment by sergey-wowwow** [comment]
Their app is huge (100k+ source files), that's why it takes a long time. Jadx-gui shows only class structure immediately, but it doesn't decompile everything.

**Comment by prasanth-vegabird** [comment]
Thank You
