### ISSUE TITLE
[core][bug] case sensitive and insensitive errors

### ISSUE THREAD

**Issue by idoheinemann** [skylot/jadx#747]
when running on MacBook Pro, Jadx recognises case sensitive file systems as insensitive file systems and case insensitive file systems as case sensitive.

**Comment by jpstotz** [comment]
When opening an issue you should provide a bit more info that just one sentence:

1. What is Jade?
2. What is the effect of this case sensitive and insensitive errors?

**Comment by idoheinemann** [comment]
Jade is a typo, supposed to be "Jadx".
I learned about this bug due to the following situation:
I had classes in the same package, one is called Z and one is called z (only difference is lower-upper case).
when running Jadx decompiler (not Jadx gui) on the apk file on a case insensitive file system, I found out that only the file z.java exists, and it holds the content that the file Z.java should have held.
I tried to do the same thing using a case sensitive file system, and found out that neither of the files exist in the package, instead appeared files calle C001.java and C002.java, when i opened the files there was a comment at the beggining: `/* renamed from (package name).z, reason: case insensitive file system */`

the only way i could make Jadx decompile the apk successfully is to run it on a case insensitive system, but have the output folder be mounted on a case sensitive volume

**Comment by jpstotz** [comment]
I am not sure if jadx automatically detects case (in)sensitive file-systems. For Jadx on command-line you should use the parameter `--fs-case-sensitive` if you are on a case sensitive file-system.

**Comment by skylot** [comment]
@idoheinemann jadx do not try to detect file system case sensitivity and treat it like case insensitive by default.
In your case, the only way to save `z.java` and `Z.java` is to rename one of the classes, so I think this is "correct" decompilation and I don't see any errors here.
If you have case sensitive filesystem and don't like such renaming, you can change this using `--fs-case-sensitive` options as suggested by @jpstotz.
Also, you can disable any renaming completely by providing `--rename-flags none`.
