### ISSUE TITLE
[core] Jadx not work with JRE 8 221

### ISSUE THREAD

**Issue by thelittlefireman** [skylot/jadx#748]
**Describe error**
After upgrade to jre 8 221, i cannot run jadx, i always get a "Could not create the Java Virtual Machine. Error: a fatal exception has occured. Program will exit."
I have to roolback to JRE 8 152 to get it launch.

 jadx release version 1.0.0

Thanks
regards

**Comment by sergey-wowwow** [comment]
https://stackoverflow.com/questions/18459945/how-to-solve-could-not-create-the-virtual-machine-error-of-java-virtual-machine

Edit jadx launchers and specify less memory

**Comment by Eeyhan** [comment]
before:
`set DEFAULT_JVM_OPTS="-Xms1024M" "-XX:MaxRAMPercentage=70.0" "-XX:+UseG1GC" "-Dawt.useSystemAAFontSettings=lcd" "-Dswing.aatext=true" "-Djava.util.Arrays.useLegacyMergeSort=true"
`

after modification：
`@set DEFAULT_JVM_OPTS="-Xms1024M" "-XX:MaxRAMPercentage=70.0" "-XX:+UseG1GC" "-Dawt.useSystemAAFontSettings=lcd" "-Dswing.aatext=true" "-Djava.util.Arrays.useLegacyMergeSort=true"
set DEFAULT_JVM_OPTS="-Xms128M" "-Xmx10g"`

Notice：

annotate with "@"  defalut

**Comment by jpstotz** [comment]
@Eeyhan Can you please post the exact version string of the used Java runtime (including build version). As far as I know the parameter `-XX:MaxRAMPercentage` was not included in the first (now ancient) Java 8 versions.
