### ISSUE TITLE
Hi, Maybe issue..

### ISSUE THREAD

**Issue by leekangwoo** [skylot/jadx#75]
Hi, I ran jadx.

If I run gui and click search button, search window pops up. But then it stops and at the same time errors happen in the terminal. On Window, the search bar is not activated and the progress bar keeps running. So I have to force quit it. I downloaded OSX using git to build on my own. It turned out that it’s not a problem specific to the latest version only, but it keeps showing the error message for all the previous versions as well. It doesn’t work on both Windows and OSX so I think there is a bug. Since it’s developed with java, the operation is not expected to be heavily dependent on platform and java version, but could you please check this out and confirm it for me?

Test platform
OS X 10.10 + Open JDK 6
OS X 10.10 + Open JDK 7
OS X 10.10 + Oracle JDK 6
OS X 10.10 + Oracle JDK 7
Windows 8.1(OS X 10.10 Parallels) + Open JDK 6
Windows 8.1(OS X 10.10 Parallels) + Open JDK 7
Windows 8.1(OS X 10.10 Parallels)  + Oracle JDK 6
Windows 8.1(OS X 10.10 Parallels)  + Oracle JDK 7

**Comment by skylot** [comment]
Hello,
Can you share apk file which you try to decompile or at least a error you get?
Looks like the problem in some method or class in which decompilation stuck in infinite loop.

**Comment by leekangwoo** [comment]
Thank you so much.
I will send your mail.

**Comment by leekangwoo** [comment]
Thank you so much.
I attached with a test video file.

Have a good day!

​
 Akinator_3.42.apk
<https://drive.google.com/a/seworks.co/file/d/0B63utgdKbuSEOTc4bXpkQnJ6dDQ/view?usp=drive_web>
​​
 BeFunky_5.6.0.apk
<https://drive.google.com/a/seworks.co/file/d/0B63utgdKbuSERFV2SDVBOWVFa3c/view?usp=drive_web>
​​
 com.facebook.katana.apk
<https://drive.google.com/a/seworks.co/file/d/0B63utgdKbuSEUVY2RGJJWExsVlE/view?usp=drive_web>
​​
 2015-07-20_10-57-45.mp4
<https://drive.google.com/a/seworks.co/file/d/0B63utgdKbuSEbnhPb2ZRQlcxTjg/view?usp=drive_web>
​

2015-07-20 5:16 GMT-07:00 skylot <notifications@github.com>:

**Comment by skylot** [comment]
Wow! Thank you for video )
In current version then you open search dialog starts full decompilation of all classes (and also indexing) and here 'cancel' button actually not working and after closing search dialog decompilation continues in background ( and next you open another apk which makes even worse by starting other decompilation process.

I will make those operation cancelable and background.
So for now you need to wait while decompilation finished.

Also in latest git version indexing for full text search uses a lot of memory so jadx can hang up or throws OutOfMemory exception, to fix this you need to increase maximum heap memory for java (see [Readme Troubleshooting section](https://github.com/skylot/jadx#out-of-memory-error))

**Comment by MehdiQuantom** [comment]
Hi When I Click On **jadx-gui.bat** 
Command Window Opens And Do Some Works For **1sec** Aftar That Nothing _Changed_ :(
even I Cant See Error List .
Some One Help Pls . . .

**Comment by asashour** [comment]
@MehdiQuantom: please open a new case.

Instead of clicking on `jadx-gui.bat`, open command prompt first, then `cd` to the directory, then type `jadx-gui.bat`, and see the output.
