### ISSUE TITLE
after commit 1cbaad3, code seach doesn't work properly

### ISSUE THREAD

**Issue by ryu-s-r** [skylot/jadx#755]
after 1cbaad3
![image](https://user-images.githubusercontent.com/46911763/66154942-9521aa00-e659-11e9-8407-5d12cb914e6a.png)

at 401d08e 
![image](https://user-images.githubusercontent.com/46911763/66155311-4e807f80-e65a-11e9-8022-b5e34ee9b56e.png)

**Comment by jpstotz** [comment]
@ryu-s-r Have you checked how the decompiled code of the class `MainActivity` has changed? 
May be the method `startActivityForresult` has decompiling problems/errors and therefore is no longer shown in the search result. 
Furthermore can you provide the APK file you used for identifying this issue?

**Comment by ryu-s-r** [comment]
you can find the sample APK here https://apkplz.net/app/com.beauty.cool.camera (not the same as on the screenshots,but the same problem occurs)

**Comment by skylot** [comment]
Thank you @ryu-s-r !
I made a fix for this issue.
Class was not indexed due to exception:
```java
ERROR - Index error in class: com.beauty.cool.camera.MainActivity
jadx.core.utils.exceptions.JadxRuntimeException: JavaClass not found by ClassNode: com.beauty.cool.camera.MainActivity.1.ax
	at jadx.api.JadxDecompiler.getJavaClassByNode(JadxDecompiler.java:332)
	at jadx.api.JadxDecompiler.convertNode(JadxDecompiler.java:389)
	at jadx.api.JavaClass.getUsageMap(JavaClass.java:143)
	at jadx.gui.utils.CodeUsageInfo.processClass(CodeUsageInfo.java:39)
```
which occur if class contains not generated inner class (like anonymous class in this example).
