### ISSUE TITLE
[feature] Kotlin Metadata annotation deobfuscation enhancment

### ISSUE THREAD

**Issue by yaroslavyadrov** [skylot/jadx#758]
Sometimes Kotlin [Metadata](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-metadata/index.html) annotation stays in .dex files due to bad obfuscation. It seems like this annotation contains package and class names in `extraString` parameter.
Maybe it will be useful to use them for better deobfuscation?

**Comment by skylot** [comment]
@yaroslavyadrov sure, this will be a nice feature.
Also, Kotlin often inserts null checks with names for method arguments.

**Comment by HellPie** [comment]
I would like to add that Kotlin is usually very useful in regards with reverse engineering not just for null checks, which are sometimes very vague but more with `toString`, which is often implemented by Kotlin-s compiler and offers very easy to read (at least for a human) the binding between the original name and the obfuscated name.

**Comment by yaroslavyadrov** [comment]
So, I'll try to implement this in a couple of weeks or so then
