### ISSUE TITLE
[core]Endless jadx

### ISSUE THREAD

**Issue by superpoussin22** [skylot/jadx#769]
**Checks before report**
- check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed)
- check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
- search existing issues by exception message

**Describe error**
apk used is : https://f-droid.org/repo/com.nextcloud.client_30080190.apk 

output of jadx provide ( on ubuntu 18.04) 
`` WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.rits.cloning.Cloner (file:/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/                                                                                                                    tools/jadx/lib/cloning-1.9.12.jar) to field java.util.TreeSet.m
WARNING: Please consider reporting this to the maintainers of com.rits.cloning.Cloner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
^Croot@b7138f185e6e:~/Mobile-Security-Framework-MobSF# ./StaticAnalyzer/tools/jadx/bin/jadx -ds /tmp -r /root/.MobSF/uploads/60ac13724348dac5f1f5ba427f5eebbd/60ac13724348dac5f1f5ba427f5eebbd.apk
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.rits.cloning.Cloner (file:/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/jadx/lib/cloning-1.9.12.jar) to field java.util.TreeSet.m
WARNING: Please consider reporting this to the maintainers of com.rits.cloning.Cloner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

and nothing more :(

  **Note**: no need to copy method fallback code (commented pseudocode)
- attach or provide link to apk file (double check apk version)

  **Note**: GitHub don't allow attach files with `.apk` extension, but you can change extension by adding `.zip` at the end :)

**Comment by jpstotz** [comment]
I am sorry but I can't reproduce your problem. 

Using latest unstable version "jadx-1.0.0-b1157-f228a721.zip" the command you posted works without problems and decompiles the APK file you have linked.

BTW: using /tmp without any subdirectory is a bad idea as the decompilation will create ~16 subdirectories which then mic-up with the other content of /tmp.

**Comment by superpoussin22** [comment]
will test again and let you know ( by default we only include stable release in MobSF)
using /tmp was only to grab output:    when used in MobSF we don't use /tmp

**Comment by superpoussin22** [comment]
perfect for me :)
