### ISSUE TITLE
Jadx recompile apk[feature]

### ISSUE THREAD

**Issue by ericsia** [skylot/jadx#771]
*Describe your idea:*
I have no idea how your app are so amazing at handling Unicode.
Apktool seems outdated, wonder if you can fork a version and help fixing the unicode issue.
https://github.com/iBotPeaches/Apktool/issues/2195
Or better implement recompilation of apk into your tool

**Comment by sergey-wowwow** [comment]
> Or better implement recompilation of apk into your tool
Jadx generates gradle project if requested, you can use it to built the app back

**Comment by ericsia** [comment]
it will be hard to do it like this since you need to fix a lot of syntax error if the apk is huge. That's why I ask this

**Comment by sergey-wowwow** [comment]
@ericsia 
That’s why each syntax error has to be fixed individually

**Comment by jpstotz** [comment]
That is why apktool is better for recompiling. The smali code is simpler and usually does not contain any errors.

**Comment by ericsia** [comment]
> That is why apktool is better for recompiling. The smali code is simpler and usually does not contain any errors.

It can't for certain circumstances, that's why I request for the coder's help. https://github.com/iBotPeaches/Apktool/issues/2195
