### ISSUE TITLE
Java tab to xml tab Switch bugs, as follows gif

### ISSUE THREAD

**Issue by ihbing** [skylot/jadx#772]
window10
![res](https://user-images.githubusercontent.com/27600008/67998931-299d1d80-fc95-11e9-8036-db2675e347a8.gif)

**Comment by jpstotz** [comment]
Which Jadx version do you use? Have you tried the latest unstable version? Does this bug occur always?
Which Java version is used (shown for example in Jadx about box)?

**Comment by skylot** [comment]
Can anyone confirm this issue? Because I can't reproduce it on latest master :(
