### ISSUE TITLE
Latest gui version useless with complicate apk

### ISSUE THREAD

**Issue by dungelin** [skylot/jadx#79]
I try latest version jadx-0.6.1-dev-build207(1st, August) with some apk, it's never finish.
Show progress and stop for hours and not responding (Windows 10 x64, 16GB ram, Core i7).
I have used jadx-0.6.1-dev-build201 (29th, June) with those file and it work fine.
So i guest that the pre-decompiled (index in backround) feature have some bug and it can not pass. So please add option to preference to turn off this feature .

**Comment by skylot** [comment]
In latest commits I added index for full text search and for this jadx starts in background full decompilation process. All this increase memory usage.
You can try to increase maximum java heap size, see [Increase java heap size](https://github.com/skylot/jadx#out-of-memory-error).
Also you can stop these background processes, but if you open search dialog it will run again.
Anyway I will try to reduce memory usage. And I will add option for disable auto start of background processes (or disable code search index at all)
Thank you!

**Comment by nirangasandaruwan** [comment]
even if i Increased java heap size latest jadx decompiler consumes more memory and it takes lot of time to decompile apk.some time apks dont get decompile.while i decompilin apk i cant continue my other taks and os get freezed.erlier versions before jadx-0.6.1-dev-build207 works very well.pleaseeee fix this issue ASP and try not consuming lots of memory white decompiling.Thank You.

**Comment by dungelin** [comment]
@skylot What about this bug?

**Comment by skylot** [comment]
I made some memory usage improvements and option in settings for disable autostart of full decompilation and index.
Please check latest unstable build and confirm that this work for you.

**Comment by dungelin** [comment]
@skylot Thank you, it work with me when disable autostart of full decompilation and index. But if turn on it will not finish, UI not responsible and hang the computer. Hope you can fix it soon.

**Comment by Razysb** [comment]
I have same problem am increased heap mmry but not work

**Comment by jpstotz** [comment]
@bensh Your results does not surprise me. 

The default garbage collector of Java 8 is not very good. Java consumes memory faster than the garbage collector can free it even if the memory is already unused. This ends up in a much higher memory usage. 

Newer Java versions use G1GC which drastically can reduce the memory usage because of faster memory releasing at run-time. Therefore I strongly recommend to use Java 11 for running JadX when decompiling large apps (or manually select G1GC garbage collector if you sill want to use Java 8).

**Comment by sergey-wowwow** [comment]
Should be fixed in the previously reported issues
