### ISSUE TITLE
[feature] Try to restore open tabs on file reload

### ISSUE THREAD

**Issue by S-trace** [skylot/jadx#792]
Hello.

I added a feature to allow jadx-gui to restore open tabs on file reload.
It saves a list of open classes and scroll positions before reopening file and then tries to restore tabs back when file is reopened.
This feature is extremely important for rename function, because file is reloaded after renaming items.
I pushed it to https://github.com/S-trace/jadx/tree/restore_tabs
Could you please review it and allow me to open pull request?

Thank you.

**Comment by skylot** [comment]
@S-trace nice feature! Open PR and I will merge it

**Comment by S-trace** [comment]
Thank you.
I opened the pull request #793 for this.

The only problem with current implementation is reset of the jumps history (after file reload jumps history is lost).
I don't know, is saving old jump history saint or not. Could you please take look on this problem?

**Comment by skylot** [comment]
@S-trace restore jump history is not hard I will try to fix it later :+1:
