### ISSUE TITLE
[feature] Add a classes list for keep constants references if "Replace constants" is off

### ISSUE THREAD

**Issue by S-trace** [skylot/jadx#800]
*Describe your idea:*
Hello.

The list of classes to keep references instead of inlining its constants may be very useful for class R - inlined decimal constants is very unreadable in code (R.colors.blue looks much better than 4278255360).

Maybe it would be useful to implement such list (like "Excluded packages")?
The list is necessary, because some constants (like Android Framework's constants) could be also much readable in a reference format.

@skylot 
What do you think about this?

**Comment by skylot** [comment]
@S-trace it is hard to understand what you try to archive :(
Jadx already replaces constants with field reference if possible, especially unique ones like from R class. Please clarify your idea with some before/after example.
