### ISSUE TITLE
Text search's result is incompleted

### ISSUE THREAD

**Issue by addhaloka** [skylot/jadx#801]
jadx version: 1.1.0-b1181-cc29da8e
![1](https://user-images.githubusercontent.com/30489650/70882823-e3fd9f80-200b-11ea-8c6a-8d0c51b3b580.png)

**Comment by jpstotz** [comment]
Please provide the APK file where the problem occurs (you can just rename it to zip and upload it to this issue). Otherwise it is next to impossible to reproduce and fix the problem.

**Comment by skylot** [comment]
@addhaloka please check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files), similar issue #812 was fixed recently, and maybe it fix your case too.

**Comment by addhaloka** [comment]
it works!
