### ISSUE TITLE
[core]find usage error

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#803]
jadx version: dev(2019.12.15 the lastest)
apk link:`https://drive.google.com/open?id=1K6SD0ZLd3Vidnej4f9a3KnbbjREfpLDy`
apk version:`3.2.150-3002150`

class:`com.adguard.android.l`
find:`license_valid_until_end_life`
![1](https://user-images.githubusercontent.com/42903751/71148802-9bdab900-2267-11ea-929c-6fba3fa14332.png)

but
class:`com.adguard.android.ui.DrawerActivity`
find:`license_valid_until_end_life`
method:`public void g()`
![image](https://user-images.githubusercontent.com/42903751/71148866-d2183880-2267-11ea-8938-54a00df39084.png)

**Comment by xmhwws** [comment]
The problem of finding references is a bit bad, and I have found this problem on other apks in recent days.

**Comment by jpstotz** [comment]
Then please provide at least one of them including the info which text part can not be found.

**Comment by xmhwws** [comment]
> Then please provide at least one of them including the info which text part can not be found.

I have provided 1 before, the apk download link in the screenshot is wrong?
![image](https://user-images.githubusercontent.com/42903751/71321874-035c6700-24fb-11ea-8f80-3bbb0852b514.png)

Think about finding references based on smali? I have used software similar to jadx, which is searched according to smali, so this problem has never occurred, but it is mobile software, and it requires payment, and it is not open source.

**Comment by jpstotz** [comment]
You are right, I missed that link.

**Comment by xmhwws** [comment]
> You are right, I missed that link.

I'm sorry, I don't know why this happens, I always thought you could see this link. I'm also curious, it's been several days since I apparently responded to the question, but I didn't receive a response.

What should I do to give you the link? Google link blocked by github?

**Comment by jpstotz** [comment]
Using the latest unstable build I can not reproduce this issue. 
Opening the usage of `l.license_valid_until_end_life` I am getting two references:

1. the definition in `com.adguard.android.l`
2. the usage in `com.adguard.android.ui.DrawerActivity.g()`.

Please always test the latest unstable build before opening an issue.

**Comment by xmhwws** [comment]
Thank you for your help, the problem has been resolved.


> Please always test the latest unstable build before opening an issue.

I raised this question on 2019.12.19, the screenshot is as follows:
![时间](https://user-images.githubusercontent.com/42903751/71337000-9beaf980-2584-11ea-98d8-a9974bb632cb.png)
At that time, the latest version of jadx was 2019.12.15, and the screenshot is as follows:
![commit](https://user-images.githubusercontent.com/42903751/71337028-b45b1400-2584-11ea-993c-c650978d10dc.png)
So when I asked this question, I was using the latest version of jadx。
