### ISSUE TITLE
edit resources.arsc

### ISSUE THREAD

**Issue by Henry2o1o** [skylot/jadx#805]
Is it only possible to edit resources.arsc/res/values/?
arrays-, plurals-,strings.xml, etc.

a kind of arsc editor, I just want to change/insert/remove translations

![image](https://user-images.githubusercontent.com/6131799/71160841-9326ba80-2248-11ea-94c0-4566431cba3a.png)

**Comment by sergey-wowwow** [comment]
Jadx has a feature to export gradle project, then you can edit and rebuild an app
