### ISSUE TITLE
https://bintray.com/skylot/jadx/unstable/v1.1.0-b1196-9ab003df

### ISSUE THREAD

**Issue by Henry2o1o** [skylot/jadx#810]
resource.arsc can no longer be opened

**Comment by skylot** [comment]
@Henry2o1o sorry about that. This is a regression introduced in c64ffde11fbf4fb2a76b16098f662acc90209a6a.
Just now I push a fix, you can check [build 1.1.0-b1197-0c55ab90](https://bintray.com/skylot/jadx/unstable/v1.1.0-b1197-0c55ab90#files).

**Comment by Henry2o1o** [comment]
> @Henry2o1o sorry about that. This is a regression introduced in [c64ffde](https://github.com/skylot/jadx/commit/c64ffde11fbf4fb2a76b16098f662acc90209a6a).
> Just now I push a fix, you can check [build 1.1.0-b1197-0c55ab90](https://bintray.com/skylot/jadx/unstable/v1.1.0-b1197-0c55ab90#files).

😄👍

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/71325628-d191d300-24ef-11ea-84bd-570ae8f2a633.png)
What is / will it be?

**Comment by Henry2o1o** [comment]
Will jadx ever have a string editing?
