### ISSUE TITLE
[gui] full text search does not find all occurrences

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#812]
Something similar happened before: 
https://github.com/skylot/jadx/issues/803#issue-540100836
https://github.com/skylot/jadx/issues/742#issue-484938135

jadx version: dev(2019.12.23 the lastest commit！) and jadx-1.1.0-b1197-0c55ab90
Tested both my compiled jadx and the unstable version of jadx you posted

apk link: https://drive.google.com/open?id=1ZC4soMkpfcFiGwbHb3bHIm0-PjxY6AQO
apk version:`3.3.227-10000227`

class:`com.adguard.android.n`
find:`joke_phrase_0`
![image](https://user-images.githubusercontent.com/42903751/71343146-e2971e80-2599-11ea-85be-bc289fbd9103.png)

but in GDA：
![image](https://user-images.githubusercontent.com/42903751/71343502-0444d580-259b-11ea-97cf-b70754560390.png)
Open jadx to the same location
class:`com.adguard.android.ui.DrawerActivity`
find:`joke_phrase_0`
method:`protected void onPostCreate(android.os.Bundle bundle)`
![image](https://user-images.githubusercontent.com/42903751/71343253-31dd4f00-259a-11ea-93df-2f3c7a00f9cf.png)

This is the third time I have encountered the same problem in jadx and I don't know what to do.
I sincerely suggest you think about it: `search based on smali`

**Comment by jpstotz** [comment]
I can not reproduce this issue. I downloaded the linked APK file and opened it in jadx-1.1.0-b1197-0c55ab90 on Windows using AdoptOpenJDK 11.0.5.

Full text for `joke_phrase_0` shows me 3 occurrences. The two from your screen shot plus the one in com.adguard.android.ui.DrawerActivity.

Are you sure you have assigned enough RAM/Heap for Jadx so that Jadx is able to fully decompile the app and create the full text index? If Jadx is running out of ram the full text index may be incomplete. 

In my environment 4 GB max heap is sufficient to open the APK file you have posted. If you use an older Java version you may need more RAM as the memory management of older Java versions is not as good as the one from Java 11.

**Comment by xmhwws** [comment]
This is incredible, weird!

Environment: windows10 professional version 1909 (10.0.18363.535)
`java version "1.8.0_181"`
Java (TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot (TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
jadx version: jadx-1.1.0-b1197-0c55ab90

Using the default jadx-gui.bat, the results are as follows:
![1](https://user-images.githubusercontent.com/42903751/71358888-86e28a80-25c5-11ea-9c6b-8cbed2bc0edb.png)


Modify jadx-gui.bat:
the first time:
`DEFAULT_JVM_OPTS = "-Xms600M" "-Xmx8g"`
the second time:
`DEFAULT_JVM_OPTS = "-Xms600M" "-Xmx10g"`
The results are the same twice, both are:
![2](https://user-images.githubusercontent.com/42903751/71358901-8f3ac580-25c5-11ea-8b0f-26dcf8e5ca60.png)

Is this error because the java version is too low?

**Comment by xmhwws** [comment]
I may find the reason, as shown in the figure:
![3](https://user-images.githubusercontent.com/42903751/71359571-d3c76080-25c7-11ea-94ae-34eb376f831b.png)

Right click these two, click "Exclude", jadx will increase:
![4](https://user-images.githubusercontent.com/42903751/71359574-d6c25100-25c7-11ea-9129-a8fa3937e4d6.png)

But I just want to exclude `android.support. *` and `androidx. *`, I didn't know that it would cause this bug before.

**Comment by skylot** [comment]
I found cause of the problem:
```java
ERROR - Index error in class: com.adguard.android.ui.DrawerActivity
jadx.core.utils.exceptions.JadxRuntimeException: JavaMethod not found by MethodNode: androidx.appcompat.app.AppCompatActivity.findViewById(int):T
	at jadx.api.JadxDecompiler.getJavaMethodByNode(JadxDecompiler.java:354)
	at jadx.api.JadxDecompiler.convertNode(JadxDecompiler.java:392)
	at jadx.api.JavaClass.getUsageMap(JavaClass.java:143)
	at jadx.gui.utils.CodeUsageInfo.processClass(CodeUsageInfo.java:39)
	at jadx.gui.jobs.IndexJob.lambda$runJob$0(IndexJob.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
This index error occur sometimes not always, and looks like it is a multithreading problem, setting threads count to 1 resolve all exceptions.

@xmhwws try to set 'Processing threads count' in preferences to `1`, hope this will work as a workaround.

**Comment by xmhwws** [comment]
@skylot Thanks for your help, what you said may be a hidden bug.

I identified the problem, which is what I said earlier https://github.com/skylot/jadx/issues/812#issuecomment-568469983
When I right-click on android.support, jadx excludes android, not android.support!
And com.adguard.android.ui.DrawerActivity includes android, so it may cause this bug.

As long as I un-exclude android, this problem will not exist.

Your discovery may be a new hidden bug?

**Comment by skylot** [comment]
I made a fix for synchronization issue, this fix resolve exceptions for me. Please check latest unstable build.
Also, I think that excluding packages not relevant to this issue. And looks like you have wrong understating how exclude packages is work. In short: in packages list you can edit **root** packages to exclude separated by space. So if you want to exclude `android.support.*` just write `android.support`. If you write `android` this will exclude `android` and **all sub packages** like `android.support`. Hope this will help.

**Comment by xmhwws** [comment]
@skylot  you are right.
5 threads + exclude android androidx, as shown in the figure:
![2019-12-24_16-25-38](https://user-images.githubusercontent.com/42903751/71403449-c0b99c80-266a-11ea-8db4-3e60d9db7381.png)


jadx still works, the search shows all results.

You say exclusion, writing `android` will only exclude `android. *` Instead of `. * Android. *` ? I understand it wrong.
This issue should have been resolved, so I close this issue?

**Comment by skylot** [comment]
@xmhwws 
> You say exclusion, writing android will only exclude android. * Instead of . * Android. * ?

Yes, excluded only packages started with `android.` i.e in regexp syntax: `^android\..*`
In java code [here](https://github.com/skylot/jadx/blob/7f8d03d1927b95565938a4e2089f4cbed3417979/jadx-gui/src/main/java/jadx/gui/JadxWrapper.java#L91) class excluded if:
```java
cls.getFullName().equals(exclude) || cls.getFullName().startsWith(exclude + '.')
```
