### ISSUE TITLE
[feature]Some suggestions on decompiling reserved class names when decompiling.

### ISSUE THREAD

**Issue by Humenger** [skylot/jadx#814]
*Describe your idea:*
```java

/* renamed from: gdy  reason: default package */
/* compiled from: ConvBgHelper */
public class gdy {
    public static String dak() {
        return Application.getInstance().GetProfileManager().GetCurrentProfile().path() + File.separator + "convwallpaper" + File.separator;
    }

```
![image](https://user-images.githubusercontent.com/27600008/71438358-6e42b380-2730-11ea-9651-6ef37187b770.png)
Can you rename 'gdy' directly to 'ConvBgHelper'?

**Comment by skylot** [comment]
@ihbing this feature is a part of the deobfuscation step now. To enable: switch on deobfuscation and make sure `Use source file name as class name alias` option is enabled.
And as soon as this feature is often asked I will make it independent from deobfuscation and enable by default, so I will keep this issue open.

**Comment by naijun0403** [comment]
I also want this feature. It will be very effective for analyzing proguarded apk.

**Comment by skylot** [comment]
> I will make it independent from deobfuscation

These changes already in master, check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).
Although, option disabled by default (not useful in most cases), to enable go to `Preferences->Rename identifiers->Use source file name as class name alias`

**Comment by naijun0403** [comment]
I mean, I want this function to exist independently of the obfuscation process.
