### ISSUE TITLE
Deobuscate Error AndroidMAnifest.xml and .xml and Please add feature Migrate to Androidx

### ISSUE THREAD

**Issue by klikpaspor** [skylot/jadx#819]
`ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.`

![androidmanifest](https://user-images.githubusercontent.com/42468310/71496455-b3abd180-2853-11ea-8432-72aae7bd88a9.png)

if i'm remove `<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28"/>`
i'm got error `ERROR: Manifest merger failed with multiple errors, see logs`

`Found item Animation/? more than one time`
![xml](https://user-images.githubusercontent.com/42468310/71496496-e0f87f80-2853-11ea-97d2-1bac72aa1df3.png)

![xml](https://user-images.githubusercontent.com/42468310/71497256-be686580-2857-11ea-8327-e0f03d8b672e.png)

**Comment by jpstotz** [comment]
Looks like the binary AndroidManifest.xml has been obfuscated/stripped and now contains only values for minSdkVersion and targetSdkVersion. Jadx then thinks those values are resource-ids but they are the real values. 

Can you please provide the APK file that causes this problem (you can rename it to zip and upload here or post the link).

**Comment by sergey-wowwow** [comment]
@klikpaspor 
This could be fixed in https://github.com/skylot/jadx/issues/844. Please check or attach your apk
