### ISSUE TITLE
Multi-variable type inference failed - code decompiled incorrectly

### ISSUE THREAD

**Issue by gcusick8** [skylot/jadx#821]
Issue:
public class ACAduserEnglishByteUtil {
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r0v1, resolved type: byte} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r0v3, resolved type: byte} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r0v4, resolved type: byte} */
    /* JADX WARNING: Multi-variable type inference failed */
    /* Code decompiled incorrectly, please refer to instructions dump. */
public static java.lang.String printByteArrayHex(byte[] r6, int r7, int r8) {
        /*
            java.lang.StringBuffer r3 = new java.lang.StringBuffer
            r3.<init>()
            r2 = r7
        L_0x0006:
            int r4 = r7 + r8
            if (r2 < r4) goto L_0x000f
            java.lang.String r4 = r3.toString()
            return r4
        L_0x000f:
            if (r2 <= r7) goto L_0x0016
            java.lang.String r4 = ","
            r3.append(r4)
        L_0x0016:
            byte r4 = r6[r2]
            if (r4 >= 0) goto L_0x0042
            byte r4 = r6[r2]
            int r0 = r4 + 256
        L_0x001e:
            java.lang.String r4 = java.lang.Integer.toHexString(r0)
            java.lang.String r1 = r4.toUpperCase()
            int r4 = r1.length()
            r5 = 1
            if (r4 != r5) goto L_0x0045
            java.lang.StringBuilder r4 = new java.lang.StringBuilder
            java.lang.String r5 = "0"
            r4.<init>(r5)
            java.lang.StringBuilder r4 = r4.append(r1)
            java.lang.String r4 = r4.toString()
            r3.append(r4)
        L_0x003f:
            int r2 = r2 + 1
            goto L_0x0006
        L_0x0042:
            byte r0 = r6[r2]
            goto L_0x001e
        L_0x0045:
            r3.append(r1)
            goto L_0x003f
        */
        throw new UnsupportedOperationException("Method not decompiled: com.kelly.ACAduserEnglish.ACAduserEnglishByteUtil.printByteArrayHex(byte[], int, int):java.lang.String");
    }
...
}
[ACAduserEnglish-signed.apk.zip](https://github.com/skylot/jadx/files/4007199/ACAduserEnglish-signed.apk.zip)

**Comment by gcusick8** [comment]
Using this same apk, there were other issues decompiling that I am wondering if they are the same or related issue:

public class ACAduserEnglishDeviceKerry {
...
    /* JADX WARNING: Removed duplicated region for block: B:4:0x0012 A[LOOP:0: B:4:0x0012->B:13:0x0046, LOOP_START] */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public int readcmd() {
        /*
            r9 = this;
            r3 = 1
            r4 = 0
            int r5 = r9.COMType
            if (r5 != r3) goto L_0x003f
            r5 = 300(0x12c, float:4.2E-43)
            r9.Timeout = r5
        L_0x000a:
            long[] r5 = r9.time
            long r6 = java.lang.System.currentTimeMillis()
            r5[r4] = r6
        L_0x0012:
            long r5 = java.lang.System.currentTimeMillis()
            long[] r7 = r9.time
            r7 = r7[r4]
            long r5 = r5 - r7
            int r7 = r9.Timeout
            long r7 = (long) r7
            int r5 = (r5 > r7 ? 1 : (r5 == r7 ? 0 : -1))
            if (r5 < 0) goto L_0x0044
        L_0x0022:
            boolean r5 = r9.ETS_Rx_Status
            if (r5 == 0) goto L_0x0049
            r9.ETS_Rx_Status = r4
            r0 = 0
            byte[] r5 = r9.readInfo
            byte r5 = r5[r3]
            int r5 = r5 + 3
            byte[] r0 = new byte[r5]
            byte[] r5 = r9.readInfo
            int r6 = r0.length
            java.lang.System.arraycopy(r5, r4, r0, r4, r6)
            byte r5 = r0[r4]
            byte r6 = r9.ETS_TX_CMD
            if (r5 == r6) goto L_0x0051
            r3 = 2
        L_0x003e:
            return r3
        L_0x003f:
            r5 = 100
            r9.Timeout = r5
            goto L_0x000a
        L_0x0044:
            boolean r5 = r9.ETS_Rx_Status
            if (r5 == 0) goto L_0x0012
            goto L_0x0022
        L_0x0049:
            r9.readIndex = r4
            byte[] r5 = r9.readInfo
            r5[r3] = r4
            r3 = r4
            goto L_0x003e
        L_0x0051:
            boolean r5 = r9.ETS_Rx_Error
            if (r5 == 0) goto L_0x0059
            r9.ETS_Rx_Error = r4
            r3 = 3
            goto L_0x003e
        L_0x0059:
            int r5 = r0.length
            java.lang.String r1 = com.kelly.ACAduserEnglish.ACAduserEnglishByteUtil.printByteArrayHex(r0, r4, r5)
            byte[] r5 = r9.readInfo
            byte r4 = r5[r4]
            r9.ETS_RX_CMD = r4
            byte[] r4 = r9.readInfo
            byte r4 = r4[r3]
            r9.ETS_RX_BYTES = r4
            byte r4 = r9.ETS_RX_BYTES
            if (r4 <= 0) goto L_0x003e
            r2 = 0
        L_0x006f:
            byte r4 = r9.ETS_RX_BYTES
            if (r2 >= r4) goto L_0x003e
            byte[] r4 = r9.ETS_RX_DATA
            byte[] r5 = r9.readInfo
            int r6 = r2 + 2
            byte r5 = r5[r6]
            r4[r2] = r5
            int r2 = r2 + 1
            goto L_0x006f
        */
        throw new UnsupportedOperationException("Method not decompiled: com.kelly.ACAduserEnglish.ACAduserEnglishDeviceKerry.readcmd():int");
    }

And:

public class ACAduserEnglishKellyPage extends Activity {
...
  /* JADX WARNING: type inference failed for: r5v35, types: [byte[]] */
    /* JADX WARNING: type inference failed for: r5v36, types: [byte] */
    /* JADX WARNING: type inference failed for: r5v54, types: [byte[]] */
    /* JADX WARNING: type inference failed for: r5v55, types: [byte] */
    /* JADX WARNING: type inference failed for: r5v66, types: [byte[]] */
    /* JADX WARNING: type inference failed for: r5v67, types: [byte] */
...
 /* JADX WARNING: type inference failed for: r6v21, types: [byte[]] */
    /* JADX WARNING: type inference failed for: r6v22, types: [byte] */
    /* access modifiers changed from: private */
...
}

Lastly - great work with the jadx project!  Greatly appreciate all that you and your team have done!

**Comment by sergey-wowwow** [comment]
Currently they decompiled *almost* well, except one thing `abyte & 255` expression instead of `abyte & 0xFF`. I will find a simpler case and report in a separate issue

**Comment by gcusick8** [comment]
I downloaded the latest "unstable" build and tried again.  There are
several methods still not decompiling and for more reasons than the one
thing you mentioned.  Should I have seen different results?

Thanks again for all your work on this project!

Greg

**Comment by sergey-wowwow** [comment]
@gcusick8 
Did you try to turn on `Show inconsistent code` option? It seems that there are a few reason of such errors, and it's better to try to cover them using simpler test cases instead of huge methods. The first your example should be covered with that issue https://github.com/skylot/jadx/issues/921

**Comment by gcusick8** [comment]
I turned on the "Show inconsistent code" option.  I can now see more
decompiled code but some of it seems incorrect (due to decompile issues
possibly?).  What should I be looking for?

Thanks!

Greg

**Comment by sergey-wowwow** [comment]
There are two issues, one of them is reported with simpler test case https://github.com/skylot/jadx/issues/921, second one is related to type inference, potentially your case is also reported in a separate issue (https://github.com/skylot/jadx/issues/920, https://github.com/skylot/jadx/issues/917), I would recommend to monitor them, because IMO they are more simple (methods where errors are happened seem smaller)
