### ISSUE TITLE
[core] use d8 library instead deprecated dx to convert java classes to dex

### ISSUE THREAD

**Issue by skylot** [skylot/jadx#823]
`dx` was deprecated and replaced with new [`d8`](https://developer.android.com/studio/command-line/d8) library. `dx` not support latest java class versions and java8 features, but this implemented in new `d8` library.

**Comment by jpstotz** [comment]
Just replacing dx with d8 is unfortunately not an option. See #1070 for details.

**Comment by skylot** [comment]
Now jadx have `java-input` plugin for direct parsing of java bytecode, also added option to use dx/d8.
