### ISSUE TITLE
[core]     /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v1, resolved type: byte}

### ISSUE THREAD

**Issue by jiongjarjar** [skylot/jadx#827]
package com.szcx.lib.encrypt.p205a;

import com.bumptech.glide.load.Key;
import java.security.MessageDigest;

/* renamed from: com.szcx.lib.encrypt.a.b */
public class MD5Util {
    /* renamed from: a */
    public static String m17863a(String str) {
        try {
            return m17864a(MessageDigest.getInstance("MD5").digest(str.getBytes(Key.STRING_CHARSET_NAME)));
        } catch (Exception e) {
            e.printStackTrace();
            return "";
        }
    }

    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v1, resolved type: byte} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v4, resolved type: byte} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v5, resolved type: byte} */
    /* JADX WARNING: Multi-variable type inference failed */
    /* renamed from: a */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    private static java.lang.String m17864a(byte[] r5) {
        /*
            java.lang.StringBuilder r0 = new java.lang.StringBuilder
            r0.<init>()
            int r1 = r5.length
            r2 = 0
        L_0x0007:
            if (r2 >= r1) goto L_0x0022
            byte r3 = r5[r2]
            if (r3 >= 0) goto L_0x000f
            int r3 = r3 + 256
        L_0x000f:
            r4 = 16
            if (r3 >= r4) goto L_0x0018
            java.lang.String r4 = "0"
            r0.append(r4)
        L_0x0018:
            java.lang.String r3 = java.lang.Integer.toHexString(r3)
            r0.append(r3)
            int r2 = r2 + 1
            goto L_0x0007
        L_0x0022:
            java.lang.String r5 = r0.toString()
            return r5
        */
        throw new UnsupportedOperationException("Method not decompiled: com.szcx.lib.encrypt.p205a.MD5Util.m17864a(byte[]):java.lang.String");
    }
}

**Comment by sergey-wowwow** [comment]
@jiongjarjar 
Please provide dex/jar/apk and only then reopen the issue
