### ISSUE TITLE
Issue with BindView annotation and IDs[core]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#831]
**Checks before report**
 
  Verified Everything.

**Describe error**
![image](https://user-images.githubusercontent.com/35992798/72359495-65804480-3714-11ea-82d3-da57ed4ae329.png)
Take a look at the above image. The BindView annotation have resource ID's integer value from R class instead of exact resource id like <b>@BindView(R.id.myId)</b> not like <b>@BindView(2131....)</b>

Is there any workaround for this?

**Comment by jpstotz** [comment]
The generated R classes usually have all resource IDs as `public static final int` fields. The Java compiler treats them as constants and replaces every usage of this constant by it's value to speed-up the class loading process. 

Therefore the compiled class (and hence the decompiled class) only contains the value and not the reference to the field of the R class the value comes from. 

The only chance would be to build a mapping table for all R entries and the guess for each number if it is a resource id or not.

**Comment by skylot** [comment]
@redmi111 thanks! Fixed, please check latest unstable build.

**Comment by redmi111** [comment]
Wow, that's so quick. Thanks, mate. It's solved now.

**Comment by redmi111** [comment]
![image](https://user-images.githubusercontent.com/35992798/75611942-0dc35e80-5b45-11ea-84ef-5f628efc29c2.png)

The same issue with the older butterknife library.

**Comment by skylot** [comment]
@redmi111 fixed, thanks!
