### ISSUE TITLE
Mismatching Identifier names in exception handling[core]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#833]
![image](https://user-images.githubusercontent.com/35992798/72608311-5c77b900-3948-11ea-8244-f5f46aba22bf.png)

As you can see in the above image decompiled code have a different identifier from the catch clause' parameter. 

JADX is including non-declared variable ( mostly 'e') everywhere.  

Also, see this line: <b>long unused11 = AgentCreateListing.d2 = this.date2.getTime();
</b> Why there is long unused11?

I appreciate your work, mate. Thanks in Advance.

**Comment by sergey-wowwow** [comment]
Hi @redmi111,
Such issue was already reported in https://github.com/skylot/jadx/issues/101 (I believe the cause is the same)
