### ISSUE TITLE
[core] Use of Object type instead of template type

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#836]
Hi, I've noticed an issue that prevents method resolution. Class ``` com.samsung.knox.securefolder.util.WeakReferenceHandler ```
```java
public abstract class WeakReferenceHandler<T> extends android.os.Handler {
    private java.lang.ref.WeakReference<T> mReference;

    public void handleMessage(android.os.Message message) {
        java.lang.Object obj = this.mReference.get(); // should be "T t = ..."
        if (obj != null) {
            handleMessage(obj, message);
        }
    }

    public abstract void handleMessage(T t, android.os.Message message);
```

there are many of them, but it could be a simple case

APK: https://drive.google.com/file/d/1eEUDrNOTySdg4YCAFhtrG4514KOibJzE/view?usp=sharing

**Comment by skylot** [comment]
Fixed. Anyway many other cases with generics not yet covered.
