### ISSUE TITLE
[core] Decompilation never finishes for Tiktok app

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#840]
Hi, I'm trying to decompile Tiktok app (https://drive.google.com/file/d/1lfQvIqsfxXq8Uru6_voDDn50dkx_nBh3/view?usp=sharing) with the following settings
![image](https://user-images.githubusercontent.com/15173437/73224393-65536080-417a-11ea-850f-ee1d2ecc6f0b.png)

The only thing I see is repeating outputs like
```
INFO  - JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r5v116, resolved type: java.util.List} in com.ss.android.ugc.aweme.global.config.settings.pojo.IESSettings.ProtoAdapter_IESSettings.decode(com.squareup.wire.ProtoReader, com.ss.android.ugc.aweme.global.config.settings.pojo.IESSettings):com.ss.android.ugc.aweme.global.config.settings.pojo.IESSettings
```

Decompilation stucks at 99%, I believe there is only one class left which is never finished because of an endless loop

**Comment by jpstotz** [comment]
Are you sure you waited long enough? It seems like this app contains a very large class with hundred of variables, that requires some time for decompilation. In my tests the decompilation was finished in about 30 minutes. However during the decompilation I encountered several captured StackOverflowException, may be with a larger stack it would have taken even more time.

**Comment by sergey-wowwow** [comment]
I tried to decompile it on 16 core/64 GB of RAM machine, and waited for about 20 minutes, but it never finished

> I encountered several captured StackOverflowException

I believe that stopped the decompilation process, but it wasn't finished

**Comment by skylot** [comment]
I found class with a problem: `com.ss.android.ugc.aweme.global.config.settings.pojo.IESSettings$ProtoAdapter_IESSettings`
and method: `decode(Lcom/squareup/wire/ProtoReader;Lcom/ss/android/ugc/aweme/global/config/settings/pojo/IESSettings;)Lcom/ss/android/ugc/aweme/global/config/settings/pojo/IESSettings;`
from `classes5.dex`
This method is big and produces ~20k SSA varibles so second algorithm of type inference is stuck.
I made a fix that does not try to apply types if type resolving search has not found a complete solution. And this resolve stuck on loop with deep recursions [here](https://github.com/skylot/jadx/blob/1ce8fa8bdd4f3cf14206d7f5675b6c7e07ef7e08/jadx-core/src/main/java/jadx/core/dex/visitors/typeinference/TypeSearch.java#L89).
Anyway, this method is not decompiled :(

**Comment by sergey-wowwow** [comment]
Thanks, now it’s decompiled for seconds!
