### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by snajdovski** [skylot/jadx#841]
So I have a hobby of designing logos and that I use jadx a lot for learning how some apps work under the hood I want to contribute by throwing a new material design logo
Here is link:
https://imgur.com/a/HONlL8z
Here is the svg format of the logo (many other formats added):
https://github.com/snajdovski/JADXLOGO

**Comment by skylot** [comment]
@snajdovski thanks, nice logo!
And I really like resemblance with android logo colors and style (like [this](https://zdnet4.cbsistatic.com/hub/i/r/2019/08/22/5e05c9d9-27a7-4691-93fa-257717df6582/resize/1200xauto/3b52721e776692c80a537d65e191dc0a/android-logo-stacked-rgb.jpg)).
But as soon as jadx already has a logo (thanks to @ethanblake4 #420) I don't think I will change it, sorry :( 
Anyway, thank you for the great work :+1:
