### ISSUE TITLE
[core]Decompilation error？

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#850]
the lastest unstable jadx
apk链接：https://drive.google.com/open?id=1MX9UCAAoro9pYFYLsEANtnT1rhWk2jgQ

class name：com.adobe.libs.services.utils.SVUtils
method name：public static String getServiceType(SVConstants.SERVICES_VARIANTS serviceVariant)

Lcom/adobe/libs/services/utils/SVUtils;->getServiceType(Lcom/adobe/libs/services/utils/SVConstants$SERVICES_VARIANTS;)Ljava/lang/String;

in jadx：
![jadx](https://user-images.githubusercontent.com/42903751/74235580-520fcb80-4d0a-11ea-9ac4-176e4b65630c.png)

in jeb：
![jeb](https://user-images.githubusercontent.com/42903751/74235583-54722580-4d0a-11ea-9257-9a0b3910baa3.png)

**Comment by skylot** [comment]
@xmhwws thanks! I made a fix, please check latest unstable build.

**Comment by xmhwws** [comment]
thanks! It is ok now.
