### ISSUE TITLE
[feature]upgrade smali/baksmali

### ISSUE THREAD

**Issue by superpoussin22** [skylot/jadx#852]
FYI, smali and baksmali 2.4.0 are out with more support for Android 10

2020-02-05 smali/baksmali v2.4.0 is out.

Adds support for the new hidden restriction api flags introduced for framework dex files in Android 10

This includes a backwards-incompatible change to the Method and Field interfaces, which now have a new getHiddenApiRestrictions method.

Several small fixes and improvements to the rewriter functionality
Thanks to Lanchon for the bug reports/suggestions!
This includes a backwards-incompatible change to move the DexFile rewriter from DexRewriter to 

the RewriterModule, for consistency will all the other rewriters.

Added a new DexBackedDexFile constructor that accepts a DexBuffer. Thanks huaxin-gg!
Changes

**Comment by skylot** [comment]
@superpoussin22 thanks. I update all dependencies in 87320348dd3d6d7dc22207378c62309b359cef4f
