### ISSUE TITLE
[bug]Complied class has many useless variables

### ISSUE THREAD

**Issue by GvcZhang** [skylot/jadx#859]
I had a test for this problem by using old version and latest version, the problem stays always.
![image](https://user-images.githubusercontent.com/45255699/74814578-8bf85780-5332-11ea-86f5-0cef09ae70f8.png)

I send the apk to my colleague, his result is good.
![image](https://user-images.githubusercontent.com/45255699/74814696-d5e13d80-5332-11ea-8550-4881a0286110.png)

The follow is my running environment.
![image](https://user-images.githubusercontent.com/45255699/74814796-045f1880-5333-11ea-86f3-9d3b3a927833.png)

java version "1.8.0_201"

I hope you can solve it, i need Jadx for my work.
Thanks.

**Comment by jpstotz** [comment]
Please check the Jadx preferences. The posted code looks like you have enabled the "Fallback mode (simple dump) option.

**Comment by GvcZhang** [comment]
> Please check the Jadx preferences. The posted code looks like you have enabled the "Fallback mode (simple dump) option.

Yes, thats's the problem. You save me lots of time. Thank you very much.

**Comment by GvcZhang** [comment]
1.
