### ISSUE TITLE
Don't show Enum (or other) types

### ISSUE THREAD

**Issue by eybisi** [skylot/jadx#860]
New malware obfuscators use lots of trash enums. For example following Cerberus [sample](https://github.com/skylot/jadx/files/4224302/sample.zip) have this structure when I open in jadx.
![trash](https://user-images.githubusercontent.com/21275072/74823593-010a6380-5318-11ea-9bea-68edfa01a30c.png)

Without enum:
![without_trash](https://user-images.githubusercontent.com/21275072/74822975-074c1000-5317-11ea-82b1-8412275eef90.png)

In order to filter enums ( and removing packages with only enums) option can be added to preferences.
![class](https://user-images.githubusercontent.com/21275072/74823210-69a51080-5317-11ea-96df-390b0dfb1182.png)

 If this is a feature we can add to jadx ( maybe other types also ). I can PR

**Comment by skylot** [comment]
@eybisi I see what you are trying to achieve but I don't think this is a good approach. It is better to try to detect not used enums and only after that delete them. Unfortunately, jadx doesn't collect usage info before decompilation, but I have plans to implement that sometime.
Anyway, thank you for your idea and a sample!

**Comment by addhaloka** [comment]
@skylot
```
.class final enum Lcom/sss/b;
.super Ljava/lang/Enum;

# static fields
.field public static final enum sss:Lcom/sss/b; # This field is hidden by jadx
```
