### ISSUE TITLE
Kotlin Apps Inline Issue[core]

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#862]
![image](https://user-images.githubusercontent.com/35992798/75089264-0caa9400-557d-11ea-95b2-10c0e967a088.png)

Hello there, As you can see in the above image, most of the apps which are written in Kotlin give this issue.

I'm appreciating your great work!. Thank You.

**Comment by skylot** [comment]
@redmi111 please share apk file to make it easier to reproduce and fix this issue.

**Comment by redmi111** [comment]
[https://we.tl/t-CViVYkEXuv](url) Here is the APK file and I'm sorry for the late response.
Thanks for your help.

**Comment by redmi111** [comment]
[APK Link](https://we.tl/t-CViVYkEXuv) Here is the APK file and I'm sorry for the late response.
Thanks for your help.

**Comment by redmi111** [comment]
Hi @skylot , is there any update on this. Thanks.

**Comment by sergey-wowwow** [comment]
@redmi111 
This is not an error. There are lots of codes in Kotlin contain anonymous classes and lambdas, that why a unique valid name for them is generated (there are no any real names, but you can manually change it in jadx-gui).

Please also refer to this issue https://github.com/skylot/jadx/issues/453
