### ISSUE TITLE
Warning: Can't wrap try/catch for region

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#863]
> [core] /* JADX WARNING: Can't wrap try/catch for region: R(5:1|2|3|4|(3:5|6|8)) */ /* JADX WARNING: Failed to process nested try/catch */ /* JADX WARNING: Missing exception handler attribute for start block: B:3:0x0009 */ /* JADX WARNING: Missing exception handler attribute for start block: B:5:0x0010 */ /* renamed from: a */ /* Code decompiled incorrectly, please refer to instructions dump. */

I know that some functions cannot be decommissioned, but I want to point out the full path of this function before anti-obfuscating.

**Comment by zgfflc** [comment]
In addition, I also suggest that when anti-obfuscation, some variables can be made meaningful.For example:  HashMap<String, Boolean> f422c = null;   HashMap<String, Boolean> hashMap_f422c = null;

**Comment by jpstotz** [comment]
I am sorry but based on your description it is next to impossible to derive any changes to Jadx to improve the decompilation process.

When opening an issue please include a concrete example of decompiled code and provide the APK file it was generated from.

**Comment by zgfflc** [comment]
the  app download link  http://www.dothantech.com/app/android/WeiDa_Label.apk

**Comment by jpstotz** [comment]
Based on the error message you are referring to is `com.dothantech.bluetooth.BluetoothUtils.a(android.bluetooth.BluetoothSocket)`.

@skylot The Smali code of this method seems to be relatively simple and straight-forward. 3 try-catch blocks where the 3rd try-catch block is located in the catch handler of the 2nd try-catch block. I am not sure why Jadx fails here. The only "special" besides the one nested try-catch block I see here is that the catch handler of try-block 1 and try-block 3 are empty. 

```
.method public static a(Landroid/bluetooth/BluetoothSocket;)V
    .registers 2

    if-eqz p0, :cond_13

    .line 475
    :try_start_2
    invoke-virtual {p0}, Landroid/bluetooth/BluetoothSocket;->getInputStream()Ljava/io/InputStream;

    move-result-object v0

    invoke-virtual {v0}, Ljava/io/InputStream;->close()V
    :try_end_9
    .catch Ljava/lang/Throwable; {:try_start_2 .. :try_end_9} :catch_9

    .line 480
    :catch_9
    :try_start_9
    invoke-virtual {p0}, Landroid/bluetooth/BluetoothSocket;->getOutputStream()Ljava/io/OutputStream;

    move-result-object v0

    invoke-virtual {v0}, Ljava/io/OutputStream;->close()V
    :try_end_10
    .catch Ljava/lang/Throwable; {:try_start_9 .. :try_end_10} :catch_10

    .line 485
    :catch_10
    :try_start_10
    invoke-virtual {p0}, Landroid/bluetooth/BluetoothSocket;->close()V
    :try_end_13
    .catch Ljava/lang/Throwable; {:try_start_10 .. :try_end_13} :catch_13

    :catch_13
    :cond_13
    return-void
.end method
```

**Comment by zgfflc** [comment]
That is right.Went on to say that: com.dothantech.common.DzClass , There's something wrong with this function    public static boolean m702a(java.lang.Class<?> r2, java.lang.Class<?> r3)

**Comment by zgfflc** [comment]
I found decompression code for this function m702a from JEB. For example
    public static boolean a(Class arg2, Class arg3) {
        if(arg2 == null) {
            return 0;
        }

        if(arg3 == null) {
            arg3 = Object.class;
        }

        while(true) {
            if(arg2 == arg3) {
                return 1;
            }

            if(arg2 != null) {
                if(arg2 == Object.class) {
                }
                else {
                    arg2 = arg2.getSuperclass();
                    continue;
                }
            }

            return 0;
        }

        return 0;
    }
