### ISSUE TITLE
Some long functions  decompile error

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#866]
in the com.dothantech.bluetoothprinter,some functions can not decompile. onReceive(),handleMessage()
link: https://pan.baidu.com/s/1GuMcbsV5ExGQN1gV1G1AiQ 
code：e210

**Comment by zgfflc** [comment]
After testing, I found that version 1.1.0-b1249-fa0a38d3 could be decomcompiled, but part of the source code was lost, while version 1.1.0 could not decomcompile the two functions.

**Comment by zgfflc** [comment]
com.dothantech.common.DzApplication has two functions error and lost a part of code.
    static {
        AnonymousClass1 r0;
        if (Build.VERSION.SDK_INT >= 14) {
            r0 = null;
        } else {
            r0 = new Runnable() {
                public void run() {
                    DzApplication.refreshVisibility(20);
                    DzHandler.getMainHandler().postDelayed(this, 1000);
                }
            };
        }
        sRefreshVisibilityRunnable = r0;
    }


    public static void registerVisibilityChanged() {
        synchronized (GlobalIntent) {
            if (!sVisibilityRegistered) {
                if (getApplication() != null) {
                    sVisibilityRegistered = true;
                }
            }
        }
    }

**Comment by sergey-wowwow** [comment]
@zgfflc 
Provided link is not available. Moreover, such issues related to missed blocks were already reported and currently in progress
