### ISSUE TITLE
This xml file can be decommissioned better

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#872]
android:layout_height="-1"replace android:layout_height="fill_parent"
android:orientation="0"replace android:orientation="horizontal"
android:layout_width="-1" replace android:layout_width="fill_parent"
android:orientation="1" replace android:orientation="vertical"
android:layout_gravity="0x50" replace android:layout_gravity="bottom"
android:persistentDrawingCache="0x1"  replace  android:persistentDrawingCache="animation"
android:gravity="0x70"  replace android:gravity="fill_vertical"
android:scrollbarStyle="0x3000000"  replace android:scrollbarStyle="outsideInset"
android:gravity="0x11" replace android:gravity="center"

I'm appreciating your great work!. Thank You.

**Comment by jpstotz** [comment]
I also have two "feature wishes" to you @zgfflc that would really be helpful:

1. For new issues/feature wishes use markdown formatting such as `android:layout_height="fill_parent"` that would improve readability.
2. Please provide more context what you are speaking about. In this case after reading your post the third time it was clear that you are talking about and Android layout resource, but the next time please write such details in your post.

**Comment by jpstotz** [comment]
Why do you first open an issue and later close it even if it has not been processed at all? This is the second issue you show this behavior.

**Comment by zgfflc** [comment]
I'm really sorry, because I found that your new version jadx-gui-1.1.0-b1249-fa0a38d3 solved some problems later. Some code decompression is not normal, so I refer to the tool jeb to fix it. Of course, I will continue to pay attention to your update, and then raise new issues.
