### ISSUE TITLE
Some large functions can not decompression, can use python platform decompression code twice

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#875]
When I was paying attention to your project, I was also testing the jeb software. I found that it could decompile all functions, but the resulting code contained a lot of "goto" code, which was then processed by the code of python platform.I have the script he used here for reference.
```python
# JEB script - demo AST API
# Remove dummy switches
# See www.android-decompiler.com/blog

import sys
import os
import time
from jeb.api import IScript
from jeb.api import EngineOption
from jeb.api.ui import View
from jeb.api.dex import Dex
from jeb.api.ast import SwitchStm, Compound, Constant, Goto, Label, Optimizer



class ASTRemoveDummySwitch(IScript):

  def run(self, jeb):
    self.jeb = jeb
    self.dex = self.jeb.getDex()

    # change or allow user-input or caret-based selection
    msig = 'Lcom/example/android/snake/TileView;->(Landroid/content/Context;Landroid/util/AttributeSet;I)V'
    r = jeb.decompileMethod(msig)

    m = jeb.getDecompiledMethodTree(msig)
    self.checkBlock(m.getBody())

    opt = Optimizer(jeb, m)
    opt.removeUselessGotos()
    opt.removeUnreferencedLabels()


  def checkBlock(self, block, level=0):
    i = 0
    while i < block.size():
      stm = block.get(i)
      #print '%s%s' % ('  '*level, stm)
      if isinstance(stm, SwitchStm):
        gotostm = self.checkDummySwitch(stm)
        if gotostm:
          block.set(i, gotostm)
          print '-> Switch replaced by goto %s' % gotostm.getLabel().getName()
          label = gotostm.getLabel()
          r = self.findFirstLabel(block, i + 1, level)
          if r and r[1] == level and r[0].getName() == label.getName():
            print '-> Removing [%d, %d)' % (i + 1, r[2])
            j = i + 1
            cnt = r[2] - j
            while cnt > 0:
              block.remove(j)
              cnt -= 1
      elif isinstance(stm, Compound):
        for b in stm.getBlocks():
          self.checkBlock(b, level+1)
      i += 1


  def findFirstLabel(self, block, begin=0, level=0):
    i = begin
    while i < block.size():
      stm = block.get(i)
      if isinstance(stm, Label):
        return (stm, level, i)
      elif isinstance(stm, Compound):
        for b in stm.getBlocks():
          r = self.findFirstLabel(b, 0, level+1)
          if r:
            return r
      i += 1
    return None
    

  def checkDummySwitch(self, sw):
    val = sw.getSwitchedExpression()
    if not isinstance(val, Constant):
      return None

    val = val.getInt()
    b = sw.getCaseBody(val)
    if not b or b.size() != 1:
      return None

    stm0 = b.get(0)
    if not isinstance(stm0, Goto):
      return None

    label = stm0.getLabel()
    return stm0
```

**Comment by skylot** [comment]
@zgfflc how this is relevant to jadx? And what are you trying to suggest?

**Comment by zgfflc** [comment]
What I'm trying to say is that you can also do this in two steps.
1. Simply decompile the smali code directly.
2. Use this script to process the output, or let the user call it manually.

**Comment by skylot** [comment]
So you want a scripting API? This is a lot of work and I don't think I will do it. Instead, I suggest writing an additional jadx visitor in java.
Anyway, I understand that some people just want some code and "pseudocode" with `goto` is better than nothing. Jadx already has a `fallback` mode, but it is verbose and lost some useful info. Also, you can enable `Show inconsistent code` option and this will show code if there are only warnings, but such code can be incorrect at some point so be careful.

**Comment by zgfflc** [comment]
Java has a third-party library called jython, that allows users to write their own python code if you can add it to the project.In addition, I would like to know one question, since it can be easily decommissioned into code with goto, why did it go wrong when decommissioning into real source code? Is the Java language itself not good at this logic processing coding?

**Comment by jpstotz** [comment]
Jython exists and works, however it is in my opinion not a good option as it bases on a "dead language": Python 2. And it does not look like it will ever support Python 3.

Additionally I would find it rather obscure to add a Python scripting interface to a tool that only makes sense for people with at least average Java skills.

**Comment by zgfflc** [comment]
Well, I agree with you. Now I have a project in hand that USES your tool to decompress the source code and recompile it successfully, but the execution logic is still a bit problematic. Can you update a version recently?Thank you very much!

**Comment by jpstotz** [comment]
@zgfflc Sorry but IMHO this is the wrong approach for real world Android apps. The chance that Jadx is able to compile each and every method successfully and without any errors is very very low. If you want to decompile and recompile an app please use apktool, modify the smali code and then again recompile it using apktool. Using this approach the chance of a working recompiled app is way higher.
