### ISSUE TITLE
[feature]jad -o -r -d src -s java src1/**/*.class

### ISSUE THREAD

**Issue by hktalent** [skylot/jadx#877]
jad -o -r -d src -s java src1/**/*.class

**Comment by jpstotz** [comment]
I am sorry but this is not a feature description. Please provide at a sentence that describes what feature  from your point of view should be added to Jadx and why.

**Comment by hktalent** [comment]
@jpstotz scene

- 1. I need to decompile the patch file of Weblogic's zip file
- 2. There will be many jars after unzipping
- 3. I use the following script to decompress automatically, and finally I need to decompile in batch

```
$ cat doGetWeblogicJava.sh
unzip $1
find . -name "*.jar"|xargs -I % bash -c 'unzip %;rm -rf %'
find . -name "*.jar"|xargs -I % bash -c 'unzip %;rm -rf %'
jad -o -r -d src -s java ./**/*.class
```
