### ISSUE TITLE
[core]Strange java syntax, find references are not available

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#879]
jadx version：latest unstable build（jadx-1.1.0-b1254-3c7be5e9）
apk link：https://drive.google.com/open?id=1J7vH3IPu8fVGoevW-K1kvzP6uMD4s7qN

class: `com.xmiles.finevideo.ui.widget.dialog.UpgradeVipCancelTipsDialog`
method: `onCreate`

![image](https://user-images.githubusercontent.com/42903751/76182749-ff3e0c80-6200-11ea-839c-e80d8dd31f9d.png)

![image](https://user-images.githubusercontent.com/42903751/76182786-2f85ab00-6201-11ea-9519-97b8c6deb0b9.png)

![image](https://user-images.githubusercontent.com/42903751/76182764-13820980-6201-11ea-84fd-a7a414da1b9a.png)

in jeb：
![image](https://user-images.githubusercontent.com/42903751/76182828-56dc7800-6201-11ea-8fb4-f456e79e7660.png)

![image](https://user-images.githubusercontent.com/42903751/76182862-63f96700-6201-11ea-95af-1f5c1e487cac.png)

![image](https://user-images.githubusercontent.com/42903751/76182883-75db0a00-6201-11ea-99e2-08db1b65eb2e.png)

![image](https://user-images.githubusercontent.com/42903751/76182909-8c816100-6201-11ea-8a27-d2501810c921.png)

**Comment by jpstotz** [comment]
Looks like the APK was processed by an obfuscator that renames the field names to Java reserved words like `protected` or `throws`. Look at the smali code and you will see that the names are part of the byte code.

You can easily get better field names by enabling in the Jadx preferences in section **Rename** the option **To be valid identifier**.

**Comment by xmhwws** [comment]
> Looks like the APK was processed by an obfuscator that renames the field names to Java reserved words like protected or throws. 

The important point is that only when the "**To be valid identifier**" option is turned on, lookup references can be used normally, and jeb does not have this problem.

**Comment by jpstotz** [comment]
Ok, now we are getting close to the actual issue. You have not included an issue description in your first post. Therefore it was not easy to understand why you opened the issue. 

This problem is caused by the text token type of the selected text. It is `RESERVED_WORD` and for this token type the "Find Usages" menu entry is not enabled.

**Comment by sergey-wowwow** [comment]
@xmhwws 
I'm not expecting this issue, in my case it's decompiled to
```java
    /* renamed from: abstract  reason: not valid java name */
    public android.view.View.OnClickListener f42075abstract;

    /* renamed from: boolean  reason: not valid java name */
    public android.widget.ImageView f42076boolean;

    /* renamed from: continue  reason: not valid java name */
    public java.lang.String f42077continue;

    /* renamed from: default  reason: not valid java name */
    public android.widget.TextView f42078default;

    /* renamed from: extends  reason: not valid java name */
    public android.widget.TextView f42079extends;

    /* renamed from: final  reason: not valid java name */
    public android.widget.TextView f42080final;

    /* renamed from: finally  reason: not valid java name */
    public android.widget.TextView f42081finally;

    /* renamed from: interface  reason: not valid java name */
    public final java.lang.String f42082interface;

    /* renamed from: package  reason: not valid java name */
    public android.view.View.OnClickListener f42083package;

    /* renamed from: private  reason: not valid java name */
    public android.view.View.OnClickListener f42084private;

    /* renamed from: protected  reason: not valid java name */
    public final boolean f42085protected;

    /* renamed from: strictfp  reason: not valid java name */
    public java.lang.String f42086strictfp;

    /* renamed from: throws  reason: not valid java name */
    public android.widget.TextView f42087throws;

    /* renamed from: volatile  reason: not valid java name */
    public java.lang.String f42088volatile;
```

I would recommend to enable all options in `Deobfuscation` and `Rename` sections in jadx-gui settings. Also use the latest jadx version https://github.com/skylot/jadx#build-from-source
