### ISSUE TITLE
[GUI]reproduces a previously resolved bug, search only in short names of methods and fields

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#882]
The latest version reproduces a previously resolved bug, link: https://github.com/skylot/jadx/commit/836585547502142dbdfdf4f3f73e273dcb49be59
I found that the bug is related to this Pr, link: https://github.com/skylot/jadx/pull/880

When I search for the method name, if the class name includes this string, jadx will also render. In fact, I only need jadx to match method names instead of class names;
For example, as shown in the figure:
![image](https://user-images.githubusercontent.com/42903751/76684982-28203080-664b-11ea-81fe-4fee0635e591.png)

**Comment by jpstotz** [comment]
What is the method name you actually want to find? Does it starts with `vip` is it the full method name?

**Comment by xmhwws** [comment]
> What is the method name you actually want to find? Does it starts with `vip` is it the full method name?

As shown in the figure, when the class name contains vip and the method name does not include vip, jadx also matches.
I just want to search for methods, not classes. Jadx, like this, interfered with my judgment.
If I want to search for a class, I just check the class option.
In general, jadx only needs to match methods with vip in the method name, there is no need to match methods with class names that contain vip.

**Comment by xmhwws** [comment]
For example, the above is what I want, the following is not.
![image](https://user-images.githubusercontent.com/42903751/76686013-370ae100-6653-11ea-9f70-f4f6cc4c5fb5.png)

In pr https://github.com/skylot/jadx/pull/880, you added a search for method method/field signatures, which is a great idea, thanks. This pr produces a little bug: searching for method names will match class names.

**Comment by xmhwws** [comment]
I thought about it, my previous description may not be clear.
When jadx searches for a method or field, it can match method names, variable names, and signatures. Do not match class names.

**Comment by jpstotz** [comment]
I agree with you the search options were not well-thought-out.

My main focus was that everything that is displayed also can be searched but especially for method names it does not make sense to include the class name into the search index when there is a special search type for class names. 

Therefore I played around a bit with the search types class, methods and fields to optimize the text that is used for the search index as well as the text that is displayed (see the PR #887).

**Comment by skylot** [comment]
@jpstotz I merged PR #887 but as soon as you mix types into index similar issue is possible if search string found in type but not in method/field name :(

Also, I found an issue with type formatting: if type contains generic so it cut on `<` symbol (i.e `List<String> field` become `String> field`). Looks like this issue is an old one, and exists before your change.

**Comment by jpstotz** [comment]
@skylot That you can search for the field type is IMHO a good improvement especially as the number of obfuscated APKs is more and more rising. And a field search for a field named `a` isn't very effective.  

Additionally the search type is `Field` and not `Field name`, hence users may expect to search not only for field names.

@xmhwws What is your opinion on the field and method search. What would you expect to find when using this search type?

**Comment by xmhwws** [comment]
@jpstotz My problem has been solved, you can close this issue if you want.
