### ISSUE TITLE
[feature] Remove reference in enum classes

### ISSUE THREAD

**Issue by amspeople** [skylot/jadx#885]
*Describe your idea:*
I think enum classes do not need references to values ​​in other classes.
![image](https://user-images.githubusercontent.com/5773978/76688271-62ce9c80-663c-11ea-80ca-372c003be29a.png)

**Comment by sergey-wowwow** [comment]
@amspeople 
They are written by developers, but not generated by jadx. Each enum constructor contains a set of parameters, and declared enum constants satisfy to the declaration
