### ISSUE TITLE
Method not decompiled: com.paypal.android.foundation.auth.operations.ChecksumUtil.addMfsAuthCheckSumInParams(...)

### ISSUE THREAD

**Issue by hackerftsg** [skylot/jadx#891]
Hi @skylot , when I open `com.paypal.android.foundation.auth.operations.ChecksumUtil.addMfsAuthCheckSumInParams(...)` I see:

```java
/* JADX WARNING: Code restructure failed: missing block: B:14:0x003d, code lost:
        return;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static synchronized void addMfsAuthCheckSumInParams(com.paypal.android.foundation.auth.operations.SecurityOperation.GrantType r3, com.paypal.android.foundation.auth.AccountCredentials r4, java.util.Map<java.lang.String, java.lang.String> r5) {
        /*
            java.lang.Class<com.paypal.android.foundation.auth.operations.ChecksumUtil> r0 = com.paypal.android.foundation.auth.operations.ChecksumUtil.class
            monitor-enter(r0)
            com.paypal.android.foundation.core.CommonContracts.requireNonNull(r3)     // Catch:{ all -> 0x003e }
            com.paypal.android.foundation.core.CommonContracts.requireAny(r4)     // Catch:{ all -> 0x003e }
            com.paypal.android.foundation.core.CommonContracts.requireNonNull(r5)     // Catch:{ all -> 0x003e }
            com.paypal.android.foundation.auth.operations.SecurityOperation$GrantType r1 = com.paypal.android.foundation.auth.operations.SecurityOperation.GrantType.Password     // Catch:{ all -> 0x003e }
            boolean r3 = r1.equals(r3)     // Catch:{ all -> 0x003e }
            if (r3 == 0) goto L_0x003c
            long r1 = java.lang.System.currentTimeMillis()     // Catch:{ all -> 0x003e }
            java.lang.String r3 = composeChecksumInputForGrantTypePasswordOrPin(r4, r1)     // Catch:{ all -> 0x003e }
            boolean r4 = android.text.TextUtils.isEmpty(r3)     // Catch:{ all -> 0x003e }
            if (r4 == 0) goto L_0x0024
            monitor-exit(r0)
            return
        L_0x0024:
            java.lang.String r3 = getAuthCheckSum(r3)     // Catch:{ all -> 0x003e }
            boolean r4 = android.text.TextUtils.isEmpty(r3)     // Catch:{ all -> 0x003e }
            if (r4 != 0) goto L_0x003c
            java.lang.String r4 = "authNonce"
            r5.put(r4, r3)     // Catch:{ all -> 0x003e }
            java.lang.String r3 = "timeStamp"
            java.lang.String r4 = java.lang.Long.toString(r1)     // Catch:{ all -> 0x003e }
            r5.put(r3, r4)     // Catch:{ all -> 0x003e }
        L_0x003c:
            monitor-exit(r0)
            return
        L_0x003e:
            r3 = move-exception
            monitor-exit(r0)
            throw r3
        */
        throw new UnsupportedOperationException("Method not decompiled: com.paypal.android.foundation.auth.operations.ChecksumUtil.addMfsAuthCheckSumInParams(com.paypal.android.foundation.auth.operations.SecurityOperation$GrantType, com.paypal.android.foundation.auth.AccountCredentials, java.util.Map):void");
    }
```

Can you look at it? Thanks

APK: https://drive.google.com/open?id=1phN944Dgr7E7yU5oashvQOWGf13A1kTA

**Comment by jpstotz** [comment]
In the smali dump I see `monitor-enter` and `monitor-exit` calls (begin and end of a `synchronized` block). As I have noted in #659 synchronized blocks are very special on Android and produce code that is more or less invalid if you try to decompile it one-by-one (because the blocks are nested in a way usually impossible to generate by Java). 

However this is a design pattern on Android and required by the DalvikVM, otherwise the code verification will fail.

**Comment by sergey-wowwow** [comment]
@hackerftsg 
If you enable option `Show inconsistent code`, you will receive the following code
```java
    /* JADX WARNING: Code restructure failed: missing block: B:14:0x003d, code lost:
        return;
     */
    public static synchronized void addMfsAuthCheckSumInParams(com.paypal.android.foundation.auth.operations.SecurityOperation.GrantType grantType, com.paypal.android.foundation.auth.AccountCredentials accountCredentials, java.util.Map<java.lang.String, java.lang.String> map) {
        synchronized (com.paypal.android.foundation.auth.operations.ChecksumUtil.class) {
            com.paypal.android.foundation.core.CommonContracts.requireNonNull(grantType);
            com.paypal.android.foundation.core.CommonContracts.requireAny(accountCredentials);
            com.paypal.android.foundation.core.CommonContracts.requireNonNull(map);
            if (com.paypal.android.foundation.auth.operations.SecurityOperation.GrantType.Password.equals(grantType)) {
                long currentTimeMillis = java.lang.System.currentTimeMillis();
                java.lang.String composeChecksumInputForGrantTypePasswordOrPin = composeChecksumInputForGrantTypePasswordOrPin(accountCredentials, currentTimeMillis);
                if (!android.text.TextUtils.isEmpty(composeChecksumInputForGrantTypePasswordOrPin)) {
                    java.lang.String authCheckSum = getAuthCheckSum(composeChecksumInputForGrantTypePasswordOrPin);
                    if (!android.text.TextUtils.isEmpty(authCheckSum)) {
                        map.put("authNonce", authCheckSum);
                        map.put("timeStamp", java.lang.Long.toString(currentTimeMillis));
                    }
                }
            }
        }
    }
```
It could help in your case

**Comment by hackerftsg** [comment]
> In the smali dump I see `monitor-enter` and `monitor-exit` calls (begin and end of a `synchronized` block). As I have noted in #659 synchronized blocks are very special on Android and produce code that is more or less invalid if you try to decompile it one-by-one (because the blocks are nested in a way usually impossible to generate by Java).
> 
> However this is a design pattern on Android and required by the DalvikVM, otherwise the code verification will fail.

I'm sorry for answering so late. Thank you very much for the answer, I already managed to solve the problem.

**Comment by hackerftsg** [comment]
> @hackerftsg
> If you enable option `Show inconsistent code`, you will receive the following code
> 
> ```java
>     /* JADX WARNING: Code restructure failed: missing block: B:14:0x003d, code lost:
>         return;
>      */
>     public static synchronized void addMfsAuthCheckSumInParams(com.paypal.android.foundation.auth.operations.SecurityOperation.GrantType grantType, com.paypal.android.foundation.auth.AccountCredentials accountCredentials, java.util.Map<java.lang.String, java.lang.String> map) {
>         synchronized (com.paypal.android.foundation.auth.operations.ChecksumUtil.class) {
>             com.paypal.android.foundation.core.CommonContracts.requireNonNull(grantType);
>             com.paypal.android.foundation.core.CommonContracts.requireAny(accountCredentials);
>             com.paypal.android.foundation.core.CommonContracts.requireNonNull(map);
>             if (com.paypal.android.foundation.auth.operations.SecurityOperation.GrantType.Password.equals(grantType)) {
>                 long currentTimeMillis = java.lang.System.currentTimeMillis();
>                 java.lang.String composeChecksumInputForGrantTypePasswordOrPin = composeChecksumInputForGrantTypePasswordOrPin(accountCredentials, currentTimeMillis);
>                 if (!android.text.TextUtils.isEmpty(composeChecksumInputForGrantTypePasswordOrPin)) {
>                     java.lang.String authCheckSum = getAuthCheckSum(composeChecksumInputForGrantTypePasswordOrPin);
>                     if (!android.text.TextUtils.isEmpty(authCheckSum)) {
>                         map.put("authNonce", authCheckSum);
>                         map.put("timeStamp", java.lang.Long.toString(currentTimeMillis));
>                     }
>                 }
>             }
>         }
>     }
> ```
> 
> It could help in your case

Thanks for the solution. It really helped a lot for my case, gratitude.
