### ISSUE TITLE
[feature]Request support to open hundreds of .jar packages at the same time

### ISSUE THREAD

**Issue by a961960337** [skylot/jadx#892]
*Describe your idea:*
Can you drag in hundreds of jar packages at the same time like jd-gui, then decompile and open these jar packages, and you can find the mutual method references and implementations between the jar packages.

**Comment by jpstotz** [comment]
Loading multiple JAR files via Drag&Drop is possible in Jadx in the current version. Please try it.

**Comment by skylot** [comment]
It is also possible select several files in open dialog, and also add files later using 'Add files' button.
