### ISSUE TITLE
[core]Decompilation error

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#893]
jadx: latest unstable build

apk link: https://drive.google.com/open?id=1V9DjCn5ytJ1aHLHRJc0HHVmXBbU_zWiJ

class: `com.key.keyproject.KeyUtils`
method: `dealArray`

in jadx:
![image](https://user-images.githubusercontent.com/42903751/77524635-a2aa4500-6ec2-11ea-92d7-bde78097ef8a.png)

in GDA：
![image](https://user-images.githubusercontent.com/42903751/77524728-ccfc0280-6ec2-11ea-89c4-ded236c2a31b.png)

**Comment by jackwpa** [comment]
Hmm, both outputs are incorrect:
- jadx's second issue, aside from the problematic length computation, is the extension of the try-catch block beyond its normal boundary, thereby catching any potential exception happening in the decoding loop. Unless fine-grained exception analysis is done, which I don't think is the case.
- the other code snippet discarded the try-catch block entirely, altering the behavior of the method itself.

Correct decompilation provided by JEB:
```
    private String dealArray(byte[] arg9) {
        char[] bytes;
        byte[] h;
        char[] v0 = new char[]{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(arg9);
            h = md.digest();
            int len = h.length;
            bytes = new char[len * 2];
        }
        catch(Exception unused_ex) {
            return null;
        }

        int v4 = 0;
        for(int i = 0; i < len; i++) {
            int v5 = h[i];
            int v6 = v4 + 1;
            bytes[v4] = v0[v5 >>> 4 & 15];
            v4 = v6 + 1;
            bytes[v6] = v0[v5 & 15];
        }

        return new String(bytes);
    }
```

**Comment by charles2gan** [comment]
> Hmm, both outputs are incorrect:
.........
> * the other code snippet discarded the try-catch block entirely, altering the behavior of the method itself.
 ```

GDA is my work which is a dalvik decompiler by c++, also strong but no famous at all, There's a little bug here. Here, I took a few minutes to fix it. 
[image](https://user-images.githubusercontent.com/13128580/77646088-d490d980-6f9e-11ea-945d-3d1b97678e78.png)
In addition, GDA does not lose try-catch block. To eliminate interference code and facilitate the analysis of more complex code. Try-catch blocks can be shown through the right-click menu
 like this:

![image](https://user-images.githubusercontent.com/13128580/77647667-ca240f00-6fa1-11ea-90bc-6744f853e61b.png)

At last, Jeb also has the problem of variable scope like "int len = h.length;".

**Comment by xmhwws** [comment]
The latest version seems to fix the problem.
![image](https://user-images.githubusercontent.com/42903751/78126581-4eb0da80-7445-11ea-95f1-f6be929be9ae.png)
