### ISSUE TITLE
where is the application config file/folder

### ISSUE THREAD

**Issue by gMan1990** [skylot/jadx#894]
Where is the jadx app config file/folder?
- MacOS
- Windows

**Comment by jpstotz** [comment]
On Windows the settings are stored in the registry:

`HKEY_CURRENT_USER\Software\JavaSoft\Prefs\jadx\gui` in the value `jadx.gui.settings` (type: `REG_SZ` content is a Json string).

**Comment by sergey-wowwow** [comment]
@gMan1990 
You should find the file where the preferences are stored (https://github.com/skylot/jadx/blob/d1ac43de33aede078592eed864da88540d9c4af1/jadx-gui/src/main/java/jadx/gui/settings/JadxSettingsAdapter.java#L31) and then google platform specific implementation, for Mac it's ``` ~/Library/Preferences/com.apple.java.util.prefs ``` (https://stackoverflow.com/questions/675864/where-are-java-preferences-stored-on-mac-os-x)

**Comment by gMan1990** [comment]
@sergey-wowwow 3ks
`~/Library/Preferences/com.apple.java.util.prefs.plist`
