### ISSUE TITLE
[feature]How can i get the permissions by using jadx.bat

### ISSUE THREAD

**Issue by DuranceX** [skylot/jadx#898]
*Describe your idea:*
I added some codes in CodeSearch.java that i can write the results of searching "android.permissions" to file, umm, but i have to open jadx-gui and do the search operation for each time, doesn't there have any methods that i can deal with a batch of apks without opening GUI and do search operation ? 
for example, can the jadx.bat included the search operation that can print the results of searching in the window?

**Comment by sergey-wowwow** [comment]
This functionality is not a part of jadx. It's recommended to use external scripts which decode your apks and perform external search based on your requirements
