### ISSUE TITLE
Move to jadx-decompiler organization

### ISSUE THREAD

**Issue by Neustradamus** [skylot/jadx#902]
It is possible to transfer this repository to "jadx-decompiler" organization?
- https://help.github.com/articles/about-repository-transfers/

**Comment by skylot** [comment]
@Neustradamus 
Yes, it is possible to move `jadx` repository to `jadx-decompiler` organization, but is there is any reason to do that? Are there any advantages to have repository in organization?

**Comment by Neustradamus** [comment]
@skylot: Better management...
You do not lost datas, there will have redirection, ... and if you do not like you can move here again after.

**Comment by sergey-wowwow** [comment]
@Neustradamus 
Current management format seems good and enough. If skylot decides to do that, it will be done.

**Comment by Neustradamus** [comment]
Dear @jadx-decompiler, @skylot,

We are in 2024, 4,5yo after my initial request, can you do it?

Thanks in advance.

**Comment by Neustradamus** [comment]
Dear @jadx-decompiler team, @skylot,

Have you progressed on it?
