### ISSUE TITLE
Question ❓ CAN I USE FULL JADX FEATURES ON MY ANDROID DEVICE?

### ISSUE THREAD

**Issue by Mikesew1320** [skylot/jadx#903]
Is there a way to use all Jadx features directly fr my Android device without using PC either from CLI(Termux) or GUI?

Cam anyone help me please?

**Comment by skylot** [comment]
@Mikesew1320 you can try [ShowJava](https://play.google.com/store/apps/details?id=com.njlabs.showjava) it includes jadx among other decompilers.
