### ISSUE TITLE
Unable to process android.os.AsyncTask class

### ISSUE THREAD

**Issue by renkchina** [skylot/jadx#906]
version : 1.1.0
error : 
private class DecodeTask extends AsyncTask<String, Void, Void> {
        private DecodeTask() {
        }

        /* access modifiers changed from: protected */
        /* JADX WARNING: Removed duplicated region for block: B:21:0x005d A[SYNTHETIC, Splitter:B:21:0x005d] */
        /* JADX WARNING: Removed duplicated region for block: B:29:0x006a A[SYNTHETIC, Splitter:B:29:0x006a] */
        /* Code decompiled incorrectly, please refer to instructions dump. */
        public java.lang.Void doInBackground(java.lang.String... r6) {
            /*
                r5 = this;
                r0 = 0
                r1 = 0
                r6 = r6[r0]     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                java.lang.String r0 = "://"
                boolean r0 = r6.contains(r0)     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                if (r0 != 0) goto L_0x001d
                java.lang.StringBuilder r0 = new java.lang.StringBuilder     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                r0.<init>()     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                java.lang.String r2 = "file://"
                r0.append(r2)     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                r0.append(r6)     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                java.lang.String r6 = r0.toString()     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
            L_0x001d:
                java.net.URL r0 = new java.net.URL     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                r0.<init>(r6)     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                java.io.InputStream r6 = r0.openStream()     // Catch:{ Exception -> 0x004b, all -> 0x0049 }
                com.king.kvast.ImageItem r0 = com.king.kvast.ImageItem.this     // Catch:{ Exception -> 0x0044, all -> 0x0040 }
                android.graphics.Bitmap r2 = android.graphics.BitmapFactory.decodeStream(r6)     // Catch:{ Exception -> 0x0044, all -> 0x0040 }
                android.graphics.Bitmap unused = r0.mBitmap = r2     // Catch:{ Exception -> 0x0044, all -> 0x0040 }
                com.king.kvast.ImageItem r0 = com.king.kvast.ImageItem.this     // Catch:{ Exception -> 0x0044, all -> 0x0040 }
                com.king.kvast.ImageItem r2 = com.king.kvast.ImageItem.this     // Catch:{ Exception -> 0x0044, all -> 0x0040 }
                long r2 = r2.mInstance     // Catch:{ Exception -> 0x0044, all -> 0x0040 }
                r0.onPrefetched(r2)     // Catch:{ Exception -> 0x0044, all -> 0x0040 }
                if (r6 == 0) goto L_0x0065
                r6.close()     // Catch:{ Exception -> 0x0061 }
                goto L_0x0065
            L_0x0040:
                r0 = move-exception
                r1 = r6
                r6 = r0
                goto L_0x0068
            L_0x0044:
                r0 = move-exception
                r4 = r0
                r0 = r6
                r6 = r4
                goto L_0x004d
            L_0x0049:
                r6 = move-exception
                goto L_0x0068
            L_0x004b:
                r6 = move-exception
                r0 = r1
            L_0x004d:
                r6.printStackTrace()     // Catch:{ all -> 0x0066 }
                com.king.kvast.ImageItem r6 = com.king.kvast.ImageItem.this     // Catch:{ all -> 0x0066 }
                com.king.kvast.ImageItem r2 = com.king.kvast.ImageItem.this     // Catch:{ all -> 0x0066 }
                long r2 = r2.mInstance     // Catch:{ all -> 0x0066 }
                r6.onError(r2)     // Catch:{ all -> 0x0066 }
                if (r0 == 0) goto L_0x0065
                r0.close()     // Catch:{ Exception -> 0x0061 }
                goto L_0x0065
            L_0x0061:
                r6 = move-exception
                r6.printStackTrace()
            L_0x0065:
                return r1
            L_0x0066:
                r6 = move-exception
                r1 = r0
            L_0x0068:
                if (r1 == 0) goto L_0x0072
                r1.close()     // Catch:{ Exception -> 0x006e }
                goto L_0x0072
            L_0x006e:
                r0 = move-exception
                r0.printStackTrace()
            L_0x0072:
                throw r6
            */
            throw new UnsupportedOperationException("Method not decompiled: com.king.kvast.ImageItem.DecodeTask.doInBackground(java.lang.String[]):java.lang.Void");
        }
    }

***********************************************************
 /* access modifiers changed from: protected */
    /* JADX WARNING: Can't wrap try/catch for region: R(3:14|15|16) */
    /* JADX WARNING: Code restructure failed: missing block: B:12:0x0063, code lost:
        if (r4.mConnection != null) goto L_0x0075;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:13:0x0066, code lost:
        r5 = move-exception;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:15:?, code lost:
        r4.mListener.onFailed(r4.mId, r5, 404);
     */
    /* JADX WARNING: Code restructure failed: missing block: B:19:0x007c, code lost:
        return null;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:21:0x007f, code lost:
        if (r4.mConnection != null) goto L_0x0081;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:22:0x0081, code lost:
        r4.mConnection.disconnect();
        r4.mConnection = null;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:23:0x0088, code lost:
        throw r5;
     */
    /* JADX WARNING: Failed to process nested try/catch */
    /* JADX WARNING: Missing exception handler attribute for start block: B:14:0x0068 */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public java.lang.String doInBackground(java.lang.String... r5) {
        /*
            r4 = this;
            r0 = 0
            r5 = r5[r0]
            r0 = 0
            java.lang.String r1 = "GET"
            java.net.HttpURLConnection r1 = r4.connect(r5, r1)     // Catch:{ Exception -> 0x0068 }
            r4.mConnection = r1     // Catch:{ Exception -> 0x0068 }
            java.net.HttpURLConnection r1 = r4.mConnection     // Catch:{ Exception -> 0x0068 }
            int r1 = r1.getResponseCode()     // Catch:{ Exception -> 0x0068 }
            r2 = 200(0xc8, float:2.8E-43)
            if (r1 == r2) goto L_0x0054
            com.king.kvast.http.HttpTask$HttpListener r1 = r4.mListener     // Catch:{ Exception -> 0x0068 }
            int r2 = r4.mId     // Catch:{ Exception -> 0x0068 }
            java.net.HttpURLConnection r3 = r4.mConnection     // Catch:{ Exception -> 0x0068 }
            int r3 = r3.getResponseCode()     // Catch:{ Exception -> 0x0068 }
            r1.onFailed(r2, r5, r3)     // Catch:{ Exception -> 0x0068 }
            java.lang.StringBuilder r1 = new java.lang.StringBuilder     // Catch:{ Exception -> 0x0068 }
            r1.<init>()     // Catch:{ Exception -> 0x0068 }
            java.lang.String r2 = "Server returned HTTP "
            r1.append(r2)     // Catch:{ Exception -> 0x0068 }
            java.net.HttpURLConnection r2 = r4.mConnection     // Catch:{ Exception -> 0x0068 }
            int r2 = r2.getResponseCode()     // Catch:{ Exception -> 0x0068 }
            r1.append(r2)     // Catch:{ Exception -> 0x0068 }
            java.lang.String r2 = " "
            r1.append(r2)     // Catch:{ Exception -> 0x0068 }
            java.net.HttpURLConnection r2 = r4.mConnection     // Catch:{ Exception -> 0x0068 }
            java.lang.String r2 = r2.getResponseMessage()     // Catch:{ Exception -> 0x0068 }
            r1.append(r2)     // Catch:{ Exception -> 0x0068 }
            java.lang.String r5 = r1.toString()     // Catch:{ Exception -> 0x0068 }
            java.net.HttpURLConnection r1 = r4.mConnection
            if (r1 == 0) goto L_0x0053
            java.net.HttpURLConnection r1 = r4.mConnection
            r1.disconnect()
            r4.mConnection = r0
        L_0x0053:
            return r5
        L_0x0054:
            com.king.kvast.http.HttpTask$HttpListener r1 = r4.mListener     // Catch:{ Exception -> 0x0068 }
            int r2 = r4.mId     // Catch:{ Exception -> 0x0068 }
            java.net.HttpURLConnection r3 = r4.mConnection     // Catch:{ Exception -> 0x0068 }
            byte[] r3 = r4.getResponseData(r3)     // Catch:{ Exception -> 0x0068 }
            r1.onGetSuccess(r2, r5, r3)     // Catch:{ Exception -> 0x0068 }
            java.net.HttpURLConnection r5 = r4.mConnection
            if (r5 == 0) goto L_0x007c
            goto L_0x0075
        L_0x0066:
            r5 = move-exception
            goto L_0x007d
        L_0x0068:
            com.king.kvast.http.HttpTask$HttpListener r1 = r4.mListener     // Catch:{ all -> 0x0066 }
            int r2 = r4.mId     // Catch:{ all -> 0x0066 }
            r3 = 404(0x194, float:5.66E-43)
            r1.onFailed(r2, r5, r3)     // Catch:{ all -> 0x0066 }
            java.net.HttpURLConnection r5 = r4.mConnection
            if (r5 == 0) goto L_0x007c
        L_0x0075:
            java.net.HttpURLConnection r5 = r4.mConnection
            r5.disconnect()
            r4.mConnection = r0
        L_0x007c:
            return r0
        L_0x007d:
            java.net.HttpURLConnection r1 = r4.mConnection
            if (r1 == 0) goto L_0x0088
            java.net.HttpURLConnection r1 = r4.mConnection
            r1.disconnect()
            r4.mConnection = r0
        L_0x0088:
            throw r5
        */

**Comment by sergey-wowwow** [comment]
@renkchina 
It's impossible to find out the reason and fix the issue without affected APK and full class name. Please add detains and reopen the ticket
