### ISSUE TITLE
cannot download all resources from GUI or command line

### ISSUE THREAD

**Issue by krishna81m** [skylot/jadx#91]
GUI does not have an option to save all resources, only classes get saved.

Command line gets hung 
jadx.bat "some.apk"
jadx.bat --deobf --deobf-rewrite-cfg -j 5 "some.apk"
jadx.bat --deobf --fallback --deobf-rewrite-cfg -j 5 "some.apk"

**Comment by sergey-wowwow** [comment]
It's saved right now in all versions
