### ISSUE TITLE
Jadx Max Heap Size Stuck at 1GB since PR #895

### ISSUE THREAD

**Issue by MagicWizz** [skylot/jadx#925]
Jadx had the maximum heap size to about half the memory of my pc by default, but after PR #895 is stuck at 1GB and the solution from the wiki doesn't work, it's also confirmed by the fact that v1.1.0-b1266-a5ea560 "works" and v1.1.0-b1268-c62039f3 don't

**Comment by sergey-wowwow** [comment]
@MagicWizz 
Modify `jadx` (or `jadx.bat`) and `jadx-gui` (or `jadx-gui.bat`) and change value of `-Xmx4G`

**Comment by MagicWizz** [comment]
Thanks it works with the zip version, but how to do it with the exe?

**Comment by jpstotz** [comment]
The Jadx Exe starter can be configured using an ini file: 
See https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A and look for the section on `jadx-gui.l4j.ini`.

**Comment by MagicWizz** [comment]
@jpstotz 
Well it seems like the exe file name must be exactly "jadx-gui" to make it work, that's why when i tried it before it didn't work, a bit strange actually xd, but if it's by design then this issue can be closed

**Comment by jpstotz** [comment]
@MagicWizz That is true. I already have updated the info in Wiki. 

The name of the configuration file is defined by Launch4J. Jadx can't change anything on this.
