### ISSUE TITLE
[BUG] Opening class on hover cursor

### ISSUE THREAD

**Issue by amspeople** [skylot/jadx#929]
Latest beta version. When you hold down the Ctrl key and hover over the class name in GUI- this class opens. But opening a class should only be when you click the mouse. And no way when you hover.

**Comment by jpstotz** [comment]
Seems like this behavior exists since 2dce1c0ad920c4cc3f6aaa84cf3f2124dd97ad2d

May be this is a problem with the new version 3.1.1 of rsyntaxtextarea?

**Comment by amspeople** [comment]
> May be this is a problem with the new version 3.1.1 of rsyntaxtextarea?
Probably.
[Changelog ](https://github.com/bobbylight/RSyntaxTextArea/releases) RSyntaxTextArea 3.1.0 contains such an item:
**Fix #301: Fire hyperlink events when link-scanning-mask key is depressed and mouse enters and exits links. Previously we only fired 'activated' events when the mouse was clicked on a link**
 I think it's because of him a problem.

**Comment by amspeople** [comment]
Latest version without this problem - https://bintray.com/skylot/jadx/unstable/v1.1.0-b1278-258ecad2#files

**Comment by skylot** [comment]
Fixed. Actually it is more like a workaround, but for me, it looks clear and more straightforward than the previous implementation. So I decided not to revert RSyntaxTextArea but leave this solution.
Anyway, that was a big regression in RSyntaxTextArea, relevant [issue](https://github.com/bobbylight/RSyntaxTextArea/issues/340) already reported.

@amspeople, @jpstotz thanks for the help!
