### ISSUE TITLE
[feature] support select multi dex files as input

### ISSUE THREAD

**Issue by gMan1990** [skylot/jadx#936]
like: dex encryption technology

**Comment by jpstotz** [comment]
Jadx can can load APK files and APK files contain multiple dex files. Hence from my perspective "multi dex files" can already be loaded. 

If this not what you had in mind please give more details.

**Comment by gMan1990** [comment]
@jpstotz some apks use dynamic dex load, so can't read more java code from the original apk file.

**Comment by jpstotz** [comment]
So you are not talking about "multi dex files" but multiple dex files you have downloaded manually from your device. That makes a significant difference!

**Comment by gMan1990** [comment]
@jpstotz but the "multi dex files" all belong to one apk.

**Comment by sergey-wowwow** [comment]
@gMan1990 
AFAIK those files are not official and distributed by APK-sharing sites with their own formats. In the most cases they are usual ZIP archives (but with e.g. `.apks` extensions). You should unzip such file and send to jadx `package_name.apk` file

**Comment by gMan1990** [comment]
bytecode-viewer support multi dex files, but can not select mult dex files in file explorer

**Comment by skylot** [comment]
I think this can be done. Now jadx allows this internally, so we just need to expose this in cli and gui.
But we must prohibit loading several apks, because it is unclear how to merge several resource files (ids can override).
So in jadx-gui, I will add a menu button like `Add DEX files` which will allow loading several dex files or adding them to already loaded apk.

**Comment by jackwpa** [comment]
@gMan1990 tip: if you still need to do this you can use JEB, demo or else:

- load your APK
- open up the Terminal view
- type `use py`
- type `jeb.getMainProject().findUnit(IDexUnit).addDex(FileInput(PATH_TO_ADDITIONAL_DEX))`
- done

I found this trick on this blog https://www.pnfsoftware.com/blog/reversing-dexguard-encryption/

**Comment by skylot** [comment]
Done.
Now it is possible to select several files in open dialog, also there are new `Add files` button to add additional files to current project.
I don't add any restrictions but opening several apks will decode only one `arsc` file, so for now I think such behavior is ok.
