### ISSUE TITLE
[feature] Handle version upgrade in decompilation mappings

### ISSUE THREAD

**Issue by HellPie** [skylot/jadx#937]
It would be nice to be able to have a system that can preserve .jobf mappings where possible for app updates.

Say I'm decompiling an app with minification, the chance of 1.0 and 1.1 of having the same code is very high, method signatures rarely change and often most methods' decompilation result hardly ever changes, but given the huge amount of classes and methods in Android apps thanks to massive library dependencies, there is a very high chance that most of the minified methods will be renamed to names that differ between versions, causing a cascading mess of mismatched class and methods names elsewhere within the app.

**Comment by skylot** [comment]
@HellPie if I understand right, you can do it already. Just rename `.jobf` file to new apk name and check that option `Force rewrite deobfuscation map file` is disabled. This will use all names from `.jobf` file.

**Comment by HellPie** [comment]
I tried doing that wit Google Play Services, from 20.18.16 to 20.18.17 which adds a couple of classes, but it shifted a lot of classes to other names, effectively breaking diffs, making it mark changes in over 53K classes of the 60-someting-K, while almost no code was really changed.

**Comment by skylot** [comment]
@HellPie please check that `.jobf` file is not changed after decompilation.
I am also will try to reproduce that issue.

**Comment by HellPie** [comment]
I checked again, the option is disabled as it was before as well. I deleted both .jobf files, decompiled 20.18.16, took the jobf, copy and pasted and renamed to the 20.18.17 apk file name minus the extension which I kept as .jobf, loaded up and decompiled the 20.18.17 apk, closed everything.

The last modified date on the 20.18.17 .jobf is the same as the 20.18.16 .jobf and I also diffed the content of both .jobf files, which resulted identical, despite 20.18.17 having 2 new classes that 20.18.16 didn't have. So just to be safe I redid everything, from scratch, this time saving both apks as projects when leaving even tho that shouldn't rewrite the .jobf, but again, the two files were identical and the 20.18.17 does have two new classes.

I confirmed that 20.18.17 does have new classes that 20.18.16 didn't have by exporting both versions' source code, creating a git repo, putting all the code of 20.18.16 in it and committing it, then deleting the files (not the .git folder) and putting the 20.18.17 sources in it and looking at the staged changes. Between 50-something-K files changed there were in fact 2 new files and most of the changes in all the files were related to very "core" classes that were swapped with each other, causing tons of references everywhere in Google Play Services to change and therefore tons of files too, despite the code remaining functionally the exact same.

**Comment by skylot** [comment]
@HellPie I checked apks myself and looks like original class names have changed, so name mappings from `.jobf` can't help here. The only way to track such changes is to compare classes and methods by content, but it is hard, and I don't think I will implement that in jadx.
