### ISSUE TITLE
Keep downloading gradle 2.7

### ISSUE THREAD

**Issue by Anthonyeef** [skylot/jadx#94]
Hi,

I have gradle 2.8 which is the latest version on my mac, and when I run `./gradlew dist` try to build from source, it started to download gradle 2.7 every time.

Is there a way to fix it? I want to use my gradle and don't want to download gradle again.

Thanks.

**Comment by skylot** [comment]
If you already have installed gradle you can use `gradle dist` instead of `./gradlew dist`

**Comment by Anthonyeef** [comment]
It works. I think I have this question just because I don't have a background knowledge of `gradle`. Thank you for your patience and I would try to know more about `gradle`.
