### ISSUE TITLE
[feature]希望能更改显示字体大小

### ISSUE THREAD

**Issue by ChenilleJoes** [skylot/jadx#945]
*Describe your idea:*
希望能更改显示字体大小

**Comment by Luro02** [comment]
Google Translate:
> Hope to change the display font size

I think you can already do this:
- Navigate through the menu to preferences: 
  File > Preferences
- There is a section called "Editor", where you can edit the font and size by pressing the "Change" button

**Comment by jpstotz** [comment]
Also make sure to use Java 11 or newer if your monitor is a high-dpi monitor.

**Comment by ChenilleJoes** [comment]
Oh, it’s originally here, but it’s just the current project configuration. I think it’s not very convenient to set it every time you open the program. A better way is to use  “Ctrl + scroll wheel” quick adjustment like Chrome (From Google Translate😛)

**Comment by ChenilleJoes** [comment]
> Google Translate:
> 
> > Hope to change the display font size
> 
> I think you can already do this:
> 
> * Navigate through the menu to preferences:
>   File > Preferences
> * There is a section called "Editor", where you can edit the font and size by pressing the "Change" button

Oh, it’s originally here, but it’s just the current project configuration. I think it’s not very convenient to set it every time you open the program. A better way is to use  “Ctrl + scroll wheel” quick adjustment like Chrome (From Google Translate😛)

**Comment by alissonlauffer** [comment]
> but it’s just the current project configuration. I think it’s not very convenient to set it every time you open the program.

Just edit the preferences outside of a project.
