### ISSUE TITLE
License Issue!

### ISSUE THREAD

**Issue by samyak-jn** [skylot/jadx#948]
Hi,

I intend to package `jadx` for Debian. However, I'm not able to figure out the correct License name and year for the package.

Can you please confirm once? :)

Thank you!

**Comment by jpstotz** [comment]
Have you seen https://github.com/skylot/jadx/blob/master/LICENSE?

**Comment by samyak-jn** [comment]
Hi @jpstotz,

Yes, I checked it.
But as mentioned I wasn't able to retrieve the License Author's details and License's Year. :D

I know it's licensed under Apache-2.0

Can you please confirm the following?
```
Copyright: 2020, skylot
License: Apache-2.0
```

Thanks for your quick response :)

**Comment by skylot** [comment]
> Copyright: 2020, skylot
License: Apache-2.0

@samyak-jn sure, thats correct

**Comment by samyak-jn** [comment]
Thanks! :D
