### ISSUE TITLE
[core] Loading of APK files slow

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#950]
Using the latest unstable version jadx-1.1.0-b1301-65553c15 loading larger APK files, such as Spotify or any other APK files has become very slow.

I noticed that while the initial loading process dozens of temporary zipfs* temporary files are created and deleted next to the APK file. Mostly the temporary files I have seen are just a few KB large, hence processing them in-memory would be preferable instead of creating a temporary file that lives just a few milliseconds.

**Comment by jpstotz** [comment]
@skylot Thanks loading works much better now. 

Just for curiosity: What dependencies are you talking about - Jadx dependencies or dependencies of the APK that is loaded?

**Comment by skylot** [comment]
@jpstotz apk class dependencies and usage of fields and methods.
I will use such info for many things:
- deterministic class decompilation order 
(done, now changes between runs must considered as a bug)
- fixing access modifiers
- aggressive anonymous and lambda inlining
- help for gui features: rename and find usage
