### ISSUE TITLE
[feature] Detect correct resource type in obfuscated resource folder names

### ISSUE THREAD

**Issue by alissonlauffer** [skylot/jadx#952]
Actually, if an app have its resource folder names obfuscated, Jadx won't try to decode/correct them.

Take a look at https://github.com/alissonlauffer/via-browser-dump/tree/master/src/main: Obfuscated resources are under the `r` folder with obfuscated subfolders, while others (Which are under `resources.arsc`) are under the `res` folder with non-obfuscated subfolders.

Note: If I decompile and rebuild the app with apktool, resource folder names will be decoded and jadx will decompile them fine, but this could be done by Jadx directly.

APK: https://apkpure.com/via-browser-fast-light-geek-best-choice/mark.via.gp/download

**Comment by liatsineam** [comment]
I think this feature is very useful, Jadx should add this feature like apktool.

**Comment by sergey-wowwow** [comment]
@alissonlauffer 
Can you recheck please?

**Comment by alissonlauffer** [comment]
Ok, I've built jadx with the bug_994 branch and tested saving the project as a Gradle project, but resource files are being saved inside `src/main` instead of `src/main/res`:
![image](https://user-images.githubusercontent.com/29029632/97116762-1bce7c80-16de-11eb-88d7-3efc9844898e.png)

**Comment by sergey-wowwow** [comment]
@alissonlauffer 
Updated the PR

**Comment by sergey-wowwow** [comment]
Should be fixed
