### ISSUE TITLE
[core] Use of illegal wildcard types

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#955]
CC from https://github.com/skylot/jadx/issues/913

Class ``` io.reactivex.internal.operators.observable.ObservableAny ```
```java
    public void subscribeActual(io.reactivex.Observer<? super java.lang.Boolean> observer) {
```
But ``` java.lang.Boolean ``` is a final class, and ``` ? super java.lang.Boolean ``` is illegal type

APK: https://drive.google.com/file/d/1qC3tlWs9AtPBpyS6iU9kcSphLryfJOxi/view

**Comment by skylot** [comment]
@sergey-wowwow I don't see error here. Next code is correct and compiles:
```java
    public static void test(List<? super Boolean> list) {
        list.add(Boolean.TRUE);
    }
```
Sure you can't insert in this list anything else instead Boolean.
Maybe you mistake `? super Boolean` with `? extends Boolean` ?
Anyway, these bounds include bound type, so it does not matter is class final or not, a definition will always compile. And usage in your sample is correct ([check original code](https://github.com/ReactiveX/RxJava/blob/2cb20bd41efe70556ef7d346ee60f70e20548bae/src/main/java/io/reactivex/internal/operators/observable/ObservableAny.java#L30)).

Here sample code to show differents between these bounds (JLS docs can be found [here](https://docs.oracle.com/javase/specs/jls/se14/html/jls-4.html#jls-4.5.1)):
```java
	class A { }
	class B extends A { }
	class C extends B { }

	public void check() {
		List<? super B> a = new ArrayList<A>();
		a.add(new A()); // error
		a.add(new B()); // ok
		a.add(new C()); // ok

		Object a0 = a.get(0); // ok
		A a1 = a.get(0); // error
		B a2 = a.get(0); // error
		C a3 = a.get(0); // error

		List<? extends B> b = new ArrayList<C>();
		b.add(new A()); // error
		b.add(new B()); // error
		b.add(new C()); // error

		Object b0 = b.get(0); // ok
		A b1 = b.get(0); // ok
		B b2 = b.get(0); // ok
		C b3 = b.get(0); // error
	}
```
Yeah, wildcard bounds is weird ;)
