### ISSUE TITLE
[core] Use of Object type instead of template type

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#956]
CC from https://github.com/skylot/jadx/issues/913
Class `kotlinx.coroutines.internal.ArrayQueue`
```java
public class ArrayQueue<T> {
    private java.lang.Object[] elements = new java.lang.Object[16];
    //...

    @org.jetbrains.annotations.Nullable
    public final T removeFirstOrNull() {
        int i = this.head;
        if (i == this.tail) {
            return null;
        }
        T[] tArr = this.elements; // error!
```

APK: https://drive.google.com/file/d/1qC3tlWs9AtPBpyS6iU9kcSphLryfJOxi/view

**Comment by skylot** [comment]
@sergey-wowwow fixed.
Anyway, work on generics is not yet finished, so new issues are expected.

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks! Seems to be fixed

**Comment by sergey-wowwow** [comment]
But I see that all `boolean` -> `byte` conversions are broken after last commit. E.g. in class `org.bytedeco.javacpp.indexer.UnsafeRaw`

Before
```java
    public void putBoolean(long j, boolean z) {
        UNSAFE.putByte(j, z ? 1 : 0);
    }
```

Now
```java
    public void putBoolean(long j, boolean z) {
        UNSAFE.putByte(j, z);
    }
```

**Comment by skylot** [comment]
@sergey-wowwow primitive type convertion case is fixed.

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks!
