### ISSUE TITLE
[feature]Whether the Maven version can be supported 

### ISSUE THREAD

**Issue by jgswp** [skylot/jadx#958]
*Describe your idea:*
When I come down and try to convert it into Maven build, a lot of errors, can u support a maven

**Comment by jpstotz** [comment]
Why do you try to build Jadx with maven. Jadx uses gradle. I like Maven, too even if it is a bit old-fashioned but gradle as the newer tool has a much higher flexibility and therefore projects that are gradle based  are unlikely to switch back to maven.

**Comment by jgswp** [comment]
OK, I've found a way to solve it. Thank you
