### ISSUE TITLE
[core] Decompile single .smali file

### ISSUE THREAD

**Issue by JoseGalRe** [skylot/jadx#961]
tested with adoptopenjdk 8 and 14 versions
```
java 8 update 265 (1.8.0_265-b01) openj9
java 14 update 2 (14.0.2+12) hotspot and openj9
```

in **_jadx-1.1.0-b1294-09e267f8_** single smali files can be decompiled

from **_jadx-1.1.0-b1299-ae31fee8_**
until the most recent  **_jadx-1.1.0-b1318-ae265126_** not posible anymore

**Comment by skylot** [comment]
@JoseGalRe thanks!
Looks like after big refactoring in 0d69e0ac971f53fd89dd15db16d7c5dd21c7fbb5 I totaly forgot about this feature :(

**Comment by JoseGalRe** [comment]
> @JoseGalRe thanks!
> Looks like after big refactoring in [0d69e0a](https://github.com/skylot/jadx/commit/0d69e0ac971f53fd89dd15db16d7c5dd21c7fbb5) I totaly forgot about this feature :(

Do not worry sr, thanks for you work! 😄

**Comment by skylot** [comment]
@JoseGalRe issue fixed.
