### ISSUE TITLE
[core] Use of useless casts

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#962]
Class `com.ebay.nautilus.domain.data.experience.onboarding.OnboardingAnswer`
```java
    @Override // com.ebay.nautilus.domain.data.experience.type.field.Field
    public void setSelected(boolean z) {
        ((com.ebay.nautilus.domain.data.experience.type.field.Field) this).selected = z;
    }
```
In this case, the cast is useless (and there are tons of them), `this.selected` can be used instead

APK: https://drive.google.com/file/d/1qC3tlWs9AtPBpyS6iU9kcSphLryfJOxi/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow I made a fix ... and commit has many different changes, so new issues are expected :)
