### ISSUE TITLE
[core] TikTok app isn't decompiled within 10 minutes (never finished)

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#966]
Hi @skylot, there is an APK that cannot be decompiled https://drive.google.com/file/d/18riJBSLPWttKSijRbry4_DDtDciVm8Kx/view?usp=sharing

In my case, decompilation stuck on 60% in jadx-gui

**Comment by jpstotz** [comment]
I can't reproduce this. The APK loads and decompiles fine for me (using latest version from Git, in Java 11.0.8 Win 10, 6 threads).

May be the decompilation problem only occurs if a certain preference is set?

**Comment by skylot** [comment]
@sergey-wowwow I also can't reproduce this issue.
I tried different options and threads count and decompilation always complete.
Anyway, there are tons of other issues ;(

**Comment by sergey-wowwow** [comment]
@skylot 
Can you please try this configuration
<img width="902" alt="2020-08-16_13-32-26" src="https://user-images.githubusercontent.com/15173437/90334509-d5221f00-dfd6-11ea-81e1-4e1346af969d.png">

**Comment by skylot** [comment]
@sergey-wowwow I tried your configuration several times, decompilation always successfully reached 100%.
Did you change any JVM settings like thread stack size (`-Xss`)?
