### ISSUE TITLE
jadx.gui.ui.RenameDialog window never gets pack'ed or sized.

### ISSUE THREAD

**Issue by BlindWanderer** [skylot/jadx#972]
code should be added to call pack if mainWindow.getSettings().loadWindowPos(this); in initUI returns false.

mainWindow.getSettings().saveWindowPos(this); is never called so loadWindowPos will always return false. Other windows call saveWindowPos in the dispose @Override.

A rename keyboard shortcut wouldn't go amiss either.

**Comment by skylot** [comment]
@BlindWanderer thanks! Rename dialog should be fixed now.
