### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by l111iang** [skylot/jadx#974]
It is strongly required to add comments! And can be modified and saved!

**Comment by l111iang** [comment]
Add explanation

**Comment by giacomoferretti** [comment]
You want to add comments to the decompiled code using jadx-gui?

**Comment by skylot** [comment]
This feature already requested at #359 with a detailed description, so I close this as duplicate.

**Comment by FabioNevesRezende** [comment]
@skylot What about comments on the java code in jadx-**gui**? That would be nice too, also the possibility to change variable names that are declared inside methods
