### ISSUE TITLE
[Patch included] False positives when generating @Override annotations

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#976]
Example to reproduce:

BaseClass.java

```
package test;

public class BaseClass {
  private void a() {}

  /* just to remove dead code warning */
  public void b() {
    a();
  }
}
```

MyClass.java

```
package test;

public class MyClass extends BaseClass {
  public void a() {}
}
```
Decompiled result of MyClass is:

```
package test;

public class MyClass extends BaseClass {
    @Override // test.BaseClass
    public void a() {
    }
}
```
When generating override annotations it should be checked if the method of the super class is private. With obfuscated code this error can happen more often.

The attached patch (zipped) solves this issue and generates valid code.
[avoid_override_for_private_methods.zip](https://github.com/skylot/jadx/files/5238210/avoid_override_for_private_methods.zip)

I think this would be a good candidate for a unit test.

Real world example is Database Modeler Lite 1.1 (https://apkpure.com/database-modeler-lite/adrian.adbm)
e.g. adrian.adbm.fragments.a : j0() and k0() which are trying to override private methods of androidx.fragment.app.Fragment

**Comment by skylot** [comment]
@nitram84 thanks! I totally missed this case. I apply your patch and add a unit test.
Also, I fixed a similar issue for static methods :sweat:
