### ISSUE TITLE
RenameBug

### ISSUE THREAD

**Issue by KVAC** [skylot/jadx#981]
java 1.8.0_265
git commit dcca0133fb944b495b3cd9adaf76f365e3dbd267
git Date:   Thu Sep 17 21:03:17 2020 +0300

When renaming a method / variable, the type of the variable is lost:
ArrayList \<String\> aa23;
ArrayList logins;

the same thing happens with methods.

**Comment by skylot** [comment]
@KVAC thanks! Looks like generics are lost on the class reloading.

**Comment by skylot** [comment]
Fixed.
