### ISSUE TITLE
[core]JADX ERROR: IndexOutOfBoundsException in pass: RegionMakerVisitor

### ISSUE THREAD

**Issue by yuxue521** [skylot/jadx#983]
Hey guys i was decompiling an application and it return some decompilation errors and i was wondering if someone could explain the source of these error and why they are happening

[MariaDB Server_v1.6.5-arm_apkpure.com.zip](https://github.com/skylot/jadx/files/5266091/MariaDB.Server_v1.6.5-arm_apkpure.com.zip)

use jadx 1.1.0
i got this inside the output code :
class `com.esminis.server.mariadb.server.MariaDbServerLauncher`
```java
    /*  JADX ERROR: IndexOutOfBoundsException in pass: RegionMakerVisitor
        java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        	at java.base/java.util.Objects.checkIndex(Unknown Source)
        	at java.base/java.util.ArrayList.get(Unknown Source)
        	at jadx.core.dex.nodes.InsnNode.getArg(InsnNode.java:101)
        	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:611)
        	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
        	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
        	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
        	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
        	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
        	at jadx.core.dex.visitors.regions.RegionMaker.processMonitorEnter(RegionMaker.java:561)
        	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:133)
        	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
        	at jadx.core.dex.visitors.regions.RegionMaker.processExcHandler(RegionMaker.java:1043)
        	at jadx.core.dex.visitors.regions.RegionMaker.processTryCatchBlocks(RegionMaker.java:975)
        	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:52)
        */
    /* JADX WARNING: Removed duplicated region for block: B:60:0x0173 A[SYNTHETIC] */
    void initializeDataDirectory(android.content.Context r20, java.io.File r21, java.io.File r22) throws java.io.IOException {
 ```

**Comment by yuxue521** [comment]
This is an open source project, and it is no longer being developed. I only have code snippets of the old version

void initializeDataDirectory(Context context, File binary, File root) throws IOException {
		final File[] files = root.listFiles();
		if (files != null && files.length > 0) {
			return;
		}
		final String version = getVersion(binary);
		synchronized (lock) {
			final List<String> environment = createEnvironment();
			final List<String> command = createCommandInternal(context, binary, root, null);
			final File defaultCnf = getDefaultCnf(root);
			Collections.addAll(
				command, "--bootstrap", "--log-warnings=0", "--max_allowed_packet=8M",
				"--net_buffer_length=16K"
			);
			final File dataMysqlDirectory = new File(root, "mysql");
			if (dataMysqlDirectory.isDirectory()) {
				return;
			}
			Utils.createDirectory(dataMysqlDirectory);
			final Process process = Runtime.getRuntime()
				.exec(command.toArray(new String [0]), environment.toArray(new String[0]), root);
			final Object[] finishedWithError = {null};
			final String[] log = {""};
			try {
				final OutputStream stream = process.getOutputStream();
				Completable.create(
					emitter -> {
						final InputStream inputStream = process.getErrorStream();
						for (;;) {
							synchronized (finishedWithError) {
								if (finishedWithError[0] != null) {
									break;
								}
							}
							try {
								int available = inputStream.available();
								if (available > 0) {
									for (int i = 0; i < available; i++) {
										log[0] += (char)inputStream.read();
									}
									if (
										getFreeSpace(dataMysqlDirectory) < 1024L * 1024L ||
										log[0].contains("No space left on device")
									) {
										synchronized (finishedWithError) {
											finishedWithError[0] = new IOException("No space left on device");
										}
										process.destroy();
										break;
									}
								}
							} catch (Throwable ignored) {}
							Thread.yield();
						}
						emitter.onComplete();
					}
				).subscribeOn(Schedulers.newThread()).subscribe();
				writeToStream(stream, "use mysql;\n");
				if (version != null && version.contains("10.0.0")) {
					writeToStream(stream, context, "sql/mysql_system_tables_10_0.sql");
					writeToStream(stream, context, "sql/mysql_system_tables_data_10_0.sql");
					writeToStream(stream, context, "sql/add_root_from_any_host_10_0.sql");
				} else {
					if (version != null && version.contains("10.3.")) {
						writeToStream(stream, context, "sql/mysql_system_tables_10_3.sql");
					} else {
						writeToStream(stream, context, "sql/mysql_system_tables.sql");
					}
					writeToStream(stream, context, "sql/mysql_performance_tables.sql");
					writeToStream(stream, context, "sql/mysql_system_tables_data.sql");
					writeToStream(stream, context, "sql/add_root_from_any_host.sql");
				}
				writeToStream(stream, context, "sql/fill_help_tables.sql");
				writeToStream(stream, "exit;\n");
				process.waitFor();
				if (!defaultCnf.isFile()) {
					try {
						//noinspection ResultOfMethodCallIgnored
						defaultCnf.createNewFile();
					} catch (IOException ignored) {}
				}
			} catch (Throwable e) {
				FileUtils.deleteDirectory(root);
				//noinspection ResultOfMethodCallIgnored
				root.mkdirs();
				synchronized (finishedWithError) {
					if (finishedWithError[0] != null && finishedWithError[0] instanceof IOException) {
						throw (IOException)finishedWithError[0];
					}
					throw new IOException(
						e.toString() + "\n\nLog:\n" +
							IOUtils.toString(process.getErrorStream(), Charset.defaultCharset()) + "," +
							log[0] + IOUtils.toString(process.getInputStream(), Charset.defaultCharset())
					);
				}
			} finally {
				synchronized (finishedWithError) {
					if (finishedWithError[0] == null) {
						finishedWithError[0] = true;
					}
				}
			}
		}
	}

**Comment by skylot** [comment]
In [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) IndexOutOfBoundsException is not appear, but method still decompiled incorrectly, you can check method code by enabling `Show inconsistent code` option.
The main cause is a combination of finally blocks and nested synchronized blocks.
I am not sure that I can fix this because method is too big.
Anyway, @yuxue521 thank you for report!
