### ISSUE TITLE
jadx-gui not displaying correctly in sway windows manager

### ISSUE THREAD

**Issue by jahway603** [skylot/jadx#985]
**Describe the bug**
jadx-gui not displaying correctly in sway windows manager & the mouse movement in the menu is off

**To Reproduce**
1. Start jadx-gui.
2. Select apk file.
3. I then see the following display:
![jadx-gui-sway-issue-2](https://user-images.githubusercontent.com/64485701/94210698-7d13ed80-fe9d-11ea-80e9-072e8421079d.png)

**Expected behavior**
The app should display correctly.

**Additional notes**
- I have tried setting _JAVA_AWT_WM_NONREPARENTING=1 as per [this thread](https://www.reddit.com/r/swaywm/comments/evd0lj/java_gui_swing_applications_on_sway/), but that did not resolve the issue.
- I have tried to resize the "internal windows" and can only move the "middle bar" between the two.

**Desktop:**
OS: Arch Linux
Version: Rolling
Windows manager: Sway

**Comment by skylot** [comment]
@jahway603 I just checked and it works fine for me (Sway on Arch Linux).
Also, I checked several java versions (8, 11, 14) and everything is fine (but latest java is always preferred).
So, please make sure `_JAVA_AWT_WM_NONREPARENTING=1` is enabled or just run from terminal:
```bash
_JAVA_AWT_WM_NONREPARENTING=1 jadx-gui
```
