### ISSUE TITLE
[feature] Ability to rename package names.

### ISSUE THREAD

**Issue by alissonlauffer** [skylot/jadx#987]
Currenly, Jadx is able to rename classes and field names, but not packages.

## Usage cases:
- With deobfuscation enabled, sometimes Jadx wrongly renames some packages, like `android.support.v4` to `android.support.p000v4`, so we could be able to revert it back to `v4`.
- Sometimes, package names are obfuscated, but its inner classes not. This feature could help to manually rename the obfuscated package name to a more descriptive name.

**Comment by skylot** [comment]
@alissonlauffer I have added rename for packages.
Although if package consist of serveral parts you can rename only one at a time:
![package-rename](https://user-images.githubusercontent.com/118523/94864652-0058b480-0445-11eb-8a79-a0883cc5f0c0.png)
Not sure how to implement it better.

**Comment by alissonlauffer** [comment]
I've been testing it for a while and found a regression: When renaming some packages, the renaming will happen in some of its subpackages instead of the package itself.

Try to rename `android.support.v7` to something else in the following APK: https://drive.google.com/file/d/1RQesxeywrcHQveXEZGFiv9EfIczF2Q3X/view

**Comment by skylot** [comment]
@alissonlauffer I have fixed several issues. Please check :)

**Comment by alissonlauffer** [comment]
Okay, it's now working fine. Thanks!

One last thing, I think would be great if we could rename class files by right clicking their name (just like for packages) instead of opening the file and renaming main class name.

**Comment by pkilller** [comment]
I implemented the rename function。[https://github.com/pkilller/super-jadx/raw/super-jadx/demo.gif](url)

**Comment by pkilller** [comment]
I implemented the rename function
![img](https://github.com/pkilller/super-jadx/raw/super-jadx/demo.gif)

**Comment by alissonlauffer** [comment]
@pkilller I see you created a JADX fork (apparently based on version 1.0.0) with renaming feature, but that feature is already present in dev version and will be released in v1.2.0.

**Comment by skylot** [comment]
Looks like this issue can be closed now

**Comment by ed9w2in6** [comment]
Sorry if this is not the right place for such questions.

I have been trying this feature but I see that this only allows renaming that conforms the existing structure.  That is if a class is located under `a.b.c` I cannot rename it to `a.b.c.d`.

May I ask if there are any existing method that can allow me to do so?

**Comment by ed9w2in6** [comment]
My previous comment can be ignored, sorry for bothering.
I think my issue is described in #1590.
Not sure why it didn't show up before when I searched for it.
