### ISSUE TITLE
[feature] Support dumped DEX

### ISSUE THREAD

**Issue by LGLTeam** [skylot/jadx#989]
I have dumped dex from memory since the dex was encrypted. Jadx couldn't recognize the dumped dex but apktool.jar 2.4.1 can decompile them just fine with some errors

Doesn't matter if some code could not be decompiled, I just need to be able to view dumped dex in Jadx

[dumped dex.zip](https://github.com/skylot/jadx/files/5339630/dumped.dex.zip)

**Comment by skylot** [comment]
@LGLTeam that's odex files, you need to deodex them first, check [smali wiki](https://github.com/JesusFreke/smali/wiki/DeodexInstructions#general-information-about-odex-files).
I am not sure that I will implement deodexing in jadx, it is already done in smali so just use it.
