### ISSUE TITLE
[core] ERROR - finished with errors, count: 1 

### ISSUE THREAD

**Issue by cyberjj999** [skylot/jadx#991]
Hello everyone, I am using JadX to convert APK file to its source code, this is the command i've used
`./jadx  ~/Desktop/myapk.apk`

However, I received this output
```
INFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 1
```
The error message is not very helpful and I've not seen similar problems hence I've decided to open a new issue here.
I've tried it with the `--show-bad-code` option as well but the output didn't change too

The `resources` and `sources` files are still generated with other files in the folder but I am not sure if any files are missing. 
I would appreciate any support 👍  
Thanks in advance!

UPDATE: Some APK i've tried has no error at all, but others have up to 117 errors! 
![image](https://user-images.githubusercontent.com/51283594/95407728-64e9a700-0950-11eb-92db-ab9a17a63ff7.png)

**Comment by skylot** [comment]
@cyberjj999, as you saw there are can be lots of errors, so by default jadx don't show them.
To see all errors in log you can adjust `--log-level` option to `ERROR` value. It will print all exceptions and output a report with affected classes. For other possible options check `jadx -h`:
```
--log-level     - set log level, values: QUIET, PROGRESS, ERROR, WARN, INFO, DEBUG, default: PROGRESS
```
Also, you can grep output classes by `JADX ERROR` string.
Anyway, don't expect jadx to produce 100% correct code, unfortunately, errors always exist.

**Comment by cyberjj999** [comment]
Ahh I see. Thank you very much for clarifying! I completely understand.
I confirm that this is the solution. Thanks for the help once again!
